<!DOCTYPE html>
<html lang="en"><head>
<script src="ch7_files/libs/clipboard/clipboard.min.js"></script>
<script src="ch7_files/libs/quarto-html/tabby.min.js"></script>
<script src="ch7_files/libs/quarto-html/popper.min.js"></script>
<script src="ch7_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="ch7_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="ch7_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="ch7_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.38">

  <meta name="author" content="Yu-You Liou">
  <meta name="dcterms.date" content="2026-09-20">
  <title>Statistics</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="ch7_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="ch7_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="ch7_files/libs/revealjs/dist/theme/quarto-2abc1c5b7b5c7eecd6137558e106e4c3.css">
  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">
  <link href="ch7_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="ch7_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="ch7_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="ch7_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-notes="" class="quarto-title-block center">
  <h1 class="title">Statistics</h1>
  <p class="subtitle">Chapter 7: Confidence Intervals and Sample Size</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Yu-You Liou 
</div>
        <p class="quarto-title-affiliation">
            Shih Chien University
          </p>
    </div>
</div>

  <p class="date">2026-09-20</p>
</section>
<section id="overview" class="slide level2">
<h2>Overview</h2>
<p>Chapter 7 is about <strong>estimation</strong> — using a sample statistic to estimate a population parameter, with a stated confidence level and a stated sample size.</p>
<table class="caption-top">
<colgroup>
<col style="width: 52%">
<col style="width: 47%">
</colgroup>
<thead>
<tr class="header">
<th>Section</th>
<th>Topics</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>7-1</td>
<td>Estimation; point estimates; properties of a good estimator; interval estimates; confidence level and interval; critical value <span class="math inline">z_{\alpha/2}</span>; margin of error</td>
</tr>
<tr class="even">
<td>7-2</td>
<td>Confidence interval for the mean, <span class="math inline">\sigma</span> known; assumptions; rounding rule; minimum sample size</td>
</tr>
<tr class="odd">
<td>7-3</td>
<td>The <span class="math inline">t</span> distribution; degrees of freedom; confidence interval for the mean, <span class="math inline">\sigma</span> unknown; <span class="math inline">z</span> versus <span class="math inline">t</span></td>
</tr>
</tbody>
</table>
</section>
<section id="overview-continued" class="slide level2">
<h2>Overview (continued)</h2>
<table class="caption-top">
<colgroup>
<col style="width: 52%">
<col style="width: 47%">
</colgroup>
<thead>
<tr class="header">
<th>Section</th>
<th>Topics</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>7-4</td>
<td>Sample proportion <span class="math inline">\hat{p}</span> and <span class="math inline">\hat{q}</span>; confidence interval for a proportion; minimum sample size</td>
</tr>
<tr class="even">
<td>7-5</td>
<td>The chi-square distribution; confidence intervals for a variance and a standard deviation</td>
</tr>
</tbody>
</table>
</section>
<section id="chapter-objectives" class="slide level2">
<h2>Chapter Objectives</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>After completing this chapter, you should be able to</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>Find the confidence interval for the mean when <span class="math inline">\sigma</span> is known.</li>
<li>Determine the minimum sample size for finding a confidence interval for the mean.</li>
<li>Find the confidence interval for the mean when <span class="math inline">\sigma</span> is unknown.</li>
<li>Find the confidence interval for a proportion.</li>
<li>Determine the minimum sample size for finding a confidence interval for a proportion.</li>
<li>Find a confidence interval for a variance and a standard deviation.</li>
</ol>
</div>
</div>
</div>
</section>
<section>
<section id="section-7-1-confidence-intervals" class="title-slide slide level1 center" data-background-color="#2c4a6e">
<h1>Section 7-1: Confidence Intervals</h1>

</section>
<section id="estimation" class="slide level2">
<h2>Estimation</h2>
<p>One aspect of inferential statistics is <strong>estimation</strong>: the process of estimating the value of a parameter from information obtained from a sample.</p>
<p>Sample measures (statistics) are used to estimate population measures (parameters) — a sample mean estimates a population mean, a sample proportion estimates a population proportion. Statistics used this way are called <strong>estimators</strong>.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Estimation</strong></p>
</div>
<div class="callout-content">
<p><strong>Estimation</strong> is the process of estimating the value of a parameter from information obtained from a sample.</p>
</div>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Common Assumptions for the Procedures in This Chapter</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>The sample must be <strong>randomly selected</strong>.</li>
<li>Either the sample size is <span class="math inline">n \geq 30</span>, <strong>or</strong> the population is normally or approximately normally distributed when <span class="math inline">n &lt; 30</span>.</li>
</ol>
<p>Check the second assumption with the Chapter 6 methods: look at the histogram for a bell shape, check for outliers, and inspect a normal quantile plot.</p>
</div>
</div>
</div>
</section>
<section id="point-estimates" class="slide level2">
<h2>Point Estimates</h2>
<p>A college president selects a random sample of 100 students and finds their average age to be 22.3 years. Inferring that the average age of <em>all</em> students is 22.3 years is a <strong>point estimate</strong>.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Point Estimate</strong></p>
</div>
<div class="callout-content">
<p>A <strong>point estimate</strong> is a specific numerical value estimate of a parameter. The best point estimate of the population mean <span class="math inline">\mu</span> is the sample mean <span class="math inline">\bar{X}</span>.</p>
</div>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Three Properties of a Good Estimator</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>The estimator should be an <strong>unbiased estimator</strong> — the expected value (the mean of the estimates obtained from samples of a given size) equals the parameter being estimated.</li>
<li>The estimator should be <strong>consistent</strong> — as the sample size increases, the value of the estimator approaches the value of the parameter estimated.</li>
<li>The estimator should be a <strong>relatively efficient estimator</strong> — of all the statistics that can be used to estimate a parameter, it has the smallest variance.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="interval-estimates" class="slide level2">
<h2>Interval Estimates</h2>
<p>A sample mean is almost always somewhat different from the population mean because of sampling error, and there is <strong>no way of knowing</strong> how close a particular point estimate is to <span class="math inline">\mu</span>. For that reason statisticians prefer an interval estimate.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Interval Estimate</strong></p>
</div>
<div class="callout-content">
<p>An <strong>interval estimate</strong> of a parameter is an interval or a range of values used to estimate the parameter. This estimate may or may not contain the value of the parameter being estimated.</p>
</div>
</div>
</div>
<p>An interval estimate for the average age of all students might be <span class="math inline">21.9 &lt; \mu &lt; 22.7</span>, or <span class="math inline">22.3 \pm 0.4</span> years. An interval estimate for a proportion might be <span class="math inline">0.107 &lt; p &lt; 0.113</span>, or <span class="math inline">11\% \pm 0.3\%</span>.</p>
<p>Confidence intervals may also be written with parentheses: <span class="math inline">(21.9,\ 22.7)</span> and <span class="math inline">(10.7\%,\ 11.3\%)</span>.</p>
</section>
<section id="confidence-level-and-confidence-interval" class="slide level2">
<h2>Confidence Level and Confidence Interval</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Confidence Level</strong></p>
</div>
<div class="callout-content">
<p>The <strong>confidence level</strong> of an interval estimate of a parameter is the probability that the interval estimate will contain the parameter, assuming that a large number of samples are selected and that the estimation process on the same parameter is repeated.</p>
</div>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Confidence Interval</strong></p>
</div>
<div class="callout-content">
<p>A <strong>confidence interval</strong> is a specific interval estimate of a parameter determined by using data obtained from a sample and by using the specific confidence level of the estimate.</p>
</div>
</div>
</div>
<p>Three common confidence intervals are used: the <strong>90%</strong>, the <strong>95%</strong>, and the <strong>99%</strong> confidence intervals.</p>
</section>
<section id="confidence-level-and-confidence-interval-1" class="slide level2">
<h2>Confidence Level and Confidence Interval</h2>
<p>A population has a fixed value for the mean or proportion. A confidence interval constructed from one sample either includes that parameter or it does not. If 95% confidence intervals were constructed for <strong>all possible samples</strong> of a specific size, 95% of them would contain the population parameter.</p>
<p>To be more confident — 99% instead of 95% — you must make the interval <strong>wider</strong>. A 99% interval for the mean age of college students might be <span class="math inline">21.7 &lt; \mu &lt; 22.9</span>, or <span class="math inline">22.3 \pm 0.6</span>. Hence a tradeoff occurs.</p>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Caution</strong></p>
</div>
<div class="callout-content">
<p>The confidence level describes the long-run behaviour of the <strong>procedure</strong>, not one particular interval. Once an interval has been computed, the parameter is either in it or it is not.</p>
</div>
</div>
</div>
</section>
<section id="the-critical-value-z_alpha2" class="slide level2">
<h2>The Critical Value <span class="math inline">z_{\alpha/2}</span></h2>
<p>The Greek letter <span class="math inline">\alpha</span> represents the total area in <strong>both</strong> tails of the standard normal distribution curve, and <span class="math inline">\alpha/2</span> represents the area in <strong>each</strong> tail. The value <span class="math inline">z_{\alpha/2}</span> is called a <strong>critical value</strong>.</p>
<p>The stated confidence level is the percentage equivalent of <span class="math inline">1 - \alpha</span>:</p>
<ul>
<li>95% confidence interval: <span class="math inline">\alpha = 0.05</span>, since <span class="math inline">1 - 0.05 = 0.95</span></li>
<li>99% confidence interval: <span class="math inline">\alpha = 0.01</span>, since <span class="math inline">1 - 0.01 = 0.99</span></li>
</ul>
</section>
<section id="the-critical-value-z_alpha2-1" class="slide level2">
<h2>The Critical Value <span class="math inline">z_{\alpha/2}</span></h2>
<p>Table A-4 is the paper route to these critical values; <code>qnorm()</code> is the R route. For a 95% confidence interval <span class="math inline">z_{\alpha/2} = 1.960</span>, and for a 99% confidence interval <span class="math inline">z_{\alpha/2} = 2.576</span>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href=""></a>confidence_level <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.90</span>, <span class="fl">0.95</span>, <span class="fl">0.99</span>)</span>
<span id="cb1-2"><a href=""></a>critical_z <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="dv">1</span> <span class="sc">-</span> (<span class="dv">1</span> <span class="sc">-</span> confidence_level) <span class="sc">/</span> <span class="dv">2</span>)</span>
<span id="cb1-3"><a href=""></a></span>
<span id="cb1-4"><a href=""></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">data.frame</span>(<span class="at">Confidence =</span> <span class="fu">paste0</span>(confidence_level <span class="sc">*</span> <span class="dv">100</span>, <span class="st">"%"</span>),</span>
<span id="cb1-5"><a href=""></a>                        <span class="at">alpha =</span> <span class="dv">1</span> <span class="sc">-</span> confidence_level,</span>
<span id="cb1-6"><a href=""></a>                        <span class="at">z =</span> <span class="fu">round</span>(critical_z, <span class="dv">3</span>)), <span class="at">align =</span> <span class="st">"c"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">Confidence</th>
<th style="text-align: center;">alpha</th>
<th style="text-align: center;">z</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">90%</td>
<td style="text-align: center;">0.10</td>
<td style="text-align: center;">1.645</td>
</tr>
<tr class="even">
<td style="text-align: center;">95%</td>
<td style="text-align: center;">0.05</td>
<td style="text-align: center;">1.960</td>
</tr>
<tr class="odd">
<td style="text-align: center;">99%</td>
<td style="text-align: center;">0.01</td>
<td style="text-align: center;">2.576</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="margin-of-error" class="slide level2">
<h2>Margin of Error</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Margin of Error</strong></p>
</div>
<div class="callout-content">
<p>The <strong>margin of error</strong>, also called the <strong>maximum error of the estimate</strong>, is the maximum likely difference between the point estimate of a parameter and the actual value of the parameter.</p>
</div>
</div>
</div>
<p>In the age-of-students example, where the confidence interval is <span class="math inline">21.9 &lt; \mu &lt; 22.7</span> or <span class="math inline">22.3 \pm 0.4</span>, the margin of error is <strong>0.4</strong>. For the proportion interval <span class="math inline">10.7\% &lt; p &lt; 11.3\%</span>, or <span class="math inline">11\% \pm 0.3\%</span>, the margin of error is <strong>0.003</strong>, or 0.3%.</p>
<p>For a specific value, say <span class="math inline">\alpha = 0.05</span>, 95% of the sample means or proportions will fall within this error value on either side of the population mean or proportion.</p>
</section>
<section id="confidence-intervals-in-r" class="slide level2">
<h2>95% Confidence Intervals in R</h2>
<p><strong>Prepare data</strong> — repeated sampling from a population with <span class="math inline">\mu = 50</span>, <span class="math inline">\sigma = 10</span>, <span class="math inline">n = 25</span>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href=""></a><span class="fu">set.seed</span>(<span class="dv">2023</span>)</span>
<span id="cb2-2"><a href=""></a>pop_mean <span class="ot">&lt;-</span> <span class="dv">50</span></span>
<span id="cb2-3"><a href=""></a>pop_sd <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb2-4"><a href=""></a>sample_size <span class="ot">&lt;-</span> <span class="dv">25</span></span>
<span id="cb2-5"><a href=""></a>margin_error <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="fl">0.975</span>) <span class="sc">*</span> pop_sd <span class="sc">/</span> <span class="fu">sqrt</span>(sample_size)</span>
<span id="cb2-6"><a href=""></a></span>
<span id="cb2-7"><a href=""></a>intervals <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb2-8"><a href=""></a>  <span class="at">sample_id =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">40</span>,</span>
<span id="cb2-9"><a href=""></a>  <span class="at">sample_mean =</span> <span class="fu">replicate</span>(<span class="dv">40</span>, <span class="fu">mean</span>(<span class="fu">rnorm</span>(sample_size, pop_mean, pop_sd)))) <span class="sc">|&gt;</span></span>
<span id="cb2-10"><a href=""></a>  <span class="fu">mutate</span>(<span class="at">lower =</span> sample_mean <span class="sc">-</span> margin_error,</span>
<span id="cb2-11"><a href=""></a>         <span class="at">upper =</span> sample_mean <span class="sc">+</span> margin_error,</span>
<span id="cb2-12"><a href=""></a>         <span class="at">result =</span> <span class="fu">if_else</span>(lower <span class="sc">&lt;=</span> pop_mean <span class="sc">&amp;</span> pop_mean <span class="sc">&lt;=</span> upper,</span>
<span id="cb2-13"><a href=""></a>                          <span class="st">"contains mu"</span>, <span class="st">"misses mu"</span>))</span>
<span id="cb2-14"><a href=""></a><span class="fu">sum</span>(intervals<span class="sc">$</span>result <span class="sc">==</span> <span class="st">"contains mu"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 38</code></pre>
</div>
</div>
</section>
<section id="confidence-intervals-in-r-1" class="slide level2">
<h2>95% Confidence Intervals in R</h2>
<p><strong>Draw figure</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href=""></a><span class="fu">ggplot</span>(intervals, <span class="fu">aes</span>(<span class="at">x =</span> sample_id, <span class="at">y =</span> sample_mean, <span class="at">color =</span> result)) <span class="sc">+</span></span>
<span id="cb4-2"><a href=""></a>  <span class="fu">geom_pointrange</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> lower, <span class="at">ymax =</span> upper)) <span class="sc">+</span></span>
<span id="cb4-3"><a href=""></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> pop_mean, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb4-4"><a href=""></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb4-5"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"95% Confidence Intervals for 40 Sample Means"</span>,</span>
<span id="cb4-6"><a href=""></a>       <span class="at">x =</span> <span class="st">"Sample"</span>, <span class="at">y =</span> <span class="st">"Sample mean"</span>, <span class="at">color =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb4-7"><a href=""></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="ch7_files/figure-revealjs/s7-1-3-1.png" class="quarto-figure quarto-figure-center r-stretch" style="width:80.0%"><p>About 95% of the intervals contain <span class="math inline">\mu</span>; the ones that miss are the price of sampling variability.</p>
</section></section>
<section>
<section id="section-7-2-confidence-intervals-for-the-mean-when-sigma-is-known" class="title-slide slide level1 center" data-background-color="#2c4a6e">
<h1>Section 7-2: Confidence Intervals for the Mean When <span class="math inline">\sigma</span> Is Known</h1>

</section>
<section id="assumptions-and-formula" class="slide level2">
<h2>Assumptions and Formula</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Assumptions for Finding a Confidence Interval for a Mean When <span class="math inline">\sigma</span> Is Known</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>The sample is a random sample.</li>
<li>Either <span class="math inline">n \geq 30</span> or the population is normally distributed when <span class="math inline">n &lt; 30</span>.</li>
</ol>
</div>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Robust</strong></p>
</div>
<div class="callout-content">
<p>A statistical technique is <strong>robust</strong> when the distribution of the variable can depart somewhat from normality and valid conclusions can still be obtained.</p>
</div>
</div>
</div>
<p>When you estimate a population mean you should use the <strong>sample mean</strong>: the means of samples vary less than medians or modes when many samples are drawn from the same population.</p>
</section>
<section id="assumptions-and-formula-1" class="slide level2">
<h2>Assumptions and Formula</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Formula for the Confidence Interval of the Mean When <span class="math inline">\sigma</span> Is Known</strong></p>
</div>
<div class="callout-content">
<p><span class="math display">\bar{X} - z_{\alpha/2}\left(\frac{\sigma}{\sqrt{n}}\right) &lt; \mu &lt; \bar{X} + z_{\alpha/2}\left(\frac{\sigma}{\sqrt{n}}\right)</span></p>
<p>For a 90% confidence interval <span class="math inline">z_{\alpha/2} = 1.645</span>; for a 95% confidence interval <span class="math inline">z_{\alpha/2} = 1.960</span>; and for a 99% confidence interval <span class="math inline">z_{\alpha/2} = 2.576</span>.</p>
<p>The term <span class="math inline">z_{\alpha/2}\left(\sigma/\sqrt{n}\right)</span> is the <strong>margin of error</strong>.</p>
</div>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Rounding Rule for a Confidence Interval for a Mean</strong></p>
</div>
<div class="callout-content">
<p>When computing a confidence interval for a population mean from <strong>raw data</strong>, round off to <strong>one more decimal place</strong> than the number of decimal places in the original data.</p>
<p>When computing it from a <strong>sample mean and a standard deviation</strong>, round off to the <strong>same number of decimal places</strong> as given for the mean.</p>
</div>
</div>
</div>
</section>
<section id="example-7-1" class="slide level2">
<h2>Example 7-1</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Air-Freight Transit Time to Osaka</strong></p>
</div>
<div class="callout-content">
<p>A logistics analyst at a Taipei freight forwarder wants to estimate the mean transit time, in hours, of air-freight shipments from Taoyuan to Osaka. A random sample of 49 shipments had a mean transit time of 34.0 hours. Company records give a population standard deviation of 2.8 hours. Find the best point estimate of the mean and the <strong>95% confidence interval</strong> for the population mean.</p>
<p><em>(hypothetical data)</em></p>
</div>
</div>
</div>
</section>
<section id="example-7-1-1" class="slide level2">
<h2>Example 7-1</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1</strong> The best point estimate of the mean is <strong>34.0 hours</strong>.</p>
<p><strong>Step 2</strong> For the 95% confidence interval, use <span class="math inline">z_{\alpha/2} = 1.96</span>.</p>
<p><span class="math display">34.0 - 1.96\left(\frac{2.8}{\sqrt{49}}\right) &lt; \mu &lt; 34.0 + 1.96\left(\frac{2.8}{\sqrt{49}}\right)</span> <span class="math display">34.0 - 0.8 &lt; \mu &lt; 34.0 + 0.8</span> <span class="math display">\mathbf{33.2 &lt; \mu &lt; 34.8}</span></p>
</div>
</div>
</div>
</section>
<section id="example-7-1-2" class="slide level2">
<h2>Example 7-1</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Compute in R</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href=""></a>sample_mean <span class="ot">&lt;-</span> <span class="fl">34.0</span></span>
<span id="cb5-2"><a href=""></a>pop_sd <span class="ot">&lt;-</span> <span class="fl">2.8</span></span>
<span id="cb5-3"><a href=""></a>sample_size <span class="ot">&lt;-</span> <span class="dv">49</span></span>
<span id="cb5-4"><a href=""></a></span>
<span id="cb5-5"><a href=""></a>margin_error <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="fl">0.975</span>) <span class="sc">*</span> pop_sd <span class="sc">/</span> <span class="fu">sqrt</span>(sample_size)</span>
<span id="cb5-6"><a href=""></a><span class="fu">round</span>(margin_error, <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href=""></a><span class="fu">round</span>(<span class="fu">c</span>(sample_mean <span class="sc">-</span> margin_error, sample_mean <span class="sc">+</span> margin_error), <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 33.2 34.8</code></pre>
</div>
</div>
<p>One can say with <strong>95% confidence</strong> that the interval between 33.2 and 34.8 hours contains the population mean transit time, based on a sample of 49 shipments.</p>
</div>
</div>
</div>
</section>
<section id="example-7-2" class="slide level2">
<h2>Example 7-2</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Value of Cross-Border Orders</strong></p>
</div>
<div class="callout-content">
<p>A cross-border e-commerce team wants to estimate the average value, in US dollars, of the orders its Taiwanese sellers ship overseas. A random sample of 64 orders had a mean value of 84.5 dollars. Assume the population standard deviation is 12.0 dollars. Find the best point estimate of the mean and the <strong>99% confidence interval</strong> of the population mean.</p>
<p><em>(hypothetical data)</em></p>
</div>
</div>
</div>
</section>
<section id="example-7-2-1" class="slide level2">
<h2>Example 7-2</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1</strong> The best point estimate of the population mean is <strong>84.5 dollars</strong>.</p>
<p><strong>Step 2</strong> Use <span class="math inline">z_{\alpha/2} = 2.576</span> for the 99% confidence interval.</p>
<p><span class="math display">84.5 - 2.576\left(\frac{12.0}{\sqrt{64}}\right) &lt; \mu &lt; 84.5 + 2.576\left(\frac{12.0}{\sqrt{64}}\right)</span> <span class="math display">84.5 - 3.9 &lt; \mu &lt; 84.5 + 3.9</span> <span class="math display">\mathbf{80.6 &lt; \mu &lt; 88.4}</span></p>
</div>
</div>
</div>
</section>
<section id="example-7-2-2" class="slide level2">
<h2>Example 7-2</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Compute in R</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href=""></a>sample_mean <span class="ot">&lt;-</span> <span class="fl">84.5</span></span>
<span id="cb9-2"><a href=""></a>pop_sd <span class="ot">&lt;-</span> <span class="fl">12.0</span></span>
<span id="cb9-3"><a href=""></a>sample_size <span class="ot">&lt;-</span> <span class="dv">64</span></span>
<span id="cb9-4"><a href=""></a></span>
<span id="cb9-5"><a href=""></a>margin_error <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="fl">0.995</span>) <span class="sc">*</span> pop_sd <span class="sc">/</span> <span class="fu">sqrt</span>(sample_size)</span>
<span id="cb9-6"><a href=""></a><span class="fu">round</span>(margin_error, <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.9</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href=""></a><span class="fu">round</span>(<span class="fu">c</span>(sample_mean <span class="sc">-</span> margin_error, sample_mean <span class="sc">+</span> margin_error), <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 80.6 88.4</code></pre>
</div>
</div>
<p>One can be <strong>99% confident</strong> that the mean value of a cross-border order is between 80.6 and 88.4 dollars.</p>
</div>
</div>
</div>
</section>
<section id="finding-other-values-of-z_alpha2" class="slide level2">
<h2>Finding Other Values of <span class="math inline">z_{\alpha/2}</span></h2>
<p>Confidence levels other than 90%, 95% and 99% are sometimes used. To find <span class="math inline">z_{\alpha/2}</span> for a <strong>98%</strong> confidence interval:</p>
<ol type="1">
<li>Change 98% to 0.98 and find <span class="math inline">\alpha = 1 - 0.98 = 0.02</span>.</li>
<li>Divide by 2: <span class="math inline">\alpha/2 = 0.02/2 = 0.01</span>.</li>
<li>Subtract 0.01 from 1.0000 to get 0.9900. That is the area you look up in Table A-4, and <code>qnorm(0.99)</code> returns the same critical value, <span class="math inline">z_{\alpha/2} = \mathbf{2.326}</span>.</li>
</ol>
</section>
<section id="finding-other-values-of-z_alpha2-1" class="slide level2">
<h2>Finding Other Values of <span class="math inline">z_{\alpha/2}</span></h2>
<p>For confidence intervals, only the <strong>positive</strong> <span class="math inline">z</span> score is used in the formula.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href=""></a>confidence_level <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.90</span>, <span class="fl">0.94</span>, <span class="fl">0.95</span>, <span class="fl">0.98</span>, <span class="fl">0.99</span>)</span>
<span id="cb13-2"><a href=""></a>tail_area <span class="ot">&lt;-</span> (<span class="dv">1</span> <span class="sc">-</span> confidence_level) <span class="sc">/</span> <span class="dv">2</span></span>
<span id="cb13-3"><a href=""></a></span>
<span id="cb13-4"><a href=""></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">data.frame</span>(<span class="at">Confidence =</span> <span class="fu">paste0</span>(confidence_level <span class="sc">*</span> <span class="dv">100</span>, <span class="st">"%"</span>),</span>
<span id="cb13-5"><a href=""></a>                        <span class="at">alpha_half =</span> tail_area,</span>
<span id="cb13-6"><a href=""></a>                        <span class="at">z =</span> <span class="fu">round</span>(<span class="fu">qnorm</span>(<span class="dv">1</span> <span class="sc">-</span> tail_area), <span class="dv">3</span>)), <span class="at">align =</span> <span class="st">"c"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">Confidence</th>
<th style="text-align: center;">alpha_half</th>
<th style="text-align: center;">z</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">90%</td>
<td style="text-align: center;">0.050</td>
<td style="text-align: center;">1.645</td>
</tr>
<tr class="even">
<td style="text-align: center;">94%</td>
<td style="text-align: center;">0.030</td>
<td style="text-align: center;">1.881</td>
</tr>
<tr class="odd">
<td style="text-align: center;">95%</td>
<td style="text-align: center;">0.025</td>
<td style="text-align: center;">1.960</td>
</tr>
<tr class="even">
<td style="text-align: center;">98%</td>
<td style="text-align: center;">0.010</td>
<td style="text-align: center;">2.326</td>
</tr>
<tr class="odd">
<td style="text-align: center;">99%</td>
<td style="text-align: center;">0.005</td>
<td style="text-align: center;">2.576</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="example-7-3" class="slide level2">
<h2>Example 7-3</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Container Dwell Time at Kaohsiung Port</strong></p>
</div>
<div class="callout-content">
<p>The following data represent the dwell time, in hours, of a random sample of 30 import containers at the Port of Kaohsiung. Assume the population standard deviation is 12.6 hours. Find the <strong>90% confidence interval</strong> of the mean.</p>
<pre><code>36.42    28.15    51.70
19.83    44.26    33.08
62.55    25.71    40.19
47.63    30.94    22.38
55.02    38.47    29.66
43.81    26.50    58.24
34.75    49.12    21.07
31.89    45.33    27.46
53.18    37.62    24.91
41.05    32.27    46.88</code></pre>
<p><em>(hypothetical data)</em></p>
</div>
</div>
</div>
</section>
<section id="example-7-3-1" class="slide level2">
<h2>Example 7-3</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1</strong> Find the mean for the data: <span class="math inline">\bar{X} = 38.002</span> hours. The population standard deviation is 12.6 hours.</p>
<p><strong>Step 2</strong> Find <span class="math inline">\alpha/2</span>. For a 90% confidence interval, <span class="math inline">\alpha = 1 - 0.90 = 0.10</span> and <span class="math inline">\alpha/2 = 0.10/2 = 0.05</span>.</p>
<p><strong>Step 3</strong> Find <span class="math inline">z_{\alpha/2}</span>. The area to the left of the critical value is <span class="math inline">1 - 0.05 = 0.9500</span>; that is the column you look up in Table A-4, and <code>qnorm(0.95)</code> returns the same critical value, <span class="math inline">z_{\alpha/2} = \mathbf{1.645}</span>.</p>
<p><strong>Step 4</strong> Substitute in the formula.</p>
<p><span class="math display">38.002 - 1.645\left(\frac{12.6}{\sqrt{30}}\right) &lt; \mu &lt; 38.002 + 1.645\left(\frac{12.6}{\sqrt{30}}\right)</span> <span class="math display">38.002 - 3.784 &lt; \mu &lt; 38.002 + 3.784</span> <span class="math display">\mathbf{34.218 &lt; \mu &lt; 41.786}</span></p>
</div>
</div>
</div>
</section>
<section id="example-7-3-2" class="slide level2">
<h2>Example 7-3</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Compute in R</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href=""></a>dwell_hours <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">36.42</span>, <span class="fl">28.15</span>, <span class="fl">51.70</span>, <span class="fl">19.83</span>, <span class="fl">44.26</span>, <span class="fl">33.08</span>, <span class="fl">62.55</span>, <span class="fl">25.71</span>, <span class="fl">40.19</span>, <span class="fl">47.63</span>,</span>
<span id="cb15-2"><a href=""></a>                 <span class="fl">30.94</span>, <span class="fl">22.38</span>, <span class="fl">55.02</span>, <span class="fl">38.47</span>, <span class="fl">29.66</span>, <span class="fl">43.81</span>, <span class="fl">26.50</span>, <span class="fl">58.24</span>, <span class="fl">34.75</span>, <span class="fl">49.12</span>,</span>
<span id="cb15-3"><a href=""></a>                 <span class="fl">21.07</span>, <span class="fl">31.89</span>, <span class="fl">45.33</span>, <span class="fl">27.46</span>, <span class="fl">53.18</span>, <span class="fl">37.62</span>, <span class="fl">24.91</span>, <span class="fl">41.05</span>, <span class="fl">32.27</span>, <span class="fl">46.88</span>)</span>
<span id="cb15-4"><a href=""></a>sample_mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(dwell_hours)</span>
<span id="cb15-5"><a href=""></a>pop_sd <span class="ot">&lt;-</span> <span class="fl">12.6</span></span>
<span id="cb15-6"><a href=""></a></span>
<span id="cb15-7"><a href=""></a>margin_error <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="fl">0.95</span>) <span class="sc">*</span> pop_sd <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">length</span>(dwell_hours))</span>
<span id="cb15-8"><a href=""></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">mean =</span> sample_mean, <span class="at">margin =</span> margin_error), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  mean margin 
38.002  3.784 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href=""></a><span class="fu">round</span>(<span class="fu">c</span>(sample_mean <span class="sc">-</span> margin_error, sample_mean <span class="sc">+</span> margin_error), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 34.218 41.786</code></pre>
</div>
</div>
<p>One can be <strong>90% confident</strong> that the mean dwell time of all import containers is between 34.218 and 41.786 hours, based on a sample of 30 containers.</p>
</div>
</div>
</div>
</section>
<section id="sample-size-for-estimating-a-mean" class="slide level2">
<h2>Sample Size for Estimating a Mean</h2>
<p>How large a sample is necessary to make an accurate estimate? The answer depends on three things: the <strong>margin of error</strong>, the <strong>population standard deviation</strong>, and the <strong>degree of confidence</strong>.</p>
<p>The formula is derived from the margin-of-error formula <span class="math inline">E = z_{\alpha/2}\left(\sigma/\sqrt{n}\right)</span>, solved for <span class="math inline">n</span>:</p>
<p><span class="math display">E\sqrt{n} = z_{\alpha/2}\,\sigma \quad \Longrightarrow \quad \sqrt{n} = \frac{z_{\alpha/2} \cdot \sigma}{E}</span></p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Formula for the Minimum Sample Size Needed for an Interval Estimate of the Population Mean</strong></p>
</div>
<div class="callout-content">
<p><span class="math display">n = \left(\frac{z_{\alpha/2} \cdot \sigma}{E}\right)^2</span></p>
<p>where <span class="math inline">E</span> is the margin of error. If necessary, <strong>round the answer up</strong> to obtain a whole number: if there is any fraction or decimal portion in the answer, use the next whole number for <span class="math inline">n</span>.</p>
</div>
</div>
</div>
</section>
<section id="example-7-4" class="slide level2">
<h2>Example 7-4</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Sample Size for Delivery Time</strong></p>
</div>
<div class="callout-content">
<p>An operations manager at a food-delivery platform in Taichung wishes to estimate the average delivery time per order to within <strong>2 minutes</strong>. She wishes to be <strong>99% confident</strong>, and a previous study puts the standard deviation at 4.5 minutes. How many orders should she sample?</p>
<p><em>(hypothetical data)</em></p>
</div>
</div>
</div>
</section>
<section id="example-7-4-1" class="slide level2">
<h2>Example 7-4</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p>Since <span class="math inline">\alpha = 0.01</span> (or <span class="math inline">1 - 0.99</span>), <span class="math inline">z_{\alpha/2} = 2.576</span> and <span class="math inline">E = 2</span>. Substitute in the formula.</p>
<p><span class="math display">n = \left(\frac{z_{\alpha/2} \cdot \sigma}{E}\right)^2 = \left[\frac{(2.576)(4.5)}{2}\right]^2 = 33.59</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href=""></a>pop_sd <span class="ot">&lt;-</span> <span class="fl">4.5</span></span>
<span id="cb19-2"><a href=""></a>margin_error <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb19-3"><a href=""></a></span>
<span id="cb19-4"><a href=""></a>required_n <span class="ot">&lt;-</span> (<span class="fu">qnorm</span>(<span class="fl">0.995</span>) <span class="sc">*</span> pop_sd <span class="sc">/</span> margin_error)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb19-5"><a href=""></a><span class="fu">round</span>(required_n, <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 33.59</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href=""></a><span class="fu">ceiling</span>(required_n)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 34</code></pre>
</div>
</div>
<p>Round the value up to <strong>34</strong>. To be 99% confident that the estimate is within 2 minutes of the true mean, the manager needs to sample at least 34 orders.</p>
</div>
</div>
</div>
</section>
<section id="notes-on-sample-size" class="slide level2">
<h2>Notes on Sample Size</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Caution</strong></p>
</div>
<div class="callout-content">
<p>In most cases in statistics we round off; however, when determining sample size we <strong>always round up</strong> to the next whole number.</p>
</div>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Practical Points</strong></p>
</div>
<div class="callout-content">
<ul>
<li>When the population is large or infinite, or when sampling is done with replacement, the <strong>size of the population is irrelevant</strong> to the sample size calculation.</li>
<li>The formula requires <span class="math inline">\sigma</span>. When <span class="math inline">\sigma</span> is unknown, estimate it with the standard deviation <span class="math inline">s</span> from a previous sample, or by dividing the <strong>range by 4</strong>.</li>
<li>An interval estimate is often reported in words: “an American family of two spends an average of $84 per week for groceries, accurate within $3 with 95% confidence” means <span class="math inline">81 &lt; \mu &lt; 87</span>.</li>
</ul>
</div>
</div>
</div>
</section></section>
<section>
<section id="section-7-3-confidence-intervals-for-the-mean-when-sigma-is-unknown" class="title-slide slide level1 center" data-background-color="#2c4a6e">
<h1>Section 7-3: Confidence Intervals for the Mean When <span class="math inline">\sigma</span> Is Unknown</h1>

</section>
<section id="the-t-distribution" class="slide level2">
<h2>The <span class="math inline">t</span> Distribution</h2>
<p>Usually <span class="math inline">\sigma</span> is unknown and is estimated by <span class="math inline">s</span>. Critical values <strong>greater</strong> than <span class="math inline">z_{\alpha/2}</span> are then needed, especially for small <span class="math inline">n</span>; they come from the <strong>Student’s <span class="math inline">t</span> distribution</strong>.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Characteristics of the <span class="math inline">t</span> Distribution</strong></p>
</div>
<div class="callout-content">
<p><strong>Similar to the standard normal distribution:</strong></p>
<ol type="1">
<li>It is bell-shaped.</li>
<li>It is symmetric about the mean.</li>
<li>The mean, median and mode are equal to 0 and are located at the center of the distribution.</li>
<li>The curve approaches but never touches the <span class="math inline">x</span> axis.</li>
</ol>
<p><strong>Different from the standard normal distribution:</strong></p>
<ol type="1">
<li>The variance is greater than 1.</li>
<li>The <span class="math inline">t</span> distribution is a <strong>family of curves</strong> based on degrees of freedom, which is related to sample size.</li>
<li>As the sample size increases, the <span class="math inline">t</span> distribution approaches the standard normal distribution.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="the-t-family-of-curves" class="slide level2">
<h2>The <span class="math inline">t</span> Family of Curves</h2>
<p><strong>Prepare data</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href=""></a>grid_x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">4</span>, <span class="dv">4</span>, <span class="at">length.out =</span> <span class="dv">300</span>)</span>
<span id="cb23-2"><a href=""></a></span>
<span id="cb23-3"><a href=""></a>t_curves <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb23-4"><a href=""></a>  <span class="at">x =</span> <span class="fu">rep</span>(grid_x, <span class="dv">3</span>),</span>
<span id="cb23-5"><a href=""></a>  <span class="at">density =</span> <span class="fu">c</span>(<span class="fu">dnorm</span>(grid_x), <span class="fu">dt</span>(grid_x, <span class="at">df =</span> <span class="dv">5</span>), <span class="fu">dt</span>(grid_x, <span class="at">df =</span> <span class="dv">20</span>)),</span>
<span id="cb23-6"><a href=""></a>  <span class="at">curve =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"z curve"</span>, <span class="st">"t for d.f. = 5"</span>, <span class="st">"t for d.f. = 20"</span>),</span>
<span id="cb23-7"><a href=""></a>              <span class="at">each =</span> <span class="fu">length</span>(grid_x)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="the-t-family-of-curves-1" class="slide level2">
<h2>The <span class="math inline">t</span> Family of Curves</h2>
<p><strong>Draw figure</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href=""></a><span class="fu">ggplot</span>(t_curves, <span class="fu">aes</span>(x, density, <span class="at">color =</span> curve, <span class="at">linetype =</span> curve)) <span class="sc">+</span></span>
<span id="cb24-2"><a href=""></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb24-3"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"The t Family of Curves"</span>,</span>
<span id="cb24-4"><a href=""></a>       <span class="at">x =</span> <span class="st">"Value"</span>, <span class="at">y =</span> <span class="st">"Density"</span>, <span class="at">color =</span> <span class="st">""</span>, <span class="at">linetype =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb24-5"><a href=""></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="ch7_files/figure-revealjs/s7-3-2-1.png" class="quarto-figure quarto-figure-center r-stretch" style="width:80.0%"></section>
<section id="degrees-of-freedom" class="slide level2">
<h2>Degrees of Freedom</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Degrees of Freedom</strong></p>
</div>
<div class="callout-content">
<p>The <strong>degrees of freedom</strong> are the number of values that are free to vary after a sample statistic has been computed, and they tell the researcher which specific curve to use when a distribution consists of a family of curves.</p>
</div>
</div>
</div>
<p>If the mean of 5 values is 10, then 4 of the 5 values are free to vary; once 4 are chosen the fifth must be a specific number so that the sum is 50. Hence <span class="math inline">\text{d.f.} = 5 - 1 = 4</span>.</p>
<p>The symbol <strong>d.f.</strong> is used for degrees of freedom. For a confidence interval for the mean, <span class="math inline">\text{d.f.} = n - 1</span>. (For some tests later in the book the degrees of freedom are <em>not</em> <span class="math inline">n - 1</span>.)</p>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Caution</strong></p>
</div>
<div class="callout-content">
<p>The values <span class="math inline">t_{\alpha/2}</span> come from the row labelled <strong>Confidence Intervals</strong> at the top of Table A-5. The rows labelled <em>One tail</em> and <em>Two tails</em> belong to Chapter 8 and should not be used here. When d.f. is greater than 30 and falls between two printed rows, the table convention is to <strong>round d.f. down</strong> to the nearest row (a conservative choice): d.f. = 68 is read as 65. That convention is a lookup aid; <code>qt()</code> takes the exact d.f., and where the two differ these slides report the value R computes.</p>
</div>
</div>
</div>
</section>
<section id="example-7-5" class="slide level2">
<h2>Example 7-5</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Finding a <span class="math inline">t</span> Critical Value</strong></p>
</div>
<div class="callout-content">
<p>Find the <span class="math inline">t_{\alpha/2}</span> value for a <strong>95% confidence interval</strong> when the sample size is 18.</p>
</div>
</div>
</div>
</section>
<section id="example-7-5-1" class="slide level2">
<h2>Example 7-5</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p>The <span class="math inline">\text{d.f.} = 18 - 1</span>, or 17. Find 17 in the left column of Table A-5 and 95% in the row labelled <strong>Confidence Intervals</strong>; <code>qt(0.975, df = 17)</code> returns the same critical value, <span class="math inline">t_{\alpha/2} = \mathbf{2.110}</span>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href=""></a>sample_size <span class="ot">&lt;-</span> <span class="dv">18</span></span>
<span id="cb25-2"><a href=""></a></span>
<span id="cb25-3"><a href=""></a><span class="fu">round</span>(<span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="at">df =</span> sample_size <span class="sc">-</span> <span class="dv">1</span>), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.11</code></pre>
</div>
</div>
<p>In R a confidence-interval critical value is always <code>qt(1 - alpha/2, df = n - 1)</code>; for a 95% interval that is <code>qt(0.975, df = n - 1)</code>.</p>
</div>
</div>
</div>
</section>
<section id="formula-for-the-mean-when-sigma-is-unknown" class="slide level2">
<h2>Formula for the Mean When <span class="math inline">\sigma</span> Is Unknown</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Formula for a Specific Confidence Interval for the Mean When <span class="math inline">\sigma</span> Is Unknown</strong></p>
</div>
<div class="callout-content">
<p><span class="math display">\bar{X} - t_{\alpha/2}\left(\frac{s}{\sqrt{n}}\right) &lt; \mu &lt; \bar{X} + t_{\alpha/2}\left(\frac{s}{\sqrt{n}}\right)</span></p>
<p>The degrees of freedom are <span class="math inline">n - 1</span>.</p>
</div>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Assumptions for Finding a Confidence Interval for a Mean When <span class="math inline">\sigma</span> Is Unknown</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>The sample is a random sample.</li>
<li>Either <span class="math inline">n \geq 30</span> or the population is normally distributed when <span class="math inline">n &lt; 30</span>.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="example-7-6" class="slide level2">
<h2>Example 7-6</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Weekday Occupancy of Taipei Hotels</strong></p>
</div>
<div class="callout-content">
<p>A random sample of 16 business hotels in Taipei had a mean weekday occupancy rate of 72.4%. The standard deviation of the sample was 6.8 percentage points. Assume the variable is normally distributed. Find the <strong>95% confidence interval</strong> of the population mean weekday occupancy rate.</p>
<p><em>(hypothetical data)</em></p>
</div>
</div>
</div>
</section>
<section id="example-7-6-1" class="slide level2">
<h2>Example 7-6</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><span class="math inline">\bar{X} = 72.4</span>, <span class="math inline">s = 6.8</span>, <span class="math inline">n = 16</span>.</p>
<p>Since <span class="math inline">\sigma</span> is unknown and <span class="math inline">s</span> must replace it, the <span class="math inline">t</span> distribution is used. With 15 degrees of freedom, <span class="math inline">t_{\alpha/2} = 2.131</span>.</p>
<p><span class="math display">72.4 - 2.131\left(\frac{6.8}{\sqrt{16}}\right) &lt; \mu &lt; 72.4 + 2.131\left(\frac{6.8}{\sqrt{16}}\right)</span> <span class="math display">72.4 - 3.6 &lt; \mu &lt; 72.4 + 3.6</span> <span class="math display">\mathbf{68.8 &lt; \mu &lt; 76.0}</span></p>
</div>
</div>
</div>
</section>
<section id="example-7-6-2" class="slide level2">
<h2>Example 7-6</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Compute in R</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href=""></a>sample_mean <span class="ot">&lt;-</span> <span class="fl">72.4</span></span>
<span id="cb27-2"><a href=""></a>sample_sd <span class="ot">&lt;-</span> <span class="fl">6.8</span></span>
<span id="cb27-3"><a href=""></a>sample_size <span class="ot">&lt;-</span> <span class="dv">16</span></span>
<span id="cb27-4"><a href=""></a></span>
<span id="cb27-5"><a href=""></a>margin_error <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="at">df =</span> sample_size <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> sample_sd <span class="sc">/</span> <span class="fu">sqrt</span>(sample_size)</span>
<span id="cb27-6"><a href=""></a><span class="fu">round</span>(margin_error, <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.6</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href=""></a><span class="fu">round</span>(<span class="fu">c</span>(sample_mean <span class="sc">-</span> margin_error, sample_mean <span class="sc">+</span> margin_error), <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 68.8 76.0</code></pre>
</div>
</div>
<p>One can be <strong>95% confident</strong> that the population mean weekday occupancy rate of Taipei business hotels is between 68.8% and 76.0%.</p>
</div>
</div>
</div>
</section>
<section id="example-7-7" class="slide level2">
<h2>Example 7-7</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Monthly Revenue of a Night-Market Stall</strong></p>
</div>
<div class="callout-content">
<p>The data represent the monthly revenue, in thousands of NT dollars, of a night-market beverage stall for a random sample of 7 months. Find the <strong>99% confidence interval</strong> for the mean monthly revenue.</p>
<pre><code>268    292    305    318    331    347    384</code></pre>
<p><em>(hypothetical data)</em></p>
</div>
</div>
</div>
</section>
<section id="example-7-7-1" class="slide level2">
<h2>Example 7-7</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1</strong> Find the mean and standard deviation for the data: <span class="math inline">\bar{X} = 320.7</span> and <span class="math inline">s = 38.0</span>.</p>
<p><strong>Step 2</strong> Find <span class="math inline">t_{\alpha/2}</span> for a 99% confidence interval with <span class="math inline">\text{d.f.} = 6</span>. Table A-5 and <code>qt(0.995, df = 6)</code> both give <strong>3.707</strong>.</p>
<p><strong>Step 3</strong> Substitute in the formula and solve.</p>
<p><span class="math display">320.7 - 3.707\left(\frac{38.0}{\sqrt{7}}\right) &lt; \mu &lt; 320.7 + 3.707\left(\frac{38.0}{\sqrt{7}}\right)</span> <span class="math display">320.7 - 53.2 &lt; \mu &lt; 320.7 + 53.2</span> <span class="math display">\mathbf{267.5 &lt; \mu &lt; 373.9}</span></p>
</div>
</div>
</div>
</section>
<section id="example-7-7-2" class="slide level2">
<h2>Example 7-7</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Compute in R</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href=""></a>monthly_revenue <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">268</span>, <span class="dv">292</span>, <span class="dv">305</span>, <span class="dv">318</span>, <span class="dv">331</span>, <span class="dv">347</span>, <span class="dv">384</span>)</span>
<span id="cb32-2"><a href=""></a>sample_size <span class="ot">&lt;-</span> <span class="fu">length</span>(monthly_revenue)</span>
<span id="cb32-3"><a href=""></a>sample_mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(monthly_revenue)</span>
<span id="cb32-4"><a href=""></a>sample_sd <span class="ot">&lt;-</span> <span class="fu">sd</span>(monthly_revenue)</span>
<span id="cb32-5"><a href=""></a></span>
<span id="cb32-6"><a href=""></a>margin_error <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="fl">0.995</span>, <span class="at">df =</span> sample_size <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> sample_sd <span class="sc">/</span> <span class="fu">sqrt</span>(sample_size)</span>
<span id="cb32-7"><a href=""></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">mean =</span> sample_mean, <span class="at">sd =</span> sample_sd, <span class="at">margin =</span> margin_error), <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  mean     sd margin 
 320.7   38.0   53.2 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href=""></a><span class="fu">round</span>(<span class="fu">c</span>(sample_mean <span class="sc">-</span> margin_error, sample_mean <span class="sc">+</span> margin_error), <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 267.5 373.9</code></pre>
</div>
</div>
<p>One can be <strong>99% confident</strong> that the mean monthly revenue of the stall is between 267.5 and 373.9 thousand NT dollars, based on a sample of 7 months.</p>
</div>
</div>
</div>
</section>
<section id="when-to-use-z-or-t" class="slide level2">
<h2>When to Use <span class="math inline">z</span> or <span class="math inline">t</span></h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Decision Rule (Figure 7-8)</strong></p>
</div>
<div class="callout-content">
<ul>
<li><strong>Is <span class="math inline">\sigma</span> known?</strong> Yes: use <span class="math inline">z_{\alpha/2}</span> values and <span class="math inline">\sigma</span> in the formula.</li>
<li><strong>Is <span class="math inline">\sigma</span> known?</strong> No: use <span class="math inline">t_{\alpha/2}</span> values and <span class="math inline">s</span> in the formula.</li>
</ul>
<p>In either case, if <span class="math inline">n &lt; 30</span> the variable must be normally distributed.</p>
</div>
</div>
</div>
</section>
<section id="when-to-use-z-or-t-1" class="slide level2">
<h2>When to Use <span class="math inline">z</span> or <span class="math inline">t</span></h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href=""></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">data.frame</span>(</span>
<span id="cb36-2"><a href=""></a>  <span class="at">Situation =</span> <span class="fu">c</span>(<span class="st">"sigma known, n &gt;= 30"</span>, <span class="st">"sigma known, n &lt; 30 (normal)"</span>,</span>
<span id="cb36-3"><a href=""></a>                <span class="st">"sigma unknown, n &gt;= 30"</span>, <span class="st">"sigma unknown, n &lt; 30 (normal)"</span>),</span>
<span id="cb36-4"><a href=""></a>  <span class="at">Use =</span> <span class="fu">c</span>(<span class="st">"z and sigma"</span>, <span class="st">"z and sigma"</span>, <span class="st">"t and s"</span>, <span class="st">"t and s"</span>),</span>
<span id="cb36-5"><a href=""></a>  <span class="at">R =</span> <span class="fu">c</span>(<span class="st">"qnorm(1 - alpha/2)"</span>, <span class="st">"qnorm(1 - alpha/2)"</span>,</span>
<span id="cb36-6"><a href=""></a>        <span class="st">"qt(1 - alpha/2, df = n - 1)"</span>, <span class="st">"qt(1 - alpha/2, df = n - 1)"</span>)),</span>
<span id="cb36-7"><a href=""></a>  <span class="at">align =</span> <span class="st">"c"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top">
<colgroup>
<col style="width: 43%">
<col style="width: 17%">
<col style="width: 39%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Situation</th>
<th style="text-align: center;">Use</th>
<th style="text-align: center;">R</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">sigma known, n &gt;= 30</td>
<td style="text-align: center;">z and sigma</td>
<td style="text-align: center;">qnorm(1 - alpha/2)</td>
</tr>
<tr class="even">
<td style="text-align: center;">sigma known, n &lt; 30 (normal)</td>
<td style="text-align: center;">z and sigma</td>
<td style="text-align: center;">qnorm(1 - alpha/2)</td>
</tr>
<tr class="odd">
<td style="text-align: center;">sigma unknown, n &gt;= 30</td>
<td style="text-align: center;">t and s</td>
<td style="text-align: center;">qt(1 - alpha/2, df = n - 1)</td>
</tr>
<tr class="even">
<td style="text-align: center;">sigma unknown, n &lt; 30 (normal)</td>
<td style="text-align: center;">t and s</td>
<td style="text-align: center;">qt(1 - alpha/2, df = n - 1)</td>
</tr>
</tbody>
</table>
</div>
</div>
</section></section>
<section>
<section id="section-7-4-confidence-intervals-and-sample-size-for-proportions" class="title-slide slide level1 center" data-background-color="#2c4a6e">
<h1>Section 7-4: Confidence Intervals and Sample Size for Proportions</h1>

</section>
<section id="proportions" class="slide level2">
<h2>Proportions</h2>
<p>A <strong>proportion</strong> represents a part of a whole; it can be expressed as a fraction, a decimal or a percentage. If 12% of the parcels a courier delivers in Taipei go to a convenience-store pickup point, then <span class="math inline">12\% = 0.12 = \frac{12}{100} = \frac{3}{25}</span>, and the probability that a randomly selected parcel goes to a pickup point is 0.12.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Symbols Used in Proportion Notation</strong></p>
</div>
<div class="callout-content">
<p><span class="math display">p = \text{population proportion} \qquad \hat{p} = \text{sample proportion (read "p hat")}</span></p>
<p>For a sample proportion,</p>
<p><span class="math display">\hat{p} = \frac{X}{n} \qquad \text{and} \qquad \hat{q} = \frac{n - X}{n} \quad \text{or} \quad \hat{q} = 1 - \hat{p}</span></p>
<p>where <span class="math inline">X</span> is the number of sample units that possess the characteristic of interest and <span class="math inline">n</span> is the sample size.</p>
</div>
</div>
</div>
<p>When <span class="math inline">\hat{p}</span> and <span class="math inline">\hat{q}</span> are in decimal or fraction form, <span class="math inline">\hat{p} + \hat{q} = 1</span>; when they are percentages, <span class="math inline">\hat{p} + \hat{q} = 100\%</span>. The same relations hold for the population: <span class="math inline">p + q = 1</span>.</p>
</section>
<section id="example-7-8" class="slide level2">
<h2>Example 7-8</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Convenience-Store Pickup</strong></p>
</div>
<div class="callout-content">
<p>A random sample of 180 online shoppers on a Taiwanese e-commerce platform found that 63 chose convenience-store pickup instead of home delivery. Find <span class="math inline">\hat{p}</span> and <span class="math inline">\hat{q}</span>, where <span class="math inline">\hat{p}</span> is the proportion of shoppers who chose convenience-store pickup.</p>
<p><em>(hypothetical data)</em></p>
</div>
</div>
</div>
</section>
<section id="example-7-8-1" class="slide level2">
<h2>Example 7-8</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p>In this case, <span class="math inline">X = 63</span> and <span class="math inline">n = 180</span>.</p>
<p><span class="math display">\hat{p} = \frac{X}{n} = \frac{63}{180} = 0.35 = 35\%</span> <span class="math display">\hat{q} = \frac{n - X}{n} = \frac{180 - 63}{180} = \frac{117}{180} = 0.65 = 65\%</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href=""></a>pickup_count <span class="ot">&lt;-</span> <span class="dv">63</span></span>
<span id="cb37-2"><a href=""></a>sample_size <span class="ot">&lt;-</span> <span class="dv">180</span></span>
<span id="cb37-3"><a href=""></a></span>
<span id="cb37-4"><a href=""></a>p_hat <span class="ot">&lt;-</span> pickup_count <span class="sc">/</span> sample_size</span>
<span id="cb37-5"><a href=""></a><span class="fu">c</span>(<span class="at">p_hat =</span> p_hat, <span class="at">q_hat =</span> <span class="dv">1</span> <span class="sc">-</span> p_hat)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>p_hat q_hat 
 0.35  0.65 </code></pre>
</div>
</div>
<p>So <strong>65%</strong> of the shoppers chose home delivery instead.</p>
</div>
</div>
</div>
</section>
<section id="confidence-intervals-for-a-proportion" class="slide level2">
<h2>Confidence Intervals for a Proportion</h2>
<p>For a point estimate of <span class="math inline">p</span>, the sample proportion <span class="math inline">\hat{p}</span> is used; it is unbiased, consistent and relatively efficient. When <span class="math inline">n</span> is no more than 5% of the population size, the sampling distribution of <span class="math inline">\hat{p}</span> is approximately normal with mean <span class="math inline">p</span> and standard deviation <span class="math inline">\sqrt{pq/n}</span>.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Formula for a Specific Confidence Interval for a Proportion</strong></p>
</div>
<div class="callout-content">
<p><span class="math display">\hat{p} - z_{\alpha/2}\sqrt{\frac{\hat{p}\hat{q}}{n}} &lt; p &lt; \hat{p} + z_{\alpha/2}\sqrt{\frac{\hat{p}\hat{q}}{n}}</span></p>
<p>when <span class="math inline">n\hat{p}</span> and <span class="math inline">n\hat{q}</span> are each greater than or equal to 5. The margin of error is <span class="math inline">E = z_{\alpha/2}\sqrt{\hat{p}\hat{q}/n}</span>.</p>
</div>
</div>
</div>
</section>
<section id="confidence-intervals-for-a-proportion-1" class="slide level2">
<h2>Confidence Intervals for a Proportion</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Assumptions for Finding a Confidence Interval for a Population Proportion</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>The sample is a random sample.</li>
<li>The conditions for a binomial experiment are satisfied (see Chapter 5).</li>
</ol>
</div>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Rounding Rule for a Confidence Interval for a Proportion</strong></p>
</div>
<div class="callout-content">
<p>Round off to <strong>three decimal places</strong>.</p>
</div>
</div>
</div>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Caution</strong></p>
</div>
<div class="callout-content">
<p>When a specific percentage is given in a problem, that percentage becomes <span class="math inline">\hat{p}</span> once it is changed to a decimal. If 12% of the applicants were men, then <span class="math inline">\hat{p} = 0.12</span>.</p>
</div>
</div>
</div>
</section>
<section id="example-7-9" class="slide level2">
<h2>Example 7-9</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Transfer Experience at Taoyuan Airport</strong></p>
</div>
<div class="callout-content">
<p>A passenger survey at Taoyuan International Airport sampled 1250 transfer passengers, and 375 of them rated the transfer experience as excellent. Find the <strong>90% confidence interval</strong> of the true proportion of transfer passengers who rate the experience as excellent.</p>
<p><em>(hypothetical data)</em></p>
</div>
</div>
</div>
</section>
<section id="example-7-9-1" class="slide level2">
<h2>Example 7-9</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1</strong> Determine <span class="math inline">\hat{p}</span> and <span class="math inline">\hat{q}</span>.</p>
<p><span class="math display">\hat{p} = \frac{X}{n} = \frac{375}{1250} = 0.30 \qquad \hat{q} = 1 - \hat{p} = 1.00 - 0.30 = 0.70</span></p>
<p><strong>Step 2</strong> Determine the critical value. <span class="math inline">\alpha = 1 - 0.90 = 0.10</span>, so <span class="math inline">\alpha/2 = 0.05</span> and <span class="math inline">z_{\alpha/2} = 1.645</span>.</p>
<p><strong>Step 3</strong> Substitute in the formula.</p>
<p><span class="math display">0.30 - 1.645\sqrt{\frac{(0.30)(0.70)}{1250}} &lt; p &lt; 0.30 + 1.645\sqrt{\frac{(0.30)(0.70)}{1250}}</span> <span class="math display">0.30 - 0.021 &lt; p &lt; 0.30 + 0.021</span> <span class="math display">\mathbf{0.279 &lt; p &lt; 0.321} \qquad \text{or} \qquad 27.9\% &lt; p &lt; 32.1\%</span></p>
</div>
</div>
</div>
</section>
<section id="example-7-9-2" class="slide level2">
<h2>Example 7-9</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Compute in R</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href=""></a>excellent_count <span class="ot">&lt;-</span> <span class="dv">375</span></span>
<span id="cb39-2"><a href=""></a>sample_size <span class="ot">&lt;-</span> <span class="dv">1250</span></span>
<span id="cb39-3"><a href=""></a></span>
<span id="cb39-4"><a href=""></a>p_hat <span class="ot">&lt;-</span> excellent_count <span class="sc">/</span> sample_size</span>
<span id="cb39-5"><a href=""></a><span class="fu">c</span>(<span class="at">p_hat =</span> p_hat, <span class="at">n_p_hat =</span> sample_size <span class="sc">*</span> p_hat, <span class="at">n_q_hat =</span> sample_size <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p_hat))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  p_hat n_p_hat n_q_hat 
    0.3   375.0   875.0 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href=""></a>margin_error <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="fl">0.95</span>) <span class="sc">*</span> <span class="fu">sqrt</span>(p_hat <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p_hat) <span class="sc">/</span> sample_size)</span>
<span id="cb41-2"><a href=""></a><span class="fu">round</span>(margin_error, <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.021</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href=""></a><span class="fu">round</span>(<span class="fu">c</span>(p_hat <span class="sc">-</span> margin_error, p_hat <span class="sc">+</span> margin_error), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.279 0.321</code></pre>
</div>
</div>
<p>You can be <strong>90% confident</strong> that the percentage of transfer passengers who rate the experience as excellent is between 27.9% and 32.1%.</p>
</div>
</div>
</div>
</section>
<section id="example-7-10" class="slide level2">
<h2>Example 7-10</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Buying from Overseas Sellers</strong></p>
</div>
<div class="callout-content">
<p>A survey of 2400 online shoppers in Taiwan found that 64% had bought at least one item from an overseas seller in the past year. Find the <strong>90% confidence interval</strong> of the true proportion of shoppers who buy from overseas sellers.</p>
<p><em>(hypothetical data)</em></p>
</div>
</div>
</div>
</section>
<section id="example-7-10-1" class="slide level2">
<h2>Example 7-10</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1</strong> Determine <span class="math inline">\hat{p}</span> and <span class="math inline">\hat{q}</span>. Here <span class="math inline">\hat{p}</span> is already given: 64%, or 0.64. Then <span class="math inline">\hat{q} = 1 - 0.64 = 0.36</span>.</p>
<p><strong>Step 2</strong> Determine the critical value. <span class="math inline">\alpha = 1 - 0.90 = 0.10</span>, so <span class="math inline">\alpha/2 = 0.05</span> and <span class="math inline">z_{\alpha/2} = 1.645</span>.</p>
<p><strong>Step 3</strong> Substitute in the formula.</p>
<p><span class="math display">0.64 - 1.645\sqrt{\frac{(0.64)(0.36)}{2400}} &lt; p &lt; 0.64 + 1.645\sqrt{\frac{(0.64)(0.36)}{2400}}</span> <span class="math display">0.64 - 0.016 &lt; p &lt; 0.64 + 0.016</span> <span class="math display">\mathbf{0.624 &lt; p &lt; 0.656} \qquad \text{or} \qquad 62.4\% &lt; p &lt; 65.6\%</span></p>
</div>
</div>
</div>
</section>
<section id="example-7-10-2" class="slide level2">
<h2>Example 7-10</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Compute in R</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href=""></a>p_hat <span class="ot">&lt;-</span> <span class="fl">0.64</span></span>
<span id="cb45-2"><a href=""></a>sample_size <span class="ot">&lt;-</span> <span class="dv">2400</span></span>
<span id="cb45-3"><a href=""></a></span>
<span id="cb45-4"><a href=""></a>margin_error <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="fl">0.95</span>) <span class="sc">*</span> <span class="fu">sqrt</span>(p_hat <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p_hat) <span class="sc">/</span> sample_size)</span>
<span id="cb45-5"><a href=""></a><span class="fu">round</span>(margin_error, <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.016</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href=""></a><span class="fu">round</span>(<span class="fu">c</span>(p_hat <span class="sc">-</span> margin_error, p_hat <span class="sc">+</span> margin_error), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.624 0.656</code></pre>
</div>
</div>
<p>You can say with <strong>90% confidence</strong> that the true percentage of shoppers who buy from overseas sellers is between 62.4% and 65.6%.</p>
</div>
</div>
</div>
</section>
<section id="sample-size-for-proportions" class="slide level2">
<h2>Sample Size for Proportions</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Formula for Minimum Sample Size Needed for Interval Estimate of a Population Proportion</strong></p>
</div>
<div class="callout-content">
<p><span class="math display">n = \hat{p}\hat{q}\left(\frac{z_{\alpha/2}}{E}\right)^2</span></p>
<p>If necessary, <strong>round up</strong> to obtain a whole number.</p>
</div>
</div>
</div>
<p>There are two situations to consider:</p>
<ol type="1">
<li>If some approximation of <span class="math inline">\hat{p}</span> is known (for example, from a previous study), that value is used in the formula.</li>
<li>If no approximation of <span class="math inline">\hat{p}</span> is known, use <span class="math inline">\hat{p} = 0.5</span>. This gives a sample size large enough to guarantee an accurate prediction, because the product <span class="math inline">\hat{p}\hat{q}</span> is at a maximum when <span class="math inline">\hat{p} = \hat{q} = 0.5</span>.</li>
</ol>
<p>The disadvantage of the second method is that it can lead to a larger sample size than is necessary.</p>
</section>
<section id="sample-size-for-proportions-1" class="slide level2">
<h2>Sample Size for Proportions</h2>
<p><strong>Prepare data</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href=""></a>p_hat <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fl">0.1</span>, <span class="fl">0.9</span>, <span class="at">by =</span> <span class="fl">0.1</span>)</span>
<span id="cb49-2"><a href=""></a>pq_table <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">p_hat =</span> p_hat, <span class="at">q_hat =</span> <span class="dv">1</span> <span class="sc">-</span> p_hat,</span>
<span id="cb49-3"><a href=""></a>                       <span class="at">p_times_q =</span> <span class="fu">round</span>(p_hat <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p_hat), <span class="dv">2</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The product <span class="math inline">\hat{p}\hat{q}</span> is largest at <span class="math inline">\hat{p} = \hat{q} = 0.5</span>. Using that maximum value yields the largest possible value of <span class="math inline">n</span> for a given margin of error and a given confidence interval.</p>
</section>
<section id="sample-size-for-proportions-2" class="slide level2">
<h2>Sample Size for Proportions</h2>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href=""></a>knitr<span class="sc">::</span><span class="fu">kable</span>(pq_table, <span class="at">align =</span> <span class="st">"c"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">p_hat</th>
<th style="text-align: center;">q_hat</th>
<th style="text-align: center;">p_times_q</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0.1</td>
<td style="text-align: center;">0.9</td>
<td style="text-align: center;">0.09</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.2</td>
<td style="text-align: center;">0.8</td>
<td style="text-align: center;">0.16</td>
</tr>
<tr class="odd">
<td style="text-align: center;">0.3</td>
<td style="text-align: center;">0.7</td>
<td style="text-align: center;">0.21</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.4</td>
<td style="text-align: center;">0.6</td>
<td style="text-align: center;">0.24</td>
</tr>
<tr class="odd">
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">0.25</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.6</td>
<td style="text-align: center;">0.4</td>
<td style="text-align: center;">0.24</td>
</tr>
<tr class="odd">
<td style="text-align: center;">0.7</td>
<td style="text-align: center;">0.3</td>
<td style="text-align: center;">0.21</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.8</td>
<td style="text-align: center;">0.2</td>
<td style="text-align: center;">0.16</td>
</tr>
<tr class="odd">
<td style="text-align: center;">0.9</td>
<td style="text-align: center;">0.1</td>
<td style="text-align: center;">0.09</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="example-7-11" class="slide level2">
<h2>Example 7-11</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Mobile Payment at Checkout</strong></p>
</div>
<div class="callout-content">
<p>A market-research team wishes to estimate, with <strong>95% confidence</strong>, the proportion of Taiwanese online shoppers who pay with a mobile wallet at checkout. A previous study shows that 65% of shoppers did so. The team wishes to be accurate within <strong>3%</strong> of the true proportion. Find the minimum sample size necessary.</p>
<p><em>(hypothetical data)</em></p>
<p>Continued in <a href="#/example-7-12">Example 7-12</a></p>
</div>
</div>
</div>
</section>
<section id="example-7-11-1" class="slide level2">
<h2>Example 7-11</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p>Since <span class="math inline">z_{\alpha/2} = 1.960</span>, <span class="math inline">E = 0.03</span>, <span class="math inline">\hat{p} = 0.65</span> and <span class="math inline">\hat{q} = 0.35</span>, then</p>
<p><span class="math display">n = \hat{p}\hat{q}\left(\frac{z_{\alpha/2}}{E}\right)^2 = (0.65)(0.35)\left(\frac{1.960}{0.03}\right)^2 = 971.04</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href=""></a>p_hat <span class="ot">&lt;-</span> <span class="fl">0.65</span></span>
<span id="cb51-2"><a href=""></a>margin_error <span class="ot">&lt;-</span> <span class="fl">0.03</span></span>
<span id="cb51-3"><a href=""></a></span>
<span id="cb51-4"><a href=""></a>required_n <span class="ot">&lt;-</span> p_hat <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p_hat) <span class="sc">*</span> (<span class="fu">qnorm</span>(<span class="fl">0.975</span>) <span class="sc">/</span> margin_error)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb51-5"><a href=""></a><span class="fu">round</span>(required_n, <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 971.04</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href=""></a><span class="fu">ceiling</span>(required_n)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 972</code></pre>
</div>
</div>
<p>Which, when rounded up, is <strong>972</strong> shoppers to interview.</p>
</div>
</div>
</div>
</section>
<section id="example-7-12" class="slide level2">
<h2>Example 7-12</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>No Previous Study</strong></p>
</div>
<div class="callout-content">
<p>In <a href="#/example-7-11">Example 7-11</a> assume that no previous study was done, so no approximation of <span class="math inline">\hat{p}</span> is available. Find the minimum sample size necessary to be accurate within <strong>3%</strong> of the true proportion.</p>
</div>
</div>
</div>
</section>
<section id="example-7-12-1" class="slide level2">
<h2>Example 7-12</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p>Here we do not know the values of <span class="math inline">\hat{p}</span> and <span class="math inline">\hat{q}</span>, so we use <span class="math inline">\hat{p} = 0.5</span> and <span class="math inline">\hat{q} = 0.5</span>, with <span class="math inline">E = 0.03</span> and <span class="math inline">z_{\alpha/2} = 1.960</span>.</p>
<p><span class="math display">n = \hat{p}\hat{q}\left(\frac{z_{\alpha/2}}{E}\right)^2 = (0.5)(0.5)\left(\frac{1.960}{0.03}\right)^2 = 1067.07</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href=""></a>p_hat <span class="ot">&lt;-</span> <span class="fl">0.5</span></span>
<span id="cb55-2"><a href=""></a>margin_error <span class="ot">&lt;-</span> <span class="fl">0.03</span></span>
<span id="cb55-3"><a href=""></a></span>
<span id="cb55-4"><a href=""></a>required_n <span class="ot">&lt;-</span> p_hat <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p_hat) <span class="sc">*</span> (<span class="fu">qnorm</span>(<span class="fl">0.975</span>) <span class="sc">/</span> margin_error)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb55-5"><a href=""></a><span class="fu">round</span>(required_n, <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1067.07</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href=""></a><span class="fu">ceiling</span>(required_n)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1068</code></pre>
</div>
</div>
<p>Hence <strong>1068</strong> shoppers must be interviewed when <span class="math inline">\hat{p}</span> is unknown — 96 more than are needed when <span class="math inline">\hat{p}</span> is known.</p>
</div>
</div>
</div>
</section>
<section id="sample-size-for-proportions-3" class="slide level2">
<h2>Sample Size for Proportions</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Caution</strong></p>
</div>
<div class="callout-content">
<p>In determining the sample size, the <strong>size of the population is irrelevant</strong>. Only the degree of confidence and the margin of error are necessary to make the determination.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="section-7-5-confidence-intervals-for-variances-and-standard-deviations" class="title-slide slide level1 center" data-background-color="#2c4a6e">
<h1>Section 7-5: Confidence Intervals for Variances and Standard Deviations</h1>

</section>
<section id="the-chi-square-distribution" class="slide level2">
<h2>The Chi-Square Distribution</h2>
<p>The variance and standard deviation of a variable are as important as the mean. When pipes that must fit together are made, the variation of the diameters must stay small; in medicines, the variance of the amount of medication in each pill decides whether patients receive the proper dosage.</p>
<p>These confidence intervals need a new distribution: the <strong>chi-square distribution</strong>, written <span class="math inline">\chi^2</span> (Greek letter chi, pronounced “ki”). It is obtained from the values of <span class="math inline">(n-1)s^2/\sigma^2</span> for random samples from a normally distributed population with variance <span class="math inline">\sigma^2</span>.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Characteristics of the Chi-Square Distribution</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>All chi-square values are greater than or equal to 0.</li>
<li>The chi-square distribution is a <strong>family of curves</strong> based on the degrees of freedom.</li>
<li>The area under each chi-square distribution curve is equal to 1.</li>
<li>The chi-square distributions are <strong>positively skewed</strong>.</li>
</ol>
<p>At about 100 degrees of freedom the chi-square distribution becomes somewhat symmetric.</p>
</div>
</div>
</div>
</section>
<section id="the-chi-square-family-of-curves" class="slide level2">
<h2>The Chi-Square Family of Curves</h2>
<p><strong>Prepare data</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href=""></a>chi_curves <span class="ot">&lt;-</span> <span class="fu">expand_grid</span>(<span class="at">df =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">4</span>, <span class="dv">9</span>, <span class="dv">15</span>),</span>
<span id="cb59-2"><a href=""></a>                          <span class="at">x =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">40</span>, <span class="at">length.out =</span> <span class="dv">400</span>)) <span class="sc">|&gt;</span></span>
<span id="cb59-3"><a href=""></a>  <span class="fu">mutate</span>(<span class="at">density =</span> <span class="fu">dchisq</span>(x, df),</span>
<span id="cb59-4"><a href=""></a>         <span class="at">curve =</span> <span class="fu">fct_inorder</span>(<span class="fu">paste</span>(<span class="st">"d.f. ="</span>, df)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="the-chi-square-family-of-curves-1" class="slide level2">
<h2>The Chi-Square Family of Curves</h2>
<p><strong>Draw figure</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href=""></a><span class="fu">ggplot</span>(chi_curves, <span class="fu">aes</span>(x, density, <span class="at">color =</span> curve)) <span class="sc">+</span></span>
<span id="cb60-2"><a href=""></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb60-3"><a href=""></a>  <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb60-4"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"The Chi-Square Family of Curves"</span>,</span>
<span id="cb60-5"><a href=""></a>       <span class="at">x =</span> <span class="st">"Chi-square value"</span>, <span class="at">y =</span> <span class="st">"Density"</span>, <span class="at">color =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb60-6"><a href=""></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="ch7_files/figure-revealjs/s7-5-2-1.png" class="quarto-figure quarto-figure-center r-stretch" style="width:80.0%"></section>
<section id="finding-the-two-critical-values" class="slide level2">
<h2>Finding the Two Critical Values</h2>
<p>Because the chi-square distribution is <strong>not symmetric</strong>, two different values are used in the formulas: <span class="math inline">\chi^2_{\text{left}}</span> and <span class="math inline">\chi^2_{\text{right}}</span>.</p>
<p>Table A-6 lists degrees of freedom in the left column and the <strong>area to the right</strong> of the critical value across the top row. For a 95% confidence interval:</p>
<ol type="1">
<li>Change 95% to a decimal and subtract from 1: <span class="math inline">1 - 0.95 = 0.05</span>.</li>
<li>Divide by 2: <span class="math inline">\alpha/2 = 0.05/2 = 0.025</span>. This column gives <span class="math inline">\chi^2_{\text{right}}</span>.</li>
<li>Subtract <span class="math inline">\alpha/2</span> from 1: <span class="math inline">1 - 0.025 = 0.975</span>. This column gives <span class="math inline">\chi^2_{\text{left}}</span>.</li>
<li>Read the row for <span class="math inline">\text{d.f.} = n - 1</span>.</li>
</ol>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Caution</strong></p>
</div>
<div class="callout-content">
<p>If the number for the degrees of freedom is not printed in Table A-6, use the <strong>closest lower value</strong> in the table. For example, for <span class="math inline">\text{d.f.} = 53</span>, use <span class="math inline">\text{d.f.} = 50</span>. This is a conservative approach for a paper lookup; <code>qchisq()</code> takes the exact d.f., and where the two differ these slides report the value R computes.</p>
</div>
</div>
</div>
</section>
<section id="example-7-13" class="slide level2">
<h2>Example 7-13</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Finding Chi-Square Critical Values</strong></p>
</div>
<div class="callout-content">
<p>Find the values for <span class="math inline">\chi^2_{\text{right}}</span> and <span class="math inline">\chi^2_{\text{left}}</span> for a <strong>95% confidence interval</strong> when <span class="math inline">n = 20</span>.</p>
</div>
</div>
</div>
</section>
<section id="example-7-13-1" class="slide level2">
<h2>Example 7-13</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p>To find <span class="math inline">\chi^2_{\text{right}}</span>, subtract <span class="math inline">1 - 0.95 = 0.05</span>; then divide 0.05 by 2 to get 0.025. To find <span class="math inline">\chi^2_{\text{left}}</span>, subtract <span class="math inline">1 - 0.025 = 0.975</span>.</p>
<p>Then use the 0.975 and 0.025 columns of Table A-6 with <span class="math inline">\text{d.f.} = n - 1 = 20 - 1 = 19</span>.</p>
<p><span class="math display">\chi^2_{\text{right}} = 32.852 \qquad \chi^2_{\text{left}} = 8.907</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href=""></a>degrees_freedom <span class="ot">&lt;-</span> <span class="dv">20</span> <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb61-2"><a href=""></a></span>
<span id="cb61-3"><a href=""></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">chi_right =</span> <span class="fu">qchisq</span>(<span class="fl">0.975</span>, <span class="at">df =</span> degrees_freedom),</span>
<span id="cb61-4"><a href=""></a>        <span class="at">chi_left  =</span> <span class="fu">qchisq</span>(<span class="fl">0.025</span>, <span class="at">df =</span> degrees_freedom)), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>chi_right  chi_left 
   32.852     8.907 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="formulas-for-variance-and-standard-deviation" class="slide level2">
<h2>Formulas for Variance and Standard Deviation</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Formula for the Confidence Interval for a Variance</strong></p>
</div>
<div class="callout-content">
<p><span class="math display">\frac{(n-1)s^2}{\chi^2_{\text{right}}} &lt; \sigma^2 &lt; \frac{(n-1)s^2}{\chi^2_{\text{left}}} \qquad \text{d.f.} = n - 1</span></p>
</div>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Formula for the Confidence Interval for a Standard Deviation</strong></p>
</div>
<div class="callout-content">
<p><span class="math display">\sqrt{\frac{(n-1)s^2}{\chi^2_{\text{right}}}} &lt; \sigma &lt; \sqrt{\frac{(n-1)s^2}{\chi^2_{\text{left}}}} \qquad \text{d.f.} = n - 1</span></p>
</div>
</div>
</div>
<p>Useful estimates for <span class="math inline">\sigma^2</span> and <span class="math inline">\sigma</span> are <span class="math inline">s^2</span> and <span class="math inline">s</span>. If the problem gives the sample standard deviation <span class="math inline">s</span>, be sure to <strong>square it</strong>; if the problem gives the sample variance <span class="math inline">s^2</span>, do <strong>not</strong> square it, since the variance is already in square units.</p>
</section>
<section id="formulas-for-variance-and-standard-deviation-1" class="slide level2">
<h2>Formulas for Variance and Standard Deviation</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Assumptions for Finding a Confidence Interval for a Variance or Standard Deviation</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>The sample is a random sample.</li>
<li>The population <strong>must</strong> be normally distributed.</li>
</ol>
</div>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Rounding Rule for a Confidence Interval for a Variance or Standard Deviation</strong></p>
</div>
<div class="callout-content">
<p>When computing from <strong>raw data</strong>, round off to <strong>one more decimal place</strong> than the number of decimal places in the original data.</p>
<p>When computing from a <strong>sample variance or standard deviation</strong>, round off to the <strong>same number of decimal places</strong> as given for the sample variance or standard deviation.</p>
</div>
</div>
</div>
</section>
<section id="example-7-14" class="slide level2">
<h2>Example 7-14</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Variation in Batch Defect Rates</strong></p>
</div>
<div class="callout-content">
<p>A quality engineer at an electronics plant sampled 30 production batches and found that the standard deviation of the defect rate is 1.6 defects per thousand units. Find the <strong>95% confidence interval</strong> of the variance and standard deviation of the defect rate. Assume the variable is normally distributed.</p>
<p><em>(hypothetical data)</em></p>
</div>
</div>
</div>
</section>
<section id="example-7-14-1" class="slide level2">
<h2>Example 7-14</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p>Since <span class="math inline">\alpha = 0.05</span> and the degrees of freedom is 29, the two critical values are <span class="math inline">\chi^2_{\text{left}} = 16.047</span> and <span class="math inline">\chi^2_{\text{right}} = 45.722</span>.</p>
<p><span class="math display">\frac{(30-1)(1.6)^2}{45.722} &lt; \sigma^2 &lt; \frac{(30-1)(1.6)^2}{16.047}</span> <span class="math display">\mathbf{1.62 &lt; \sigma^2 &lt; 4.63}</span></p>
<p>For the standard deviation, take the square root of each limit:</p>
<p><span class="math display">\mathbf{1.27 &lt; \sigma &lt; 2.15}</span></p>
</div>
</div>
</div>
</section>
<section id="example-7-14-2" class="slide level2">
<h2>Example 7-14</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Compute in R</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href=""></a>sample_sd <span class="ot">&lt;-</span> <span class="fl">1.6</span></span>
<span id="cb63-2"><a href=""></a>degrees_freedom <span class="ot">&lt;-</span> <span class="dv">30</span> <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb63-3"><a href=""></a></span>
<span id="cb63-4"><a href=""></a>chi_limits <span class="ot">&lt;-</span> <span class="fu">qchisq</span>(<span class="fu">c</span>(<span class="fl">0.975</span>, <span class="fl">0.025</span>), <span class="at">df =</span> degrees_freedom)</span>
<span id="cb63-5"><a href=""></a><span class="fu">round</span>(chi_limits, <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 45.722 16.047</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href=""></a>variance_limits <span class="ot">&lt;-</span> degrees_freedom <span class="sc">*</span> sample_sd<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> chi_limits</span>
<span id="cb65-2"><a href=""></a><span class="fu">round</span>(variance_limits, <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.62 4.63</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb67"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href=""></a><span class="fu">round</span>(<span class="fu">sqrt</span>(variance_limits), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.27 2.15</code></pre>
</div>
</div>
<p>One can be <strong>95% confident</strong> that the true variance of the defect rate is between 1.62 and 4.63, and that the true standard deviation is between 1.27 and 2.15 defects per thousand units, based on a sample of 30 batches.</p>
</div>
</div>
</div>
</section>
<section id="example-7-15" class="slide level2">
<h2>Example 7-15</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Daily Call Volume at a Service Centre</strong></p>
</div>
<div class="callout-content">
<p>Find the <strong>90% confidence interval</strong> for the variance and standard deviation of the number of inbound calls received per day at a customer-service centre. A random sample of 10 days has been used. Assume the distribution is approximately normal.</p>
<pre><code>124   127   130   130   135
140   148   155   158   163</code></pre>
<p><em>(hypothetical data)</em></p>
</div>
</div>
</div>
</section>
<section id="example-7-15-1" class="slide level2">
<h2>Example 7-15</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1</strong> Find the variance for the data: <span class="math inline">s^2 = 198</span>.</p>
<p><strong>Step 2</strong> Find <span class="math inline">\chi^2_{\text{right}}</span> and <span class="math inline">\chi^2_{\text{left}}</span> from Table A-6, using <span class="math inline">10 - 1 = 9</span> degrees of freedom. With <span class="math inline">\alpha/2 = 0.05</span> and <span class="math inline">1 - \alpha/2 = 0.95</span>: <span class="math inline">\chi^2_{\text{right}} = 16.919</span> and <span class="math inline">\chi^2_{\text{left}} = 3.325</span>.</p>
<p><strong>Step 3</strong> Substitute in the formula.</p>
<p><span class="math display">\frac{(10-1)(198)}{16.919} &lt; \sigma^2 &lt; \frac{(10-1)(198)}{3.325}</span> <span class="math display">\mathbf{105.3 &lt; \sigma^2 &lt; 535.9}</span> <span class="math display">\sqrt{105.3} &lt; \sigma &lt; \sqrt{535.9} \qquad \Longrightarrow \qquad \mathbf{10.3 &lt; \sigma &lt; 23.1}</span></p>
</div>
</div>
</div>
</section>
<section id="example-7-15-2" class="slide level2">
<h2>Example 7-15</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Compute in R</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb70"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href=""></a>daily_calls <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">124</span>, <span class="dv">127</span>, <span class="dv">130</span>, <span class="dv">130</span>, <span class="dv">135</span>,</span>
<span id="cb70-2"><a href=""></a>                 <span class="dv">140</span>, <span class="dv">148</span>, <span class="dv">155</span>, <span class="dv">158</span>, <span class="dv">163</span>)</span>
<span id="cb70-3"><a href=""></a>degrees_freedom <span class="ot">&lt;-</span> <span class="fu">length</span>(daily_calls) <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb70-4"><a href=""></a>sample_variance <span class="ot">&lt;-</span> <span class="fu">var</span>(daily_calls)</span>
<span id="cb70-5"><a href=""></a>sample_variance</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 198</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb72"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href=""></a>chi_limits <span class="ot">&lt;-</span> <span class="fu">qchisq</span>(<span class="fu">c</span>(<span class="fl">0.95</span>, <span class="fl">0.05</span>), <span class="at">df =</span> degrees_freedom)</span>
<span id="cb72-2"><a href=""></a><span class="fu">round</span>(chi_limits, <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 16.919  3.325</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb74"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href=""></a>variance_limits <span class="ot">&lt;-</span> degrees_freedom <span class="sc">*</span> sample_variance <span class="sc">/</span> chi_limits</span>
<span id="cb74-2"><a href=""></a><span class="fu">round</span>(variance_limits, <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 105.3 535.9</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb76"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href=""></a><span class="fu">round</span>(<span class="fu">sqrt</span>(variance_limits), <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10.3 23.1</code></pre>
</div>
</div>
<p>One can be <strong>90% confident</strong> that the standard deviation of the daily number of inbound calls is between 10.3 and 23.1 calls, based on a random sample of 10 days.</p>
</div>
</div>
</div>
</section>
<section id="important-terms" class="slide level2">
<h2>Important Terms</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Chapter 7 Vocabulary</strong></p>
</div>
<div class="callout-content">
<p>assumptions · chi-square distribution · confidence interval · confidence level · consistent estimator · degrees of freedom · estimation · estimator · interval estimate · margin of error · point estimate · proportion · relatively efficient estimator · robust · <span class="math inline">t</span> distribution · unbiased estimator</p>
</div>
</div>
</div>
</section>
<section id="key-formulas" class="slide level2">
<h2>Key Formulas</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Confidence Intervals for a Mean</strong></p>
</div>
<div class="callout-content">
<p>Confidence interval of the mean when <span class="math inline">\sigma</span> is known (when <span class="math inline">n \geq 30</span>, <span class="math inline">s</span> can be used if <span class="math inline">\sigma</span> is unknown):</p>
<p><span class="math display">\bar{X} - z_{\alpha/2}\left(\frac{\sigma}{\sqrt{n}}\right) &lt; \mu &lt; \bar{X} + z_{\alpha/2}\left(\frac{\sigma}{\sqrt{n}}\right)</span></p>
<p>Confidence interval of the mean when <span class="math inline">\sigma</span> is unknown, with <span class="math inline">\text{d.f.} = n - 1</span>:</p>
<p><span class="math display">\bar{X} - t_{\alpha/2}\left(\frac{s}{\sqrt{n}}\right) &lt; \mu &lt; \bar{X} + t_{\alpha/2}\left(\frac{s}{\sqrt{n}}\right)</span></p>
<p>Sample size for means, where <span class="math inline">E</span> is the margin of error:</p>
<p><span class="math display">n = \left(\frac{z_{\alpha/2} \cdot \sigma}{E}\right)^2</span></p>
</div>
</div>
</div>
</section>
<section id="key-formulas-1" class="slide level2">
<h2>Key Formulas</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Proportions, Variances and Standard Deviations</strong></p>
</div>
<div class="callout-content">
<p>Confidence interval for a proportion, where <span class="math inline">\hat{p} = X/n</span> and <span class="math inline">\hat{q} = 1 - \hat{p}</span>:</p>
<p><span class="math display">\hat{p} - z_{\alpha/2}\sqrt{\frac{\hat{p}\hat{q}}{n}} &lt; p &lt; \hat{p} + z_{\alpha/2}\sqrt{\frac{\hat{p}\hat{q}}{n}} \qquad n = \hat{p}\hat{q}\left(\frac{z_{\alpha/2}}{E}\right)^2</span></p>
<p>Confidence interval for a variance and for a standard deviation, with <span class="math inline">\text{d.f.} = n - 1</span>:</p>
<p><span class="math display">\frac{(n-1)s^2}{\chi^2_{\text{right}}} &lt; \sigma^2 &lt; \frac{(n-1)s^2}{\chi^2_{\text{left}}} \qquad \sqrt{\frac{(n-1)s^2}{\chi^2_{\text{right}}}} &lt; \sigma &lt; \sqrt{\frac{(n-1)s^2}{\chi^2_{\text{left}}}}</span></p>
</div>
</div>
</div>
</section>
<section id="key-takeaways" class="slide level2">
<h2>Key Takeaways</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Key point</strong></p>
</div>
<div class="callout-content">
<ul>
<li><strong>Estimation</strong> uses a sample statistic to estimate a parameter; a good estimator is <strong>unbiased</strong>, <strong>consistent</strong> and <strong>relatively efficient</strong>, and <span class="math inline">\bar{X}</span> is the best point estimate of <span class="math inline">\mu</span></li>
<li>A <strong>point estimate</strong> is a single value; an <strong>interval estimate</strong> is a range, and its <strong>confidence level</strong> is the long-run probability that such intervals capture the parameter</li>
<li>The <strong>margin of error</strong> (maximum error of the estimate) is the largest likely gap between the point estimate and the parameter; higher confidence means a <strong>wider</strong> interval</li>
<li>Use <span class="math inline">z_{\alpha/2}</span> and <span class="math inline">\sigma</span> when <span class="math inline">\sigma</span> is known; use <span class="math inline">t_{\alpha/2}</span> and <span class="math inline">s</span> with <span class="math inline">\text{d.f.} = n - 1</span> when <span class="math inline">\sigma</span> is unknown — and if <span class="math inline">n &lt; 30</span> the variable must be normally distributed</li>
<li>Sample sizes come from <span class="math inline">n = \left(z_{\alpha/2}\sigma/E\right)^2</span> and <span class="math inline">n = \hat{p}\hat{q}\left(z_{\alpha/2}/E\right)^2</span>, and are <strong>always rounded up</strong>; the population size is irrelevant</li>
<li>For proportions, <span class="math inline">\hat{p} = X/n</span> and <span class="math inline">\hat{q} = 1 - \hat{p}</span>, the interval requires <span class="math inline">n\hat{p} \geq 5</span> and <span class="math inline">n\hat{q} \geq 5</span>, and limits are rounded to <strong>three decimal places</strong>; when <span class="math inline">\hat{p}</span> is unknown use <span class="math inline">\hat{p} = 0.5</span></li>
<li>Confidence intervals for <span class="math inline">\sigma^2</span> and <span class="math inline">\sigma</span> use the <strong>positively skewed</strong> chi-square distribution with two critical values, and <strong>require</strong> a normally distributed population</li>
</ul>
</div>
</div>
</div>
</section>
<section id="acknowledgement" class="slide level2">
<h2>Acknowledgement</h2>
<ul>
<li><p><strong>Copyright notice.</strong> These teaching materials follow the organization and terminology of <strong>Bluman, A. G. (2023). Elementary statistics: A step by step approach (11th ed.). McGraw Hill</strong>. All rights in the original work are reserved by its authors and publishers.</p></li>
<li><p><strong>Original examples.</strong> Every worked example, data set, and R script in these slides was written for this course. The data are hypothetical unless stated otherwise.</p></li>
<li><p><strong>Non-commercial use only.</strong> These materials are strictly intended for educational purposes and must not be used for commercial gain or profit.</p></li>
<li><p><strong>Proper attribution.</strong> Any reproduction, distribution, or use of these materials must provide proper attribution to the original source.</p></li>
</ul>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="logo.svg" class="slide-logo"></p>
<div class="footer footer-default">
<p>Elementary Statistics: A Step by Step Approach</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="ch7_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="ch7_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="ch7_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="ch7_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="ch7_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="ch7_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="ch7_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="ch7_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="ch7_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":false,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true,"hideMissingTitles":true,"titleSelector":"h1"},
'smaller': true,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    <script>
    Reveal.on('ready', function() {
      var title = Reveal.getSlides()[0];
      if (title) {
        title.insertAdjacentHTML('beforeend',
          '<p style="font-size:0.5em; margin-top:1.5em;">' +
          '<a href="ch7-zh.html"  style="color:#555;">[中文版由此去]</a>' +
          '</p>');
      }
    });
    </script>
    

</body></html>