<!DOCTYPE html>
<html lang="en"><head>
<script src="ch13_files/libs/clipboard/clipboard.min.js"></script>
<script src="ch13_files/libs/quarto-html/tabby.min.js"></script>
<script src="ch13_files/libs/quarto-html/popper.min.js"></script>
<script src="ch13_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="ch13_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="ch13_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="ch13_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.38">

  <meta name="author" content="Yu-You Liou">
  <meta name="dcterms.date" content="2026-10-08">
  <title>Statistics</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="ch13_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="ch13_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="ch13_files/libs/revealjs/dist/theme/quarto-2abc1c5b7b5c7eecd6137558e106e4c3.css">
  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">
  <link href="ch13_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="ch13_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="ch13_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="ch13_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-notes="" class="quarto-title-block center">
  <h1 class="title">Statistics</h1>
  <p class="subtitle">Chapter 13: Nonparametric Statistics</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Yu-You Liou 
</div>
        <p class="quarto-title-affiliation">
            Shih Chien University
          </p>
    </div>
</div>

  <p class="date">2026-10-08</p>
</section>
<section id="overview" class="slide level2">
<h2>Overview</h2>
<p>Chapter 13 presents <strong>nonparametric</strong> (distribution-free) methods — statistical tests that can be used when the assumption of normality cannot be met, when the data are nominal or ordinal, or when the hypothesis does not involve a population parameter.</p>
<table class="caption-top">
<colgroup>
<col style="width: 52%">
<col style="width: 47%">
</colgroup>
<thead>
<tr class="header">
<th>Section</th>
<th>Topics</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>13-1</td>
<td>Parametric vs.&nbsp;nonparametric tests; advantages and disadvantages; ranking and the rule for ties</td>
</tr>
<tr class="even">
<td>13-2</td>
<td>Sign test for a median; Table A-10; large-sample <span class="math inline">z</span>; paired-sample sign test</td>
</tr>
<tr class="odd">
<td>13-3</td>
<td>Wilcoxon rank sum test (two independent samples); <span class="math inline">R</span>, <span class="math inline">\mu_R</span>, <span class="math inline">\sigma_R</span></td>
</tr>
</tbody>
</table>
</section>
<section id="overview-continued" class="slide level2">
<h2>Overview (continued)</h2>
<table class="caption-top">
<colgroup>
<col style="width: 52%">
<col style="width: 47%">
</colgroup>
<thead>
<tr class="header">
<th>Section</th>
<th>Topics</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>13-4</td>
<td>Wilcoxon signed-rank test (two dependent samples); <span class="math inline">w_s</span>; <span class="math inline">z</span> formula for <span class="math inline">n &gt; 30</span></td>
</tr>
<tr class="even">
<td>13-5</td>
<td>Kruskal-Wallis <span class="math inline">H</span> test (three or more samples); chi-square approximation, <span class="math inline">\text{d.f.} = k - 1</span></td>
</tr>
<tr class="odd">
<td>13-6</td>
<td>Spearman rank correlation <span class="math inline">r_s</span>; runs test for randomness, <span class="math inline">G</span>; large-sample <span class="math inline">z</span></td>
</tr>
</tbody>
</table>
</section>
<section id="chapter-objectives" class="slide level2">
<h2>Chapter Objectives</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>After completing this chapter, you should be able to</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>State the advantages and disadvantages of nonparametric methods.</li>
<li>Test hypotheses, using the sign test.</li>
<li>Test hypotheses, using the Wilcoxon rank sum test.</li>
<li>Test hypotheses, using the signed-rank test.</li>
<li>Test hypotheses, using the Kruskal-Wallis test.</li>
<li>Compute the Spearman rank correlation coefficient.</li>
<li>Test hypotheses, using the runs test.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="introduction" class="slide level2">
<h2>Introduction</h2>
<p>Statistical tests such as the <span class="math inline">z</span>, <span class="math inline">t</span> and <span class="math inline">F</span> tests are called <strong>parametric tests</strong>. They are tests for population parameters such as means, variances and proportions, and they involve assumptions about the populations from which the samples were selected — one assumption being that those populations are normally distributed.</p>
<p>But what if the population in a particular hypothesis-testing situation is <em>not</em> normally distributed? Statisticians have developed a branch of statistics known as <strong>nonparametric statistics</strong>, or <strong>distribution-free statistics</strong>, for exactly that case. Nonparametric statistics can also be used to test hypotheses that do not involve specific population parameters such as <span class="math inline">\mu</span>, <span class="math inline">\sigma</span> or <span class="math inline">p</span>.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Nonparametric Statistical Tests</strong></p>
</div>
<div class="callout-content">
<p><strong>Nonparametric statistical tests</strong> are used to test hypotheses about population parameters when the assumption about normality cannot be met.</p>
</div>
</div>
</div>
</section>
<section id="what-this-chapter-covers" class="slide level2">
<h2>What This Chapter Covers</h2>
<p>A sportswriter may wish to know whether there is a relationship between the rankings of two judges on the diving abilities of 10 Olympic swimmers. A sociologist may wish to determine whether men and women enroll at random for a specific drug rehabilitation program. The statistical tests used in these situations are nonparametric, or distribution-free, tests.</p>
<p>The nonparametric tests explained in this chapter are the <strong>sign test</strong>, the <strong>Wilcoxon rank sum test</strong>, the <strong>Wilcoxon signed-rank test</strong>, the <strong>Kruskal-Wallis test</strong> and the <strong>runs test</strong>. In addition, the <strong>Spearman rank correlation coefficient</strong>, a statistic for determining the relationship between ranks, is explained.</p>
</section>
<section>
<section id="section-13-1-advantages-and-disadvantages-of-nonparametric-methods" class="title-slide slide level1 center" data-background-color="#2c4a6e">
<h1>Section 13-1: Advantages and Disadvantages of Nonparametric Methods</h1>

</section>
<section id="advantages-of-nonparametric-methods" class="slide level2">
<h2>Advantages of Nonparametric Methods</h2>
<p>Nonparametric tests and statistics can be used in place of their parametric counterparts (<span class="math inline">z</span>, <span class="math inline">t</span> and <span class="math inline">F</span>) when the assumption of normality cannot be met. You should <strong>not</strong>, however, assume that these statistics are a better alternative than the parametric statistics — there are both advantages and disadvantages to their use.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Six Advantages</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>They can be used to test population parameters when the variable is <strong>not normally distributed</strong>.</li>
<li>They can be used when the data are <strong>nominal or ordinal</strong>.</li>
<li>They can be used to test hypotheses that <strong>do not involve population parameters</strong>.</li>
<li>In some cases, the <strong>computations are easier</strong> than those for the parametric counterparts.</li>
<li>They are <strong>easy to understand</strong>.</li>
<li>There are <strong>fewer assumptions</strong> that have to be met, and the assumptions are <strong>easier to verify</strong>.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="disadvantages-of-nonparametric-methods" class="slide level2">
<h2>Disadvantages of Nonparametric Methods</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Three Disadvantages</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>They are <strong>less sensitive</strong> than their parametric counterparts when the assumptions of the parametric methods are met. Therefore, larger differences are needed before the null hypothesis can be rejected.</li>
<li>They tend to <strong>use less information</strong> than the parametric tests. For example, the sign test requires the researcher to determine only whether the data values are above or below the median, not <em>how much</em> above or below the median each value is.</li>
<li>They are <strong>less efficient</strong> than their parametric counterparts when the assumptions of the parametric methods are met — larger sample sizes are needed to overcome the loss of information. The nonparametric sign test is about <strong>60% as efficient</strong> as its parametric counterpart, the <span class="math inline">z</span> test: a sample size of 100 is needed for the sign test, compared with a sample size of 60 for the <span class="math inline">z</span> test, to obtain the same results.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="choosing-between-the-two-approaches" class="slide level2">
<h2>Choosing Between the Two Approaches</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Caution</strong></p>
</div>
<div class="callout-content">
<p>Since there are both advantages and disadvantages to the nonparametric methods, the researcher should use <strong>caution</strong> in selecting these methods. If the parametric assumptions <strong>can</strong> be met, the parametric methods are preferred. When the parametric assumptions <strong>cannot</strong> be met, the nonparametric methods are a valuable tool for analyzing the data.</p>
</div>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Assumptions for Nonparametric Statistics</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>The sample or samples are <strong>randomly selected</strong>.</li>
<li>If two or more samples are used, they must be <strong>independent</strong> of each other unless otherwise stated.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="ranking" class="slide level2">
<h2>Ranking</h2>
<p>Many nonparametric tests involve the <strong>ranking</strong> of data.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Ranking</strong></p>
</div>
<div class="callout-content">
<p><strong>Ranking</strong> is the positioning of a data value in a data array according to some rating scale. Ranking is an <strong>ordinal</strong> variable.</p>
</div>
</div>
</div>
<p>A judge rates five speakers on a scale of 1 to 10, with 1 best and 10 worst.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Speaker</th>
<th>A</th>
<th>B</th>
<th>C</th>
<th>D</th>
<th>E</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Rating</td>
<td>8</td>
<td>6</td>
<td>10</td>
<td>3</td>
<td>1</td>
</tr>
</tbody>
</table>
<p>Speaker E has the lowest score (1 point) and is ranked first; speaker D (3 points) is ranked second; and so on.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Speaker</th>
<th>E</th>
<th>D</th>
<th>B</th>
<th>A</th>
<th>C</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Rating</td>
<td>1</td>
<td>3</td>
<td>6</td>
<td>8</td>
<td>10</td>
</tr>
<tr class="even">
<td>Ranking</td>
<td>1</td>
<td>2</td>
<td>3</td>
<td>4</td>
<td>5</td>
</tr>
</tbody>
</table>
</section>
<section id="ranking-when-there-are-ties" class="slide level2">
<h2>Ranking When There Are Ties</h2>
<p>Suppose two or more speakers receive the same number of points:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Speaker</th>
<th>A</th>
<th>B</th>
<th>C</th>
<th>D</th>
<th>E</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Rating</td>
<td>8</td>
<td>6</td>
<td>10</td>
<td>6</td>
<td>3</td>
</tr>
</tbody>
</table>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Rule for Tied Values</strong></p>
</div>
<div class="callout-content">
<p>When places tie, the <strong>average of the ranks</strong> must be used. D and B tie for 2nd and 3rd, so each is ranked</p>
<p><span class="math display">\frac{2 + 3}{2} = \frac{5}{2} = 2.5</span></p>
</div>
</div>
</div>
<table class="caption-top">
<thead>
<tr class="header">
<th>Speaker</th>
<th>E</th>
<th>D</th>
<th>B</th>
<th>A</th>
<th>C</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Rating</td>
<td>3</td>
<td>6</td>
<td>6</td>
<td>8</td>
<td>10</td>
</tr>
<tr class="even">
<td>Ranking</td>
<td>1</td>
<td>2.5</td>
<td>2.5</td>
<td>4</td>
<td>5</td>
</tr>
</tbody>
</table>
<p>Data are often already ranked. P-values apply only to normal or chi-square tests.</p>
</section>
<section id="ranking-in-r" class="slide level2">
<h2>Ranking in R</h2>
<p><strong>Prepare data</strong> — <code>rank()</code> ranks from lowest to highest and, by default, assigns the <strong>average</strong> of the ranks to tied values, which is exactly the rule above.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href=""></a>rating <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">8</span>, <span class="dv">6</span>, <span class="dv">10</span>, <span class="dv">6</span>, <span class="dv">3</span>)</span>
<span id="cb1-2"><a href=""></a></span>
<span id="cb1-3"><a href=""></a><span class="fu">rank</span>(rating)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.0 2.5 5.0 2.5 1.0</code></pre>
</div>
</div>
<p>The two speakers rated 6 would have occupied ranks 2 and 3, so each receives rank 2.5.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href=""></a><span class="fu">sort</span>(rating)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  3  6  6  8 10</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href=""></a><span class="fu">rank</span>(<span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">6</span>, <span class="dv">6</span>, <span class="dv">8</span>, <span class="dv">10</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.0 2.5 2.5 4.0 5.0</code></pre>
</div>
</div>
</section></section>
<section>
<section id="section-13-2-the-sign-test" class="title-slide slide level1 center" data-background-color="#2c4a6e">
<h1>Section 13-2: The Sign Test</h1>

</section>
<section id="the-single-sample-sign-test" class="slide level2">
<h2>The Single-Sample Sign Test</h2>
<p>The simplest nonparametric test, the <strong>sign test for single samples</strong>, is used to test the value of a median for a specific sample.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Sign Test for a Single Sample</strong></p>
</div>
<div class="callout-content">
<p>The <strong>sign test for a single sample</strong> is a nonparametric test used to test the value of a <strong>population median</strong>.</p>
</div>
</div>
</div>
<p>The researcher hypothesizes a specific value for the median of a population, then selects a random sample and compares each value with the conjectured median.</p>
<ul>
<li>If the data value is <strong>above</strong> the conjectured median, it is assigned a <strong>plus</strong> sign.</li>
<li>If the data value is <strong>below</strong> the conjectured median, it is assigned a <strong>minus</strong> sign.</li>
<li>If the data value is <strong>exactly the same</strong> as the conjectured median, it is assigned a <strong>0</strong>.</li>
</ul>
<p>If <span class="math inline">H_0</span> is true, the number of plus signs should be approximately equal to the number of minus signs. If <span class="math inline">H_0</span> is not true, there will be a disproportionate number of plus or minus signs.</p>
</section>
<section id="test-statistic-for-the-sign-test" class="slide level2">
<h2>Test Statistic for the Sign Test</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Test Statistic for the Sign Test</strong></p>
</div>
<div class="callout-content">
<p>If <span class="math inline">n \leq 25</span>, the test statistic is the <strong>smaller number of plus or minus signs</strong>. When <span class="math inline">n &gt; 25</span>, the test statistic is</p>
<p><span class="math display">z = \frac{(X + 0.5) - 0.5n}{\sqrt{n} / 2}</span></p>
<p>where <span class="math inline">X</span> is the smaller number of plus or minus signs and <span class="math inline">n</span> is the total number of plus <strong>or</strong> minus signs.</p>
</div>
</div>
</div>
<ul>
<li>When <span class="math inline">n \leq 25</span>, <strong>Table A-10</strong> gives the critical value. For a specific <span class="math inline">\alpha</span>, if the test statistic is <strong>less than or equal to</strong> the critical value, reject <span class="math inline">H_0</span>. The values in Table A-10 come from the binomial distribution with <span class="math inline">p = 0.5</span>.</li>
<li>When <span class="math inline">n &gt; 25</span>, the normal approximation with <strong>Table A-4</strong> is used. Here <span class="math inline">\mu = np = 0.5n</span> and <span class="math inline">\sigma = \sqrt{npq} = \sqrt{n(0.5)(0.5)} = \sqrt{n}/2</span>, since <span class="math inline">p = q = 0.5</span>.</li>
</ul>
</section>
<section id="procedure-table-performing-the-sign-test" class="slide level2">
<h2>Procedure Table: Performing the Sign Test</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Five Steps</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> State the hypotheses and identify the claim.</p>
<p><strong>Step 2.</strong> Find the critical value. Use <strong>Table A-10</strong> when <span class="math inline">n \leq 25</span> and <strong>Table A-4</strong> when <span class="math inline">n &gt; 25</span>.</p>
<p><strong>Step 3.</strong> Compute the test statistic.</p>
<p><strong>Step 4.</strong> Make the decision.</p>
<p><strong>Step 5.</strong> Summarize the results.</p>
</div>
</div>
</div>
</section>
<section id="example-13-1" class="slide level2">
<h2>Example 13-1</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Daily Drink Orders at a Night Market Stall</strong></p>
</div>
<div class="callout-content">
<p>The owner of a bubble-tea stall in a Taipei night market claims that the median number of drink orders the stall fills per day is 45. To test the claim, an intern randomly selects 20 business days and records the number of orders filled each day <em>(hypothetical data)</em>. At <span class="math inline">\alpha = 0.05</span>, test the claim that the median number of orders filled per day is 45.</p>
<pre><code>52   48   51   50   70
47   39   53   60   37
27   46   54   49   51
45   58   46   45   47</code></pre>
</div>
</div>
</div>
</section>
<section id="example-13-1-1" class="slide level2">
<h2>Example 13-1</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> State the hypotheses and identify the claim.</p>
<p><span class="math inline">H_0</span>: Median <span class="math inline">= 45</span> <em>(claim)</em>; <span class="math inline">H_1</span>: Median <span class="math inline">\neq 45</span>.</p>
<p><strong>Step 2.</strong> Find the critical value. Subtract the hypothesized median, 45, from each data value: a value above 45 is assigned a <span class="math inline">+</span>, a value below 45 a <span class="math inline">-</span>, and a value equal to 45 a <span class="math inline">0</span>. For example, <span class="math inline">52 - 45 = +7</span> so 52 gets a <span class="math inline">+</span>; <span class="math inline">27 - 45 = -18</span> so 27 gets a <span class="math inline">-</span>; <span class="math inline">45 - 45 = 0</span> so 45 gets a <span class="math inline">0</span>.</p>
<pre><code>+    +    +    +    +
+    -    +    +    -
-    +    +    +    +
0    +    +    0    +</code></pre>
<p>Since <span class="math inline">n \leq 25</span>, use <strong>Table A-10</strong>. Here <span class="math inline">n = 20 - 2 = 18</span> (there are two zeros) and <span class="math inline">\alpha = 0.05</span>; the critical value for a two-tailed test is <strong>4</strong>.</p>
</div>
</div>
</div>
</section>
<section id="example-13-1-2" class="slide level2">
<h2>Example 13-1</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 3 in R</strong> — count the signs and use the smaller count as the test statistic.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href=""></a>daily_orders <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">52</span>, <span class="dv">48</span>, <span class="dv">51</span>, <span class="dv">50</span>, <span class="dv">70</span>,</span>
<span id="cb9-2"><a href=""></a>                  <span class="dv">47</span>, <span class="dv">39</span>, <span class="dv">53</span>, <span class="dv">60</span>, <span class="dv">37</span>,</span>
<span id="cb9-3"><a href=""></a>                  <span class="dv">27</span>, <span class="dv">46</span>, <span class="dv">54</span>, <span class="dv">49</span>, <span class="dv">51</span>,</span>
<span id="cb9-4"><a href=""></a>                  <span class="dv">45</span>, <span class="dv">58</span>, <span class="dv">46</span>, <span class="dv">45</span>, <span class="dv">47</span>)</span>
<span id="cb9-5"><a href=""></a></span>
<span id="cb9-6"><a href=""></a><span class="fu">sum</span>(daily_orders <span class="sc">&gt;</span> <span class="dv">45</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 15</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href=""></a><span class="fu">sum</span>(daily_orders <span class="sc">&lt;</span> <span class="dv">45</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="example-13-1-3" class="slide level2">
<h2>Example 13-1</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 4.</strong> Make the decision. Compare the test statistic 3 with the critical value 4. If the test statistic is <strong>less than or equal to</strong> the critical value, reject <span class="math inline">H_0</span>. Here <span class="math inline">3 &lt; 4</span>, so <strong>reject the null hypothesis</strong>.</p>
<p><strong>Step 5.</strong> Summarize the results. There is enough evidence to reject the claim that the median number of drink orders filled per day is 45.</p>
<p><strong>P-value.</strong> The critical values in Table A-10 come from the binomial distribution with <span class="math inline">p = 0.5</span>, so the exact P-value is a binomial probability.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href=""></a><span class="co"># two-tailed test: twice P(X &lt;= 3)</span></span>
<span id="cb13-2"><a href=""></a><span class="dv">2</span> <span class="sc">*</span> <span class="fu">pbinom</span>(<span class="dv">3</span>, <span class="dv">18</span>, <span class="fl">0.5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.007537842</code></pre>
</div>
</div>
<p><span class="math inline">P = 0.0075 &lt; 0.05</span>, which agrees with the traditional decision to reject <span class="math inline">H_0</span>.</p>
</div>
</div>
</div>
</section>
<section id="example-13-2" class="slide level2">
<h2>Example 13-2</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Daily Parcels Leaving a Fulfilment Centre</strong></p>
</div>
<div class="callout-content">
<p>A logistics analyst hypothesizes that the median number of parcels shipped per day from a cross-border e-commerce fulfilment centre in Taoyuan is 500. A random sample of 40 days is selected, and on 15 of those days fewer than 500 parcels were shipped <em>(hypothetical data)</em>. At <span class="math inline">\alpha = 0.05</span>, test the claim that the median number of parcels shipped per day is 500.</p>
<p>Back to <a href="#/example-13-3">Example 13-3</a></p>
</div>
</div>
</div>
</section>
<section id="example-13-2-1" class="slide level2">
<h2>Example 13-2</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> State the hypotheses and identify the claim.</p>
<p><span class="math inline">H_0</span>: Median <span class="math inline">= 500</span> <em>(claim)</em>; <span class="math inline">H_1</span>: Median <span class="math inline">\neq 500</span>.</p>
<p><strong>Step 2.</strong> Find the critical values. Since <span class="math inline">\alpha = 0.05</span>, <span class="math inline">n = 40</span> and the test is two-tailed, the critical values from Table A-4 are <span class="math inline">+1.96</span> and <span class="math inline">-1.96</span>.</p>
<p><strong>Step 3.</strong> Compute the test statistic. On 15 days the count was below 500, so on <span class="math inline">40 - 15 = 25</span> days it was 500 or above. <span class="math inline">X</span> is the <strong>smaller</strong> of 15 and 25, so <span class="math inline">X = 15</span>.</p>
<p><span class="math display">z = \frac{(X + 0.5) - 0.5n}{\sqrt{n}/2} = \frac{(15 + 0.5) - 0.5(40)}{\sqrt{40}/2} = -1.42</span></p>
</div>
</div>
</div>
</section>
<section id="example-13-2-2" class="slide level2">
<h2>Example 13-2</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 3 in R</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href=""></a>((<span class="dv">15</span> <span class="sc">+</span> <span class="fl">0.5</span>) <span class="sc">-</span> <span class="fl">0.5</span> <span class="sc">*</span> <span class="dv">40</span>) <span class="sc">/</span> (<span class="fu">sqrt</span>(<span class="dv">40</span>) <span class="sc">/</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1.423025</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href=""></a><span class="fu">qnorm</span>(<span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1.959964  1.959964</code></pre>
</div>
</div>
<p><strong>Step 4.</strong> Make the decision. Since the test statistic <span class="math inline">-1.42</span> is greater than <span class="math inline">-1.96</span>, the decision is to <strong>not reject</strong> the null hypothesis.</p>
<p><strong>Step 5.</strong> Summarize the results. There is not enough evidence to reject the claim that the median number of parcels shipped per day is 500.</p>
</div>
</div>
</div>
</section>
<section id="which-count-is-x" class="slide level2">
<h2>Which Count Is <span class="math inline">X</span>?</h2>
<p>Suppose a researcher hypothesized that the median age of houses in a municipality was 40 years, and in a random sample of 100 houses 68 were older than 40 years. There would be 68 positive signs and 32 negative signs, so <span class="math inline">X = 32</span> — the smaller of the two values.</p>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Caution</strong></p>
</div>
<div class="callout-content">
<p>Because the sign test uses the <strong>smaller</strong> number of plus or minus signs, the test is either a <strong>two-tailed</strong> test or a <strong>left-tailed</strong> test. When the test is two-tailed, the critical value is found on the left side of the standard normal distribution. When the sign test is a <strong>right-tailed</strong> test, the formula becomes</p>
<p><span class="math display">z = \frac{(X - 0.5) - 0.5n}{\sqrt{n}/2}</span></p>
<p>and the <strong>larger</strong> number of plus or minus signs is used for <span class="math inline">X</span>. The hypotheses are then <span class="math inline">H_0</span>: Median <span class="math inline">= k</span> and <span class="math inline">H_1</span>: Median <span class="math inline">&gt; k</span>, and the right side of the <span class="math inline">z</span> distribution supplies the critical value.</p>
</div>
</div>
</div>
</section>
<section id="the-paired-sample-sign-test" class="slide level2">
<h2>The Paired-Sample Sign Test</h2>
<p>The sign test can also compare two <strong>dependent</strong> samples, such as a before-and-after test. Use the <span class="math inline">t</span> test (Section 9-4) when the populations are normal; when normality cannot be met, use the nonparametric sign test.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Paired-Sample Sign Test</strong></p>
</div>
<div class="callout-content">
<p>The <strong>paired-sample sign test</strong> is a nonparametric test that is used to test the difference between two <strong>population medians</strong> when the samples are <strong>dependent</strong>.</p>
</div>
</div>
</div>
<p><span class="math inline">X_B</span> is the value <strong>before</strong> the treatment and <span class="math inline">X_A</span> the value <strong>after</strong>. Form the differences <span class="math inline">X_B - X_A</span> and give each a plus or minus sign; <strong>zeros are ignored</strong>. The test can be left-tailed, right-tailed or two-tailed, and the procedure is the same as for the single-sample sign test.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Two Assumptions for the Paired-Sample Sign Test</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>The sample is <strong>random</strong>.</li>
<li>The variables are <strong>dependent</strong> or <strong>paired</strong>.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="example-13-3" class="slide level2">
<h2>Example 13-3</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Mis-picked Items Before and After a New Picking System</strong></p>
</div>
<div class="callout-content">
<p>A warehouse manager believed that the number of mis-picked items per shift can be reduced if a pick-to-light system replaces paper pick lists. Ten pickers were selected, and the number of mis-picked items was recorded for one shift before the system was installed and for one shift after it was installed <em>(hypothetical data)</em>. At <span class="math inline">\alpha = 0.05</span>, can the manager conclude that the new system reduced the number of mis-picked items?</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Picker</th>
<th>Before, <span class="math inline">X_B</span></th>
<th>After, <span class="math inline">X_A</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td>6</td>
<td>4</td>
</tr>
<tr class="even">
<td>B</td>
<td>2</td>
<td>3</td>
</tr>
<tr class="odd">
<td>C</td>
<td>7</td>
<td>5</td>
</tr>
<tr class="even">
<td>D</td>
<td>5</td>
<td>1</td>
</tr>
<tr class="odd">
<td>E</td>
<td>4</td>
<td>2</td>
</tr>
<tr class="even">
<td>F</td>
<td>6</td>
<td>3</td>
</tr>
<tr class="odd">
<td>G</td>
<td>3</td>
<td>1</td>
</tr>
<tr class="even">
<td>H</td>
<td>8</td>
<td>5</td>
</tr>
<tr class="odd">
<td>I</td>
<td>4</td>
<td>4</td>
</tr>
<tr class="even">
<td>J</td>
<td>2</td>
<td>5</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="example-13-3-1" class="slide level2">
<h2>Example 13-3</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> State the hypotheses and identify the claim.</p>
<p><span class="math inline">H_0</span>: The number of mis-picked items will not be reduced.</p>
<p><span class="math inline">H_1</span>: The number of mis-picked items will be reduced <em>(claim)</em>.</p>
<p><strong>Step 2.</strong> Find the critical value. Subtract the after values <span class="math inline">X_A</span> from the before values <span class="math inline">X_B</span> and record the sign of each difference.</p>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 23%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th>Picker</th>
<th>A</th>
<th>B</th>
<th>C</th>
<th>D</th>
<th>E</th>
<th>F</th>
<th>G</th>
<th>H</th>
<th>I</th>
<th>J</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sign of difference</td>
<td><span class="math inline">+</span></td>
<td><span class="math inline">-</span></td>
<td><span class="math inline">+</span></td>
<td><span class="math inline">+</span></td>
<td><span class="math inline">+</span></td>
<td><span class="math inline">+</span></td>
<td><span class="math inline">+</span></td>
<td><span class="math inline">+</span></td>
<td><span class="math inline">0</span></td>
<td><span class="math inline">-</span></td>
</tr>
</tbody>
</table>
<p>From <strong>Table A-10</strong>, with <span class="math inline">n = 9</span> (the total number of positive and negative signs; the 0 is not counted) and <span class="math inline">\alpha = 0.05</span> one-tailed, at most <strong>1</strong> negative sign is needed to reject <span class="math inline">H_0</span>, because 1 is the smallest entry in the <span class="math inline">\alpha = 0.05</span> column.</p>
</div>
</div>
</div>
</section>
<section id="example-13-3-2" class="slide level2">
<h2>Example 13-3</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 3 in R</strong> — since <span class="math inline">n \leq 25</span>, the test statistic is the smaller of the two sign counts.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href=""></a>errors_before <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">6</span>, <span class="dv">2</span>, <span class="dv">7</span>, <span class="dv">5</span>, <span class="dv">4</span>, <span class="dv">6</span>, <span class="dv">3</span>, <span class="dv">8</span>, <span class="dv">4</span>, <span class="dv">2</span>)</span>
<span id="cb19-2"><a href=""></a>errors_after  <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">5</span>, <span class="dv">4</span>, <span class="dv">5</span>)</span>
<span id="cb19-3"><a href=""></a></span>
<span id="cb19-4"><a href=""></a><span class="fu">sum</span>(errors_before <span class="sc">&gt;</span> errors_after)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href=""></a><span class="fu">sum</span>(errors_before <span class="sc">&lt;</span> errors_after)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2</code></pre>
</div>
</div>
<p><strong>Step 4.</strong> Make the decision. Compare the test statistic 2 with the critical value 1. Here <span class="math inline">2 &gt; 1</span>, so the decision is to <strong>not reject</strong> <span class="math inline">H_0</span>.</p>
<p><strong>Step 5.</strong> Summarize the results. There is not enough evidence to support the claim that the pick-to-light system reduced the number of mis-picked items.</p>
</div>
</div>
</div>
</section>
<section id="reasoning-before-testing" class="slide level2">
<h2>Reasoning Before Testing</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Caution</strong></p>
</div>
<div class="callout-content">
<p>When conducting a <strong>one-tailed</strong> sign test, the researcher must scrutinize the data to determine whether they <strong>support the null hypothesis</strong>. If they do, there is no need to conduct the test.</p>
<p>In Example 13-3, <span class="math inline">H_0</span> states that the number of mis-picked items will not be reduced. The data would support <span class="math inline">H_0</span> if there were more negative signs than positive signs, because then the before values <span class="math inline">X_B</span> would mostly be smaller than the after values <span class="math inline">X_A</span>. The researcher would stop there. Since the positive signs dominate in Example 13-3, the procedure was continued.</p>
<p>When the sample size is <strong>26 or more</strong>, the normal approximation is used in the same manner as in <a href="#/example-13-2">Example 13-2</a>.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="section-13-3-the-wilcoxon-rank-sum-test" class="title-slide slide level1 center" data-background-color="#2c4a6e">
<h1>Section 13-3: The Wilcoxon Rank Sum Test</h1>

</section>
<section id="why-ranks" class="slide level2">
<h2>Why Ranks?</h2>
<p>The sign test does not consider the <strong>magnitude</strong> of the data: whether a value is 1 point or 100 points below the median, it receives a negative sign. The <strong>Wilcoxon tests</strong> consider differences in magnitudes by using ranks.</p>
<p>The two tests are the <strong>Wilcoxon rank sum test</strong>, used for <em>independent</em> samples (this section), and the <strong>Wilcoxon signed-rank test</strong>, used for <em>dependent</em> samples (Section 13-4). Both are used to compare distributions. The parametric equivalents are the <span class="math inline">z</span> and <span class="math inline">t</span> tests for independent samples and the <span class="math inline">t</span> test for dependent samples.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Wilcoxon Rank Sum Test</strong></p>
</div>
<div class="callout-content">
<p>The <strong>Wilcoxon rank sum test</strong>, sometimes called the <strong>Mann-Whitney test</strong>, is a nonparametric test that uses ranks to determine if two <strong>independent</strong> samples were selected from populations that have the <strong>same distributions</strong>.</p>
</div>
</div>
</div>
<p>In this test the values of the data for both samples are <strong>combined and then ranked</strong>. If <span class="math inline">H_0</span> is true, the values in each sample should be ranked approximately the same, so the rank sums should be approximately equal. A large difference in the sums of the ranks means the distributions are not identical and <span class="math inline">H_0</span> is rejected.</p>
</section>
<section id="assumptions-and-formulas" class="slide level2">
<h2>Assumptions and Formulas</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Assumptions for the Wilcoxon Rank Sum Test</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>The samples are <strong>random</strong> and <strong>independent</strong> of one another.</li>
<li>The size of each sample must be <strong>greater than or equal to 10</strong>.</li>
</ol>
</div>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Formula for the Wilcoxon Rank Sum Test When Samples Are Independent</strong></p>
</div>
<div class="callout-content">
<p><span class="math display">z = \frac{R - \mu_R}{\sigma_R} \qquad \text{where} \qquad \mu_R = \frac{n_1(n_1 + n_2 + 1)}{2}, \qquad \sigma_R = \sqrt{\frac{n_1 n_2 (n_1 + n_2 + 1)}{12}}</span></p>
<ul>
<li><span class="math inline">R</span> = sum of ranks for the <strong>smaller</strong> sample size (<span class="math inline">n_1</span>)</li>
<li><span class="math inline">n_1</span> = smaller of the sample sizes, <span class="math inline">n_2</span> = larger of the sample sizes</li>
<li><span class="math inline">n_1 \geq 10</span> and <span class="math inline">n_2 \geq 10</span></li>
</ul>
<p>If both samples are the same size, either size can be used as <span class="math inline">n_1</span>. <strong>Table A-4</strong> is used for the critical values.</p>
</div>
</div>
</div>
</section>
<section id="procedure-table-wilcoxon-rank-sum-test" class="slide level2">
<h2>Procedure Table: Wilcoxon Rank Sum Test</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Five Steps</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> State the hypotheses and identify the claim.</p>
<p><strong>Step 2.</strong> Find the critical value(s). Use <strong>Table A-4</strong>.</p>
<p><strong>Step 3.</strong> Compute the test statistic.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;a. Combine the data from the two samples, arrange the combined data in order, and rank each value.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;b. Sum the ranks of the group with the smaller sample size. (If both groups have the same sample size, either one can be used.)</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;c.&nbsp;Use the formulas for <span class="math inline">\mu_R</span>, <span class="math inline">\sigma_R</span> and <span class="math inline">z</span>.</p>
<p><strong>Step 4.</strong> Make the decision.</p>
<p><strong>Step 5.</strong> Summarize the results.</p>
</div>
</div>
</div>
</section>
<section id="example-13-4" class="slide level2">
<h2>Example 13-4</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Order-Picking Times at Two Distribution Centres</strong></p>
</div>
<div class="callout-content">
<p>An operations team draws two independent random samples of order lines, one from the company’s Kaohsiung distribution centre and one from its Taoyuan distribution centre, and records the time in seconds needed to pick each line <em>(hypothetical data)</em>. At <span class="math inline">\alpha = 0.05</span>, is there a difference in the picking times at the two centres?</p>
<pre><code>Kaohsiung    58   60   63   72   74   76   78   88   92   96  125
Taoyuan      69   79   84   88   93   99  106  112  120  131  140  152</code></pre>
</div>
</div>
</div>
</section>
<section id="example-13-4-1" class="slide level2">
<h2>Example 13-4</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> State the hypotheses and identify the claim.</p>
<p><span class="math inline">H_0</span>: There is no difference in the picking times at the two distribution centres.</p>
<p><span class="math inline">H_1</span>: There is a difference in the picking times at the two distribution centres <em>(claim)</em>.</p>
<p><strong>Step 2.</strong> Find the critical values. Since <span class="math inline">\alpha = 0.05</span> and the test is two-tailed, the critical values from Table A-4 are <span class="math inline">+1.96</span> and <span class="math inline">-1.96</span>.</p>
<p><strong>Step 3a.</strong> Combine the data, arrange in ascending order, and rank each value (K = Kaohsiung, T = Taoyuan).</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Time</th>
<th>58</th>
<th>60</th>
<th>63</th>
<th>69</th>
<th>72</th>
<th>74</th>
<th>76</th>
<th>78</th>
<th>79</th>
<th>84</th>
<th>88</th>
<th>88</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Centre</td>
<td>K</td>
<td>K</td>
<td>K</td>
<td>T</td>
<td>K</td>
<td>K</td>
<td>K</td>
<td>K</td>
<td>T</td>
<td>T</td>
<td>K</td>
<td>T</td>
</tr>
<tr class="even">
<td>Rank</td>
<td>1</td>
<td>2</td>
<td>3</td>
<td>4</td>
<td>5</td>
<td>6</td>
<td>7</td>
<td>8</td>
<td>9</td>
<td>10</td>
<td>11.5</td>
<td>11.5</td>
</tr>
</tbody>
</table>
<table class="caption-top">
<thead>
<tr class="header">
<th>Time</th>
<th>92</th>
<th>93</th>
<th>96</th>
<th>99</th>
<th>106</th>
<th>112</th>
<th>120</th>
<th>125</th>
<th>131</th>
<th>140</th>
<th>152</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Centre</td>
<td>K</td>
<td>T</td>
<td>K</td>
<td>T</td>
<td>T</td>
<td>T</td>
<td>T</td>
<td>K</td>
<td>T</td>
<td>T</td>
<td>T</td>
</tr>
<tr class="even">
<td>Rank</td>
<td>13</td>
<td>14</td>
<td>15</td>
<td>16</td>
<td>17</td>
<td>18</td>
<td>19</td>
<td>20</td>
<td>21</td>
<td>22</td>
<td>23</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="example-13-4-2" class="slide level2">
<h2>Example 13-4</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 3b.</strong> Kaohsiung has the smaller sample size, so sum its ranks.</p>
<p><span class="math display">R = 1 + 2 + 3 + 5 + 6 + 7 + 8 + 11.5 + 13 + 15 + 20 = 91.5</span></p>
<p><strong>Step 3c.</strong> Substitute in the formulas, with <span class="math inline">n_1 = 11</span> and <span class="math inline">n_2 = 12</span>.</p>
<p><span class="math display">\mu_R = \frac{11(11 + 12 + 1)}{2} = 132 \qquad \sigma_R = \sqrt{\frac{(11)(12)(11 + 12 + 1)}{12}} = \sqrt{264} = 16.248</span></p>
<p><span class="math display">z = \frac{R - \mu_R}{\sigma_R} = \frac{91.5 - 132}{16.248} = -2.493</span></p>
</div>
</div>
</div>
</section>
<section id="example-13-4-3" class="slide level2">
<h2>Example 13-4</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 3 in R</strong> — <code>rank()</code> reproduces the ranking above, including the averaged ranks for the tied value 88.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href=""></a>kaohsiung <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">58</span>, <span class="dv">60</span>, <span class="dv">63</span>, <span class="dv">72</span>, <span class="dv">74</span>, <span class="dv">76</span>, <span class="dv">78</span>, <span class="dv">88</span>, <span class="dv">92</span>, <span class="dv">96</span>, <span class="dv">125</span>)</span>
<span id="cb24-2"><a href=""></a>taoyuan   <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">69</span>, <span class="dv">79</span>, <span class="dv">84</span>, <span class="dv">88</span>, <span class="dv">93</span>, <span class="dv">99</span>, <span class="dv">106</span>, <span class="dv">112</span>, <span class="dv">120</span>, <span class="dv">131</span>, <span class="dv">140</span>, <span class="dv">152</span>)</span>
<span id="cb24-3"><a href=""></a>ranks <span class="ot">&lt;-</span> <span class="fu">rank</span>(<span class="fu">c</span>(kaohsiung, taoyuan))</span>
<span id="cb24-4"><a href=""></a></span>
<span id="cb24-5"><a href=""></a>ranks</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]  1.0  2.0  3.0  5.0  6.0  7.0  8.0 11.5 13.0 15.0 20.0  4.0  9.0 10.0 11.5
[16] 14.0 16.0 17.0 18.0 19.0 21.0 22.0 23.0</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href=""></a><span class="fu">sum</span>(ranks[<span class="dv">1</span><span class="sc">:</span><span class="dv">11</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 91.5</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href=""></a>z <span class="ot">&lt;-</span> (<span class="fl">91.5</span> <span class="sc">-</span> <span class="dv">11</span> <span class="sc">*</span> (<span class="dv">11</span> <span class="sc">+</span> <span class="dv">12</span> <span class="sc">+</span> <span class="dv">1</span>) <span class="sc">/</span> <span class="dv">2</span>) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">11</span> <span class="sc">*</span> <span class="dv">12</span> <span class="sc">*</span> (<span class="dv">11</span> <span class="sc">+</span> <span class="dv">12</span> <span class="sc">+</span> <span class="dv">1</span>) <span class="sc">/</span> <span class="dv">12</span>)</span>
<span id="cb28-2"><a href=""></a>z</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -2.492603</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="example-13-4-4" class="slide level2">
<h2>Example 13-4</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 4.</strong> Make the decision. The decision is to <strong>reject</strong> the null hypothesis, since <span class="math inline">-2.493 &lt; -1.96</span>.</p>
<p><strong>Step 5.</strong> Summarize the results. There is enough evidence to support the claim that there is a difference in the picking times at the two distribution centres.</p>
<p><strong>P-value.</strong> The test is two-tailed, so the P-value is twice the area to the left of <span class="math inline">z = -2.493</span>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href=""></a><span class="dv">2</span> <span class="sc">*</span> <span class="fu">pnorm</span>(z)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.01268107</code></pre>
</div>
</div>
<p>Since <span class="math inline">P = 0.0127 &lt; 0.05</span>, <span class="math inline">H_0</span> is rejected, which agrees with the traditional decision.</p>
</div>
</div>
</div>
</section>
<section id="the-rank-sum-test-in-r" class="slide level2">
<h2>The Rank Sum Test in R</h2>
<p>R’s <code>wilcox.test()</code> reports the Mann-Whitney <span class="math inline">U</span> statistic rather than the rank sum <span class="math inline">R</span>. The two statistics carry the same information: <span class="math inline">U = R - \dfrac{n_1(n_1+1)}{2} = 91.5 - 66 = 25.5</span>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href=""></a><span class="fu">wilcox.test</span>(kaohsiung, taoyuan)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon rank sum test with continuity correction

data:  kaohsiung and taoyuan
W = 25.5, p-value = 0.0138
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Caution</strong></p>
</div>
<div class="callout-content">
<p>The hand computation taught here uses the plain normal approximation, with neither a tie correction nor a continuity correction, and gives <span class="math inline">P = 0.0127</span>. <code>wilcox.test()</code> applies a continuity correction by default and reports <span class="math inline">P = 0.0138</span>. Both P-values are far below <span class="math inline">\alpha = 0.05</span>, so the decision is unchanged.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="section-13-4-the-wilcoxon-signed-rank-test" class="title-slide slide level1 center" data-background-color="#2c4a6e">
<h1>Section 13-4: The Wilcoxon Signed-Rank Test</h1>

</section>
<section id="the-wilcoxon-signed-rank-test" class="slide level2">
<h2>The Wilcoxon Signed-Rank Test</h2>
<p>When the samples are <strong>dependent</strong>, as they would be in a before-and-after test using the same subjects, the Wilcoxon signed-rank test can be used in place of the <span class="math inline">t</span> test for dependent samples. Again, this test does not require the condition of normality.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Wilcoxon Signed-Rank Test</strong></p>
</div>
<div class="callout-content">
<p>The <strong>Wilcoxon signed-rank test</strong> is a nonparametric test used to test whether two <strong>dependent</strong> samples have been selected from two populations having the <strong>same distributions</strong>.</p>
</div>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Assumptions for the Wilcoxon Signed-Rank Test</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>The paired data have been obtained from a <strong>random sample</strong>.</li>
<li>The population of <strong>differences</strong> has a distribution that is approximately <strong>symmetric</strong>.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="the-test-statistic-w_s" class="slide level2">
<h2>The Test Statistic <span class="math inline">w_s</span></h2>
<p>To find the test statistic for the Wilcoxon signed-rank test, denoted by <span class="math inline">w_s</span>, when <span class="math inline">n \leq 30</span>:</p>
<ul>
<li>rank the <strong>absolute values</strong> of the differences of each pair of data values;</li>
<li>assign either a <span class="math inline">+</span> or a <span class="math inline">-</span> sign to each rank according to the original sign of the difference;</li>
<li>sum the positive ranks and the negative ranks <strong>separately</strong>;</li>
<li>select the <strong>smaller of the absolute values</strong> of the two sums as the test statistic <span class="math inline">w_s</span>.</li>
</ul>
<p><strong>Table A-11</strong> is used for the critical values when <span class="math inline">n \leq 30</span>: use the column for the critical value along with the row for the value of <span class="math inline">n</span>.</p>
</section>
<section id="the-test-statistic-w_s-1" class="slide level2">
<h2>The Test Statistic <span class="math inline">w_s</span></h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Large Samples: <span class="math inline">n &gt; 30</span></strong></p>
</div>
<div class="callout-content">
<p>When <span class="math inline">n &gt; 30</span>, the normal distribution approximates the Wilcoxon distribution and the same critical values from <strong>Table A-4</strong> are used:</p>
<p><span class="math display">z = \frac{w_s - \dfrac{n(n+1)}{4}}{\sqrt{\dfrac{n(n+1)(2n+1)}{24}}}</span></p>
<p>where <span class="math inline">n</span> = number of pairs where the difference is not 0, and <span class="math inline">w_s</span> = smaller sum in absolute value of the signed ranks.</p>
</div>
</div>
</div>
</section>
<section id="procedure-table-wilcoxon-signed-rank-test" class="slide level2">
<h2>Procedure Table: Wilcoxon Signed-Rank Test</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Five Steps</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> State the hypotheses and identify the claim.</p>
<p><strong>Step 2.</strong> Find the critical value from <strong>Table A-11</strong> when <span class="math inline">n \leq 30</span> and from <strong>Table A-4</strong> when <span class="math inline">n &gt; 30</span>.</p>
<p><strong>Step 3.</strong> Compute the test statistic. When <span class="math inline">n \leq 30</span>: (a) make a table with columns <span class="math inline">X_B</span>, <span class="math inline">X_A</span>, <span class="math inline">D = X_B - X_A</span>, <span class="math inline">|D|</span>, Rank and Signed rank; (b) find the differences; (c) find the absolute value of each difference; (d) rank each absolute value from lowest to highest; (e) give each rank the sign of its difference; (f) find the sum of the positive ranks and the sum of the negative ranks separately; (g) select the smaller of the absolute values of the sums as <span class="math inline">w_s</span>. When <span class="math inline">n &gt; 30</span>, use the <span class="math inline">z</span> formula and Table A-4.</p>
<p><strong>Step 4.</strong> Make the decision. <strong>Reject <span class="math inline">H_0</span> if the test statistic is less than or equal to the critical value.</strong></p>
<p><strong>Step 5.</strong> Summarize the results.</p>
</div>
</div>
</div>
</section>
<section id="example-13-5" class="slide level2">
<h2>Example 13-5</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Complaints Before and After a New Self-Service Menu</strong></p>
</div>
<div class="callout-content">
<p>The manager of a customer service centre wishes to see whether the number of escalated complaints per day will change after a new self-service menu is added to the hotline. The number of escalated complaints is recorded for 7 days before the menu is added and for the matching 7 days of the following week <em>(hypothetical data)</em>. Is there enough evidence to support the claim, at <span class="math inline">\alpha = 0.05</span>, that there is a difference in the number of escalated complaints before and after the change?</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Day</th>
<th>Before</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Monday</td>
<td>9</td>
<td>7</td>
</tr>
<tr class="even">
<td>Tuesday</td>
<td>4</td>
<td>5</td>
</tr>
<tr class="odd">
<td>Wednesday</td>
<td>5</td>
<td>6</td>
</tr>
<tr class="even">
<td>Thursday</td>
<td>8</td>
<td>5</td>
</tr>
<tr class="odd">
<td>Friday</td>
<td>7</td>
<td>3</td>
</tr>
<tr class="even">
<td>Saturday</td>
<td>10</td>
<td>8</td>
</tr>
<tr class="odd">
<td>Sunday</td>
<td>14</td>
<td>6</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="example-13-5-1" class="slide level2">
<h2>Example 13-5</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> State the hypotheses and identify the claim.</p>
<p><span class="math inline">H_0</span>: There is no difference in escalated complaints before and after the change.</p>
<p><span class="math inline">H_1</span>: There is a difference in escalated complaints before and after the change <em>(claim)</em>.</p>
<p><strong>Step 2.</strong> Because <span class="math inline">n \leq 30</span>, use <strong>Table A-11</strong>: with <span class="math inline">n = 7</span> and <span class="math inline">\alpha = 0.05</span> (two-tailed) the critical value is <strong>2</strong>.</p>
<p><strong>Step 3.</strong> Build the table of differences <span class="math inline">D = X_B - X_A</span>, their absolute values, ranks and signed ranks.</p>
<table class="caption-top">
<colgroup>
<col style="width: 12%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Day</th>
<th>Before, <span class="math inline">X_B</span></th>
<th>After, <span class="math inline">X_A</span></th>
<th><span class="math inline">D</span></th>
<th><span class="math inline">\lvert D \rvert</span></th>
<th>Rank</th>
<th>Signed rank</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mon.</td>
<td>9</td>
<td>7</td>
<td>2</td>
<td>2</td>
<td>3.5</td>
<td><span class="math inline">+3.5</span></td>
</tr>
<tr class="even">
<td>Tues.</td>
<td>4</td>
<td>5</td>
<td><span class="math inline">-1</span></td>
<td>1</td>
<td>1.5</td>
<td><span class="math inline">-1.5</span></td>
</tr>
<tr class="odd">
<td>Wed.</td>
<td>5</td>
<td>6</td>
<td><span class="math inline">-1</span></td>
<td>1</td>
<td>1.5</td>
<td><span class="math inline">-1.5</span></td>
</tr>
<tr class="even">
<td>Thurs.</td>
<td>8</td>
<td>5</td>
<td>3</td>
<td>3</td>
<td>5</td>
<td><span class="math inline">+5</span></td>
</tr>
<tr class="odd">
<td>Fri.</td>
<td>7</td>
<td>3</td>
<td>4</td>
<td>4</td>
<td>6</td>
<td><span class="math inline">+6</span></td>
</tr>
<tr class="even">
<td>Sat.</td>
<td>10</td>
<td>8</td>
<td>2</td>
<td>2</td>
<td>3.5</td>
<td><span class="math inline">+3.5</span></td>
</tr>
<tr class="odd">
<td>Sun.</td>
<td>14</td>
<td>6</td>
<td>8</td>
<td>8</td>
<td>7</td>
<td><span class="math inline">+7</span></td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="example-13-5-2" class="slide level2">
<h2>Example 13-5</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 3 (f) and (g).</strong> Sum the positive and negative ranks separately and take the smaller absolute value.</p>
<p><span class="math display">\text{Positive rank sum} = (+3.5) + (+5) + (+6) + (+3.5) + (+7) = +25</span></p>
<p><span class="math display">\text{Negative rank sum} = (-1.5) + (-1.5) = -3 \qquad \Rightarrow \qquad w_s = \lvert -3 \rvert = 3</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href=""></a>complaints_before <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">9</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">8</span>, <span class="dv">7</span>, <span class="dv">10</span>, <span class="dv">14</span>)</span>
<span id="cb34-2"><a href=""></a>complaints_after  <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">7</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">5</span>, <span class="dv">3</span>,  <span class="dv">8</span>,  <span class="dv">6</span>)</span>
<span id="cb34-3"><a href=""></a>differences  <span class="ot">&lt;-</span> complaints_before <span class="sc">-</span> complaints_after</span>
<span id="cb34-4"><a href=""></a>signed_ranks <span class="ot">&lt;-</span> <span class="fu">sign</span>(differences) <span class="sc">*</span> <span class="fu">rank</span>(<span class="fu">abs</span>(differences))</span>
<span id="cb34-5"><a href=""></a></span>
<span id="cb34-6"><a href=""></a>signed_ranks</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  3.5 -1.5 -1.5  5.0  6.0  3.5  7.0</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href=""></a><span class="fu">sum</span>(signed_ranks[signed_ranks <span class="sc">&gt;</span> <span class="dv">0</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 25</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href=""></a><span class="fu">sum</span>(signed_ranks[signed_ranks <span class="sc">&lt;</span> <span class="dv">0</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -3</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="example-13-5-3" class="slide level2">
<h2>Example 13-5</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 4.</strong> Make the decision. Reject <span class="math inline">H_0</span> if the test statistic is less than or equal to the critical value. In this case <span class="math inline">3 &gt; 2</span>, so the decision is to <strong>not reject</strong> the null hypothesis.</p>
<p><strong>Step 5.</strong> Summarize the results. There is not enough evidence at <span class="math inline">\alpha = 0.05</span> to support the claim that there is a difference in the number of escalated complaints before and after the change. Hence, the new self-service menu probably made no difference to the number of escalated complaints.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href=""></a><span class="fu">wilcox.test</span>(complaints_before, complaints_after, <span class="at">paired =</span> <span class="cn">TRUE</span>, <span class="at">exact =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon signed rank test with continuity correction

data:  complaints_before and complaints_after
V = 25, p-value = 0.07488
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
<p>R reports <span class="math inline">V = 25</span>, the sum of the <strong>positive</strong> ranks, whereas <span class="math inline">w_s = 3</span> is the smaller of the two sums. The P-value, <span class="math inline">0.0749 &gt; 0.05</span>, leads to the same decision.</p>
</div>
</div>
</div>
</section>
<section id="rationale-for-the-signed-rank-test" class="slide level2">
<h2>Rationale for the Signed-Rank Test</h2>
<p>Think of a diet study. If the diet is working, most of the postweights will be smaller than the preweights. When the postweights are subtracted from the preweights, most of the signs will be <strong>positive</strong>, and the absolute value of the sum of the <strong>negative</strong> ranks will be <strong>small</strong> — probably smaller than the critical value from Table A-11 — and <span class="math inline">H_0</span> will be rejected.</p>
<p>If the diet does <strong>not</strong> work, some people will gain weight, others will lose weight, and still others will stay about the same. The sum of the positive ranks and the absolute value of the sum of the negative ranks will then be approximately equal, each about one-half of the sum of all the ranks. The smaller of the two absolute values will still be <strong>larger</strong> than the critical value, and <span class="math inline">H_0</span> will not be rejected.</p>
</section></section>
<section>
<section id="section-13-5-the-kruskal-wallis-test" class="title-slide slide level1 center" data-background-color="#2c4a6e">
<h1>Section 13-5: The Kruskal-Wallis Test</h1>

</section>
<section id="the-kruskal-wallis-test" class="slide level2">
<h2>The Kruskal-Wallis Test</h2>
<p>The analysis of variance uses the <span class="math inline">F</span> test to compare the means of three or more populations. The assumptions for the ANOVA test are that the populations are <strong>normally distributed</strong> and that the <strong>population variances are equal</strong>. When these assumptions cannot be met, the nonparametric Kruskal-Wallis test, sometimes called the <strong><span class="math inline">H</span> test</strong>, can be used to compare three or more means.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Kruskal-Wallis Test</strong></p>
</div>
<div class="callout-content">
<p>The <strong>Kruskal-Wallis test</strong> is a nonparametric test that is used to determine whether <strong>three or more</strong> samples came from populations with the <strong>same distributions</strong>.</p>
</div>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Assumptions for the Kruskal-Wallis Test</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>There are at least <strong>three</strong> random samples.</li>
<li>The size of each sample must be <strong>at least 5</strong>.</li>
</ol>
</div>
</div>
</div>
<p>When each sample size is 5 or more, the distribution can be approximated by the <strong>chi-square</strong> distribution with <span class="math inline">\text{d.f.} = k - 1</span>, where <span class="math inline">k</span> is the number of groups.</p>
</section>
<section id="the-h-statistic" class="slide level2">
<h2>The <span class="math inline">H</span> Statistic</h2>
<p>In the Kruskal-Wallis test, all the data values are considered as one group and ranked. The ranks are then separated and the <span class="math inline">H</span> formula, which approximates the variance of the ranks, is computed. If the samples come from different populations, the sums of the ranks will differ and <span class="math inline">H</span> will be <strong>large</strong>, so <span class="math inline">H_0</span> is rejected. If they come from the same population, the rank sums will be about the same and <span class="math inline">H</span> will be <strong>small</strong>. This test is always a <strong>right-tailed</strong> test, and <strong>Table A-6</strong> (chi-square) with <span class="math inline">\text{d.f.} = k - 1</span> supplies the critical value.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Formula for the Kruskal-Wallis Test</strong></p>
</div>
<div class="callout-content">
<p><span class="math display">H = \frac{12}{N(N+1)}\left(\frac{R_1^2}{n_1} + \frac{R_2^2}{n_2} + \cdots + \frac{R_k^2}{n_k}\right) - 3(N+1)</span></p>
<p>where <span class="math inline">R_i</span> = sum of ranks of sample <span class="math inline">i</span>, <span class="math inline">n_i</span> = size of sample <span class="math inline">i</span>, <span class="math inline">N = n_1 + n_2 + \cdots + n_k</span> and <span class="math inline">k</span> = number of samples.</p>
<p>Since the test is right-tailed, <span class="math inline">H_0</span> is rejected if the test statistic is <strong>greater than or equal to</strong> the critical value.</p>
</div>
</div>
</div>
</section>
<section id="procedure-table-kruskal-wallis-test" class="slide level2">
<h2>Procedure Table: Kruskal-Wallis Test</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Five Steps</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> State the hypotheses and identify the claim.</p>
<p><strong>Step 2.</strong> Find the critical value. Use the chi-square table, <strong>Table A-6</strong>, with <span class="math inline">\text{d.f.} = k - 1</span> (<span class="math inline">k</span> = number of groups).</p>
<p><strong>Step 3.</strong> Compute the test statistic. (a) Arrange the data from lowest to highest and rank each value. (b) Find the sum of the ranks of each group. (c) Substitute in the <span class="math inline">H</span> formula.</p>
<p><strong>Step 4.</strong> Make the decision.</p>
<p><strong>Step 5.</strong> Summarize the results.</p>
</div>
</div>
</div>
</section>
<section id="example-13-6" class="slide level2">
<h2>Example 13-6</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Transit Times of Three Air Freight Carriers</strong></p>
</div>
<div class="callout-content">
<p>A trade compliance team compares three air freight carriers on the Taipei-Tokyo lane. Five shipments are selected at random from each carrier and the door-to-door transit time, in hours, is recorded <em>(hypothetical data)</em>. At <span class="math inline">\alpha = 0.05</span>, is there enough evidence to claim that the transit times differ among the three carriers?</p>
<pre><code>Carrier A   Carrier B   Carrier C
   38.9        28.6        25.4
   42.8        31.2        27.1
   44.1        34.0        29.8
   46.5        37.6        32.5
   49.3        41.2        35.3</code></pre>
</div>
</div>
</div>
</section>
<section id="example-13-6-1" class="slide level2">
<h2>Example 13-6</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> State the hypotheses and identify the claim.</p>
<p><span class="math inline">H_0</span>: There is no difference in the transit times of the three carriers.</p>
<p><span class="math inline">H_1</span>: There is a difference in the transit times of the three carriers <em>(claim)</em>.</p>
<p><strong>Step 2.</strong> Find the critical value. Use Table A-6 with <span class="math inline">\text{d.f.} = k - 1 = 3 - 1 = 2</span> and <span class="math inline">\alpha = 0.05</span>; the critical value is <strong>5.991</strong>.</p>
<p><strong>Step 3a.</strong> Arrange all the data from lowest to highest and rank each value.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Hours</th>
<th>25.4</th>
<th>27.1</th>
<th>28.6</th>
<th>29.8</th>
<th>31.2</th>
<th>32.5</th>
<th>34.0</th>
<th>35.3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Carrier</td>
<td>C</td>
<td>C</td>
<td>B</td>
<td>C</td>
<td>B</td>
<td>C</td>
<td>B</td>
<td>C</td>
</tr>
<tr class="even">
<td>Rank</td>
<td>1</td>
<td>2</td>
<td>3</td>
<td>4</td>
<td>5</td>
<td>6</td>
<td>7</td>
<td>8</td>
</tr>
</tbody>
</table>
<table class="caption-top">
<thead>
<tr class="header">
<th>Hours</th>
<th>37.6</th>
<th>38.9</th>
<th>41.2</th>
<th>42.8</th>
<th>44.1</th>
<th>46.5</th>
<th>49.3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Carrier</td>
<td>B</td>
<td>A</td>
<td>B</td>
<td>A</td>
<td>A</td>
<td>A</td>
<td>A</td>
</tr>
<tr class="even">
<td>Rank</td>
<td>9</td>
<td>10</td>
<td>11</td>
<td>12</td>
<td>13</td>
<td>14</td>
<td>15</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="example-13-6-2" class="slide level2">
<h2>Example 13-6</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 3b.</strong> Find the sum of the ranks for each carrier.</p>
<p><span class="math display">R_1 = 10 + 12 + 13 + 14 + 15 = 64 \qquad R_2 = 3 + 5 + 7 + 9 + 11 = 35</span></p>
<p><span class="math display">R_3 = 1 + 2 + 4 + 6 + 8 = 21</span></p>
<p><strong>Step 3c.</strong> Substitute in the formula, with <span class="math inline">N = 15</span> and <span class="math inline">n_1 = n_2 = n_3 = 5</span>.</p>
<p><span class="math display">H = \frac{12}{15(15+1)}\left(\frac{64^2}{5} + \frac{35^2}{5} + \frac{21^2}{5}\right) - 3(15+1) = 9.62</span></p>
<p><strong>Step 4.</strong> Make the decision. Since the test statistic <span class="math inline">9.62</span> is greater than <span class="math inline">5.991</span>, <strong>reject</strong> the null hypothesis.</p>
<p><strong>Step 5.</strong> Summarize the results. There is enough evidence to support the claim that the transit times differ among the three carriers.</p>
</div>
</div>
</div>
</section>
<section id="example-13-6-3" class="slide level2">
<h2>Example 13-6</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 3 in R</strong> — <code>kruskal.test()</code> ranks the pooled data and returns <span class="math inline">H</span> directly.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href=""></a>transit_hours <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">38.9</span>, <span class="fl">42.8</span>, <span class="fl">44.1</span>, <span class="fl">46.5</span>, <span class="fl">49.3</span>,</span>
<span id="cb43-2"><a href=""></a>                   <span class="fl">28.6</span>, <span class="fl">31.2</span>, <span class="fl">34.0</span>, <span class="fl">37.6</span>, <span class="fl">41.2</span>,</span>
<span id="cb43-3"><a href=""></a>                   <span class="fl">25.4</span>, <span class="fl">27.1</span>, <span class="fl">29.8</span>, <span class="fl">32.5</span>, <span class="fl">35.3</span>)</span>
<span id="cb43-4"><a href=""></a>carrier <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"A"</span>, <span class="st">"B"</span>, <span class="st">"C"</span>), <span class="at">each =</span> <span class="dv">5</span>)</span>
<span id="cb43-5"><a href=""></a></span>
<span id="cb43-6"><a href=""></a><span class="fu">kruskal.test</span>(transit_hours <span class="sc">~</span> carrier)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  transit_hours by carrier
Kruskal-Wallis chi-squared = 9.62, df = 2, p-value = 0.008148</code></pre>
</div>
</div>
<p>The critical value is <code>qchisq(0.95, df = 2)</code> <span class="math inline">= 5.991</span> and the P-value is <span class="math inline">0.0081</span>.</p>
</div>
</div>
</div>
</section>
<section id="example-13-6-4" class="slide level2">
<h2>Example 13-6</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>The <span class="math inline">H</span> formula by hand.</strong> The formula on the procedure slide can be computed directly from the rank sums and checked against the built-in test.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href=""></a>ranks <span class="ot">&lt;-</span> <span class="fu">rank</span>(transit_hours)</span>
<span id="cb45-2"><a href=""></a></span>
<span id="cb45-3"><a href=""></a><span class="fu">sum</span>(ranks[carrier <span class="sc">==</span> <span class="st">"A"</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 64</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href=""></a><span class="fu">sum</span>(ranks[carrier <span class="sc">==</span> <span class="st">"B"</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 35</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href=""></a><span class="fu">sum</span>(ranks[carrier <span class="sc">==</span> <span class="st">"C"</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 21</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href=""></a><span class="dv">12</span> <span class="sc">/</span> (<span class="dv">15</span> <span class="sc">*</span> (<span class="dv">15</span> <span class="sc">+</span> <span class="dv">1</span>)) <span class="sc">*</span> (<span class="dv">64</span><span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="dv">5</span> <span class="sc">+</span> <span class="dv">35</span><span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="dv">5</span> <span class="sc">+</span> <span class="dv">21</span><span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="dv">5</span>) <span class="sc">-</span> <span class="dv">3</span> <span class="sc">*</span> (<span class="dv">15</span> <span class="sc">+</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9.62</code></pre>
</div>
</div>
<p>There are no tied transit times, so the hand formula and <code>kruskal.test()</code> agree exactly.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="section-13-6-the-spearman-rank-correlation-coefficient-and-the-runs-test" class="title-slide slide level1 center" data-background-color="#2c4a6e">
<h1>Section 13-6: The Spearman Rank Correlation Coefficient and the Runs Test</h1>

</section>
<section id="the-spearman-rank-correlation-coefficient" class="slide level2">
<h2>The Spearman Rank Correlation Coefficient</h2>
<p>Chapter 10’s Pearson correlation coefficient (<span class="math inline">-1</span> to <span class="math inline">+1</span>) tests whether two variables are <strong>linearly related</strong>, assuming <strong>normally distributed</strong> populations. When they are not, use the nonparametric equivalent for ranked data.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Spearman Rank Correlation Coefficient</strong></p>
</div>
<div class="callout-content">
<p>The <strong>Spearman rank correlation coefficient</strong>, denoted by <span class="math inline">r_s</span>, is a nonparametric statistic that uses <strong>ranks</strong> to determine if there is a relationship between two variables.</p>
</div>
</div>
</div>
<p>Instead, rank each data set and compute <span class="math inline">r_s</span> from the rank differences.</p>
<ul>
<li>If both sets of data have the <strong>same</strong> ranks, <span class="math inline">r_s = +1</span>.</li>
<li>If the sets are ranked in exactly the <strong>opposite</strong> way, <span class="math inline">r_s = -1</span>.</li>
<li>If there is <strong>no</strong> relationship between the rankings, <span class="math inline">r_s</span> will be near 0.</li>
</ul>
</section>
<section id="formula-and-hypotheses" class="slide level2">
<h2>Formula and Hypotheses</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Assumptions for Spearman’s Rank Correlation Coefficient</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>The sample is a <strong>random sample</strong>.</li>
<li>The data consist of <strong>two measurements or observations taken on the same individual</strong>.</li>
</ol>
</div>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Formula for Computing the Spearman Rank Correlation Coefficient</strong></p>
</div>
<div class="callout-content">
<p><span class="math display">r_s = 1 - \frac{6 \sum d^2}{n(n^2 - 1)}</span></p>
<p>where <span class="math inline">d</span> = difference in ranks and <span class="math inline">n</span> = number of data pairs.</p>
<p>Use it when the ranks have <strong>no ties</strong>; otherwise apply the Chapter 10 Pearson formula to the ranks:</p>
<p><span class="math display">r = \frac{n\sum xy - (\sum x)(\sum y)}{\sqrt{\left[n\sum x^2 - (\sum x)^2\right]\left[n\sum y^2 - (\sum y)^2\right]}}</span></p>
</div>
</div>
</div>
<p><strong>Table A-12</strong> gives critical values for <span class="math inline">n \leq 30</span>; for larger <span class="math inline">n</span> use the normal distribution. All tests here are <strong>two-tailed</strong>: <span class="math inline">H_0: \rho = 0</span> vs.&nbsp;<span class="math inline">H_1: \rho \neq 0</span>.</p>
</section>
<section id="procedure-table-finding-and-testing-r_s" class="slide level2">
<h2>Procedure Table: Finding and Testing <span class="math inline">r_s</span></h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Five Steps</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> State the hypotheses.</p>
<p><strong>Step 2.</strong> Find the critical values.</p>
<p><strong>Step 3.</strong> Find the test statistic. (a) Rank the values in each data set. (b) Subtract the rankings for each pair of data values (<span class="math inline">X_1 - X_2</span>). (c) Square the differences. (d) Find the sum of the squares. (e) Substitute in the formula <span class="math inline">r_s = 1 - \dfrac{6\sum d^2}{n(n^2-1)}</span>.</p>
<p><strong>Step 4.</strong> Make the decision.</p>
<p><strong>Step 5.</strong> Summarize the results.</p>
</div>
</div>
</div>
</section>
<section id="example-13-7" class="slide level2">
<h2>Example 13-7</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Order Volume and Quality-Audit Score of Suppliers</strong></p>
</div>
<div class="callout-content">
<p>A sourcing manager wishes to see whether the annual order volume a supplier receives is related to the supplier’s quality-audit score. Eight suppliers are selected, and the annual order volume (in thousands of units) and the audit score (out of 100) are recorded <em>(hypothetical data)</em>. At <span class="math inline">\alpha = 0.05</span>, is there a significant linear relationship between the order volume and the audit score?</p>
<pre><code>Supplier   Order volume   Audit score
   A             24            81
   B             52            72
   C             45            61
   D             31            93
   E             18            78
   F             37            75
   G             76            88
   H             68            68</code></pre>
</div>
</div>
</div>
</section>
<section id="example-13-7-1" class="slide level2">
<h2>Example 13-7</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> State the hypotheses: <span class="math inline">H_0: \rho = 0</span> and <span class="math inline">H_1: \rho \neq 0</span>.</p>
<p><strong>Step 2.</strong> Find the critical value. Use <strong>Table A-12</strong> with <span class="math inline">n = 8</span> and <span class="math inline">\alpha = 0.05</span>; it is <span class="math inline">\pm 0.738</span>.</p>
<p><strong>Step 3a and 3b.</strong> Rank each data set, then subtract the rankings. Let <span class="math inline">X_1</span> be the rank of the order volumes and <span class="math inline">X_2</span> the rank of the audit scores.</p>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 18%">
<col style="width: 20%">
<col style="width: 13%">
<col style="width: 11%">
<col style="width: 13%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th>Supplier</th>
<th>Order volume</th>
<th><span class="math inline">X_1</span></th>
<th>Audit score</th>
<th><span class="math inline">X_2</span></th>
<th><span class="math inline">d = X_1 - X_2</span></th>
<th><span class="math inline">d^2</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td>24</td>
<td>2</td>
<td>81</td>
<td>6</td>
<td><span class="math inline">-4</span></td>
<td>16</td>
</tr>
<tr class="even">
<td>B</td>
<td>52</td>
<td>6</td>
<td>72</td>
<td>3</td>
<td>3</td>
<td>9</td>
</tr>
<tr class="odd">
<td>C</td>
<td>45</td>
<td>5</td>
<td>61</td>
<td>1</td>
<td>4</td>
<td>16</td>
</tr>
<tr class="even">
<td>D</td>
<td>31</td>
<td>3</td>
<td>93</td>
<td>8</td>
<td><span class="math inline">-5</span></td>
<td>25</td>
</tr>
<tr class="odd">
<td>E</td>
<td>18</td>
<td>1</td>
<td>78</td>
<td>5</td>
<td><span class="math inline">-4</span></td>
<td>16</td>
</tr>
<tr class="even">
<td>F</td>
<td>37</td>
<td>4</td>
<td>75</td>
<td>4</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td>G</td>
<td>76</td>
<td>8</td>
<td>88</td>
<td>7</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td>H</td>
<td>68</td>
<td>7</td>
<td>68</td>
<td>2</td>
<td>5</td>
<td>25</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="example-13-7-2" class="slide level2">
<h2>Example 13-7</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 3c to 3e.</strong> Square the differences, sum the squares, and substitute in the formula.</p>
<p><span class="math display">\sum d^2 = 16 + 9 + 16 + 25 + 16 + 0 + 1 + 25 = 108</span></p>
<p><span class="math display">r_s = 1 - \frac{6 \sum d^2}{n(n^2 - 1)} = 1 - \frac{6(108)}{8(8^2 - 1)} = 1 - \frac{648}{504} = -0.286</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href=""></a>order_volume <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">24</span>, <span class="dv">52</span>, <span class="dv">45</span>, <span class="dv">31</span>, <span class="dv">18</span>, <span class="dv">37</span>, <span class="dv">76</span>, <span class="dv">68</span>)</span>
<span id="cb54-2"><a href=""></a>audit_score  <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">81</span>, <span class="dv">72</span>, <span class="dv">61</span>, <span class="dv">93</span>, <span class="dv">78</span>, <span class="dv">75</span>, <span class="dv">88</span>, <span class="dv">68</span>)</span>
<span id="cb54-3"><a href=""></a>d <span class="ot">&lt;-</span> <span class="fu">rank</span>(order_volume) <span class="sc">-</span> <span class="fu">rank</span>(audit_score)</span>
<span id="cb54-4"><a href=""></a></span>
<span id="cb54-5"><a href=""></a><span class="fu">sum</span>(d<span class="sc">^</span><span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 108</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href=""></a><span class="dv">1</span> <span class="sc">-</span> <span class="dv">6</span> <span class="sc">*</span> <span class="dv">108</span> <span class="sc">/</span> (<span class="dv">8</span> <span class="sc">*</span> (<span class="dv">8</span><span class="sc">^</span><span class="dv">2</span> <span class="sc">-</span> <span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.2857143</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href=""></a><span class="fu">cor</span>(order_volume, audit_score, <span class="at">method =</span> <span class="st">"spearman"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.2857143</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="example-13-7-3" class="slide level2">
<h2>Example 13-7</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 4.</strong> Make the decision. <strong>Do not reject</strong> the null hypothesis, since <span class="math inline">-0.286 &gt; -0.738</span>.</p>
<p><strong>Step 5.</strong> Summarize the results. There is not enough evidence to say there is a linear relationship between a supplier’s order volume and its quality-audit score.</p>
</div>
</div>
</div>
</section>
<section id="spearman-rank-correlation-in-r" class="slide level2">
<h2>Spearman Rank Correlation in R</h2>
<p><strong>Prepare data</strong> — plotting the <strong>ranks</strong> against each other shows why <span class="math inline">r_s</span> is close to zero: the points show no consistent upward or downward pattern. The data entered in Example 13-7 are reused here.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href=""></a>supplier_ranks <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">volume_rank =</span> <span class="fu">rank</span>(order_volume),</span>
<span id="cb60-2"><a href=""></a>                             <span class="at">score_rank  =</span> <span class="fu">rank</span>(audit_score))</span>
<span id="cb60-3"><a href=""></a>supplier_ranks</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  volume_rank score_rank
1           2          6
2           6          3
3           5          1
4           3          8
5           1          5
6           4          4
7           8          7
8           7          2</code></pre>
</div>
</div>
</section>
<section id="spearman-rank-correlation-in-r-1" class="slide level2">
<h2>Spearman Rank Correlation in R</h2>
<p><strong>Output figure</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href=""></a><span class="fu">ggplot</span>(supplier_ranks, <span class="fu">aes</span>(volume_rank, score_rank)) <span class="sc">+</span></span>
<span id="cb62-2"><a href=""></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb62-3"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Ranks of Order Volume and Audit Score for Eight Suppliers"</span>,</span>
<span id="cb62-4"><a href=""></a>       <span class="at">x =</span> <span class="st">"Rank of annual order volume"</span>, <span class="at">y =</span> <span class="st">"Rank of quality-audit score"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="ch13_files/figure-revealjs/s13-6-2-1.png" class="quarto-figure quarto-figure-center r-stretch" style="width:80.0%"></section>
<section id="the-runs-test" class="slide level2">
<h2>The Runs Test</h2>
<p>When samples are selected, you assume that they are selected <strong>at random</strong>. How do you know if the data obtained from a sample are truly random? One way to answer this question is to use the <strong>runs test</strong>. Before you can use it, you must be able to determine the number of <strong>runs</strong> in a sequence of events.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Run</strong></p>
</div>
<div class="callout-content">
<p>A <strong>run</strong> is a succession of identical letters preceded or followed by a different letter or no letter at all, such as the beginning or end of the succession.</p>
</div>
</div>
</div>
</section>
<section id="counting-the-runs-in-a-sequence" class="slide level2">
<h2>Counting the Runs in a Sequence</h2>
<p>Consider a researcher interviewing 20 people for a survey, with gender denoted M and F.</p>
<pre><code>Situation 1    M M M M M M M M M M F F F F F F F F F F
Situation 2    F M F M F M F M F M F M F M F M F M F M
Situation 3    F F F M M F M F M M F F M M F F M M M F</code></pre>
<p>Situation 1 does not look random — 10 males were selected first, then 10 females; it has only <strong>2 runs</strong>. Situation 2 does not look random either — the researcher seems to alternate; it has <strong>20 runs</strong>, each letter forming its own run. Situation 3 looks as if it may be random; it has <strong>11 runs</strong>. Here <span class="math inline">n_1 = 10</span> and <span class="math inline">n_2 = 10</span> in all three situations, and <span class="math inline">G</span> denotes the number of runs.</p>
</section>
<section id="example-13-8" class="slide level2">
<h2>Example 13-8</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Number of Runs</strong></p>
</div>
<div class="callout-content">
<p>Determine the number of runs and the values of <span class="math inline">n_1</span> and <span class="math inline">n_2</span> in each sequence.</p>
<pre><code>a.   D D D X X D D X          (D = domestic order, X = export order)
b.   L L E L E E E E L L      (E = early shift, L = late shift)
c.   C C P P C P P P C C P    (C = cash, P = card)</code></pre>
<p>Back to <a href="#/example-13-9">Example 13-9</a></p>
</div>
</div>
</div>
</section>
<section id="example-13-8-1" class="slide level2">
<h2>Example 13-8</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>a.</strong> There are <strong>four</strong> runs: <code>DDD | XX | DD | X</code>. There are five D’s and three X’s, so <span class="math inline">n_1 = 5</span> and <span class="math inline">n_2 = 3</span>.</p>
<p><strong>b.</strong> There are <strong>five</strong> runs: <code>LL | E | L | EEEE | LL</code>. There are five E’s and five L’s, so <span class="math inline">n_1 = 5</span> and <span class="math inline">n_2 = 5</span>.</p>
<p><strong>c.</strong> There are <strong>six</strong> runs: <code>CC | PP | C | PPP | CC | P</code>. There are five C’s and six P’s, so <span class="math inline">n_1 = 5</span> and <span class="math inline">n_2 = 6</span>.</p>
<p>In R, <code>rle()</code> lists the length of every run, and <code>length()</code> counts them.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href=""></a>orders   <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"D"</span>,<span class="st">"D"</span>,<span class="st">"D"</span>,<span class="st">"X"</span>,<span class="st">"X"</span>,<span class="st">"D"</span>,<span class="st">"D"</span>,<span class="st">"X"</span>)</span>
<span id="cb65-2"><a href=""></a>shifts   <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"L"</span>,<span class="st">"L"</span>,<span class="st">"E"</span>,<span class="st">"L"</span>,<span class="st">"E"</span>,<span class="st">"E"</span>,<span class="st">"E"</span>,<span class="st">"E"</span>,<span class="st">"L"</span>,<span class="st">"L"</span>)</span>
<span id="cb65-3"><a href=""></a>payments <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"C"</span>,<span class="st">"C"</span>,<span class="st">"P"</span>,<span class="st">"P"</span>,<span class="st">"C"</span>,<span class="st">"P"</span>,<span class="st">"P"</span>,<span class="st">"P"</span>,<span class="st">"C"</span>,<span class="st">"C"</span>,<span class="st">"P"</span>)</span>
<span id="cb65-4"><a href=""></a></span>
<span id="cb65-5"><a href=""></a><span class="fu">length</span>(<span class="fu">rle</span>(orders)<span class="sc">$</span>lengths)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb67"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href=""></a><span class="fu">length</span>(<span class="fu">rle</span>(shifts)<span class="sc">$</span>lengths)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb69"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href=""></a><span class="fu">length</span>(<span class="fu">rle</span>(payments)<span class="sc">$</span>lengths)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="the-runs-test-for-randomness" class="slide level2">
<h2>The Runs Test for Randomness</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Runs Test for Randomness</strong></p>
</div>
<div class="callout-content">
<p>The <strong>runs test for randomness</strong> is a nonparametric test that is used to determine if a sequence of data values occurs at random.</p>
</div>
</div>
</div>
<p>The test considers the <strong>number of runs</strong> rather than the frequency of the letters: for data to be selected at random, there should be neither <strong>too few</strong> nor <strong>too many</strong> runs. The runs test does not consider how many of each category were selected or how many of each are in a specific run.</p>
<p>When the data are <strong>numerical</strong>, use the <strong>median</strong> to determine the number of runs: find the median, then assign the letter <strong>A</strong> to each value above the median and <strong>B</strong> to each value below the median. <strong>Ignore any data values that are equal to the median.</strong></p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Assumptions for the Runs Test for Randomness</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>The data from the sample are arranged in the <strong>order in which they were selected</strong>.</li>
<li>Each letter, number or event can be classified into <strong>one of two mutually exclusive categories</strong>.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="test-statistic-and-critical-values" class="slide level2">
<h2>Test Statistic and Critical Values</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Formulas for the Test Statistic Value for the Runs Test</strong></p>
</div>
<div class="callout-content">
<p>When <span class="math inline">n_1 \leq 20</span> and <span class="math inline">n_2 \leq 20</span>, use the number of runs, denoted by <span class="math inline">G</span>, as the test statistic value. When <span class="math inline">n_1 &gt; 20</span> or <span class="math inline">n_2 &gt; 20</span>, use</p>
<p><span class="math display">z = \frac{G - \mu_G}{\sigma_G} \qquad \text{where} \qquad \mu_G = \frac{2 n_1 n_2}{n_1 + n_2} + 1, \qquad \sigma_G = \sqrt{\frac{2 n_1 n_2 (2 n_1 n_2 - n_1 - n_2)}{(n_1 + n_2)^2 (n_1 + n_2 - 1)}}</span></p>
</div>
</div>
</div>
<p><strong>Table A-13</strong> gives the critical values when <span class="math inline">n_1 \leq 20</span> and <span class="math inline">n_2 \leq 20</span>; its values are for a <strong>two-tailed test with <span class="math inline">\alpha = 0.05</span></strong>. For a sample of 12 males and 8 females, for example, any number of runs from <strong>7 to 15</strong> would be considered random; 6 or fewer, or 16 or more, means the sample is probably not random and <span class="math inline">H_0</span> should be rejected. The critical values are 6 and 16.</p>
</section>
<section id="procedure-table-the-runs-test" class="slide level2">
<h2>Procedure Table: The Runs Test</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Five Steps</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> State the hypotheses and identify the claim.</p>
<p><strong>Step 2.</strong> Find the critical values. Use <strong>Table A-13</strong> when <span class="math inline">n_1 \leq 20</span> and <span class="math inline">n_2 \leq 20</span>; use <strong>Table A-4</strong> when <span class="math inline">n_1 &gt; 20</span> or <span class="math inline">n_2 &gt; 20</span>.</p>
<p><strong>Step 3.</strong> Find the test statistic. Use the number of runs <span class="math inline">G</span> if <span class="math inline">n_1 \leq 20</span> and <span class="math inline">n_2 \leq 20</span>; otherwise use <span class="math inline">z = \dfrac{G - \mu_G}{\sigma_G}</span>.</p>
<p><strong>Step 4.</strong> Make the decision.</p>
<p><strong>Step 5.</strong> Summarize the results.</p>
</div>
</div>
</div>
</section>
<section id="example-13-9" class="slide level2">
<h2>Example 13-9</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Domestic and Export Orders</strong></p>
</div>
<div class="callout-content">
<p>A coordinator at a trading company wishes to see whether domestic and export orders arrive at random during a shift. She records the first 25 orders of the morning, where D denotes a domestic order and E an export order <em>(hypothetical data)</em>. Test for randomness at <span class="math inline">\alpha = 0.05</span>.</p>
<pre><code>D D D E E D D D D E D E E E D D D D E E D D D E E</code></pre>
</div>
</div>
</div>
</section>
<section id="example-13-9-1" class="slide level2">
<h2>Example 13-9</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> State the hypotheses and identify the claim.</p>
<p><span class="math inline">H_0</span>: The orders arrive at random, according to type <em>(claim)</em>.</p>
<p><span class="math inline">H_1</span>: The orders do not arrive at random, according to type.</p>
<p><strong>Step 2.</strong> Determine the critical values. There are 10 E’s and 15 D’s, so <span class="math inline">n_1 = 10</span> and <span class="math inline">n_2 = 15</span>. Using <strong>Table A-13</strong> and <span class="math inline">\alpha = 0.05</span>, the critical values are <strong>7</strong> and <strong>18</strong>: reject <span class="math inline">H_0</span> if <span class="math inline">G \leq 7</span> or <span class="math inline">G \geq 18</span>.</p>
<p><strong>Step 3.</strong> Find the test statistic by arranging the letters into runs.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Run</th>
<th>1</th>
<th>2</th>
<th>3</th>
<th>4</th>
<th>5</th>
<th>6</th>
<th>7</th>
<th>8</th>
<th>9</th>
<th>10</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Type</td>
<td>DDD</td>
<td>EE</td>
<td>DDDD</td>
<td>E</td>
<td>D</td>
<td>EEE</td>
<td>DDDD</td>
<td>EE</td>
<td>DDD</td>
<td>EE</td>
</tr>
</tbody>
</table>
<p>There are <strong>10 runs</strong>.</p>
</div>
</div>
</div>
</section>
<section id="example-13-9-2" class="slide level2">
<h2>Example 13-9</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 3 in R</strong> — count the runs with <code>rle()</code> as in <a href="#/example-13-8">Example 13-8</a>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb72"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href=""></a>order_types <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"D"</span>,<span class="st">"D"</span>,<span class="st">"D"</span>,<span class="st">"E"</span>,<span class="st">"E"</span>,<span class="st">"D"</span>,<span class="st">"D"</span>,<span class="st">"D"</span>,<span class="st">"D"</span>,<span class="st">"E"</span>,<span class="st">"D"</span>,<span class="st">"E"</span>,<span class="st">"E"</span>,</span>
<span id="cb72-2"><a href=""></a>                 <span class="st">"E"</span>,<span class="st">"D"</span>,<span class="st">"D"</span>,<span class="st">"D"</span>,<span class="st">"D"</span>,<span class="st">"E"</span>,<span class="st">"E"</span>,<span class="st">"D"</span>,<span class="st">"D"</span>,<span class="st">"D"</span>,<span class="st">"E"</span>,<span class="st">"E"</span>)</span>
<span id="cb72-3"><a href=""></a></span>
<span id="cb72-4"><a href=""></a><span class="fu">table</span>(order_types)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>order_types
 D  E 
15 10 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb74"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href=""></a><span class="fu">length</span>(<span class="fu">rle</span>(order_types)<span class="sc">$</span>lengths)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10</code></pre>
</div>
</div>
<p><strong>Step 4.</strong> Make the decision. Since the number of runs is 10, and 10 is neither less than or equal to 7 nor greater than or equal to 18, <strong>do not reject</strong> the null hypothesis.</p>
<p><strong>Step 5.</strong> Summarize the results. There is not enough evidence to reject the hypothesis that the orders arrive at random according to type.</p>
</div>
</div>
</div>
</section>
<section id="example-13-10" class="slide level2">
<h2>Example 13-10</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Cartons Shipped per Day</strong></p>
</div>
<div class="callout-content">
<p>A supervisor records the number of cartons shipped per day at a small e-commerce warehouse for 20 consecutive business days <em>(hypothetical data)</em>. Test the claim that the daily carton counts, in the order the days occurred, occur at random, at <span class="math inline">\alpha = 0.05</span>.</p>
<pre><code>48, 74, 45, 52, 57, 86, 54, 62, 62, 78,
41, 84, 76, 68, 66, 88, 92, 45, 50, 55</code></pre>
</div>
</div>
</div>
</section>
<section id="example-13-10-1" class="slide level2">
<h2>Example 13-10</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> State the hypotheses and identify the claim.</p>
<p><span class="math inline">H_0</span>: The numbers of cartons shipped, in the order the days occurred, occur at random <em>(claim)</em>.</p>
<p><span class="math inline">H_1</span>: The numbers of cartons shipped, in the order the days occurred, do not occur at random.</p>
<p><strong>Step 2.</strong> Find the critical values. Arrange the data in ascending order:</p>
<pre><code>41 45 45 48 50 52 54 55 57 62 62 66 68 74 76 78 84 86 88 92</code></pre>
<p>The median is <strong>62</strong>. Replace each number in the <strong>original</strong> sequence with an <strong>A</strong> if it is above the median and a <strong>B</strong> if it is below; eliminate any number equal to the median. The sequence of letters is</p>
<pre><code>B A B B B A B  A B A A A A A A  B B B</code></pre>
<p>There are 9 A’s and 9 B’s. Table A-13 shows that with <span class="math inline">n_1 = 9</span>, <span class="math inline">n_2 = 9</span> and <span class="math inline">\alpha = 0.05</span>, the number of runs should be <strong>5 or less</strong> or <strong>15 or greater</strong> to reject <span class="math inline">H_0</span>.</p>
</div>
</div>
</div>
</section>
<section id="example-13-10-2" class="slide level2">
<h2>Example 13-10</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 3.</strong> Determine the number of runs from the sequence of letters.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Run</th>
<th>1</th>
<th>2</th>
<th>3</th>
<th>4</th>
<th>5</th>
<th>6</th>
<th>7</th>
<th>8</th>
<th>9</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Letters</td>
<td>B</td>
<td>A</td>
<td>BBB</td>
<td>A</td>
<td>B</td>
<td>A</td>
<td>B</td>
<td>AAAAAA</td>
<td>BBB</td>
</tr>
</tbody>
</table>
<p>The number of runs is <span class="math inline">G = 9</span>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb79"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href=""></a>cartons <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">48</span>, <span class="dv">74</span>, <span class="dv">45</span>, <span class="dv">52</span>, <span class="dv">57</span>, <span class="dv">86</span>, <span class="dv">54</span>, <span class="dv">62</span>, <span class="dv">62</span>, <span class="dv">78</span>,</span>
<span id="cb79-2"><a href=""></a>             <span class="dv">41</span>, <span class="dv">84</span>, <span class="dv">76</span>, <span class="dv">68</span>, <span class="dv">66</span>, <span class="dv">88</span>, <span class="dv">92</span>, <span class="dv">45</span>, <span class="dv">50</span>, <span class="dv">55</span>)</span>
<span id="cb79-3"><a href=""></a></span>
<span id="cb79-4"><a href=""></a><span class="fu">median</span>(cartons)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 62</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb81"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href=""></a>above_below <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(cartons[cartons <span class="sc">!=</span> <span class="dv">62</span>] <span class="sc">&gt;</span> <span class="dv">62</span>, <span class="st">"A"</span>, <span class="st">"B"</span>)</span>
<span id="cb81-2"><a href=""></a>above_below</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "B" "A" "B" "B" "B" "A" "B" "A" "B" "A" "A" "A" "A" "A" "A" "B" "B" "B"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb83"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href=""></a><span class="fu">table</span>(above_below)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>above_below
A B 
9 9 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb85"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href=""></a><span class="fu">length</span>(<span class="fu">rle</span>(above_below)<span class="sc">$</span>lengths)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="example-13-10-3" class="slide level2">
<h2>Example 13-10</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 4.</strong> Make the decision. Since there are 9 runs and 9 falls between the critical values 5 and 15, the null hypothesis is <strong>not rejected</strong>.</p>
<p><strong>Step 5.</strong> Summarize the results. There is not enough evidence to reject the hypothesis that the numbers of cartons shipped occur at random.</p>
</div>
</div>
</div>
</section>
<section id="example-13-11" class="slide level2">
<h2>Example 13-11</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Destination Region of Export Bookings</strong></p>
</div>
<div class="callout-content">
<p>A freight forwarder in Taipei records the destination region of 45 consecutive export bookings, where A denotes Asia and N denotes North America <em>(hypothetical data)</em>. At <span class="math inline">\alpha = 0.05</span>, can it be concluded that the sequence of destinations is random?</p>
<pre><code>A A A A N N N N N A A A A A N A A A N A N A A A
N N A A N A N N N N A N A A A A A N N N N</code></pre>
<p>Here <span class="math inline">n_1</span> (North America) <span class="math inline">= 20</span> and <span class="math inline">n_2</span> (Asia) <span class="math inline">= 25</span>.</p>
</div>
</div>
</div>
</section>
<section id="example-13-11-1" class="slide level2">
<h2>Example 13-11</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> State the hypotheses and identify the claim.</p>
<p><span class="math inline">H_0</span>: The destinations occur at random <em>(claim)</em>; <span class="math inline">H_1</span>: The destinations do not occur at random.</p>
<p><strong>Step 2.</strong> Determine the critical values. Since <span class="math inline">n_1 &gt; 20</span> or <span class="math inline">n_2 &gt; 20</span>, <strong>Table A-4</strong> is used. At <span class="math inline">\alpha = 0.05</span> the critical values are <span class="math inline">\pm 1.96</span>.</p>
<p><strong>Step 3.</strong> Find the test statistic. Counting the runs gives <span class="math inline">G = 18</span>.</p>
<p><span class="math display">\mu_G = \frac{2 n_1 n_2}{n_1 + n_2} + 1 = \frac{2(20)(25)}{20 + 25} + 1 = 23.222</span></p>
<p><span class="math display">\sigma_G = \sqrt{\frac{2(20)(25)\left[2(20)(25) - 20 - 25\right]}{(20+25)^2(20+25-1)}} = \sqrt{\frac{955{,}000}{89{,}100}} = \sqrt{10.718} = 3.274</span></p>
<p><span class="math display">z = \frac{G - \mu_G}{\sigma_G} = \frac{18 - 23.222}{3.274} = -1.595</span></p>
</div>
</div>
</div>
</section>
<section id="example-13-11-2" class="slide level2">
<h2>Example 13-11</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 3 in R</strong> — <code>rle()</code> counts the runs again, and no value is rounded before the division.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb88"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href=""></a>destinations <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"A"</span>,<span class="st">"A"</span>,<span class="st">"A"</span>,<span class="st">"A"</span>,<span class="st">"N"</span>,<span class="st">"N"</span>,<span class="st">"N"</span>,<span class="st">"N"</span>,<span class="st">"N"</span>,<span class="st">"A"</span>,<span class="st">"A"</span>,<span class="st">"A"</span>,<span class="st">"A"</span>,<span class="st">"A"</span>,<span class="st">"N"</span>,</span>
<span id="cb88-2"><a href=""></a>                  <span class="st">"A"</span>,<span class="st">"A"</span>,<span class="st">"A"</span>,<span class="st">"N"</span>,<span class="st">"A"</span>,<span class="st">"N"</span>,<span class="st">"A"</span>,<span class="st">"A"</span>,<span class="st">"A"</span>,<span class="st">"N"</span>,<span class="st">"N"</span>,<span class="st">"A"</span>,<span class="st">"A"</span>,<span class="st">"N"</span>,<span class="st">"A"</span>,</span>
<span id="cb88-3"><a href=""></a>                  <span class="st">"N"</span>,<span class="st">"N"</span>,<span class="st">"N"</span>,<span class="st">"N"</span>,<span class="st">"A"</span>,<span class="st">"N"</span>,<span class="st">"A"</span>,<span class="st">"A"</span>,<span class="st">"A"</span>,<span class="st">"A"</span>,<span class="st">"A"</span>,<span class="st">"N"</span>,<span class="st">"N"</span>,<span class="st">"N"</span>,<span class="st">"N"</span>)</span>
<span id="cb88-4"><a href=""></a>mu_G    <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> <span class="dv">20</span> <span class="sc">*</span> <span class="dv">25</span> <span class="sc">/</span> (<span class="dv">20</span> <span class="sc">+</span> <span class="dv">25</span>) <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb88-5"><a href=""></a>sigma_G <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="dv">2</span> <span class="sc">*</span> <span class="dv">20</span> <span class="sc">*</span> <span class="dv">25</span> <span class="sc">*</span> (<span class="dv">2</span> <span class="sc">*</span> <span class="dv">20</span> <span class="sc">*</span> <span class="dv">25</span> <span class="sc">-</span> <span class="dv">20</span> <span class="sc">-</span> <span class="dv">25</span>) <span class="sc">/</span></span>
<span id="cb88-6"><a href=""></a>                ((<span class="dv">20</span> <span class="sc">+</span> <span class="dv">25</span>)<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> (<span class="dv">20</span> <span class="sc">+</span> <span class="dv">25</span> <span class="sc">-</span> <span class="dv">1</span>)))</span>
<span id="cb88-7"><a href=""></a></span>
<span id="cb88-8"><a href=""></a><span class="fu">table</span>(destinations)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>destinations
 A  N 
25 20 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb90"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href=""></a><span class="fu">length</span>(<span class="fu">rle</span>(destinations)<span class="sc">$</span>lengths)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 18</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb92"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href=""></a>mu_G</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 23.22222</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb94"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href=""></a>sigma_G</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.273881</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb96"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href=""></a>(<span class="dv">18</span> <span class="sc">-</span> mu_G) <span class="sc">/</span> sigma_G</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1.595117</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="example-13-11-3" class="slide level2">
<h2>Example 13-11</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 4.</strong> Make the decision. Since <span class="math inline">-1.96 &lt; -1.595</span>, the decision is to <strong>not reject</strong> the null hypothesis.</p>
<p><strong>Step 5.</strong> Summarize the results. There is not enough evidence to reject the claim that the sequence of destinations occurs at random.</p>
</div>
</div>
</div>
</section>
<section id="nonparametric-tests-and-their-parametric-counterparts" class="slide level2">
<h2>Nonparametric Tests and Their Parametric Counterparts</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Summary of the Chapter’s Tests</strong></p>
</div>
<div class="callout-content">
<table class="caption-top">
<colgroup>
<col style="width: 41%">
<col style="width: 35%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th>Nonparametric test</th>
<th>Parametric test</th>
<th>Condition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Single-sample sign test (13-2)</td>
<td><span class="math inline">z</span> or <span class="math inline">t</span> test</td>
<td>One sample</td>
</tr>
<tr class="even">
<td>Paired-sample sign test (13-2)</td>
<td><span class="math inline">z</span> or <span class="math inline">t</span> test</td>
<td>Two dependent samples</td>
</tr>
<tr class="odd">
<td>Wilcoxon rank sum test (13-3)</td>
<td><span class="math inline">z</span> or <span class="math inline">t</span> test</td>
<td>Two independent samples</td>
</tr>
<tr class="even">
<td>Wilcoxon signed-rank test (13-4)</td>
<td><span class="math inline">t</span> test</td>
<td>Two dependent samples</td>
</tr>
<tr class="odd">
<td>Kruskal-Wallis test (13-5)</td>
<td>ANOVA</td>
<td>Three or more independent samples</td>
</tr>
<tr class="even">
<td>Spearman rank correlation coefficient (13-6)</td>
<td>Pearson’s correlation coefficient</td>
<td>Relationships between variables</td>
</tr>
<tr class="odd">
<td>Runs test (13-6)</td>
<td>None</td>
<td>Randomness</td>
</tr>
</tbody>
</table>
<p>When the assumptions of the parametric tests <strong>can</strong> be met, the parametric tests should be used instead of their nonparametric counterparts.</p>
</div>
</div>
</div>
</section>
<section id="important-terms" class="slide level2">
<h2>Important Terms</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Chapter 13 Vocabulary</strong></p>
</div>
<div class="callout-content">
<p>distribution-free statistics · Kruskal-Wallis test · nonparametric statistics · paired-sample sign test · parametric tests · ranking · run · runs test for randomness · sign test · Spearman rank correlation coefficient · Wilcoxon rank sum test · Wilcoxon signed-rank test</p>
</div>
</div>
</div>
</section>
<section id="key-formulas" class="slide level2">
<h2>Key Formulas</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important Formulas</strong></p>
</div>
<div class="callout-content">
<p>Formula for the <span class="math inline">z</span> test statistic in the <strong>sign test</strong>, where <span class="math inline">n</span> is the sample size (greater than 25) and <span class="math inline">X</span> is the smaller number of positive or negative signs:</p>
<p><span class="math display">z = \frac{(X + 0.5) - 0.5n}{\sqrt{n}/2}</span></p>
<p>Formula for the <strong>Wilcoxon rank sum test</strong>, where <span class="math inline">R</span> is the sum of the ranks for the smaller sample size <span class="math inline">n_1</span>, and <span class="math inline">n_1 \geq 10</span>, <span class="math inline">n_2 \geq 10</span>:</p>
<p><span class="math display">z = \frac{R - \mu_R}{\sigma_R}, \qquad \mu_R = \frac{n_1(n_1 + n_2 + 1)}{2}, \qquad \sigma_R = \sqrt{\frac{n_1 n_2 (n_1 + n_2 + 1)}{12}}</span></p>
<p>Formula for the <strong>Wilcoxon signed-rank test</strong>, where <span class="math inline">n</span> is the number of pairs whose difference is not 0 (<span class="math inline">n \geq 30</span>) and <span class="math inline">w_s</span> is the smaller sum in absolute value of the signed ranks:</p>
<p><span class="math display">z = \frac{w_s - \dfrac{n(n+1)}{4}}{\sqrt{\dfrac{n(n+1)(2n+1)}{24}}}</span></p>
</div>
</div>
</div>
</section>
<section id="key-formulas-1" class="slide level2">
<h2>Key Formulas</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important Formulas</strong></p>
</div>
<div class="callout-content">
<p>Formula for the <strong>Kruskal-Wallis test</strong>, where <span class="math inline">R_i</span> is the sum of ranks of sample <span class="math inline">i</span>, <span class="math inline">n_i</span> is the size of sample <span class="math inline">i</span>, <span class="math inline">N = n_1 + n_2 + \cdots + n_k</span> and <span class="math inline">k</span> is the number of samples:</p>
<p><span class="math display">H = \frac{12}{N(N+1)}\left(\frac{R_1^2}{n_1} + \frac{R_2^2}{n_2} + \cdots + \frac{R_k^2}{n_k}\right) - 3(N+1)</span></p>
<p>Formula for the <strong>Spearman rank correlation coefficient</strong>, where <span class="math inline">d</span> is the difference in ranks and <span class="math inline">n</span> is the number of data pairs:</p>
<p><span class="math display">r_s = 1 - \frac{6 \sum d^2}{n(n^2 - 1)}</span></p>
<p>Formulas for the test statistic value for the <strong>runs test</strong>. When <span class="math inline">n_1 \leq 20</span> and <span class="math inline">n_2 \leq 20</span>, use the number of runs <span class="math inline">G</span>; when <span class="math inline">n_1 &gt; 20</span> or <span class="math inline">n_2 &gt; 20</span>, use</p>
<p><span class="math display">z = \frac{G - \mu_G}{\sigma_G}, \qquad \mu_G = \frac{2 n_1 n_2}{n_1 + n_2} + 1, \qquad \sigma_G = \sqrt{\frac{2 n_1 n_2 (2 n_1 n_2 - n_1 - n_2)}{(n_1 + n_2)^2 (n_1 + n_2 - 1)}}</span></p>
</div>
</div>
</div>
</section>
<section id="key-takeaways" class="slide level2">
<h2>Key Takeaways</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Key point</strong></p>
</div>
<div class="callout-content">
<ul>
<li><strong>Parametric tests</strong> (<span class="math inline">z</span>, <span class="math inline">t</span>, <span class="math inline">F</span>) are tests for population parameters that assume the populations are normally distributed; <strong>nonparametric</strong> or <strong>distribution-free</strong> methods are used when that assumption cannot be met</li>
<li>Nonparametric methods have <strong>six advantages</strong> — no normality needed, nominal or ordinal data, hypotheses without parameters, easier computation, easy to understand, fewer and simpler assumptions — and <strong>three disadvantages</strong>: less sensitive, less information used, less efficient (the sign test is about 60% as efficient as the <span class="math inline">z</span> test)</li>
<li><strong>Ties are ranked by the average of the ranks</strong> the tied values would have occupied</li>
<li>The <strong>sign test</strong> tests a <strong>median</strong>: the test statistic is the smaller number of plus or minus signs when <span class="math inline">n \leq 25</span> (Table A-10), and <span class="math inline">z = \dfrac{(X+0.5) - 0.5n}{\sqrt{n}/2}</span> when <span class="math inline">n &gt; 25</span> (Table A-4); zeros are discarded</li>
<li>The <strong>paired-sample sign test</strong> uses the signs of <span class="math inline">X_B - X_A</span> to compare two <strong>dependent</strong> samples</li>
<li>The <strong>Wilcoxon rank sum test</strong> compares two <strong>independent</strong> samples with <span class="math inline">n_1 \geq 10</span> and <span class="math inline">n_2 \geq 10</span>, using <span class="math inline">R</span>, <span class="math inline">\mu_R</span>, <span class="math inline">\sigma_R</span> and Table A-4</li>
</ul>
</div>
</div>
</div>
</section>
<section id="key-takeaways-1" class="slide level2">
<h2>Key Takeaways</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Key point</strong></p>
</div>
<div class="callout-content">
<ul>
<li>The <strong>Wilcoxon signed-rank test</strong> compares two <strong>dependent</strong> samples; <span class="math inline">w_s</span> is the smaller absolute rank sum, compared with Table A-11 when <span class="math inline">n \leq 30</span>, and <span class="math inline">H_0</span> is rejected when <span class="math inline">w_s \leq</span> the critical value</li>
<li>The <strong>Kruskal-Wallis <span class="math inline">H</span> test</strong> compares three or more independent samples of size at least 5; it is always <strong>right-tailed</strong> with <span class="math inline">\text{d.f.} = k - 1</span></li>
<li>The <strong>Spearman rank correlation coefficient</strong> <span class="math inline">r_s</span> ranges from <span class="math inline">-1</span> to <span class="math inline">+1</span> and is tested against Table A-12 for <span class="math inline">n \leq 30</span></li>
<li>The <strong>runs test</strong> tests <strong>randomness</strong>: too few or too many runs both lead to rejecting <span class="math inline">H_0</span>; use <span class="math inline">G</span> with Table A-13 when <span class="math inline">n_1 \leq 20</span> and <span class="math inline">n_2 \leq 20</span>, and the <span class="math inline">z</span> formula with Table A-4 otherwise</li>
<li>When the parametric assumptions <strong>can</strong> be met, the parametric test is preferred</li>
</ul>
</div>
</div>
</div>
</section>
<section id="acknowledgement" class="slide level2">
<h2>Acknowledgement</h2>
<ul>
<li><p><strong>Copyright notice.</strong> These teaching materials follow the organization and terminology of <strong>Bluman, A. G. (2023). Elementary statistics: A step by step approach (11th ed.). McGraw Hill</strong>. All rights in the original work are reserved by its authors and publishers.</p></li>
<li><p><strong>Original examples.</strong> Every worked example, data set, and R script in these slides was written for this course. The data are hypothetical unless stated otherwise.</p></li>
<li><p><strong>Non-commercial use only.</strong> These materials are strictly intended for educational purposes and must not be used for commercial gain or profit.</p></li>
<li><p><strong>Proper attribution.</strong> Any reproduction, distribution, or use of these materials must provide proper attribution to the original source.</p></li>
</ul>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="logo.svg" class="slide-logo"></p>
<div class="footer footer-default">
<p>Elementary Statistics: A Step by Step Approach</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="ch13_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="ch13_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="ch13_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="ch13_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="ch13_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="ch13_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="ch13_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="ch13_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="ch13_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":false,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true,"hideMissingTitles":true,"titleSelector":"h1"},
'smaller': true,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    <script>
    Reveal.on('ready', function() {
      var title = Reveal.getSlides()[0];
      if (title) {
        title.insertAdjacentHTML('beforeend',
          '<p style="font-size:0.5em; margin-top:1.5em;">' +
          '<a href="ch13-zh.html"  style="color:#555;">[中文版由此去]</a>' +
          '</p>');
      }
    });
    </script>
    

</body></html>