<!DOCTYPE html>
<html lang="en"><head>
<script src="ch2_files/libs/clipboard/clipboard.min.js"></script>
<script src="ch2_files/libs/quarto-html/tabby.min.js"></script>
<script src="ch2_files/libs/quarto-html/popper.min.js"></script>
<script src="ch2_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="ch2_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="ch2_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="ch2_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.38">

  <meta name="author" content="Yu-You Liou">
  <meta name="dcterms.date" content="2026-10-08">
  <title>Statistics</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="ch2_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="ch2_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="ch2_files/libs/revealjs/dist/theme/quarto-2abc1c5b7b5c7eecd6137558e106e4c3.css">
  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">
  <link href="ch2_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="ch2_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="ch2_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="ch2_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-notes="" class="quarto-title-block center">
  <h1 class="title">Statistics</h1>
  <p class="subtitle">Chapter 2: Frequency Distributions and Graphs</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Yu-You Liou 
</div>
        <p class="quarto-title-affiliation">
            Shih Chien University
          </p>
    </div>
</div>

  <p class="date">2026-10-08</p>
</section>
<section id="overview" class="slide level2">
<h2>Overview</h2>
<p>Chapter 2 shows how to <strong>organize data into frequency distributions</strong> and how to <strong>present data with charts and graphs</strong>, so that patterns which are invisible in raw data become easy to see.</p>
<table class="caption-top">
<colgroup>
<col style="width: 52%">
<col style="width: 47%">
</colgroup>
<thead>
<tr class="header">
<th>Section</th>
<th>Topics</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2-1</td>
<td>Organizing data: categorical, grouped, and ungrouped frequency distributions; cumulative frequencies</td>
</tr>
<tr class="even">
<td>2-2</td>
<td>Histograms, frequency polygons, and ogives; relative frequency graphs; distribution shapes</td>
</tr>
<tr class="odd">
<td>2-3</td>
<td>Other types of graphs: bar graphs, Pareto charts, time series graphs, pie graphs, dotplots, stem and leaf plots; misleading graphs</td>
</tr>
</tbody>
</table>
</section>
<section id="chapter-objectives" class="slide level2">
<h2>Chapter Objectives</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>After completing this chapter, you should be able to</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>Organize data using a frequency distribution.</li>
<li>Represent data in frequency distributions graphically, using histograms, frequency polygons, and ogives.</li>
<li>Represent data using bar graphs, Pareto charts, time series graphs, pie graphs, and dotplots.</li>
<li>Draw and interpret a stem and leaf plot.</li>
</ol>
</div>
</div>
</div>
</section>
<section>
<section id="section-2-1-organizing-data" class="title-slide slide level1 center" data-background-color="#2c4a6e">
<h1>Section 2-1: Organizing Data</h1>

</section>
<section id="raw-data" class="slide level2">
<h2>Raw Data</h2>
<p>When a researcher first gathers data for a variable, the values are in their original, unprocessed form.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Raw Data</strong></p>
</div>
<div class="callout-content">
<p>When data are collected in <strong>original form</strong>, they are called <strong>raw data</strong>.</p>
</div>
</div>
</div>
<p>Suppose a researcher studies the ages of the 50 wealthiest people in the world. Little information can be obtained from looking at the raw list below, so the researcher organizes it into a <strong>frequency distribution</strong>.</p>
<pre><code>45  46  64  57  85      88  45  89  67  56
92  51  71  54  48      81  58  55  62  38
27  66  76  55  69      55  56  64  81  38
54  44  54  75  46      49  68  91  56  68
61  68  78  61  83      46  47  83  71  62</code></pre>
</section>
<section id="frequency-distributions" class="slide level2">
<h2>Frequency Distributions</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Frequency Distribution</strong></p>
</div>
<div class="callout-content">
<p>A <strong>frequency distribution</strong> is the organization of raw data in <strong>table form</strong>, using <strong>classes</strong> and <strong>frequencies</strong>.</p>
<ul>
<li>Each raw data value is placed into a quantitative or qualitative category called a <strong>class</strong>.</li>
<li>The <strong>frequency</strong> of a class is the number of data values contained in that class.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="ages-of-the-50-wealthiest-people" class="slide level2">
<h2>Ages of the 50 Wealthiest People</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Class limits</th>
<th>Frequency</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>27–35</td>
<td>1</td>
</tr>
<tr class="even">
<td>36–44</td>
<td>3</td>
</tr>
<tr class="odd">
<td>45–53</td>
<td>9</td>
</tr>
<tr class="even">
<td>54–62</td>
<td>15</td>
</tr>
<tr class="odd">
<td>63–71</td>
<td>10</td>
</tr>
<tr class="even">
<td>72–80</td>
<td>3</td>
</tr>
<tr class="odd">
<td>81–89</td>
<td>7</td>
</tr>
<tr class="even">
<td>90–98</td>
<td>2</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td><strong>50</strong></td>
</tr>
</tbody>
</table>
<p>Now a general observation can be made: the <strong>majority of the wealthy people in the study are 45 years old or older</strong>. The values 27, 35, 36, 44, … are called <strong>class limits</strong>.</p>
</section>
<section id="three-types-of-frequency-distributions" class="slide level2">
<h2>Three Types of Frequency Distributions</h2>
<table class="caption-top">
<colgroup>
<col style="width: 35%">
<col style="width: 64%">
</colgroup>
<thead>
<tr class="header">
<th>Type</th>
<th>Used when</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Categorical</strong></td>
<td>The data can be placed in specific categories — nominal- or ordinal-level data such as political affiliation, religious affiliation, or major field of study</td>
</tr>
<tr class="even">
<td><strong>Grouped</strong></td>
<td>The range of the data is large, so classes more than one unit wide are needed</td>
</tr>
<tr class="odd">
<td><strong>Ungrouped</strong></td>
<td>The range of the data is small, so each class is a single data value</td>
</tr>
</tbody>
</table>
</section>
<section id="categorical-frequency-distributions" class="slide level2">
<h2>Categorical Frequency Distributions</h2>
<p>The <strong>categorical frequency distribution</strong> is used for data that can be placed in specific categories.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Percentage and Relative Frequency</strong></p>
</div>
<div class="callout-content">
<p>Find the percentage of values in each class with</p>
<p><span class="math display">\% = \frac{f}{n} \cdot 100</span></p>
<p>where <span class="math inline">f</span> is the frequency of the class and <span class="math inline">n</span> is the total number of values. Percentages are not normally part of a frequency distribution, but they can be added since they are used in graphs such as pie graphs. The <strong>decimal equivalent of a percent is called a relative frequency</strong>.</p>
</div>
</div>
</div>
</section>
<section id="example-2-1" class="slide level2">
<h2>Example 2-1</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Payment Methods at a Convenience Store</strong></p>
</div>
<div class="callout-content">
<p>Forty customers at a campus convenience store were asked how they paid for their purchase. Construct a categorical frequency distribution for the data and summarize the results. Use these classes: C = cash, E = stored-value card, M = mobile payment, D = credit card, and G = gift voucher. <em>(hypothetical data)</em></p>
<pre><code>C  E  M  C  D  E  G  C  E  M
C  D  C  E  M  E  C  G  M  D
E  C  M  D  C  E  M  C  D  E
M  C  G  D  E  C  M  C  C  D</code></pre>
<p>Back to <a href="#/example-2-11">Example 2-11</a></p>
</div>
</div>
</div>
</section>
<section id="example-2-1-1" class="slide level2">
<h2>Example 2-1</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Solve</strong></p>
<p>Since the data are categorical, discrete classes are used: C, E, M, D, and G. Tally the data, count the tallies, and compute <span class="math inline">\% = \frac{f}{n}\cdot 100</span>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href=""></a>payments <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"C"</span>,<span class="st">"E"</span>,<span class="st">"M"</span>,<span class="st">"C"</span>,<span class="st">"D"</span>,<span class="st">"E"</span>,<span class="st">"G"</span>,<span class="st">"C"</span>,<span class="st">"E"</span>,<span class="st">"M"</span>,</span>
<span id="cb3-2"><a href=""></a>              <span class="st">"C"</span>,<span class="st">"D"</span>,<span class="st">"C"</span>,<span class="st">"E"</span>,<span class="st">"M"</span>,<span class="st">"E"</span>,<span class="st">"C"</span>,<span class="st">"G"</span>,<span class="st">"M"</span>,<span class="st">"D"</span>,</span>
<span id="cb3-3"><a href=""></a>              <span class="st">"E"</span>,<span class="st">"C"</span>,<span class="st">"M"</span>,<span class="st">"D"</span>,<span class="st">"C"</span>,<span class="st">"E"</span>,<span class="st">"M"</span>,<span class="st">"C"</span>,<span class="st">"D"</span>,<span class="st">"E"</span>,</span>
<span id="cb3-4"><a href=""></a>              <span class="st">"M"</span>,<span class="st">"C"</span>,<span class="st">"G"</span>,<span class="st">"D"</span>,<span class="st">"E"</span>,<span class="st">"C"</span>,<span class="st">"M"</span>,<span class="st">"C"</span>,<span class="st">"C"</span>,<span class="st">"D"</span>)</span>
<span id="cb3-5"><a href=""></a></span>
<span id="cb3-6"><a href=""></a><span class="fu">table</span>(payments)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>payments
 C  D  E  G  M 
13  7  9  3  8 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href=""></a><span class="fu">table</span>(payments) <span class="sc">/</span> <span class="dv">40</span> <span class="sc">*</span> <span class="dv">100</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>payments
   C    D    E    G    M 
32.5 17.5 22.5  7.5 20.0 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="example-2-1-2" class="slide level2">
<h2>Example 2-1</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Interpretation</strong></p>
<p>For the sample, <strong>most customers paid in cash</strong> (13 people, 32.5%) and the <strong>smallest number used a gift voucher</strong> (3 people, 7.5%). The stored-value card was used by 9 (22.5%), mobile payment by 8 (20%), and a credit card by 7 (17.5%). It is a good idea to add the Percent column to check that it sums to 100% — although it will not always do so because of rounding.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href=""></a><span class="fu">ggplot</span>(<span class="fu">data.frame</span>(payments), <span class="fu">aes</span>(payments)) <span class="sc">+</span></span>
<span id="cb7-2"><a href=""></a>  <span class="fu">geom_bar</span>() <span class="sc">+</span></span>
<span id="cb7-3"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Payment Methods of 40 Customers"</span>,</span>
<span id="cb7-4"><a href=""></a>       <span class="at">x =</span> <span class="st">"Payment method"</span>, <span class="at">y =</span> <span class="st">"Frequency"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="ch2_files/figure-revealjs/e2-1-2-1.png" class="quarto-figure quarto-figure-center" style="width:48.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="grouped-frequency-distributions" class="slide level2">
<h2>Grouped Frequency Distributions</h2>
<p>When the range of the data is large, the data must be grouped into classes that are <strong>more than one unit in width</strong>. The result is a <strong>grouped frequency distribution</strong>.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Class limits</th>
<th>Class boundaries</th>
<th>Frequency</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>58–64</td>
<td>57.5–64.5</td>
<td>1</td>
</tr>
<tr class="even">
<td>65–71</td>
<td>64.5–71.5</td>
<td>6</td>
</tr>
<tr class="odd">
<td>72–78</td>
<td>71.5–78.5</td>
<td>10</td>
</tr>
<tr class="even">
<td>79–85</td>
<td>78.5–85.5</td>
<td>14</td>
</tr>
<tr class="odd">
<td>86–92</td>
<td>85.5–92.5</td>
<td>12</td>
</tr>
<tr class="even">
<td>93–99</td>
<td>92.5–99.5</td>
<td>5</td>
</tr>
<tr class="odd">
<td>100–106</td>
<td>99.5–106.5</td>
<td>2</td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td></td>
<td><strong>50</strong></td>
</tr>
</tbody>
</table>
<p>Blood glucose levels (mg/dL) for 50 randomly selected college students.</p>
</section>
<section id="class-limits-and-class-boundaries" class="slide level2">
<h2>Class Limits and Class Boundaries</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Limits and Boundaries</strong></p>
</div>
<div class="callout-content">
<ul>
<li>The <strong>lower class limit</strong> is the smallest data value that can be included in the class; the <strong>upper class limit</strong> is the largest data value that can be included in the class.</li>
<li><strong>Class boundaries</strong> separate the classes so that there are <strong>no gaps</strong> in the frequency distribution.</li>
</ul>
</div>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Rule of Thumb for Boundaries</strong></p>
</div>
<div class="callout-content">
<p>The <strong>class limits</strong> should have the <strong>same decimal place value as the data</strong>, but the <strong>class boundaries</strong> should have <strong>one additional place value</strong> and <strong>end in a 5</strong>.</p>
<p><span class="math display">\text{Lower limit} - 0.5 = 58 - 0.5 = 57.5 \qquad \text{Upper limit} + 0.5 = 64 + 0.5 = 64.5</span></p>
<p>If the data are in tenths, limits of 7.8–8.8 give boundaries of 7.75–8.85 (subtract and add 0.05).</p>
</div>
</div>
</div>
</section>
<section id="class-width-and-class-midpoint" class="slide level2">
<h2>Class Width and Class Midpoint</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Width and Midpoint</strong></p>
</div>
<div class="callout-content">
<p>The <strong>class width</strong> is found by subtracting the <strong>lower (or upper) class limit of one class from the lower (or upper) class limit of the next class</strong>: <span class="math inline">65 - 58 = 7</span>. Equivalently, subtract the lower boundary from the upper boundary of a class: <span class="math inline">64.5 - 57.5 = 7</span>.</p>
<p>The <strong>class midpoint</strong> <span class="math inline">X_m</span> is</p>
<p><span class="math display">X_m = \frac{\text{lower boundary} + \text{upper boundary}}{2} \quad\text{or}\quad X_m = \frac{\text{lower limit} + \text{upper limit}}{2}</span></p>
<p>For the first glucose class, <span class="math inline">X_m = \dfrac{57.5 + 64.5}{2} = 61</span> or <span class="math inline">\dfrac{58 + 64}{2} = 61</span>.</p>
</div>
</div>
</div>
</section>
<section id="class-width-and-class-midpoint-1" class="slide level2">
<h2>Class Width and Class Midpoint</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Caution</strong></p>
</div>
<div class="callout-content">
<p><strong>Do not subtract the limits of a single class.</strong> It will result in an incorrect answer — <span class="math inline">64 - 58 = 6</span>, not the true width of 7.</p>
<p>If the class width is an even number, the midpoint is in tenths: with boundaries 5.5 and 11.5, <span class="math inline">X_m = \dfrac{5.5 + 11.5}{2} = 8.5</span>.</p>
</div>
</div>
</div>
</section>
<section id="rules-for-constructing-a-grouped-frequency-distribution" class="slide level2">
<h2>Rules for Constructing a Grouped Frequency Distribution</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Six Rules</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>There should be between <strong>5 and 20 classes</strong> — enough to present a clear description of the collected data.</li>
<li>It is <strong>preferable but not absolutely necessary</strong> that the class width be an <strong>odd number</strong>, so the midpoint has the same place value as the data. This rule is not rigorously followed, especially when a computer is used.</li>
<li>The classes must be <strong>mutually exclusive</strong> — nonoverlapping class limits, so data cannot be placed into two classes. Classes such as 10–20, 20–30, 30–40 are poor: where does a 40-year-old go? Use 10–20, 21–31, 32–42 instead.</li>
<li>The classes must be <strong>continuous</strong> — even if a class has no values, it must be included. The only exception is a zero-frequency class at the very beginning or end.</li>
<li>The classes must be <strong>exhaustive</strong> — there must be enough classes to accommodate all the data.</li>
<li>The classes must be <strong>equal in width</strong>, which avoids a distorted view of the data. The exception is an <strong>open-ended</strong> class.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="open-ended-distributions" class="slide level2">
<h2>Open-Ended Distributions</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Open-Ended Distribution</strong></p>
</div>
<div class="callout-content">
<p>A frequency distribution in which the <strong>first class has no specific lower limit</strong>, or the <strong>last class has no specific upper limit</strong>, is called an <strong>open-ended distribution</strong>.</p>
</div>
</div>
</div>
<table class="caption-top">
<thead>
<tr class="header">
<th>Age</th>
<th>Frequency</th>
<th></th>
<th>Minutes</th>
<th>Frequency</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>10–20</td>
<td>3</td>
<td></td>
<td>Below 110</td>
<td>16</td>
</tr>
<tr class="even">
<td>21–31</td>
<td>6</td>
<td></td>
<td>110–114</td>
<td>24</td>
</tr>
<tr class="odd">
<td>32–42</td>
<td>4</td>
<td></td>
<td>115–119</td>
<td>38</td>
</tr>
<tr class="even">
<td>43–53</td>
<td>10</td>
<td></td>
<td>120–124</td>
<td>14</td>
</tr>
<tr class="odd">
<td>54 and above</td>
<td>8</td>
<td></td>
<td>125–129</td>
<td>5</td>
</tr>
</tbody>
</table>
<p>Anybody 54 years or older is tallied in the last age class; any minute value below 110 is tallied in the first minutes class.</p>
</section>
<section id="procedure-table" class="slide level2">
<h2>Procedure Table</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Constructing a Grouped Frequency Distribution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1 — Determine the classes.</strong></p>
<ul>
<li>Find the highest and lowest values.</li>
<li>Find the range, <span class="math inline">R = H - L</span>.</li>
<li>Select the number of classes desired.</li>
<li>Find the width by dividing the range by the number of classes and <strong>rounding up</strong>.</li>
<li>Select a starting point (usually the lowest value or a convenient number less than it); add the width to get the lower limits.</li>
<li>Find the upper class limits.</li>
<li>Find the boundaries.</li>
</ul>
<p><strong>Step 2 — Tally the data.</strong></p>
<p><strong>Step 3 — Find the numerical frequencies from the tallies, and find the cumulative frequencies.</strong></p>
</div>
</div>
</div>
</section>
<section id="example-2-2" class="slide level2">
<h2>Example 2-2</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Delivery Times for Online Food Orders</strong></p>
</div>
<div class="callout-content">
<p>These data represent the delivery times, in minutes, for 50 orders handled by a food-delivery platform on one weekday evening. Construct a grouped frequency distribution for the data, using 7 classes. <em>(hypothetical data)</em></p>
<pre><code>31  27  35  29  22  40  30  26  33  28
25  32  37  30  43  29  36  31  27  34
38  30  28  45  32  26  35  24  31  29
18  34  41  32  27  52  30  36  25  39
23  37  21  33  42  32  47  40  35  37</code></pre>
<p>Back to <a href="#/example-2-4">Example 2-4</a> · <a href="#/example-2-5">Example 2-5</a> · <a href="#/example-2-6">Example 2-6</a></p>
</div>
</div>
</div>
</section>
<section id="example-2-2-1" class="slide level2">
<h2>Example 2-2</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1 — Determine the classes</strong></p>
<p><span class="math inline">H = 52</span> and <span class="math inline">L = 18</span>, so <span class="math inline">R = 52 - 18 = 34</span>. With 7 classes, the width is <span class="math inline">\frac{34}{7} \approx 4.9</span>, rounded <strong>up</strong> to 5. Starting at 18 gives lower limits 18, 23, 28, …; <span class="math inline">23 - 1 = 22</span> gives the first upper limit, so the classes are 18–22, 23–27, etc. Boundaries are 17.5–22.5, 22.5–27.5, and so on.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href=""></a>delivery_times <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">31</span>,<span class="dv">27</span>,<span class="dv">35</span>,<span class="dv">29</span>,<span class="dv">22</span>,<span class="dv">40</span>,<span class="dv">30</span>,<span class="dv">26</span>,<span class="dv">33</span>,<span class="dv">28</span>,</span>
<span id="cb9-2"><a href=""></a>                    <span class="dv">25</span>,<span class="dv">32</span>,<span class="dv">37</span>,<span class="dv">30</span>,<span class="dv">43</span>,<span class="dv">29</span>,<span class="dv">36</span>,<span class="dv">31</span>,<span class="dv">27</span>,<span class="dv">34</span>,</span>
<span id="cb9-3"><a href=""></a>                    <span class="dv">38</span>,<span class="dv">30</span>,<span class="dv">28</span>,<span class="dv">45</span>,<span class="dv">32</span>,<span class="dv">26</span>,<span class="dv">35</span>,<span class="dv">24</span>,<span class="dv">31</span>,<span class="dv">29</span>,</span>
<span id="cb9-4"><a href=""></a>                    <span class="dv">18</span>,<span class="dv">34</span>,<span class="dv">41</span>,<span class="dv">32</span>,<span class="dv">27</span>,<span class="dv">52</span>,<span class="dv">30</span>,<span class="dv">36</span>,<span class="dv">25</span>,<span class="dv">39</span>,</span>
<span id="cb9-5"><a href=""></a>                    <span class="dv">23</span>,<span class="dv">37</span>,<span class="dv">21</span>,<span class="dv">33</span>,<span class="dv">42</span>,<span class="dv">32</span>,<span class="dv">47</span>,<span class="dv">40</span>,<span class="dv">35</span>,<span class="dv">37</span>)</span>
<span id="cb9-6"><a href=""></a></span>
<span id="cb9-7"><a href=""></a><span class="fu">max</span>(delivery_times)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 52</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href=""></a><span class="fu">min</span>(delivery_times)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 18</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href=""></a>(<span class="fu">max</span>(delivery_times) <span class="sc">-</span> <span class="fu">min</span>(delivery_times)) <span class="sc">/</span> <span class="dv">7</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.857143</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="example-2-2-2" class="slide level2">
<h2>Example 2-2</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Steps 2 and 3 — Tally the data and find the frequencies</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href=""></a>class_breaks  <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fl">17.5</span>, <span class="fl">52.5</span>, <span class="at">by =</span> <span class="dv">5</span>)</span>
<span id="cb15-2"><a href=""></a>delivery_freq <span class="ot">&lt;-</span> <span class="fu">table</span>(<span class="fu">cut</span>(delivery_times, class_breaks))</span>
<span id="cb15-3"><a href=""></a>delivery_freq</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
(17.5,22.5] (22.5,27.5] (27.5,32.5] (32.5,37.5] (37.5,42.5] (42.5,47.5] 
          3           9          16          12           6           3 
(47.5,52.5] 
          1 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="example-2-2-3" class="slide level2">
<h2>Example 2-2</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Interpretation</strong></p>
<p>The frequency distribution shows that the class <strong>27.5–32.5 contains the largest number of delivery times (16)</strong>, followed by the class 32.5–37.5 with 12 delivery times. Hence, <strong>most of the deliveries (28) took between 28 and 37 minutes</strong>.</p>
<p>Analyze a frequency distribution by looking for <strong>peaks</strong> — the classes with the most data values — and for <strong>extreme values</strong>, called <strong>outliers</strong>, which are large or small relative to the other data values.</p>
</div>
</div>
</div>
</section>
<section id="cumulative-frequency-distributions" class="slide level2">
<h2>Cumulative Frequency Distributions</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Cumulative Frequency Distribution</strong></p>
</div>
<div class="callout-content">
<p>A <strong>cumulative frequency distribution</strong> is a distribution that shows the <strong>number of data values less than or equal to a specific value</strong> (usually an upper boundary).</p>
</div>
</div>
</div>
<p>The values are found by adding the frequencies of the classes less than or equal to the upper class boundary of a specific class. For Example 2-2 the cumulative frequency for the first class is <span class="math inline">0 + 3 = 3</span>; for the second, <span class="math inline">0 + 3 + 9 = 12</span>; for the third, <span class="math inline">0 + 3 + 9 + 16 = 28</span>. A shorter way is to add the frequency of the given class to the cumulative frequency of the class below: <span class="math inline">12 + 16 = 28</span>.</p>
</section>
<section id="example-2-2-4" class="slide level2">
<h2>Example 2-2</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Cumulative frequency distribution</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href=""></a><span class="fu">cumsum</span>(delivery_freq)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>(17.5,22.5] (22.5,27.5] (27.5,32.5] (32.5,37.5] (37.5,42.5] (42.5,47.5] 
          3          12          28          40          46          49 
(47.5,52.5] 
         50 </code></pre>
</div>
</div>
<p>Of the 50 delivery times, <strong>28 are less than or equal to 32 minutes</strong> and <strong>46 are less than or equal to 42 minutes</strong>.</p>
</div>
</div>
</div>
</section>
<section id="ungrouped-frequency-distributions" class="slide level2">
<h2>Ungrouped Frequency Distributions</h2>
<p>When the range of the data values is relatively small, a frequency distribution can be constructed using <strong>single data values</strong> for each class.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Ungrouped Frequency Distribution</strong></p>
</div>
<div class="callout-content">
<p>An <strong>ungrouped frequency distribution</strong> uses a <strong>single data value for each class</strong>, rather than a range of values.</p>
</div>
</div>
</div>
<p>If the data are continuous, class boundaries can still be used: subtract 0.5 from each class value to get the lower class boundary, and add 0.5 to get the upper class boundary.</p>
</section>
<section id="example-2-3" class="slide level2">
<h2>Example 2-3</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Items per Shopping Basket</strong></p>
</div>
<div class="callout-content">
<p>The data show the number of items scanned in each of 30 shopping baskets at a supermarket checkout during one lunch hour. Construct an <strong>ungrouped frequency distribution</strong> for the data and analyze the distribution. <em>(hypothetical data)</em></p>
<pre><code>4  9  3  5  6  4
5  3  7  4  2  6
3  5  4  8  5  3
6  4  2  5  7  4
3  6  5  4  8  7</code></pre>
</div>
</div>
</div>
</section>
<section id="example-2-3-1" class="slide level2">
<h2>Example 2-3</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Steps 1 to 3 — Determine the classes, tally, and find the frequencies</strong></p>
<p>Since the range is small (<span class="math inline">9 - 2 = 7</span>), classes consisting of a single data value can be used: 2, 3, 4, 5, 6, 7, 8, 9.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href=""></a>basket_items <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">9</span>, <span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">4</span>,</span>
<span id="cb20-2"><a href=""></a>                  <span class="dv">5</span>, <span class="dv">3</span>, <span class="dv">7</span>, <span class="dv">4</span>, <span class="dv">2</span>, <span class="dv">6</span>,</span>
<span id="cb20-3"><a href=""></a>                  <span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">4</span>, <span class="dv">8</span>, <span class="dv">5</span>, <span class="dv">3</span>,</span>
<span id="cb20-4"><a href=""></a>                  <span class="dv">6</span>, <span class="dv">4</span>, <span class="dv">2</span>, <span class="dv">5</span>, <span class="dv">7</span>, <span class="dv">4</span>,</span>
<span id="cb20-5"><a href=""></a>                  <span class="dv">3</span>, <span class="dv">6</span>, <span class="dv">5</span>, <span class="dv">4</span>, <span class="dv">8</span>, <span class="dv">7</span>)</span>
<span id="cb20-6"><a href=""></a></span>
<span id="cb20-7"><a href=""></a><span class="fu">table</span>(basket_items)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>basket_items
2 3 4 5 6 7 8 9 
2 5 7 6 4 3 2 1 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href=""></a><span class="fu">cumsum</span>(<span class="fu">table</span>(basket_items))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> 2  3  4  5  6  7  8  9 
 2  7 14 20 24 27 29 30 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="example-2-3-2" class="slide level2">
<h2>Example 2-3</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Interpretation</strong></p>
<p>In this case, <strong>seven baskets held 4 items and this was the largest frequency</strong>. Reading the cumulative frequencies: 14 baskets held fewer than 4.5 items, 27 held fewer than 7.5 items, and all 30 held fewer than 9.5 items.</p>
<p>Note that several different but correct frequency distributions can be constructed for the same data by using a different class width, a different number of classes, or a different starting point. Whatever method is used, classes should be <strong>mutually exclusive, continuous, exhaustive, and of equal width</strong>.</p>
</div>
</div>
</div>
</section>
<section id="why-construct-a-frequency-distribution" class="slide level2">
<h2>Why Construct a Frequency Distribution?</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Five Reasons</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>To <strong>organize the data</strong> in a meaningful, intelligible way.</li>
<li>To enable the reader to determine the <strong>nature or shape</strong> of the distribution.</li>
<li>To facilitate <strong>computational procedures</strong> for measures of average and spread (Sections 3-1 and 3-2).</li>
<li>To enable the researcher to draw <strong>charts and graphs</strong> for the presentation of data (Section 2-2).</li>
<li>To enable the reader to make <strong>comparisons</strong> among different data sets.</li>
</ol>
</div>
</div>
</div>
</section></section>
<section>
<section id="section-2-2-histograms-frequency-polygons-and-ogives" class="title-slide slide level1 center" data-background-color="#2c4a6e">
<h1>Section 2-2: Histograms, Frequency Polygons, and Ogives</h1>

</section>
<section id="presenting-data-graphically" class="slide level2">
<h2>Presenting Data Graphically</h2>
<p>The purpose of graphs in statistics is to convey the data to the viewers in <strong>pictorial form</strong>. It is easier for most people to comprehend data presented graphically than data presented numerically in tables, especially if the users have little or no statistical knowledge.</p>
<p>The three most commonly used graphs in research are</p>
<ol type="1">
<li>The <strong>histogram</strong>.</li>
<li>The <strong>frequency polygon</strong>.</li>
<li>The <strong>cumulative frequency graph</strong>, or <strong>ogive</strong> (pronounced o-jive).</li>
</ol>
</section>
<section id="procedure-table-1" class="slide level2">
<h2>Procedure Table</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Constructing a Histogram, Frequency Polygon, and Ogive</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> Draw and label the <span class="math inline">x</span> and <span class="math inline">y</span> axes.</p>
<p><strong>Step 2.</strong> On the <span class="math inline">x</span> axis, label the <strong>class boundaries</strong> of the frequency distribution for the <strong>histogram</strong> and the <strong>ogive</strong>. Label the <strong>midpoints</strong> for the <strong>frequency polygon</strong>.</p>
<p><strong>Step 3.</strong> Plot the frequencies for each class, and draw the vertical bars for the histogram and the lines for the frequency polygon and ogive.</p>
<p><em>Note:</em> the lines for the frequency polygon <strong>begin and end on the <span class="math inline">x</span> axis</strong>, while the lines for the ogive <strong>begin on the <span class="math inline">x</span> axis</strong>.</p>
</div>
</div>
</div>
</section>
<section id="the-histogram" class="slide level2">
<h2>The Histogram</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Histogram</strong></p>
</div>
<div class="callout-content">
<p>The <strong>histogram</strong> is a graph that displays the data by using <strong>contiguous vertical bars</strong> (unless the frequency of a class is 0) of various heights to represent the <strong>frequencies of the classes</strong>.</p>
</div>
</div>
</div>
<p>Karl Pearson introduced the histogram in 1891, using it to show time concepts of the various reigns of Prime Ministers.</p>
</section>
<section id="example-2-4" class="slide level2">
<h2>Example 2-4</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Delivery Times for Online Food Orders</strong></p>
</div>
<div class="callout-content">
<p>Construct a <strong>histogram</strong> to represent the data shown for the delivery times of the 50 food orders (see <a href="#/example-2-2">Example 2-2</a>).</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Class boundaries</th>
<th>Frequency</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>17.5–22.5</td>
<td>3</td>
</tr>
<tr class="even">
<td>22.5–27.5</td>
<td>9</td>
</tr>
<tr class="odd">
<td>27.5–32.5</td>
<td>16</td>
</tr>
<tr class="even">
<td>32.5–37.5</td>
<td>12</td>
</tr>
<tr class="odd">
<td>37.5–42.5</td>
<td>6</td>
</tr>
<tr class="even">
<td>42.5–47.5</td>
<td>3</td>
</tr>
<tr class="odd">
<td>47.5–52.5</td>
<td>1</td>
</tr>
</tbody>
</table>
<p>Back to <a href="#/example-2-5">Example 2-5</a> · <a href="#/example-2-6">Example 2-6</a></p>
</div>
</div>
</div>
</section>
<section id="example-2-4-1" class="slide level2">
<h2>Example 2-4</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Draw figure</strong></p>
<p>Put the frequency on the <span class="math inline">y</span> axis and the class boundaries on the <span class="math inline">x</span> axis, then draw a vertical bar of that height for each class.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href=""></a><span class="fu">ggplot</span>(<span class="fu">data.frame</span>(delivery_times), <span class="fu">aes</span>(delivery_times)) <span class="sc">+</span></span>
<span id="cb24-2"><a href=""></a>  <span class="fu">geom_histogram</span>(<span class="at">breaks =</span> class_breaks, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb24-3"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Delivery Times for 50 Food Orders"</span>,</span>
<span id="cb24-4"><a href=""></a>       <span class="at">x =</span> <span class="st">"Delivery time (minutes)"</span>, <span class="at">y =</span> <span class="st">"Frequency"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="ch2_files/figure-revealjs/e2-4-1-1.png" class="quarto-figure quarto-figure-center" style="width:44.0%"></p>
</figure>
</div>
</div>
</div>
<p>The largest class (16) is <strong>27.5–32.5</strong>, then 12 for 32.5–37.5. The graph has <strong>one peak</strong>, with the data clustering around it.</p>
</div>
</div>
</div>
</section>
<section id="the-frequency-polygon" class="slide level2">
<h2>The Frequency Polygon</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Frequency Polygon</strong></p>
</div>
<div class="callout-content">
<p>The <strong>frequency polygon</strong> is a graph that displays the data by using <strong>lines that connect points plotted for the frequencies at the midpoints of the classes</strong>. The frequencies are represented by the heights of the points.</p>
</div>
</div>
</div>
<p>The frequency polygon and the histogram are two different ways to represent the same data set; the choice is left to the discretion of the researcher.</p>
</section>
<section id="example-2-5" class="slide level2">
<h2>Example 2-5</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Delivery Times for Online Food Orders</strong></p>
</div>
<div class="callout-content">
<p>Using the frequency distribution given in <a href="#/example-2-4">Example 2-4</a>, construct a <strong>frequency polygon</strong>.</p>
</div>
</div>
</div>
</section>
<section id="example-2-5-1" class="slide level2">
<h2>Example 2-5</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1 — Find the midpoints of each class</strong></p>
<p>Midpoints are found by adding the upper and lower boundaries and dividing by 2: <span class="math inline">\frac{17.5 + 22.5}{2} = 20</span>, <span class="math inline">\frac{22.5 + 27.5}{2} = 25</span>, and so on.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href=""></a>polygon_points <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">midpoint  =</span> <span class="fu">seq</span>(<span class="dv">15</span>, <span class="dv">55</span>, <span class="at">by =</span> <span class="dv">5</span>),</span>
<span id="cb25-2"><a href=""></a>                             <span class="at">frequency =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">3</span>, <span class="dv">9</span>, <span class="dv">16</span>, <span class="dv">12</span>, <span class="dv">6</span>, <span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">0</span>))</span>
<span id="cb25-3"><a href=""></a>polygon_points</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  midpoint frequency
1       15         0
2       20         3
3       25         9
4       30        16
5       35        12
6       40         6
7       45         3
8       50         1
9       55         0</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="example-2-5-2" class="slide level2">
<h2>Example 2-5</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Output figure</strong></p>
<p>Connect adjacent points with line segments, then draw a line back to the <span class="math inline">x</span> axis at the beginning and end of the graph, at the same distance that the previous and next midpoints would be located.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href=""></a><span class="fu">ggplot</span>(polygon_points, <span class="fu">aes</span>(midpoint, frequency)) <span class="sc">+</span></span>
<span id="cb27-2"><a href=""></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb27-3"><a href=""></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb27-4"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Delivery Times for 50 Food Orders"</span>,</span>
<span id="cb27-5"><a href=""></a>       <span class="at">x =</span> <span class="st">"Delivery time (minutes)"</span>, <span class="at">y =</span> <span class="st">"Frequency"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="ch2_files/figure-revealjs/e2-5-2-1.png" class="quarto-figure quarto-figure-center" style="width:52.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="the-ogive" class="slide level2">
<h2>The Ogive</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Cumulative Frequency and the Ogive</strong></p>
</div>
<div class="callout-content">
<p>The <strong>cumulative frequency</strong> is the sum of the frequencies accumulated up to the <strong>upper boundary</strong> of a class in the distribution.</p>
<p>The <strong>ogive</strong> is a graph that represents the <strong>cumulative frequencies</strong> for the classes in a frequency distribution.</p>
</div>
</div>
</div>
</section>
<section id="example-2-6" class="slide level2">
<h2>Example 2-6</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Delivery Times for Online Food Orders</strong></p>
</div>
<div class="callout-content">
<p>Construct an <strong>ogive</strong> for the frequency distribution described in <a href="#/example-2-4">Example 2-4</a>.</p>
</div>
</div>
</div>
</section>
<section id="example-2-6-1" class="slide level2">
<h2>Example 2-6</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1 — Find the cumulative frequency for each class</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href=""></a>ogive_points <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">boundary   =</span> class_breaks,</span>
<span id="cb28-2"><a href=""></a>                           <span class="at">cumulative =</span> <span class="fu">cumsum</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">3</span>, <span class="dv">9</span>, <span class="dv">16</span>, <span class="dv">12</span>, <span class="dv">6</span>, <span class="dv">3</span>, <span class="dv">1</span>)))</span>
<span id="cb28-3"><a href=""></a>ogive_points</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  boundary cumulative
1     17.5          0
2     22.5          3
3     27.5         12
4     32.5         28
5     37.5         40
6     42.5         46
7     47.5         49
8     52.5         50</code></pre>
</div>
</div>
<p>Plot the cumulative frequency at each <strong>upper class boundary</strong>, then extend the graph back to the first lower class boundary, 17.5, on the <span class="math inline">x</span> axis.</p>
</div>
</div>
</div>
</section>
<section id="example-2-6-2" class="slide level2">
<h2>Example 2-6</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Output figure</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href=""></a><span class="fu">ggplot</span>(ogive_points, <span class="fu">aes</span>(boundary, cumulative)) <span class="sc">+</span></span>
<span id="cb30-2"><a href=""></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb30-3"><a href=""></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb30-4"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Delivery Times for 50 Food Orders"</span>,</span>
<span id="cb30-5"><a href=""></a>       <span class="at">x =</span> <span class="st">"Delivery time (minutes)"</span>, <span class="at">y =</span> <span class="st">"Cumulative frequency"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="ch2_files/figure-revealjs/e2-6-2-1.png" class="quarto-figure quarto-figure-center" style="width:40.0%"></p>
</figure>
</div>
</div>
</div>
<p>Go up from 32.5 on the <span class="math inline">x</span> axis to the graph, then across to the <span class="math inline">y</span> axis: <strong>28</strong>.</p>
</div>
</div>
</div>
</section>
<section id="relative-frequency-graphs" class="slide level2">
<h2>Relative Frequency Graphs</h2>
<p>The histogram, frequency polygon, and ogive shown so far were constructed using frequencies in terms of the raw data. These distributions can be converted to <strong>proportions</strong> instead; the graphs are then called <strong>relative frequency graphs</strong>.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>When to Use Relative Frequencies</strong></p>
</div>
<div class="callout-content">
<p>Use relative frequencies when the <strong>proportion</strong> of data values falling into a class matters more than the actual <strong>number</strong>. Comparing the age distribution of Philadelphia (population 1,526,006) with Erie (population 101,786) using raw counts would make every Philadelphia bar much taller.</p>
<p>To convert a frequency into a relative frequency, <strong>divide the frequency for each class by the total of the frequencies</strong>. The sum of the relative frequencies is always 1.</p>
</div>
</div>
</div>
</section>
<section id="example-2-7" class="slide level2">
<h2>Example 2-7</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Floor Area of Retail Units</strong></p>
</div>
<div class="callout-content">
<p>The following frequency distribution shows the floor area, in square metres, of 50 retail units in a shopping mall. Draw a <strong>relative frequency histogram</strong>, a <strong>relative frequency polygon</strong>, and a <strong>relative ogive</strong> for the data. <em>(hypothetical data)</em></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Class boundaries</th>
<th>Frequency</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>24.5–31.5</td>
<td>6</td>
</tr>
<tr class="even">
<td>31.5–38.5</td>
<td>13</td>
</tr>
<tr class="odd">
<td>38.5–45.5</td>
<td>19</td>
</tr>
<tr class="even">
<td>45.5–52.5</td>
<td>8</td>
</tr>
<tr class="odd">
<td>52.5–59.5</td>
<td>4</td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td><strong>50</strong></td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="example-2-7-1" class="slide level2">
<h2>Example 2-7</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Steps 1 and 2 — Find the relative and cumulative relative frequencies</strong></p>
<p>For the class 24.5–31.5 the relative frequency is <span class="math inline">\frac{6}{50} = 0.12</span>; for 31.5–38.5 it is <span class="math inline">\frac{13}{50} = 0.26</span>; and so on. The cumulative relative frequencies are <span class="math inline">0.12</span>, <span class="math inline">0.38</span>, <span class="math inline">0.76</span>, <span class="math inline">0.92</span>, <span class="math inline">1.00</span>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href=""></a>frequency <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">6</span>, <span class="dv">13</span>, <span class="dv">19</span>, <span class="dv">8</span>, <span class="dv">4</span>)</span>
<span id="cb31-2"><a href=""></a></span>
<span id="cb31-3"><a href=""></a>frequency <span class="sc">/</span> <span class="dv">50</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.12 0.26 0.38 0.16 0.08</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href=""></a><span class="fu">cumsum</span>(frequency <span class="sc">/</span> <span class="dv">50</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.12 0.38 0.76 0.92 1.00</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="example-2-7-2" class="slide level2">
<h2>Example 2-7</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Relative frequency histogram</strong></p>
<p>For the histogram and ogive use the <strong>class boundaries</strong> along the <span class="math inline">x</span> axis; for the frequency polygon use the <strong>midpoints</strong>. For the scale on the <span class="math inline">y</span> axis, use proportions.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href=""></a>rel_histogram <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">midpoint =</span> <span class="fu">c</span>(<span class="dv">28</span>, <span class="dv">35</span>, <span class="dv">42</span>, <span class="dv">49</span>, <span class="dv">56</span>),</span>
<span id="cb35-2"><a href=""></a>                            <span class="at">rel_freq =</span> frequency <span class="sc">/</span> <span class="dv">50</span>)</span>
<span id="cb35-3"><a href=""></a></span>
<span id="cb35-4"><a href=""></a><span class="fu">ggplot</span>(rel_histogram, <span class="fu">aes</span>(midpoint, rel_freq)) <span class="sc">+</span></span>
<span id="cb35-5"><a href=""></a>  <span class="fu">geom_col</span>(<span class="at">width =</span> <span class="dv">7</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb35-6"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Relative Frequency Histogram"</span>,</span>
<span id="cb35-7"><a href=""></a>       <span class="at">x =</span> <span class="st">"Floor area (square metres)"</span>, <span class="at">y =</span> <span class="st">"Relative frequency"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="ch2_files/figure-revealjs/e2-7-2-1.png" class="quarto-figure quarto-figure-center" style="width:52.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="example-2-7-3" class="slide level2">
<h2>Example 2-7</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Relative frequency polygon</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href=""></a>rel_polygon <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">midpoint =</span> <span class="fu">c</span>(<span class="dv">21</span>, <span class="dv">28</span>, <span class="dv">35</span>, <span class="dv">42</span>, <span class="dv">49</span>, <span class="dv">56</span>, <span class="dv">63</span>),</span>
<span id="cb36-2"><a href=""></a>                          <span class="at">rel_freq =</span> <span class="fu">c</span>(<span class="dv">0</span>, frequency, <span class="dv">0</span>) <span class="sc">/</span> <span class="dv">50</span>)</span>
<span id="cb36-3"><a href=""></a></span>
<span id="cb36-4"><a href=""></a><span class="fu">ggplot</span>(rel_polygon, <span class="fu">aes</span>(midpoint, rel_freq)) <span class="sc">+</span></span>
<span id="cb36-5"><a href=""></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb36-6"><a href=""></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb36-7"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Relative Frequency Polygon"</span>,</span>
<span id="cb36-8"><a href=""></a>       <span class="at">x =</span> <span class="st">"Floor area (square metres)"</span>, <span class="at">y =</span> <span class="st">"Relative frequency"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="ch2_files/figure-revealjs/e2-7-3-1.png" class="quarto-figure quarto-figure-center" style="width:52.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="example-2-7-4" class="slide level2">
<h2>Example 2-7</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Relative ogive</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href=""></a>rel_ogive <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">boundary =</span> <span class="fu">c</span>(<span class="fl">24.5</span>, <span class="fl">31.5</span>, <span class="fl">38.5</span>, <span class="fl">45.5</span>, <span class="fl">52.5</span>, <span class="fl">59.5</span>),</span>
<span id="cb37-2"><a href=""></a>                        <span class="at">cum_rel  =</span> <span class="fu">cumsum</span>(<span class="fu">c</span>(<span class="dv">0</span>, frequency)) <span class="sc">/</span> <span class="dv">50</span>)</span>
<span id="cb37-3"><a href=""></a></span>
<span id="cb37-4"><a href=""></a><span class="fu">ggplot</span>(rel_ogive, <span class="fu">aes</span>(boundary, cum_rel)) <span class="sc">+</span></span>
<span id="cb37-5"><a href=""></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb37-6"><a href=""></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb37-7"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Relative Ogive"</span>,</span>
<span id="cb37-8"><a href=""></a>       <span class="at">x =</span> <span class="st">"Floor area (square metres)"</span>, <span class="at">y =</span> <span class="st">"Cumulative relative frequency"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="ch2_files/figure-revealjs/e2-7-4-1.png" class="quarto-figure quarto-figure-center" style="width:52.0%"></p>
</figure>
</div>
</div>
</div>
<p>The three graphs have exactly the same shapes as the corresponding frequency graphs; only the <span class="math inline">y</span> axis has changed from counts to proportions.</p>
</div>
</div>
</div>
</section>
<section id="distribution-shapes" class="slide level2">
<h2>Distribution Shapes</h2>
<p>The <strong>shape of a distribution</strong> decides which statistical methods fit later.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Shape</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Bell-shaped</strong> (mound)</td>
<td>One peak, tapering at both ends; symmetric</td>
</tr>
<tr class="even">
<td><strong>Uniform</strong></td>
<td>Basically flat or rectangular</td>
</tr>
<tr class="odd">
<td><strong>J-shaped</strong></td>
<td>Few values at the left, rising to the right</td>
</tr>
<tr class="even">
<td><strong>Reverse J-shaped</strong></td>
<td>The opposite of the J-shaped distribution</td>
</tr>
<tr class="odd">
<td><strong>Right-skewed</strong> (positive)</td>
<td>Peak at the left, tapering right</td>
</tr>
<tr class="even">
<td><strong>Left-skewed</strong> (negative)</td>
<td>Clustered at the right, tapering left</td>
</tr>
<tr class="odd">
<td><strong>Bimodal</strong></td>
<td>Two peaks of the same height</td>
</tr>
<tr class="even">
<td><strong>U-shaped</strong></td>
<td>High at both ends, low in the middle</td>
</tr>
</tbody>
</table>
</section>
<section id="distribution-shapes-1" class="slide level2">
<h2>Distribution Shapes</h2>
<p>Distributions are most often <strong>not perfectly shaped</strong>, so it is not necessary to have an exact shape but rather to identify an <strong>overall pattern</strong>.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Analyzing a Histogram or Frequency Polygon</strong></p>
</div>
<div class="callout-content">
<ul>
<li>Does it have <strong>one peak or two</strong>? Distributions with one peak — bell-shaped, right-skewed, left-skewed — are said to be <strong>unimodal</strong>; a distribution with two peaks of the same height is <strong>bimodal</strong>.</li>
<li>Is it relatively <strong>flat</strong>, or is it <strong>U-shaped</strong>?</li>
<li>Are the data <strong>spread out</strong>, or <strong>clustered around the center</strong>?</li>
<li>Are there data values at the <strong>extreme ends</strong>? These may be <strong>outliers</strong> (Section 3-3).</li>
<li>Are there <strong>gaps</strong> in the histogram, or does the frequency polygon touch the <span class="math inline">x</span> axis somewhere other than at the ends?</li>
<li>Are the data clustered at one end or the other, indicating a <strong>skewed</strong> distribution?</li>
</ul>
</div>
</div>
</div>
</section>
<section id="distribution-shapes-in-r" class="slide level2">
<h2>Distribution Shapes in R</h2>
<p><strong>Prepare data</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href=""></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb38-2"><a href=""></a>shapes <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb38-3"><a href=""></a>  <span class="at">shape =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"Bell-shaped"</span>, <span class="st">"Uniform"</span>, <span class="st">"J-shaped"</span>, <span class="st">"Reverse J-shaped"</span>,</span>
<span id="cb38-4"><a href=""></a>                <span class="st">"Right-skewed"</span>, <span class="st">"Left-skewed"</span>, <span class="st">"Bimodal"</span>, <span class="st">"U-shaped"</span>),</span>
<span id="cb38-5"><a href=""></a>              <span class="at">each =</span> <span class="dv">500</span>),</span>
<span id="cb38-6"><a href=""></a>  <span class="at">value =</span> <span class="fu">c</span>(<span class="fu">rnorm</span>(<span class="dv">500</span>, <span class="dv">50</span>, <span class="dv">10</span>), <span class="fu">runif</span>(<span class="dv">500</span>, <span class="dv">20</span>, <span class="dv">80</span>), <span class="dv">100</span> <span class="sc">-</span> <span class="fu">rexp</span>(<span class="dv">500</span>, <span class="fl">0.05</span>),</span>
<span id="cb38-7"><a href=""></a>            <span class="fu">rexp</span>(<span class="dv">500</span>, <span class="fl">0.05</span>), <span class="fu">rgamma</span>(<span class="dv">500</span>, <span class="dv">2</span>, <span class="fl">0.1</span>), <span class="dv">80</span> <span class="sc">-</span> <span class="fu">rgamma</span>(<span class="dv">500</span>, <span class="dv">2</span>, <span class="fl">0.1</span>),</span>
<span id="cb38-8"><a href=""></a>            <span class="fu">rnorm</span>(<span class="dv">250</span>, <span class="dv">30</span>, <span class="dv">5</span>), <span class="fu">rnorm</span>(<span class="dv">250</span>, <span class="dv">70</span>, <span class="dv">5</span>), <span class="fu">rbeta</span>(<span class="dv">500</span>, <span class="fl">0.4</span>, <span class="fl">0.4</span>) <span class="sc">*</span> <span class="dv">100</span>)</span>
<span id="cb38-9"><a href=""></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="distribution-shapes-in-r-1" class="slide level2">
<h2>Distribution Shapes in R</h2>
<p><strong>Output figure</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href=""></a><span class="fu">ggplot</span>(shapes, <span class="fu">aes</span>(value)) <span class="sc">+</span></span>
<span id="cb39-2"><a href=""></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">20</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb39-3"><a href=""></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> shape, <span class="at">scales =</span> <span class="st">"free"</span>, <span class="at">ncol =</span> <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="ch2_files/figure-revealjs/s2-2-2-1.png" class="quarto-figure quarto-figure-center r-stretch" style="width:88.0%"></section></section>
<section>
<section id="section-2-3-other-types-of-graphs" class="title-slide slide level1 center" data-background-color="#2c4a6e">
<h1>Section 2-3: Other Types of Graphs</h1>

</section>
<section id="beyond-the-histogram" class="slide level2">
<h2>Beyond the Histogram</h2>
<p>In addition to the histogram, the frequency polygon, and the ogive, several other types of graphs are often used in statistics:</p>
<ul>
<li><strong>Bar graph</strong> — for qualitative or categorical data</li>
<li><strong>Pareto chart</strong> — a bar graph whose bars are ordered from highest to lowest</li>
<li><strong>Time series graph</strong> — for data collected over a period of time</li>
<li><strong>Pie graph</strong> — for showing the relationship of the parts to the whole</li>
<li><strong>Dotplot</strong> — each data value plotted as a point above a horizontal axis</li>
<li><strong>Stem and leaf plot</strong> — a combination of sorting and graphing that retains the actual data</li>
</ul>
</section>
<section id="bar-graphs" class="slide level2">
<h2>Bar Graphs</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Bar Graph</strong></p>
</div>
<div class="callout-content">
<p>A <strong>bar graph</strong> represents the data by using <strong>vertical or horizontal bars</strong> whose <strong>heights or lengths</strong> represent the frequencies of the data.</p>
</div>
</div>
</div>
<p>When the data are qualitative or categorical, bar graphs can be used to represent the data. A bar graph can be drawn using either horizontal or vertical bars.</p>
</section>
<section id="example-2-8" class="slide level2">
<h2>Example 2-8</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Monthly Student Spending</strong></p>
</div>
<div class="callout-content">
<p>The table shows the average amount, in NT dollars, that students in an international trade programme spend each month in four categories. Draw a <strong>horizontal</strong> and a <strong>vertical</strong> bar graph for the data. <em>(hypothetical data)</em></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Category</th>
<th>Average spending</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Meals off campus</td>
<td>3,200</td>
</tr>
<tr class="even">
<td>Commuting</td>
<td>1,500</td>
</tr>
<tr class="odd">
<td>Mobile data plan</td>
<td>750</td>
</tr>
<tr class="even">
<td>Study materials</td>
<td>480</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="example-2-8-1" class="slide level2">
<h2>Example 2-8</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Prepare data</strong></p>
<p>Draw and label the <span class="math inline">x</span> and <span class="math inline">y</span> axes. For the horizontal bar graph place the frequency scale on the <span class="math inline">x</span> axis; for the vertical bar graph place the frequency scale on the <span class="math inline">y</span> axis.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href=""></a>monthly_spending <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb40-2"><a href=""></a>  <span class="at">category =</span> <span class="fu">c</span>(<span class="st">"Meals off campus"</span>, <span class="st">"Commuting"</span>,</span>
<span id="cb40-3"><a href=""></a>               <span class="st">"Mobile data plan"</span>, <span class="st">"Study materials"</span>),</span>
<span id="cb40-4"><a href=""></a>  <span class="at">amount   =</span> <span class="fu">c</span>(<span class="dv">3200</span>, <span class="dv">1500</span>, <span class="dv">750</span>, <span class="dv">480</span>)</span>
<span id="cb40-5"><a href=""></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</div>
</section>
<section id="example-2-8-2" class="slide level2">
<h2>Example 2-8</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Draw figure — horizontal bar graph</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href=""></a><span class="fu">ggplot</span>(monthly_spending, <span class="fu">aes</span>(amount, category)) <span class="sc">+</span></span>
<span id="cb41-2"><a href=""></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb41-3"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Average Monthly Student Spending"</span>,</span>
<span id="cb41-4"><a href=""></a>       <span class="at">x =</span> <span class="st">"Average amount (NT dollars)"</span>, <span class="at">y =</span> <span class="cn">NULL</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="ch2_files/figure-revealjs/e2-8-2-1.png" class="quarto-figure quarto-figure-center" style="width:52.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="example-2-8-3" class="slide level2">
<h2>Example 2-8</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Output figure — vertical bar graph</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href=""></a><span class="fu">ggplot</span>(monthly_spending, <span class="fu">aes</span>(category, amount)) <span class="sc">+</span></span>
<span id="cb42-2"><a href=""></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb42-3"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Average Amount Spent"</span>,</span>
<span id="cb42-4"><a href=""></a>       <span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Average amount (NT dollars)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="ch2_files/figure-revealjs/e2-8-3-1.png" class="quarto-figure quarto-figure-center" style="width:52.0%"></p>
</figure>
</div>
</div>
</div>
<p>The graphs show that these students spend the most on <strong>meals off campus</strong>.</p>
</div>
</div>
</div>
</section>
<section id="compound-bar-graphs" class="slide level2">
<h2>Compound Bar Graphs</h2>
<p>Bar graphs can also be used to compare data for <strong>two or more groups</strong>; these are called <strong>compound bar graphs</strong>. It is not necessary to have equal class sizes in these types of graphs.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Store format</th>
<th>Weekday</th>
<th>Weekend</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Convenience store</td>
<td>820</td>
<td>960</td>
</tr>
<tr class="even">
<td>Supermarket</td>
<td>540</td>
<td>910</td>
</tr>
<tr class="odd">
<td>Hypermarket</td>
<td>310</td>
<td>720</td>
</tr>
</tbody>
</table>
<p>Average number of customers visiting one store per day, by store format. <em>(hypothetical data)</em></p>
</section>
<section id="compound-bar-graphs-in-r" class="slide level2">
<h2>Compound Bar Graphs in R</h2>
<p><strong>Draw figure</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href=""></a>store_visits <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb43-2"><a href=""></a>  <span class="at">format   =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"Convenience"</span>, <span class="st">"Supermarket"</span>, <span class="st">"Hypermarket"</span>), <span class="at">each =</span> <span class="dv">2</span>),</span>
<span id="cb43-3"><a href=""></a>  <span class="at">day_type =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"Weekday"</span>, <span class="st">"Weekend"</span>), <span class="at">times =</span> <span class="dv">3</span>),</span>
<span id="cb43-4"><a href=""></a>  <span class="at">visits   =</span> <span class="fu">c</span>(<span class="dv">820</span>, <span class="dv">960</span>, <span class="dv">540</span>, <span class="dv">910</span>, <span class="dv">310</span>, <span class="dv">720</span>)</span>
<span id="cb43-5"><a href=""></a>)</span>
<span id="cb43-6"><a href=""></a></span>
<span id="cb43-7"><a href=""></a><span class="fu">ggplot</span>(store_visits, <span class="fu">aes</span>(format, visits, <span class="at">fill =</span> day_type)) <span class="sc">+</span></span>
<span id="cb43-8"><a href=""></a>  <span class="fu">geom_col</span>(<span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span></span>
<span id="cb43-9"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Average Daily Visitors by Store Format"</span>,</span>
<span id="cb43-10"><a href=""></a>       <span class="at">x =</span> <span class="st">"Store format"</span>, <span class="at">y =</span> <span class="st">"Visitors per day"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="ch2_files/figure-revealjs/s2-3-1-1.png" class="quarto-figure quarto-figure-center r-stretch" style="width:48.0%"><p>The graph shows that <strong>every format is busier at the weekend</strong>, and that the weekend increase is <strong>largest for the hypermarket</strong>, whose visitor count more than doubles, and smallest for the convenience store.</p>
</section>
<section id="pareto-charts" class="slide level2">
<h2>Pareto Charts</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Pareto Chart</strong></p>
</div>
<div class="callout-content">
<p>A <strong>Pareto chart</strong> is used to represent a frequency distribution for a <strong>categorical variable</strong>, and the frequencies are displayed by the heights of <strong>vertical bars</strong>, which are <strong>arranged in order from highest to lowest</strong>.</p>
</div>
</div>
</div>
<p>Vilfredo Pareto (1848–1923) was an Italian scholar whose research on income distribution became known as Pareto’s law; the Pareto distribution is named after him.</p>
</section>
<section id="example-2-9" class="slide level2">
<h2>Example 2-9</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Reasons for Abandoning an Online Cart</strong></p>
</div>
<div class="callout-content">
<p>An online retailer asked shoppers who left items in a shopping cart why they did not complete the order. The percentage of shoppers naming each reason is shown. Draw a <strong>Pareto chart</strong> for the data. <em>(hypothetical data)</em></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Reason</th>
<th>Percent naming it</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Shipping cost</td>
<td>41%</td>
</tr>
<tr class="even">
<td>Slow delivery</td>
<td>26%</td>
</tr>
<tr class="odd">
<td>Checkout steps</td>
<td>33%</td>
</tr>
<tr class="even">
<td>Payment options</td>
<td>18%</td>
</tr>
<tr class="odd">
<td>Out of stock</td>
<td>29%</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="example-2-9-1" class="slide level2">
<h2>Example 2-9</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1 — Arrange the data from largest value to smallest value</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href=""></a>cart_reasons <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb44-2"><a href=""></a>  <span class="at">reason  =</span> <span class="fu">c</span>(<span class="st">"Shipping cost"</span>, <span class="st">"Slow delivery"</span>, <span class="st">"Checkout steps"</span>,</span>
<span id="cb44-3"><a href=""></a>              <span class="st">"Payment options"</span>, <span class="st">"Out of stock"</span>),</span>
<span id="cb44-4"><a href=""></a>  <span class="at">percent =</span> <span class="fu">c</span>(<span class="dv">41</span>, <span class="dv">26</span>, <span class="dv">33</span>, <span class="dv">18</span>, <span class="dv">29</span>)</span>
<span id="cb44-5"><a href=""></a>)</span>
<span id="cb44-6"><a href=""></a></span>
<span id="cb44-7"><a href=""></a><span class="fu">arrange</span>(cart_reasons, <span class="fu">desc</span>(percent))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>           reason percent
1   Shipping cost      41
2  Checkout steps      33
3    Out of stock      29
4   Slow delivery      26
5 Payment options      18</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="example-2-9-2" class="slide level2">
<h2>Example 2-9</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Steps 2 and 3 — Draw and label the axes, then draw vertical bars for the percents</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href=""></a><span class="fu">ggplot</span>(cart_reasons, <span class="fu">aes</span>(<span class="fu">reorder</span>(reason, <span class="sc">-</span>percent), percent)) <span class="sc">+</span></span>
<span id="cb46-2"><a href=""></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb46-3"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Why Shoppers Abandon a Cart"</span>,</span>
<span id="cb46-4"><a href=""></a>       <span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Percent of shoppers"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="ch2_files/figure-revealjs/e2-9-2-1.png" class="quarto-figure quarto-figure-center" style="width:50.0%"></p>
</figure>
</div>
</div>
</div>
<p><strong>Shipping cost is named by 41% of the shoppers</strong>, while the payment options are named by only <strong>18%</strong> — so the retailer should look at shipping cost first.</p>
</div>
</div>
</div>
</section>
<section id="suggestions-for-drawing-pareto-charts" class="slide level2">
<h2>Suggestions for Drawing Pareto Charts</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Three Suggestions</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>Make the <strong>bars the same width</strong>.</li>
<li><strong>Arrange the data from largest to smallest</strong> according to frequency.</li>
<li>Make the <strong>units</strong> that are used for the frequency <strong>equal in size</strong>.</li>
</ol>
<p>When you analyze a Pareto chart, make comparisons by looking at the <strong>heights of the bars</strong>.</p>
</div>
</div>
</div>
</section>
<section id="the-time-series-graph" class="slide level2">
<h2>The Time Series Graph</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Time Series Graph</strong></p>
</div>
<div class="callout-content">
<p>A <strong>time series graph</strong> represents data that occur over a <strong>specific period of time</strong>.</p>
</div>
</div>
</div>
<p>When you analyze a time series graph, look for a <strong>trend or pattern</strong> over the time period: is the line <strong>ascending</strong> (an increase over time) or <strong>descending</strong> (a decrease)? Also look at the <strong>slope</strong>, or steepness — a steep line indicates a rapid increase or decrease over that period.</p>
</section>
<section id="example-2-10" class="slide level2">
<h2>Example 2-10</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Hot Spring Hotel Visitors</strong></p>
</div>
<div class="callout-content">
<p>The data show the number of visitors, in <strong>thousands</strong>, to a hot spring hotel in each month of a one-year period. Draw a <strong>time series graph</strong> for the data and describe the results. <em>(hypothetical data)</em></p>
<table class="caption-top">
<tbody>
<tr class="odd">
<td>Jan 9.8</td>
<td>May 5.5</td>
<td>Sept 6.0</td>
<td></td>
</tr>
<tr class="even">
<td>Feb 9.1</td>
<td>June 4.8</td>
<td>Oct 7.2</td>
<td></td>
</tr>
<tr class="odd">
<td>Mar 7.4</td>
<td>July 5.1</td>
<td>Nov 8.6</td>
<td></td>
</tr>
<tr class="even">
<td>Apr 6.2</td>
<td>Aug 5.4</td>
<td>Dec 10.4</td>
<td></td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="example-2-10-1" class="slide level2">
<h2>Example 2-10</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Prepare data</strong></p>
<p>Label the <span class="math inline">x</span> axis for months and the <span class="math inline">y</span> axis for thousands of visitors, then plot each point.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href=""></a>hotel_visitors <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb47-2"><a href=""></a>  <span class="at">month    =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>,</span>
<span id="cb47-3"><a href=""></a>  <span class="at">visitors =</span> <span class="fu">c</span>(<span class="fl">9.8</span>, <span class="fl">9.1</span>, <span class="fl">7.4</span>, <span class="fl">6.2</span>, <span class="fl">5.5</span>, <span class="fl">4.8</span>,</span>
<span id="cb47-4"><a href=""></a>               <span class="fl">5.1</span>, <span class="fl">5.4</span>, <span class="fl">6.0</span>, <span class="fl">7.2</span>, <span class="fl">8.6</span>, <span class="fl">10.4</span>)</span>
<span id="cb47-5"><a href=""></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</div>
</section>
<section id="example-2-10-2" class="slide level2">
<h2>Example 2-10</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Output figure</strong></p>
<p>Draw line segments connecting adjacent points; do <strong>not</strong> draw a smooth curve through the points.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href=""></a><span class="fu">ggplot</span>(hotel_visitors, <span class="fu">aes</span>(month, visitors)) <span class="sc">+</span></span>
<span id="cb48-2"><a href=""></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb48-3"><a href=""></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb48-4"><a href=""></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb48-5"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Hot Spring Hotel Visitors"</span>,</span>
<span id="cb48-6"><a href=""></a>       <span class="at">x =</span> <span class="st">"Month"</span>, <span class="at">y =</span> <span class="st">"Visitors (thousands)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="ch2_files/figure-revealjs/e2-10-2-1.png" class="quarto-figure quarto-figure-center" style="width:52.0%"></p>
</figure>
</div>
</div>
</div>
<p>Visitors were <strong>highest in December, January, and February</strong> and <strong>lowest in June</strong>, so the hotel’s business clearly follows the cold season.</p>
</div>
</div>
</div>
</section>
<section id="compound-time-series-graphs" class="slide level2">
<h2>Compound Time Series Graphs</h2>
<p>Two or more data sets can be compared on the same graph — a <strong>compound time series graph</strong> — by drawing two or more lines.</p>
<p>For example, an airline records its <strong>load factor</strong> — the percentage of seats sold — for short-haul and for long-haul routes in each year from 2018 to 2024. Two lines drawn on one pair of axes show at a glance that <strong>both fell sharply in 2020</strong>, that the <strong>short-haul</strong> line recovered first, and that the <strong>long-haul</strong> line was still below its 2018 level in 2024. <em>(hypothetical data)</em></p>
</section>
<section id="the-pie-graph" class="slide level2">
<h2>The Pie Graph</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Pie Graph</strong></p>
</div>
<div class="callout-content">
<p>A <strong>pie graph</strong> is a circle that is divided into sections or wedges according to the <strong>percentage of frequencies in each category</strong> of the distribution.</p>
</div>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Degrees for Each Section</strong></p>
</div>
<div class="callout-content">
<p><span class="math display">\text{Degrees} = \frac{f}{n} \cdot 360^\circ</span></p>
<p>where <span class="math inline">f</span> is the frequency for each class and <span class="math inline">n</span> is the sum of the frequencies. The degrees should sum to <span class="math inline">360^\circ</span>, and the percentages to 100% — although rounding can make the totals slightly off.</p>
</div>
</div>
</div>
</section>
<section id="example-2-11" class="slide level2">
<h2>Example 2-11</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Hot Drinks Sold by a Convenience Store Chain</strong></p>
</div>
<div class="callout-content">
<p>This frequency distribution shows the number of <strong>cups</strong>, in thousands, of each hot drink sold by a convenience store chain in one week. Construct a <strong>pie graph</strong> for the data. The percentage formula is the one introduced in <a href="#/example-2-1">Example 2-1</a>. <em>(hypothetical data)</em></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Drink</th>
<th>Cups (frequency)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Latte</td>
<td>12.7 thousand</td>
</tr>
<tr class="even">
<td>Americano</td>
<td>9.4 thousand</td>
</tr>
<tr class="odd">
<td>Milk tea</td>
<td>6.1 thousand</td>
</tr>
<tr class="even">
<td>Black tea</td>
<td>4.8 thousand</td>
</tr>
<tr class="odd">
<td>Hot cocoa</td>
<td>3.0 thousand</td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td><strong><span class="math inline">n =</span> 36.0 thousand</strong></td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="example-2-11-1" class="slide level2">
<h2>Example 2-11</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Steps 1 and 2 — Convert each frequency to degrees and to a percentage</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href=""></a>cups <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">12.7</span>, <span class="fl">9.4</span>, <span class="fl">6.1</span>, <span class="fl">4.8</span>, <span class="fl">3.0</span>)</span>
<span id="cb49-2"><a href=""></a></span>
<span id="cb49-3"><a href=""></a>cups <span class="sc">/</span> <span class="dv">36</span> <span class="sc">*</span> <span class="dv">360</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 127  94  61  48  30</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href=""></a>cups <span class="sc">/</span> <span class="dv">36</span> <span class="sc">*</span> <span class="dv">100</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 35.277778 26.111111 16.944444 13.333333  8.333333</code></pre>
</div>
</div>
<p>The degrees are <span class="math inline">127^\circ</span>, <span class="math inline">94^\circ</span>, <span class="math inline">61^\circ</span>, <span class="math inline">48^\circ</span>, and <span class="math inline">30^\circ</span>; the percentages are 35.3%, 26.1%, 16.9%, 13.3%, and 8.3%.</p>
</div>
</div>
</div>
</section>
<section id="example-2-11-2" class="slide level2">
<h2>Example 2-11</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 3 — Draw the graph and label each section</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href=""></a><span class="fu">pie</span>(cups, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Latte"</span>, <span class="st">"Americano"</span>, <span class="st">"Milk tea"</span>, <span class="st">"Black tea"</span>, <span class="st">"Hot cocoa"</span>),</span>
<span id="cb53-2"><a href=""></a>    <span class="at">main =</span> <span class="st">"Hot Drinks Sold in One Week"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="ch2_files/figure-revealjs/e2-11-2-1.png" class="quarto-figure quarto-figure-center" style="width:42.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="example-2-12" class="slide level2">
<h2>Example 2-12</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Packages Sorted by Shift</strong></p>
</div>
<div class="callout-content">
<p>Construct and analyze a <strong>pie graph</strong> for the number of packages a distribution centre sorted on each of its three daily shifts last month. <em>(hypothetical data)</em></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Shift</th>
<th>Frequency</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1. Morning</td>
<td>3060</td>
</tr>
<tr class="even">
<td>2. Afternoon</td>
<td>3240</td>
</tr>
<tr class="odd">
<td>3. Night</td>
<td>2700</td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td><strong>9000</strong></td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="example-2-12-1" class="slide level2">
<h2>Example 2-12</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Steps 1 and 2 — Find the number of degrees and the percentages for each shift</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href=""></a>packages <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">3060</span>, <span class="dv">3240</span>, <span class="dv">2700</span>)</span>
<span id="cb54-2"><a href=""></a></span>
<span id="cb54-3"><a href=""></a>packages <span class="sc">/</span> <span class="dv">9000</span> <span class="sc">*</span> <span class="dv">360</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 122.4 129.6 108.0</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href=""></a>packages <span class="sc">/</span> <span class="dv">9000</span> <span class="sc">*</span> <span class="dv">100</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 34 36 30</code></pre>
</div>
</div>
<p>Morning: <span class="math inline">\frac{3060}{9000}\cdot 360^\circ \approx 122^\circ</span> and 34%; Afternoon: <span class="math inline">130^\circ</span> and 36%; Night: <span class="math inline">108^\circ</span> and 30%.</p>
</div>
</div>
</div>
</section>
<section id="example-2-12-2" class="slide level2">
<h2>Example 2-12</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 3 — Graph each section and write its name</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href=""></a><span class="fu">pie</span>(packages, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Morning"</span>, <span class="st">"Afternoon"</span>, <span class="st">"Night"</span>),</span>
<span id="cb58-2"><a href=""></a>    <span class="at">main =</span> <span class="st">"Packages Sorted by Shift"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="ch2_files/figure-revealjs/e2-12-2-1.png" class="quarto-figure quarto-figure-center" style="width:42.0%"></p>
</figure>
</div>
</div>
</div>
<p>The numbers of packages sorted on the three shifts are <strong>about equal</strong>, although slightly more were handled on the <strong>afternoon</strong> shift.</p>
</div>
</div>
</div>
</section>
<section id="dotplots" class="slide level2">
<h2>Dotplots</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Dotplot</strong></p>
</div>
<div class="callout-content">
<p>A <strong>dotplot</strong> is a statistical graph in which <strong>each data value is plotted as a point (dot) above the horizontal axis</strong>. If the data values occur more than once, the corresponding points are plotted <strong>above one another</strong>.</p>
</div>
</div>
</div>
<p>Dotplots are used to show how the data values are <strong>distributed</strong> and to see whether there are any <strong>extremely high or low</strong> data values.</p>
</section>
<section id="example-2-13" class="slide level2">
<h2>Example 2-13</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Complaints by Product Line</strong></p>
</div>
<div class="callout-content">
<p>The data show the number of complaints a customer service centre logged about each of 50 product lines during one month. Draw a <strong>dotplot</strong> for the data and summarize the results. <em>(hypothetical data)</em></p>
<pre><code>2  1  0  3  12  1  4  1  2  5
1  0  2  1   3  6  1  0  2  1
3  9  5  2   1  4  0  2  1  0
1  4  2  3   0  1  6  2  3  7
0  2  1  3   4  5  6  3  2  4</code></pre>
</div>
</div>
</div>
</section>
<section id="example-2-13-1" class="slide level2">
<h2>Example 2-13</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Prepare data</strong></p>
<p>The lowest data value is 0 and the highest is 12, so a scale from 0 to 12 is needed.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href=""></a>complaints <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">3</span>,<span class="dv">12</span>,<span class="dv">1</span>,<span class="dv">4</span>,<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">5</span>,</span>
<span id="cb60-2"><a href=""></a>                <span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">2</span>,<span class="dv">1</span>, <span class="dv">3</span>,<span class="dv">6</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">2</span>,<span class="dv">1</span>,</span>
<span id="cb60-3"><a href=""></a>                <span class="dv">3</span>,<span class="dv">9</span>,<span class="dv">5</span>,<span class="dv">2</span>, <span class="dv">1</span>,<span class="dv">4</span>,<span class="dv">0</span>,<span class="dv">2</span>,<span class="dv">1</span>,<span class="dv">0</span>,</span>
<span id="cb60-4"><a href=""></a>                <span class="dv">1</span>,<span class="dv">4</span>,<span class="dv">2</span>,<span class="dv">3</span>, <span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">6</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">7</span>,</span>
<span id="cb60-5"><a href=""></a>                <span class="dv">0</span>,<span class="dv">2</span>,<span class="dv">1</span>,<span class="dv">3</span>, <span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">3</span>,<span class="dv">2</span>,<span class="dv">4</span>)</span>
<span id="cb60-6"><a href=""></a></span>
<span id="cb60-7"><a href=""></a><span class="fu">table</span>(complaints)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>complaints
 0  1  2  3  4  5  6  7  9 12 
 7 12 10  7  5  3  3  1  1  1 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="example-2-13-2" class="slide level2">
<h2>Example 2-13</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Output figure</strong></p>
<p>Draw a horizontal scale, then plot each value above it, stacking repeated values on top of one another.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href=""></a><span class="fu">stripchart</span>(complaints, <span class="at">method =</span> <span class="st">"stack"</span>, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">at =</span> <span class="dv">0</span>,</span>
<span id="cb62-2"><a href=""></a>           <span class="at">main =</span> <span class="st">"Complaints by Product Line"</span>, <span class="at">xlab =</span> <span class="st">"Number of complaints"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="ch2_files/figure-revealjs/e2-13-2-1.png" class="quarto-figure quarto-figure-center" style="width:66.0%"></p>
</figure>
</div>
</div>
</div>
<p>Most product lines drew <strong>between zero and three complaints</strong>, with <strong>12 product lines drawing exactly one complaint</strong> — the largest frequency.</p>
</div>
</div>
</div>
</section>
<section id="stem-and-leaf-plots" class="slide level2">
<h2>Stem and Leaf Plots</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Stem and Leaf Plot</strong></p>
</div>
<div class="callout-content">
<p>A <strong>stem and leaf plot</strong> is a data plot that uses <strong>part of the data value as the stem</strong> and <strong>part of the data value as the leaf</strong> to form groups or classes.</p>
</div>
</div>
</div>
<p>A data value of 34 would have 3 as the stem and 4 as the leaf; a data value of 356 would have 35 as the stem and 6 as the leaf. The stem and leaf plot has the advantage over a grouped frequency distribution of <strong>retaining the actual data</strong> while showing them in graphical form.</p>
</section>
<section id="example-2-14" class="slide level2">
<h2>Example 2-14</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Customers Served at a Night Market Stall</strong></p>
</div>
<div class="callout-content">
<p>A night market food stall recorded the number of customers it served each evening for 20 evenings. Construct a <strong>stem and leaf plot</strong> for the data. <em>(hypothetical data)</em></p>
<pre><code>33  22  41  13  54
08  35  31  58  26
45  32  17  38  24
51  33  47  36  42</code></pre>
</div>
</div>
</div>
</section>
<section id="example-2-14-1" class="slide level2">
<h2>Example 2-14</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Steps 1 to 3 — Arrange the data in order, separate by leading digit, and plot</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href=""></a>evening_customers <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">33</span>,<span class="dv">22</span>,<span class="dv">41</span>,<span class="dv">13</span>,<span class="dv">54</span>,</span>
<span id="cb64-2"><a href=""></a>                        <span class="dv">8</span>,<span class="dv">35</span>,<span class="dv">31</span>,<span class="dv">58</span>,<span class="dv">26</span>,</span>
<span id="cb64-3"><a href=""></a>                       <span class="dv">45</span>,<span class="dv">32</span>,<span class="dv">17</span>,<span class="dv">38</span>,<span class="dv">24</span>,</span>
<span id="cb64-4"><a href=""></a>                       <span class="dv">51</span>,<span class="dv">33</span>,<span class="dv">47</span>,<span class="dv">36</span>,<span class="dv">42</span>)</span>
<span id="cb64-5"><a href=""></a></span>
<span id="cb64-6"><a href=""></a><span class="fu">stem</span>(evening_customers, <span class="at">scale =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  The decimal point is 1 digit(s) to the right of the |

  0 | 8
  1 | 37
  2 | 246
  3 | 1233568
  4 | 1257
  5 | 148</code></pre>
</div>
</div>
<p><code>scale = 2</code> gives each stem its own row. If there are no data values in a class, write the stem number and <strong>leave the leaf row blank</strong> — do not put a zero in the leaf row.</p>
</div>
</div>
</div>
</section>
<section id="example-2-14-2" class="slide level2">
<h2>Example 2-14</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Interpretation</strong></p>
<p>The plot shows that the distribution <strong>peaks in the center</strong> and that there are <strong>no gaps</strong> in the data. For <strong>7 of the 20 evenings</strong> the number of customers served was <strong>between 31 and 38</strong>. The plot also shows that the stall served from a minimum of <strong>8</strong> customers to a maximum of <strong>58</strong> customers in any one evening.</p>
<p>When you analyze a stem and leaf plot, look for <strong>peaks and gaps</strong>, see whether the distribution is <strong>symmetric or skewed</strong>, and check the <strong>variability</strong> by looking at the spread.</p>
</div>
</div>
</div>
</section>
<section id="example-2-15" class="slide level2">
<h2>Example 2-15</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Pallets Dispatched by a Distribution Centre</strong></p>
</div>
<div class="callout-content">
<p>A distribution centre recorded the number of pallets it dispatched each day for 30 days. Construct a <strong>stem and leaf plot</strong> by using classes 50–54, 55–59, 60–64, 65–69, 70–74, and 75–79. <em>(hypothetical data)</em></p>
<pre><code>57  63  50  66  55
69  52  58  61  76
54  67  59  65  60
71  56  64  51  68
53  62  57  78  55
59  73  66  63  69</code></pre>
</div>
</div>
</div>
</section>
<section id="example-2-15-1" class="slide level2">
<h2>Example 2-15</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Steps 1 to 3 — Arrange the data in order, separate by class, and plot</strong></p>
<p>Because the classes are 5 units wide, each stem is <strong>repeated twice</strong>: once for the leaves 0–4 and once for the leaves 5–9.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb67"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href=""></a>pallets <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">57</span>,<span class="dv">63</span>,<span class="dv">50</span>,<span class="dv">66</span>,<span class="dv">55</span>,</span>
<span id="cb67-2"><a href=""></a>             <span class="dv">69</span>,<span class="dv">52</span>,<span class="dv">58</span>,<span class="dv">61</span>,<span class="dv">76</span>,</span>
<span id="cb67-3"><a href=""></a>             <span class="dv">54</span>,<span class="dv">67</span>,<span class="dv">59</span>,<span class="dv">65</span>,<span class="dv">60</span>,</span>
<span id="cb67-4"><a href=""></a>             <span class="dv">71</span>,<span class="dv">56</span>,<span class="dv">64</span>,<span class="dv">51</span>,<span class="dv">68</span>,</span>
<span id="cb67-5"><a href=""></a>             <span class="dv">53</span>,<span class="dv">62</span>,<span class="dv">57</span>,<span class="dv">78</span>,<span class="dv">55</span>,</span>
<span id="cb67-6"><a href=""></a>             <span class="dv">59</span>,<span class="dv">73</span>,<span class="dv">66</span>,<span class="dv">63</span>,<span class="dv">69</span>)</span>
<span id="cb67-7"><a href=""></a></span>
<span id="cb67-8"><a href=""></a><span class="fu">stem</span>(pallets)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  The decimal point is 1 digit(s) to the right of the |

  5 | 01234
  5 | 55677899
  6 | 012334
  6 | 5667899
  7 | 13
  7 | 68</code></pre>
</div>
</div>
<p>The distribution has no gaps; the largest class, 55–59, contains 8 of the 30 days.</p>
</div>
</div>
</div>
</section>
<section id="back-to-back-stem-and-leaf-plots" class="slide level2">
<h2>Back-to-Back Stem and Leaf Plots</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Back-to-Back Stem and Leaf Plot</strong></p>
</div>
<div class="callout-content">
<p>Related distributions can be compared by using a <strong>back-to-back stem and leaf plot</strong>. It uses the <strong>same digits for the stems of both distributions</strong>, but the digits used for the leaves are arranged in order <strong>out from the stems on both sides</strong>.</p>
</div>
</div>
</div>
<p>Stem and leaf plots are part of the techniques called <strong>exploratory data analysis</strong>; more on this topic appears in Chapter 3.</p>
</section>
<section id="example-2-16" class="slide level2">
<h2>Example 2-16</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Monthly Revenue of Coffee Shops in Two Cities</strong></p>
</div>
<div class="callout-content">
<p>The monthly revenue, in hundreds of thousands of NT dollars, of two randomly selected samples of coffee shops in <strong>Taipei</strong> and <strong>Taichung</strong> is shown. Construct a <strong>back-to-back stem and leaf plot</strong> for the data and compare the distributions. <em>(hypothetical data)</em></p>
<pre><code>       Taipei                    Taichung
64  57  52  45  60        45  53  44  36  47
55  38  68  50  62        61  55  40  35  32
63  44  58  70  41        54  34  51  43  36
69  53  61  66  56        48  41  39  50  72
73  58  49  45  64        58  42  66  45  55</code></pre>
</div>
</div>
</div>
</section>
<section id="example-2-16-1" class="slide level2">
<h2>Example 2-16</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Steps 1 and 2 — Arrange each data set in order with <code>stem()</code></strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb70"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href=""></a>taipei   <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">64</span>,<span class="dv">57</span>,<span class="dv">52</span>,<span class="dv">45</span>,<span class="dv">60</span>, <span class="dv">55</span>,<span class="dv">38</span>,<span class="dv">68</span>,<span class="dv">50</span>,<span class="dv">62</span>, <span class="dv">63</span>,<span class="dv">44</span>,<span class="dv">58</span>,<span class="dv">70</span>,<span class="dv">41</span>,</span>
<span id="cb70-2"><a href=""></a>              <span class="dv">69</span>,<span class="dv">53</span>,<span class="dv">61</span>,<span class="dv">66</span>,<span class="dv">56</span>, <span class="dv">73</span>,<span class="dv">58</span>,<span class="dv">49</span>,<span class="dv">45</span>,<span class="dv">64</span>)</span>
<span id="cb70-3"><a href=""></a>taichung <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">45</span>,<span class="dv">53</span>,<span class="dv">44</span>,<span class="dv">36</span>,<span class="dv">47</span>, <span class="dv">61</span>,<span class="dv">55</span>,<span class="dv">40</span>,<span class="dv">35</span>,<span class="dv">32</span>, <span class="dv">54</span>,<span class="dv">34</span>,<span class="dv">51</span>,<span class="dv">43</span>,<span class="dv">36</span>,</span>
<span id="cb70-4"><a href=""></a>              <span class="dv">48</span>,<span class="dv">41</span>,<span class="dv">39</span>,<span class="dv">50</span>,<span class="dv">72</span>, <span class="dv">58</span>,<span class="dv">42</span>,<span class="dv">66</span>,<span class="dv">45</span>,<span class="dv">55</span>)</span>
<span id="cb70-5"><a href=""></a></span>
<span id="cb70-6"><a href=""></a><span class="fu">stem</span>(taipei)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  The decimal point is 1 digit(s) to the right of the |

  3 | 8
  4 | 14559
  5 | 02356788
  6 | 012344689
  7 | 03</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb72"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href=""></a><span class="fu">stem</span>(taichung)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  The decimal point is 1 digit(s) to the right of the |

  3 | 245669
  4 | 012345578
  5 | 0134558
  6 | 16
  7 | 2</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="example-2-16-2" class="slide level2">
<h2>Example 2-16</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 3 — Put the two plots back to back and compare</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: right;">Taipei</th>
<th style="text-align: center;">Stem</th>
<th style="text-align: left;">Taichung</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">8</td>
<td style="text-align: center;">3</td>
<td style="text-align: left;">2 4 5 6 6 9</td>
</tr>
<tr class="even">
<td style="text-align: right;">9 5 5 4 1</td>
<td style="text-align: center;">4</td>
<td style="text-align: left;">0 1 2 3 4 5 5 7 8</td>
</tr>
<tr class="odd">
<td style="text-align: right;">8 8 7 6 5 3 2 0</td>
<td style="text-align: center;">5</td>
<td style="text-align: left;">0 1 3 4 5 5 8</td>
</tr>
<tr class="even">
<td style="text-align: right;">9 8 6 4 4 3 2 1 0</td>
<td style="text-align: center;">6</td>
<td style="text-align: left;">1 6</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3 0</td>
<td style="text-align: center;">7</td>
<td style="text-align: left;">2</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>Taipei’s coffee shops generally take in more</strong> than those in Taichung.</li>
<li>The distribution for the shops in <strong>Taipei peaks at 60 to 69</strong>, while the shops in <strong>Taichung peak at 40 to 49</strong>.</li>
<li>Taipei has 11 shops with revenue of 60 or more; Taichung has 3.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="misleading-graphs" class="slide level2">
<h2>Misleading Graphs</h2>
<p>Graphs give a visual representation that enables readers to analyze and interpret data more easily than they could simply by looking at numbers. However, <strong>inappropriately drawn graphs can misrepresent the data</strong> and lead the reader to false conclusions.</p>
<p>A car manufacturer’s ad stated that 98% of the vehicles it had sold in the past 10 years were still on the road, and showed a bar graph whose vertical axis ran only from <strong>95% to 100%</strong>. Redrawn on a scale from <strong>0 to 100%</strong>, there is hardly a noticeable difference between the manufacturer and its competitors.</p>
</section>
<section id="misleading-graphs-in-r" class="slide level2">
<h2>Misleading Graphs in R</h2>
<p><strong>Prepare data</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb74"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href=""></a>vehicles_on_road <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb74-2"><a href=""></a>  <span class="at">maker   =</span> <span class="fu">c</span>(<span class="st">"Manufacturer"</span>, <span class="st">"Competitor I"</span>, <span class="st">"Competitor II"</span>),</span>
<span id="cb74-3"><a href=""></a>  <span class="at">percent =</span> <span class="fu">c</span>(<span class="dv">98</span>, <span class="dv">97</span>, <span class="fl">96.5</span>)</span>
<span id="cb74-4"><a href=""></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="misleading-graphs-in-r-1" class="slide level2">
<h2>Misleading Graphs in R</h2>
<p><strong>Draw figure — the truncated scale (95% to 100%)</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb75"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href=""></a><span class="fu">ggplot</span>(vehicles_on_road, <span class="fu">aes</span>(maker, percent)) <span class="sc">+</span></span>
<span id="cb75-2"><a href=""></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb75-3"><a href=""></a>  <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">95</span>, <span class="dv">100</span>)) <span class="sc">+</span></span>
<span id="cb75-4"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Vehicles on the Road (scale 95 to 100)"</span>,</span>
<span id="cb75-5"><a href=""></a>       <span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Percent of cars on road"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="ch2_files/figure-revealjs/s2-3-3-1.png" class="quarto-figure quarto-figure-center r-stretch" style="width:46.0%"></section>
<section id="misleading-graphs-in-r-2" class="slide level2">
<h2>Misleading Graphs in R</h2>
<p><strong>Output figure — the full scale (0% to 100%)</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb76"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href=""></a><span class="fu">ggplot</span>(vehicles_on_road, <span class="fu">aes</span>(maker, percent)) <span class="sc">+</span></span>
<span id="cb76-2"><a href=""></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb76-3"><a href=""></a>  <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">100</span>)) <span class="sc">+</span></span>
<span id="cb76-4"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Vehicles on the Road (scale 0 to 100)"</span>,</span>
<span id="cb76-5"><a href=""></a>       <span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Percent of cars on road"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="ch2_files/figure-revealjs/s2-3-4-1.png" class="quarto-figure quarto-figure-center r-stretch" style="width:46.0%"><p>Both graphs plot <strong>exactly the same numbers</strong>. It is not wrong to truncate an axis — many times it is necessary — but the reader should be aware of it and interpret the graph accordingly.</p>
</section>
<section id="stretching-the-scale" class="slide level2">
<h2>Stretching the Scale</h2>
<p>The average number of parcels a courier at a distribution hub delivers per hour is shown for six years; it rose from 12.4 to 13.5 parcels per hour. <em>(hypothetical data)</em></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Year</th>
<th>2019</th>
<th>2020</th>
<th>2021</th>
<th>2022</th>
<th>2023</th>
<th>2024</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Parcels per hour</td>
<td>12.4</td>
<td>12.7</td>
<td>12.9</td>
<td>13.0</td>
<td>13.2</td>
<td>13.5</td>
</tr>
</tbody>
</table>
<p>On a <span class="math inline">y</span> axis running from 0 to 20 the increase looks slight; <strong>spreading out the scale</strong> so that it runs only from 12 to 14 in steps of 0.2 makes the same data values look like a much larger increase.</p>
</section>
<section id="two-dimensional-pictures" class="slide level2">
<h2>Two-Dimensional Pictures</h2>
<p>Another misleading technique <strong>exaggerates a one-dimensional increase by showing it in two dimensions</strong>.</p>
<p>Suppose a logistics firm’s daily parcel volume grew from <strong>20,000 to 60,000</strong> — three times as large <em>(hypothetical data)</em>. Drawn as two bars, the change is compared by the <strong>heights</strong> of the bars, which is one dimension, so the taller bar is three times the shorter one. Drawn as two circles whose diameters are in the same 1-to-3 ratio, the difference looks far larger, because the eye compares the <strong>areas</strong> of the circles, and the larger area is nine times the smaller one.</p>
</section>
<section id="misleading-graphs-1" class="slide level2">
<h2>Misleading Graphs</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Caution</strong></p>
</div>
<div class="callout-content">
<p>It is <strong>not wrong</strong> to truncate a scale or to represent data by two-dimensional pictures — but when these techniques are used, the reader should be <strong>cautious</strong> of the conclusions drawn from the graph. Before accepting a graph, check:</p>
<ul>
<li>Does the value axis <strong>start at zero</strong>, or has it been <strong>truncated</strong>?</li>
<li>Has the scale been <strong>stretched or compressed</strong> to exaggerate a change?</li>
<li>Are picture symbols scaled by <strong>area</strong> rather than by height?</li>
<li>Are <strong>labels or units omitted</strong> from the axes? Without numbers on the <span class="math inline">y</span> axis, only a crude ranking can be obtained and there is no way to decide the actual magnitude of the differences.</li>
<li>Is a <strong>source</strong> given for the information? A source lets you check the reliability of the organization presenting the data.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="summary" class="slide level2">
<h2>Summary</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Graph type</th>
<th>Best used for</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Histogram</td>
<td>Grouped frequencies; contiguous vertical bars</td>
</tr>
<tr class="even">
<td>Frequency polygon</td>
<td>Frequencies at midpoints, joined by lines</td>
</tr>
<tr class="odd">
<td>Ogive</td>
<td>Cumulative frequencies at upper boundaries</td>
</tr>
<tr class="even">
<td>Bar graph</td>
<td>Categorical data; horizontal or vertical bars</td>
</tr>
<tr class="odd">
<td>Pareto chart</td>
<td>Categorical data, bars highest to lowest</td>
</tr>
<tr class="even">
<td>Time series graph</td>
<td>Data occurring over a period of time</td>
</tr>
<tr class="odd">
<td>Pie graph</td>
<td>The relationship of the parts to the whole</td>
</tr>
<tr class="even">
<td>Dotplot</td>
<td>Each value as a dot; spotting extreme values</td>
</tr>
<tr class="odd">
<td>Stem and leaf plot</td>
<td>Keeps the actual values and shows the shape</td>
</tr>
</tbody>
</table>
</section>
<section id="important-terms" class="slide level2">
<h2>Important Terms</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Chapter 2 Vocabulary</strong></p>
</div>
<div class="callout-content">
<p>bar graph · categorical frequency distribution · class · class boundaries · class midpoint · class width · compound bar graphs · cumulative frequency · cumulative frequency distribution · dotplot · frequency · frequency distribution · frequency polygon · grouped frequency distribution · histogram · lower class limit · ogive · open-ended distribution · Pareto chart · pie graph · raw data · relative frequency graph · stem and leaf plot · time series graph · ungrouped frequency distribution · upper class limit</p>
</div>
</div>
</div>
</section>
<section id="key-formulas" class="slide level2">
<h2>Key Formulas</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important Formulas</strong></p>
</div>
<div class="callout-content">
<p>Percentage of values in each class: <span class="math inline">\displaystyle \% = \frac{f}{n} \cdot 100</span></p>
<p>Range: <span class="math inline">R = \text{highest value} - \text{lowest value}</span></p>
<p>Class width: <span class="math inline">\text{Class width} = \text{upper boundary} - \text{lower boundary}</span></p>
<p>Class midpoint: <span class="math display">X_m = \frac{\text{lower boundary} + \text{upper boundary}}{2} \quad\text{or}\quad X_m = \frac{\text{lower limit} + \text{upper limit}}{2}</span></p>
<p>Degrees for each section of a pie graph: <span class="math inline">\displaystyle \text{Degrees} = \frac{f}{n} \cdot 360^\circ</span></p>
</div>
</div>
</div>
</section>
<section id="key-takeaways" class="slide level2">
<h2>Key Takeaways</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Key point</strong></p>
</div>
<div class="callout-content">
<ul>
<li><strong>Raw data</strong> — values collected in original form; little can be learned until they are organized</li>
<li><strong>Frequency distribution</strong> — the organization of raw data in table form, using <strong>classes</strong> and <strong>frequencies</strong></li>
<li><strong>Three types</strong> — categorical (specific categories), grouped (large range), ungrouped (small range)</li>
<li><strong>Class limits / boundaries / width / midpoint</strong> — limits carry the data’s decimal place; boundaries carry one more and end in 5; width is the difference between consecutive lower limits</li>
<li><strong>Six rules</strong> — 5 to 20 classes, preferably odd width, mutually exclusive, continuous, exhaustive, equal in width (except open-ended)</li>
<li><strong>Cumulative frequency distribution</strong> — the number of data values less than or equal to a specific value</li>
<li><strong>Histogram / frequency polygon / ogive</strong> — boundaries, midpoints, and cumulative frequencies respectively</li>
<li><strong>Relative frequency graphs</strong> — proportions instead of counts; needed when comparing data sets of different sizes</li>
<li><strong>Distribution shapes</strong> — bell-shaped, uniform, J-shaped, reverse J-shaped, right-skewed, left-skewed, bimodal, U-shaped</li>
<li><strong>Other graphs</strong> — bar graph, Pareto chart, time series graph, pie graph, dotplot, stem and leaf plot</li>
<li><strong>Misleading graphs</strong> — truncated or stretched scales, two-dimensional pictures, and omitted labels distort the message</li>
</ul>
</div>
</div>
</div>
</section>
<section id="acknowledgement" class="slide level2">
<h2>Acknowledgement</h2>
<ul>
<li><p><strong>Copyright notice.</strong> These teaching materials follow the organization and terminology of <strong>Bluman, A. G. (2023). Elementary statistics: A step by step approach (11th ed.). McGraw Hill</strong>. All rights in the original work are reserved by its authors and publishers.</p></li>
<li><p><strong>Original examples.</strong> Every worked example, data set, and R script in these slides was written for this course. The data are hypothetical unless stated otherwise.</p></li>
<li><p><strong>Non-commercial use only.</strong> These materials are strictly intended for educational purposes and must not be used for commercial gain or profit.</p></li>
<li><p><strong>Proper attribution.</strong> Any reproduction, distribution, or use of these materials must provide proper attribution to the original source.</p></li>
</ul>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="logo.svg" class="slide-logo"></p>
<div class="footer footer-default">
<p>Elementary Statistics: A Step by Step Approach</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="ch2_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="ch2_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="ch2_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="ch2_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="ch2_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="ch2_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="ch2_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="ch2_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="ch2_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":false,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true,"hideMissingTitles":true,"titleSelector":"h1"},
'smaller': true,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    <script>
    Reveal.on('ready', function() {
      var title = Reveal.getSlides()[0];
      if (title) {
        title.insertAdjacentHTML('beforeend',
          '<p style="font-size:0.5em; margin-top:1.5em;">' +
          '<a href="ch2-zh.html"  style="color:#555;">[中文版由此去]</a>' +
          '</p>');
      }
    });
    </script>
    

</body></html>