<!DOCTYPE html>
<html lang="en"><head>
<script src="ch10_files/libs/clipboard/clipboard.min.js"></script>
<script src="ch10_files/libs/quarto-html/tabby.min.js"></script>
<script src="ch10_files/libs/quarto-html/popper.min.js"></script>
<script src="ch10_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="ch10_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="ch10_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="ch10_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.38">

  <meta name="author" content="Yu-You Liou">
  <meta name="dcterms.date" content="2026-09-20">
  <title>Statistics</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="ch10_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="ch10_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="ch10_files/libs/revealjs/dist/theme/quarto-2abc1c5b7b5c7eecd6137558e106e4c3.css">
  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">
  <link href="ch10_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="ch10_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="ch10_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="ch10_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-notes="" class="quarto-title-block center">
  <h1 class="title">Statistics</h1>
  <p class="subtitle">Chapter 10: Correlation and Regression</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Yu-You Liou 
</div>
        <p class="quarto-title-affiliation">
            Shih Chien University
          </p>
    </div>
</div>

  <p class="date">2026-09-20</p>
</section>
<section id="overview" class="slide level2">
<h2>Overview</h2>
<p>Chapter 10 is about <strong>correlation and regression</strong> — whether two variables are linearly related, how strong the relation is, and how to predict.</p>
<table class="caption-top">
<colgroup>
<col style="width: 52%">
<col style="width: 47%">
</colgroup>
<thead>
<tr class="header">
<th>Section</th>
<th>Topics</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>10-1</td>
<td>Scatter plots; the correlation coefficient <span class="math inline">r</span> and its properties; testing <span class="math inline">H_0: \rho = 0</span>; correlation vs.&nbsp;causation</td>
</tr>
<tr class="even">
<td>10-2</td>
<td>Regression line <span class="math inline">y' = a + bx</span>; least squares and residuals; marginal change; extrapolation; influential points</td>
</tr>
</tbody>
</table>
</section>
<section id="overview-continued" class="slide level2">
<h2>Overview (continued)</h2>
<table class="caption-top">
<colgroup>
<col style="width: 52%">
<col style="width: 47%">
</colgroup>
<thead>
<tr class="header">
<th>Section</th>
<th>Topics</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>10-3</td>
<td>Types of variation; residual plots; <span class="math inline">r^2</span>; <span class="math inline">s_{est}</span>; prediction intervals</td>
</tr>
<tr class="even">
<td>10-4</td>
<td>Multiple regression; partial coefficients; <span class="math inline">R</span>, the <span class="math inline">F</span> test, adjusted <span class="math inline">R^2</span></td>
</tr>
</tbody>
</table>
</section>
<section id="chapter-objectives" class="slide level2">
<h2>Chapter Objectives</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>After completing this chapter, you should be able to</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>Draw a scatter plot for a set of ordered pairs.</li>
<li>Compute the correlation coefficient.</li>
<li>Test the hypothesis <span class="math inline">H_0: \rho = 0</span>.</li>
<li>Compute the equation of the regression line.</li>
<li>Compute the coefficient of determination.</li>
<li>Compute the standard error of the estimate.</li>
<li>Find a prediction interval.</li>
<li>Be familiar with the concept of multiple regression.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="four-questions-this-chapter-answers" class="slide level2">
<h2>Four Questions This Chapter Answers</h2>
<p>Correlation and regression analysis are part of <strong>inferential statistics</strong>: they decide whether a relationship exists between two or more numerical variables and describe it.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>The Purpose of the Chapter</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>Are two or more variables linearly related?</li>
<li>If so, what is the strength of the relationship?</li>
<li>What type of relationship exists?</li>
<li>What kind of predictions can be made from the relationship?</li>
</ol>
</div>
</div>
</div>
</section>
<section>
<section id="section-10-1-scatter-plots-and-correlation" class="title-slide slide level1 center" data-background-color="#2c4a6e">
<h1>Section 10-1: Scatter Plots and Correlation</h1>

</section>
<section id="independent-and-dependent-variables" class="slide level2">
<h2>Independent and Dependent Variables</h2>
<p>In simple correlation and regression studies, the researcher collects data on <strong>two numerical (quantitative) variables</strong> to see whether a relationship exists between them.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Independent and Dependent Variables</strong></p>
</div>
<div class="callout-content">
<p>The <strong>independent variable</strong> is the variable in regression that can be controlled or manipulated; it is designated <span class="math inline">x</span> and is also called the <strong>explanatory variable</strong>.</p>
<p>The <strong>dependent variable</strong> is the variable in regression that cannot be controlled or manipulated; it is designated <span class="math inline">y</span> and is also called the <strong>response variable</strong>.</p>
</div>
</div>
</div>
<p>The choice of <span class="math inline">x</span> and <span class="math inline">y</span> is not always clear-cut. Age can reasonably be taken to affect blood pressure, but for the attitudes of husbands and wives on the same issue the researcher may assign the roles arbitrarily.</p>
</section>
<section id="scatter-plots" class="slide level2">
<h2>Scatter Plots</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Scatter Plot</strong></p>
</div>
<div class="callout-content">
<p>A <strong>scatter plot</strong> is a graph of the ordered pairs <span class="math inline">(x, y)</span> of numbers consisting of the independent variable <span class="math inline">x</span> and the dependent variable <span class="math inline">y</span>.</p>
</div>
</div>
</div>
<p>The independent variable <span class="math inline">x</span> is plotted on the horizontal axis and the dependent variable <span class="math inline">y</span> on the vertical axis. The scales of the two variables may differ; the coordinates of the axes are set by the smallest and largest data values.</p>
</section>
<section id="types-of-relationships" class="slide level2">
<h2>Types of Relationships</h2>
<p>Researchers look for patterns in a scatter plot (Figure 10-1).</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Four Patterns</strong></p>
</div>
<div class="callout-content">
<ul>
<li><strong>Positive linear relationship</strong> — as <span class="math inline">x</span> increases, <span class="math inline">y</span> increases; the points form roughly a straight line rising from left to right.</li>
<li><strong>Negative linear relationship</strong> — as <span class="math inline">x</span> increases, <span class="math inline">y</span> decreases; the points form roughly a straight line falling from left to right.</li>
<li><strong>Curvilinear (nonlinear) relationship</strong> — the points follow a curve.</li>
<li><strong>No relationship</strong> — no line or curve can be seen in the points.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="procedure-table-drawing-a-scatter-plot" class="slide level2">
<h2>Procedure Table: Drawing a Scatter Plot</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Drawing a Scatter Plot</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1</strong> Draw and label the <span class="math inline">x</span> and <span class="math inline">y</span> axes.</p>
<p><strong>Step 2</strong> Plot each point on the graph.</p>
<p><strong>Step 3</strong> Determine the type of relationship (if any) that exists for the variables.</p>
</div>
</div>
</div>
</section>
<section id="example-10-1" class="slide level2">
<h2>Example 10-1</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Advertising Spend and Orders</strong></p>
</div>
<div class="callout-content">
<p>A cross-border e-commerce team records, for six of its product lines, last month’s online advertising spend (in thousands of NT dollars) and the number of orders received. Construct a scatter plot for the data.</p>
<pre><code>Ad spend, x     20     30     40     50     60     70
Orders, y      200    180    235    265    270    350</code></pre>
<p><em>(hypothetical data)</em></p>
<p>Back to <a href="#/example-10-4">Example 10-4</a></p>
</div>
</div>
</div>
</section>
<section id="example-10-1-1" class="slide level2">
<h2>Example 10-1</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1 — draw and label the axes; Step 2 — plot each point</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href=""></a>ad_spend <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">20</span>, <span class="dv">30</span>, <span class="dv">40</span>, <span class="dv">50</span>, <span class="dv">60</span>, <span class="dv">70</span>)</span>
<span id="cb2-2"><a href=""></a>orders   <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">200</span>, <span class="dv">180</span>, <span class="dv">235</span>, <span class="dv">265</span>, <span class="dv">270</span>, <span class="dv">350</span>)</span>
<span id="cb2-3"><a href=""></a></span>
<span id="cb2-4"><a href=""></a>scatter_ads <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="fu">data.frame</span>(ad_spend, orders),</span>
<span id="cb2-5"><a href=""></a>                      <span class="fu">aes</span>(<span class="at">x =</span> ad_spend, <span class="at">y =</span> orders)) <span class="sc">+</span></span>
<span id="cb2-6"><a href=""></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb2-7"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Advertising Spend and Orders"</span>,</span>
<span id="cb2-8"><a href=""></a>       <span class="at">x =</span> <span class="st">"Ad spend (thousand NT dollars)"</span>, <span class="at">y =</span> <span class="st">"Orders"</span>) <span class="sc">+</span></span>
<span id="cb2-9"><a href=""></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</div>
</section>
<section id="example-10-1-2" class="slide level2">
<h2>Example 10-1</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Output figure (Figure 10-2)</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href=""></a>scatter_ads</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="ch10_files/figure-revealjs/e10-1-2-1.png" class="quarto-figure quarto-figure-center" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p><strong>Step 3</strong> It looks like there is a <strong>positive relationship</strong> between advertising spend and the number of orders.</p>
</div>
</div>
</div>
</section>
<section id="example-10-2" class="slide level2">
<h2>Example 10-2</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Days Late and Customer Rating</strong></p>
</div>
<div class="callout-content">
<p>A freight forwarder in Taichung reviews seven export orders that reached the buyer after the promised date. For each order it records how many days late the shipment was and the satisfaction rating (out of 100) the customer gave afterwards. Construct a scatter plot for the data.</p>
<pre><code>Order                     A      B      C      D      E      F      G
Days late, x              1      2      3      4      5      6      7
Customer rating, y       94     84     86     80     78     68     70</code></pre>
<p><em>(hypothetical data)</em></p>
<p>Back to <a href="#/example-10-5">Example 10-5</a></p>
</div>
</div>
</div>
</section>
<section id="example-10-2-1" class="slide level2">
<h2>Example 10-2</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1 — draw and label the axes; Step 2 — plot each point</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href=""></a>days_late <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">7</span>)</span>
<span id="cb5-2"><a href=""></a>rating    <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">94</span>, <span class="dv">84</span>, <span class="dv">86</span>, <span class="dv">80</span>, <span class="dv">78</span>, <span class="dv">68</span>, <span class="dv">70</span>)</span>
<span id="cb5-3"><a href=""></a></span>
<span id="cb5-4"><a href=""></a>scatter_rating <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="fu">data.frame</span>(days_late, rating),</span>
<span id="cb5-5"><a href=""></a>                         <span class="fu">aes</span>(<span class="at">x =</span> days_late, <span class="at">y =</span> rating)) <span class="sc">+</span></span>
<span id="cb5-6"><a href=""></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">"tomato"</span>) <span class="sc">+</span></span>
<span id="cb5-7"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Days Late and Customer Rating"</span>,</span>
<span id="cb5-8"><a href=""></a>       <span class="at">x =</span> <span class="st">"Days late"</span>, <span class="at">y =</span> <span class="st">"Customer rating"</span>) <span class="sc">+</span></span>
<span id="cb5-9"><a href=""></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</div>
</section>
<section id="example-10-2-2" class="slide level2">
<h2>Example 10-2</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Output figure (Figure 10-3)</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href=""></a>scatter_rating</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="ch10_files/figure-revealjs/e10-2-2-1.png" class="quarto-figure quarto-figure-center" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p><strong>Step 3</strong> It looks as if a <strong>negative linear relationship</strong> exists between the number of days a shipment is late and the rating the customer gives.</p>
</div>
</div>
</div>
</section>
<section id="example-10-3" class="slide level2">
<h2>Example 10-3</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Years in Operation and Order Growth</strong></p>
</div>
<div class="callout-content">
<p>A trade association wishes to see whether there is a relationship between how long a small trading company has been in operation and how fast its orders grew last year. Seven member companies in Kaohsiung are selected. Construct a scatter plot for the data.</p>
<pre><code>Company                      A      B      C      D      E      F      G
Years in operation, x        2      4      6      8     10     12     14
Order growth, y (%)          9     12      7      8     10      9     11</code></pre>
<p><em>(hypothetical data)</em></p>
<p>Back to <a href="#/example-10-6">Example 10-6</a></p>
</div>
</div>
</div>
</section>
<section id="example-10-3-1" class="slide level2">
<h2>Example 10-3</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1 — draw and label the axes; Step 2 — plot each point</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href=""></a>years_operating <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">6</span>, <span class="dv">8</span>, <span class="dv">10</span>, <span class="dv">12</span>, <span class="dv">14</span>)</span>
<span id="cb8-2"><a href=""></a>growth_rate     <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">9</span>, <span class="dv">12</span>, <span class="dv">7</span>, <span class="dv">8</span>, <span class="dv">10</span>, <span class="dv">9</span>, <span class="dv">11</span>)</span>
<span id="cb8-3"><a href=""></a></span>
<span id="cb8-4"><a href=""></a>scatter_growth <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="fu">data.frame</span>(years_operating, growth_rate),</span>
<span id="cb8-5"><a href=""></a>                         <span class="fu">aes</span>(<span class="at">x =</span> years_operating, <span class="at">y =</span> growth_rate)) <span class="sc">+</span></span>
<span id="cb8-6"><a href=""></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">"purple"</span>) <span class="sc">+</span></span>
<span id="cb8-7"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Years in Operation and Order Growth"</span>,</span>
<span id="cb8-8"><a href=""></a>       <span class="at">x =</span> <span class="st">"Years in operation"</span>, <span class="at">y =</span> <span class="st">"Order growth (%)"</span>) <span class="sc">+</span></span>
<span id="cb8-9"><a href=""></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</div>
</section>
<section id="example-10-3-2" class="slide level2">
<h2>Example 10-3</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Output figure (Figure 10-4)</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href=""></a>scatter_growth</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="ch10_files/figure-revealjs/e10-3-2-1.png" class="quarto-figure quarto-figure-center" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p><strong>Step 3</strong> There is <strong>no strong positive or negative linear relationship</strong> between the number of years a company has been in operation and its order growth.</p>
</div>
</div>
</div>
</section>
<section id="correlation" class="slide level2">
<h2>Correlation</h2>
<p>Statisticians use a measure called the <strong>correlation coefficient</strong> to determine the strength of the linear relationship between two variables. There are several types of correlation coefficients.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Population and Sample Correlation Coefficients</strong></p>
</div>
<div class="callout-content">
<p>The <strong>population correlation coefficient</strong>, denoted by the Greek letter <span class="math inline">\rho</span>, is the correlation computed by using all possible pairs of data values <span class="math inline">(x, y)</span> taken from a population.</p>
<p>The <strong>linear correlation coefficient</strong> computed from the sample data measures the strength and direction of a linear relationship between two quantitative variables. The symbol for the sample correlation coefficient is <span class="math inline">r</span>.</p>
</div>
</div>
</div>
<p>The correlation coefficient of this section is the <strong>Pearson product moment correlation coefficient (PPMC)</strong>, named after Karl Pearson.</p>
</section>
<section id="range-of-values-for-r" class="slide level2">
<h2>Range of Values for <span class="math inline">r</span></h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Interpreting the Value of <span class="math inline">r</span> (Figure 10-5)</strong></p>
</div>
<div class="callout-content">
<p>The range of the linear correlation coefficient is from <span class="math inline">-1</span> to <span class="math inline">+1</span>.</p>
<ul>
<li><span class="math inline">r</span> close to <span class="math inline">+1</span>: a <strong>strong positive</strong> linear relationship.</li>
<li><span class="math inline">r</span> close to <span class="math inline">-1</span>: a <strong>strong negative</strong> linear relationship.</li>
<li><span class="math inline">r</span> close to <span class="math inline">0</span>: <strong>no linear relationship</strong> or only a weak one.</li>
</ul>
<p>A value of <span class="math inline">r</span> equal to or close to <span class="math inline">0</span> implies only that there is <strong>no linear</strong> relationship; the data may still be related in some other, nonlinear way.</p>
</div>
</div>
</div>
</section>
<section id="properties-of-the-linear-correlation-coefficient" class="slide level2">
<h2>Properties of the Linear Correlation Coefficient</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Five Properties</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>The correlation coefficient is a <strong>unitless</strong> measure.</li>
<li>The value of <span class="math inline">r</span> will always be between <span class="math inline">-1</span> and <span class="math inline">+1</span> inclusively, that is, <span class="math inline">-1 \leq r \leq 1</span>.</li>
<li>If the values of <span class="math inline">x</span> and <span class="math inline">y</span> are <strong>interchanged</strong>, the value of <span class="math inline">r</span> will be unchanged.</li>
<li>If the values of <span class="math inline">x</span> and/or <span class="math inline">y</span> are converted to a <strong>different scale</strong>, the value of <span class="math inline">r</span> will be unchanged.</li>
<li>The value of <span class="math inline">r</span> is <strong>sensitive to outliers</strong> and can change dramatically if they are present in the data.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="assumptions-for-the-correlation-coefficient" class="slide level2">
<h2>Assumptions for the Correlation Coefficient</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Three Assumptions</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>The sample is a <strong>random sample</strong>.</li>
<li>The data pairs fall <strong>approximately on a straight line</strong> and are measured at the <strong>interval or ratio</strong> level.</li>
<li>The variables have a <strong>bivariate normal distribution</strong>: given any specific value of <span class="math inline">x</span>, the <span class="math inline">y</span> values are normally distributed; and given any specific value of <span class="math inline">y</span>, the <span class="math inline">x</span> values are normally distributed.</li>
</ol>
</div>
</div>
</div>
<p>In this book the assumptions are assumed to be met in the exercises; in other situations you must check them before proceeding.</p>
</section>
<section id="formula-for-the-linear-correlation-coefficient" class="slide level2">
<h2>Formula for the Linear Correlation Coefficient</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Formula and Rounding Rule</strong></p>
</div>
<div class="callout-content">
<p><span class="math display">r = \frac{n(\sum xy) - (\sum x)(\sum y)}{\sqrt{[n(\sum x^2) - (\sum x)^2][n(\sum y^2) - (\sum y)^2]}}</span></p>
<p>where <span class="math inline">n</span> is the number of data pairs.</p>
<p><strong>Rounding Rule for the Correlation Coefficient.</strong> Round the value of <span class="math inline">r</span> to <strong>three decimal places</strong>.</p>
</div>
</div>
</div>
</section>
<section id="procedure-table-finding-the-value-of-r" class="slide level2">
<h2>Procedure Table: Finding the Value of <span class="math inline">r</span></h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Finding the Value of the Linear Correlation Coefficient</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1</strong> Make a table with columns <span class="math inline">x</span>, <span class="math inline">y</span>, <span class="math inline">xy</span>, <span class="math inline">x^2</span>, <span class="math inline">y^2</span>.</p>
<p><strong>Step 2</strong> Place the values of <span class="math inline">x</span> and <span class="math inline">y</span> in the first two columns. Multiply each <span class="math inline">x</span> value by the corresponding <span class="math inline">y</span> value and place the products in the <span class="math inline">xy</span> column. Square each <span class="math inline">x</span> value and each <span class="math inline">y</span> value and place them in the <span class="math inline">x^2</span> and <span class="math inline">y^2</span> columns. Find the sum of each column.</p>
<p><strong>Step 3</strong> Substitute in the formula and find the value for <span class="math inline">r</span>.</p>
</div>
</div>
</div>
</section>
<section id="example-10-4" class="slide level2">
<h2>Example 10-4</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Advertising Spend and Orders</strong></p>
</div>
<div class="callout-content">
<p>Compute the linear correlation coefficient for the data in <a href="#/example-10-1">Example 10-1</a>.</p>
<p>Back to <a href="#/example-10-9">Example 10-9</a></p>
</div>
</div>
</div>
</section>
<section id="example-10-4-1" class="slide level2">
<h2>Example 10-4</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Steps 1 and 2 — make the table and sum each column</strong></p>
<table class="caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Ad spend, <span class="math inline">x</span></th>
<th>Orders, <span class="math inline">y</span></th>
<th><span class="math inline">xy</span></th>
<th><span class="math inline">x^2</span></th>
<th><span class="math inline">y^2</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>20</td>
<td>200</td>
<td>4,000</td>
<td>400</td>
<td>40,000</td>
</tr>
<tr class="even">
<td>30</td>
<td>180</td>
<td>5,400</td>
<td>900</td>
<td>32,400</td>
</tr>
<tr class="odd">
<td>40</td>
<td>235</td>
<td>9,400</td>
<td>1,600</td>
<td>55,225</td>
</tr>
<tr class="even">
<td>50</td>
<td>265</td>
<td>13,250</td>
<td>2,500</td>
<td>70,225</td>
</tr>
<tr class="odd">
<td>60</td>
<td>270</td>
<td>16,200</td>
<td>3,600</td>
<td>72,900</td>
</tr>
<tr class="even">
<td>70</td>
<td>350</td>
<td>24,500</td>
<td>4,900</td>
<td>122,500</td>
</tr>
<tr class="odd">
<td><span class="math inline">\sum x = 270</span></td>
<td><span class="math inline">\sum y = 1500</span></td>
<td><span class="math inline">\sum xy = 72{,}750</span></td>
<td><span class="math inline">\sum x^2 = 13{,}900</span></td>
<td><span class="math inline">\sum y^2 = 393{,}250</span></td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="example-10-4-2" class="slide level2">
<h2>Example 10-4</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 3 — substitute in the formula and solve for <span class="math inline">r</span></strong></p>
<p><span class="math display">r = \frac{6(72{,}750) - (270)(1500)}{\sqrt{[6(13{,}900) - 270^2][6(393{,}250) - 1500^2]}} = \frac{31{,}500}{33{,}907.96} = 0.929</span></p>
<p>The value of <span class="math inline">r</span> suggests a <strong>strong positive linear relationship</strong> between advertising spend and the number of orders: the more a product line spends on advertising, the more orders it takes.</p>
</div>
</div>
</div>
</section>
<section id="example-10-4-3" class="slide level2">
<h2>Example 10-4</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Compute in R</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href=""></a><span class="fu">round</span>(<span class="fu">cor</span>(ad_spend, orders), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.929</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="example-10-5" class="slide level2">
<h2>Example 10-5</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Days Late and Customer Rating</strong></p>
</div>
<div class="callout-content">
<p>Compute the value of the linear correlation coefficient for the data on the seven late export orders given in <a href="#/example-10-2">Example 10-2</a>.</p>
<p>Back to <a href="#/example-10-10">Example 10-10</a></p>
</div>
</div>
</div>
</section>
<section id="example-10-5-1" class="slide level2">
<h2>Example 10-5</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Steps 1 and 2 — make the table and sum each column</strong></p>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Order</th>
<th>Days late, <span class="math inline">x</span></th>
<th>Rating, <span class="math inline">y</span></th>
<th><span class="math inline">xy</span></th>
<th><span class="math inline">x^2</span></th>
<th><span class="math inline">y^2</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td>1</td>
<td>94</td>
<td>94</td>
<td>1</td>
<td>8,836</td>
</tr>
<tr class="even">
<td>B</td>
<td>2</td>
<td>84</td>
<td>168</td>
<td>4</td>
<td>7,056</td>
</tr>
<tr class="odd">
<td>C</td>
<td>3</td>
<td>86</td>
<td>258</td>
<td>9</td>
<td>7,396</td>
</tr>
<tr class="even">
<td>D</td>
<td>4</td>
<td>80</td>
<td>320</td>
<td>16</td>
<td>6,400</td>
</tr>
<tr class="odd">
<td>E</td>
<td>5</td>
<td>78</td>
<td>390</td>
<td>25</td>
<td>6,084</td>
</tr>
<tr class="even">
<td>F</td>
<td>6</td>
<td>68</td>
<td>408</td>
<td>36</td>
<td>4,624</td>
</tr>
<tr class="odd">
<td>G</td>
<td>7</td>
<td>70</td>
<td>490</td>
<td>49</td>
<td>4,900</td>
</tr>
<tr class="even">
<td></td>
<td><span class="math inline">\sum x = 28</span></td>
<td><span class="math inline">\sum y = 560</span></td>
<td><span class="math inline">\sum xy = 2128</span></td>
<td><span class="math inline">\sum x^2 = 140</span></td>
<td><span class="math inline">\sum y^2 = 45{,}296</span></td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="example-10-5-2" class="slide level2">
<h2>Example 10-5</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 3 — substitute in the formula and solve for <span class="math inline">r</span></strong></p>
<p><span class="math display">r = \frac{7(2128) - (28)(560)}{\sqrt{[7(140) - 28^2][7(45{,}296) - 560^2]}} = \frac{-784}{824.93} = -0.950</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href=""></a><span class="fu">round</span>(<span class="fu">cor</span>(days_late, rating), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.95</code></pre>
</div>
</div>
<p>The value of <span class="math inline">r</span> suggests a <strong>strong negative linear relationship</strong>: the later a shipment arrives, the lower the rating the customer gives.</p>
</div>
</div>
</div>
</section>
<section id="example-10-6" class="slide level2">
<h2>Example 10-6</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Years in Operation and Order Growth</strong></p>
</div>
<div class="callout-content">
<p>Compute the value of the correlation coefficient for the data given in <a href="#/example-10-3">Example 10-3</a> for the years in operation and the order growth of the seven trading companies.</p>
<p>Back to <a href="#/example-10-8">Example 10-8</a></p>
</div>
</div>
</div>
</section>
<section id="example-10-6-1" class="slide level2">
<h2>Example 10-6</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Steps 1 and 2 — make the table and sum each column</strong></p>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Company</th>
<th>Years, <span class="math inline">x</span></th>
<th>Growth, <span class="math inline">y</span></th>
<th><span class="math inline">xy</span></th>
<th><span class="math inline">x^2</span></th>
<th><span class="math inline">y^2</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td>2</td>
<td>9</td>
<td>18</td>
<td>4</td>
<td>81</td>
</tr>
<tr class="even">
<td>B</td>
<td>4</td>
<td>12</td>
<td>48</td>
<td>16</td>
<td>144</td>
</tr>
<tr class="odd">
<td>C</td>
<td>6</td>
<td>7</td>
<td>42</td>
<td>36</td>
<td>49</td>
</tr>
<tr class="even">
<td>D</td>
<td>8</td>
<td>8</td>
<td>64</td>
<td>64</td>
<td>64</td>
</tr>
<tr class="odd">
<td>E</td>
<td>10</td>
<td>10</td>
<td>100</td>
<td>100</td>
<td>100</td>
</tr>
<tr class="even">
<td>F</td>
<td>12</td>
<td>9</td>
<td>108</td>
<td>144</td>
<td>81</td>
</tr>
<tr class="odd">
<td>G</td>
<td>14</td>
<td>11</td>
<td>154</td>
<td>196</td>
<td>121</td>
</tr>
<tr class="even">
<td></td>
<td><span class="math inline">\sum x = 56</span></td>
<td><span class="math inline">\sum y = 66</span></td>
<td><span class="math inline">\sum xy = 534</span></td>
<td><span class="math inline">\sum x^2 = 560</span></td>
<td><span class="math inline">\sum y^2 = 640</span></td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="example-10-6-2" class="slide level2">
<h2>Example 10-6</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 3 — substitute in the formula and solve for <span class="math inline">r</span></strong></p>
<p><span class="math display">r = \frac{7(534) - (56)(66)}{\sqrt{[7(560) - 56^2][7(640) - 66^2]}} = \frac{42}{311.79} = 0.135</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href=""></a><span class="fu">round</span>(<span class="fu">cor</span>(years_operating, growth_rate), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.135</code></pre>
</div>
</div>
<p>The value of <span class="math inline">r</span> indicates a <strong>very weak positive linear relationship</strong> between the years a company has been in operation and its order growth.</p>
</div>
</div>
</div>
</section>
<section id="the-significance-of-the-correlation-coefficient" class="slide level2">
<h2>The Significance of the Correlation Coefficient</h2>
<p>Since <span class="math inline">r</span> is computed from sample data, there are two possibilities when <span class="math inline">r</span> is not zero: either <span class="math inline">r</span> is high enough to conclude that a <strong>significant</strong> linear relationship exists, or the value of <span class="math inline">r</span> is <strong>due to chance</strong>.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Traditional Method — Five Steps</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1</strong> State the hypotheses.</p>
<p><strong>Step 2</strong> Find the critical values.</p>
<p><strong>Step 3</strong> Compute the test statistic.</p>
<p><strong>Step 4</strong> Make the decision.</p>
<p><strong>Step 5</strong> Summarize the results.</p>
</div>
</div>
</div>
</section>
<section id="assumptions-for-testing-the-significance-of-r" class="slide level2">
<h2>Assumptions for Testing the Significance of <span class="math inline">r</span></h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Four Assumptions</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>The data are <strong>quantitative</strong> and are obtained from a <strong>simple random sample</strong>.</li>
<li>The scatter plot shows that the data are <strong>approximately linearly related</strong>.</li>
<li>There are <strong>no outliers</strong> in the data.</li>
<li>The variables <span class="math inline">x</span> and <span class="math inline">y</span> must come from <strong>normally distributed populations</strong>.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="the-hypotheses" class="slide level2">
<h2>The Hypotheses</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong><span class="math inline">H_0</span> and <span class="math inline">H_1</span></strong></p>
</div>
<div class="callout-content">
<p><span class="math display">H_0: \rho = 0 \qquad H_1: \rho \neq 0</span></p>
<p><span class="math inline">H_0</span> means that there is <strong>no correlation</strong> between the <span class="math inline">x</span> and <span class="math inline">y</span> variables in the population. <span class="math inline">H_1</span> means that there is a <strong>significant correlation</strong> between the variables in the population.</p>
<p>You do not have to identify the claim here, since the question will always be whether there is a significant linear relationship between the variables.</p>
</div>
</div>
</div>
<p>When <span class="math inline">H_0</span> is rejected, <span class="math inline">r</span> differs significantly from <span class="math inline">0</span>; when <span class="math inline">H_0</span> is not rejected, <span class="math inline">r</span> is probably due to chance.</p>
</section>
<section id="the-t-test-for-the-correlation-coefficient" class="slide level2">
<h2>The <span class="math inline">t</span> Test for the Correlation Coefficient</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Formula for the <span class="math inline">t</span> Test for the Correlation Coefficient</strong></p>
</div>
<div class="callout-content">
<p><span class="math display">t = r \sqrt{\frac{n-2}{1-r^2}}</span></p>
<p>with degrees of freedom equal to <span class="math inline">n - 2</span>, where <span class="math inline">n</span> is the number of ordered pairs <span class="math inline">(x, y)</span>.</p>
</div>
</div>
</div>
<p>The <strong>two-tailed</strong> critical values are used; they are found in <strong>Table A-5</strong>. Both variables <span class="math inline">x</span> and <span class="math inline">y</span> must come from normally distributed populations.</p>
</section>
<section id="example-10-7" class="slide level2">
<h2>Example 10-7</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Testing the Significance of <span class="math inline">r</span></strong></p>
</div>
<div class="callout-content">
<p>Test the significance of the correlation coefficient found in <a href="#/example-10-4">Example 10-4</a>. Use <span class="math inline">\alpha = 0.05</span> and <span class="math inline">r = 0.929</span>.</p>
</div>
</div>
</div>
</section>
<section id="example-10-7-1" class="slide level2">
<h2>Example 10-7</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1</strong> State the hypotheses: <span class="math inline">H_0: \rho = 0</span> and <span class="math inline">H_1: \rho \neq 0</span>.</p>
<p><strong>Step 2</strong> Find the critical values. Since <span class="math inline">\alpha = 0.05</span> and there are <span class="math inline">6 - 2 = 4</span> degrees of freedom, the critical values from Table A-5 are <span class="math inline">\pm 2.776</span> (Figure 10-7).</p>
<p><strong>Step 3</strong> Compute the test statistic.</p>
<p><span class="math display">t = r \sqrt{\frac{n-2}{1-r^2}} = 0.929\sqrt{\frac{6-2}{1-(0.929)^2}} = 5.02</span></p>
<p><strong>Step 4</strong> Make the decision: <strong>reject the null hypothesis</strong>, since the test statistic falls in the critical region (Figure 10-8).</p>
<p><strong>Step 5</strong> Summarize the results: there is a <strong>significant relationship</strong> between advertising spend and the number of orders.</p>
</div>
</div>
</div>
</section>
<section id="example-10-7-2" class="slide level2">
<h2>Example 10-7</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Compute in R</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href=""></a>correlation_test <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(ad_spend, orders)</span>
<span id="cb16-2"><a href=""></a></span>
<span id="cb16-3"><a href=""></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">t =</span> <span class="fu">unname</span>(correlation_test<span class="sc">$</span>statistic),</span>
<span id="cb16-4"><a href=""></a>        <span class="at">p_value =</span> correlation_test<span class="sc">$</span>p.value), <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      t p_value 
 5.0200  0.0074 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href=""></a><span class="fu">round</span>(<span class="fu">qt</span>(<span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>), <span class="at">df =</span> <span class="fu">length</span>(ad_spend) <span class="sc">-</span> <span class="dv">2</span>), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -2.776  2.776</code></pre>
</div>
</div>
<p><code>cor.test()</code> gives <span class="math inline">t = 5.02</span> with a P-value of <span class="math inline">0.0074</span>, and the two-tailed critical values from Table A-5 are <span class="math inline">\pm 2.776</span>.</p>
</div>
</div>
</div>
</section>
<section id="the-p-value-method" class="slide level2">
<h2>The P-Value Method</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Five Steps</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1</strong> State the hypotheses.</p>
<p><strong>Step 2</strong> Find the test statistic (here, the <span class="math inline">t</span> test).</p>
<p><strong>Step 3</strong> Find the P-value (here, use Table A-5).</p>
<p><strong>Step 4</strong> Make the decision.</p>
<p><strong>Step 5</strong> Summarize the results.</p>
</div>
</div>
</div>
<p>For the test in <a href="#/example-10-7">Example 10-7</a>, <span class="math inline">t = 5.02</span> with <span class="math inline">\text{d.f.} = 4</span>. In the <em>Two tails</em> row of Table A-5 the entry at <span class="math inline">\alpha = 0.01</span> for <span class="math inline">\text{d.f.} = 4</span> is <span class="math inline">4.604</span>, and <span class="math inline">5.02 &gt; 4.604</span>, so the P-value is less than <span class="math inline">0.01</span>; <code>cor.test()</code> gives <span class="math inline">0.0074</span>. Since P-value <span class="math inline">&lt; 0.05</span>, reject <span class="math inline">H_0</span>.</p>
</section>
<section id="using-table-a-8" class="slide level2">
<h2>Using Table A-8</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Critical Values for the PPMC</strong></p>
</div>
<div class="callout-content">
<p><strong>Table A-8</strong> gives the values of the correlation coefficient that are significant for a specific <span class="math inline">\alpha</span> level and a specific number of degrees of freedom. For <span class="math inline">\text{d.f.} = 7</span> and <span class="math inline">\alpha = 0.05</span> the table gives <span class="math inline">0.666</span>: any value of <span class="math inline">r</span> greater than <span class="math inline">+0.666</span> or less than <span class="math inline">-0.666</span> is significant, and <span class="math inline">H_0</span> is rejected (Figure 10-9).</p>
<p>When Table A-8 is used, <strong>you need not compute the <span class="math inline">t</span> test statistic</strong>. Table A-8 is for <strong>two-tailed tests only</strong>.</p>
</div>
</div>
</div>
</section>
<section id="example-10-8" class="slide level2">
<h2>Example 10-8</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Using Table A-8</strong></p>
</div>
<div class="callout-content">
<p>Using Table A-8, test the significance at <span class="math inline">\alpha = 0.05</span> of the correlation coefficient <span class="math inline">r = 0.135</span> obtained in <a href="#/example-10-6">Example 10-6</a>.</p>
</div>
</div>
</div>
</section>
<section id="example-10-8-1" class="slide level2">
<h2>Example 10-8</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><span class="math display">H_0: \rho = 0 \qquad H_1: \rho \neq 0</span></p>
<p>The critical values from Table A-8 at <span class="math inline">\alpha = 0.05</span> with <span class="math inline">5</span> degrees of freedom are <span class="math inline">\pm 0.754</span>. Since <span class="math inline">0.135 &lt; 0.754</span>, the decision is <strong>do not reject the null hypothesis</strong> (Figure 10-10).</p>
<p>Hence, there is <strong>not enough evidence</strong> to say that there is a significant relationship between the number of years a company has been in operation and its order growth. <em>(Note: the P-value is <span class="math inline">0.7734</span>.)</em></p>
</div>
</div>
</div>
</section>
<section id="example-10-8-2" class="slide level2">
<h2>Example 10-8</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Compute in R</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href=""></a>df_error   <span class="ot">&lt;-</span> <span class="fu">length</span>(years_operating) <span class="sc">-</span> <span class="dv">2</span></span>
<span id="cb20-2"><a href=""></a>t_critical <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="at">df =</span> df_error)</span>
<span id="cb20-3"><a href=""></a></span>
<span id="cb20-4"><a href=""></a><span class="fu">round</span>(<span class="fu">sqrt</span>(t_critical<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> (t_critical<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> df_error)), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.754</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href=""></a><span class="fu">round</span>(<span class="fu">cor.test</span>(years_operating, growth_rate)<span class="sc">$</span>p.value, <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7734</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="one-tailed-tests" class="slide level2">
<h2>One-Tailed Tests</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>One-Tailed Hypotheses</strong></p>
</div>
<div class="callout-content">
<p>Significance tests for correlation coefficients are generally <strong>two-tailed</strong>, but they can be one-tailed. For a hypothesized <strong>positive</strong> linear relationship,</p>
<p><span class="math display">H_0: \rho = 0 \qquad H_1: \rho &gt; 0</span></p>
<p>and for a hypothesized <strong>negative</strong> linear relationship,</p>
<p><span class="math display">H_0: \rho = 0 \qquad H_1: \rho &lt; 0</span></p>
<p>In these cases the <span class="math inline">t</span> test and the P-value test are one-tailed, and one-tailed versions of Table A-8 exist. In this book the examples and exercises involve two-tailed tests.</p>
</div>
</div>
</div>
</section>
<section id="correlation-and-causation" class="slide level2">
<h2>Correlation and Causation</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Possible Relationships Between Variables</strong></p>
</div>
<div class="callout-content">
<p>When <span class="math inline">H_0</span> has been rejected for a specific <span class="math inline">\alpha</span> value, any of the following <strong>five</strong> possibilities can exist.</p>
<ol type="1">
<li>There is a <strong>direct cause-and-effect</strong> relationship: <span class="math inline">x</span> causes <span class="math inline">y</span> (water causes plants to grow, heat causes ice to melt).</li>
<li>There is a <strong>reverse cause-and-effect</strong> relationship: <span class="math inline">y</span> causes <span class="math inline">x</span> (an extremely nervous person may crave coffee, rather than coffee causing nervousness).</li>
<li>The relationship may be caused by a <strong>third variable</strong> (drowning deaths and soft-drink sales are both related to heat and humidity).</li>
<li>There may be a <strong>complexity of interrelationships</strong> among many variables (high school and college grades are also tied to IQ, hours of study, motivation, age, instructors).</li>
<li>The relationship may be <strong>coincidental</strong> (the rise in the number of people exercising and the rise in the number of people committing crimes).</li>
</ol>
</div>
</div>
</div>
</section>
<section id="caution-lurking-variables-and-averages" class="slide level2">
<h2>Caution: Lurking Variables and Averages</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Caution</strong></p>
</div>
<div class="callout-content">
<p>A third variable that is unknown to the researcher or not accounted for in the study is called a <strong>lurking variable</strong>. The researcher should try to identify such variables and control their influence.</p>
<p>Even if the correlation between two variables is high, it <strong>does not necessarily mean causation</strong>.</p>
<p>Be cautious when the data for one or both variables are <strong>averages</strong> rather than individual data. Using averages is not wrong, but the results cannot be generalized to individuals, since averaging smooths out the variability among individual values and can produce a <strong>higher correlation than actually exists</strong>.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="section-10-2-regression" class="title-slide slide level1 center" data-background-color="#2c4a6e">
<h1>Section 10-2: Regression</h1>

</section>
<section id="line-of-best-fit" class="slide level2">
<h2>Line of Best Fit</h2>
<p>If the value of the correlation coefficient is significant, the next step is to determine the equation of the <strong>regression line</strong>, the data’s <em>line of best fit</em>.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Best Fit, Residuals and Least Squares</strong></p>
</div>
<div class="callout-content">
<p><strong>Best fit</strong> means that the sum of the squares of the vertical distances from each point to the line is at a minimum.</p>
<p>The difference between the actual value <span class="math inline">y</span> and the predicted value <span class="math inline">y'</span> (the vertical distance) is called a <strong>residual</strong> or a <em>predicted error</em>.</p>
<p>The method used for making the residuals as small as possible is the <strong>method of least squares</strong>; the regression line is therefore also called the <strong>least squares regression line</strong>.</p>
</div>
</div>
</div>
<p>Determining the regression line when <span class="math inline">r</span> is <strong>not</strong> significant, and then making predictions with it, is meaningless.</p>
</section>
<section id="determination-of-the-regression-line-equation" class="slide level2">
<h2>Determination of the Regression Line Equation</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Algebra Versus Statistics (Figure 10-13)</strong></p>
</div>
<div class="callout-content">
<p>In algebra the equation of a line is written <span class="math inline">y = mx + b</span>, where <span class="math inline">m</span> is the slope and <span class="math inline">b</span> is the <span class="math inline">y</span> intercept.</p>
<p>In statistics the equation of the regression line is written</p>
<p><span class="math display">y' = a + bx</span></p>
<p>where <span class="math inline">a</span> is the <span class="math inline">y'</span> <strong>intercept</strong> and <span class="math inline">b</span> is the <strong>slope</strong> of the line.</p>
</div>
</div>
</div>
<p>When <span class="math inline">r</span> is positive the line slopes upward to the right; when <span class="math inline">r</span> is negative it slopes downward from left to right.</p>
</section>
<section id="formulas-for-the-regression-line" class="slide level2">
<h2>Formulas for the Regression Line</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Formulas for the Regression Line <span class="math inline">y' = a + bx</span></strong></p>
</div>
<div class="callout-content">
<p><span class="math display">a = \frac{(\sum y)(\sum x^2) - (\sum x)(\sum xy)}{n(\sum x^2) - (\sum x)^2}</span></p>
<p><span class="math display">b = \frac{n(\sum xy) - (\sum x)(\sum y)}{n(\sum x^2) - (\sum x)^2}</span></p>
<p>where <span class="math inline">a</span> is the <span class="math inline">y'</span> intercept and <span class="math inline">b</span> is the slope of the line.</p>
<p><strong>Rounding Rule for the Intercept and Slope.</strong> Round the values of <span class="math inline">a</span> and <span class="math inline">b</span> to <strong>three decimal places</strong>.</p>
</div>
</div>
</div>
</section>
<section id="procedure-table-finding-the-regression-line-equation" class="slide level2">
<h2>Procedure Table: Finding the Regression Line Equation</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Finding the Regression Line Equation</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1</strong> Make a table with columns <span class="math inline">x</span>, <span class="math inline">y</span>, <span class="math inline">xy</span>, <span class="math inline">x^2</span>, <span class="math inline">y^2</span>.</p>
<p><strong>Step 2</strong> Find the values of <span class="math inline">xy</span>, <span class="math inline">x^2</span> and <span class="math inline">y^2</span>, place them in the appropriate columns and sum each column.</p>
<p><strong>Step 3</strong> When <span class="math inline">r</span> is significant, substitute in the formulas to find the values of <span class="math inline">a</span> and <span class="math inline">b</span> for the regression line equation <span class="math inline">y' = a + bx</span>.</p>
</div>
</div>
</div>
</section>
<section id="example-10-9" class="slide level2">
<h2>Example 10-9</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Advertising Spend and Orders</strong></p>
</div>
<div class="callout-content">
<p>Find the equation of the regression line for the data in <a href="#/example-10-4">Example 10-4</a>, and graph the line on the scatter plot of the data.</p>
</div>
</div>
</div>
</section>
<section id="example-10-9-1" class="slide level2">
<h2>Example 10-9</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p>The values needed are <span class="math inline">n = 6</span>, <span class="math inline">\sum x = 270</span>, <span class="math inline">\sum y = 1500</span>, <span class="math inline">\sum xy = 72{,}750</span>, <span class="math inline">\sum x^2 = 13{,}900</span>.</p>
<p><span class="math display">a = \frac{(1500)(13{,}900) - (270)(72{,}750)}{6(13{,}900) - 270^2} = \frac{1{,}207{,}500}{10{,}500} = 115</span></p>
<p><span class="math display">b = \frac{6(72{,}750) - (270)(1500)}{6(13{,}900) - 270^2} = \frac{31{,}500}{10{,}500} = 3</span></p>
<p>Hence the equation of the regression line is</p>
<p><span class="math display">y' = 115 + 3x</span></p>
</div>
</div>
</div>
</section>
<section id="example-10-9-2" class="slide level2">
<h2>Example 10-9</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Compute in R.</strong> The two formulas above are worth writing out once; everywhere else <code>lm()</code> does the work.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href=""></a>regression_coefficients <span class="ot">&lt;-</span> <span class="cf">function</span>(x, y) {</span>
<span id="cb24-2"><a href=""></a>  denominator <span class="ot">&lt;-</span> <span class="fu">length</span>(x) <span class="sc">*</span> <span class="fu">sum</span>(x<span class="sc">^</span><span class="dv">2</span>) <span class="sc">-</span> <span class="fu">sum</span>(x)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb24-3"><a href=""></a>  <span class="fu">c</span>(<span class="at">a =</span> (<span class="fu">sum</span>(y) <span class="sc">*</span> <span class="fu">sum</span>(x<span class="sc">^</span><span class="dv">2</span>) <span class="sc">-</span> <span class="fu">sum</span>(x) <span class="sc">*</span> <span class="fu">sum</span>(x <span class="sc">*</span> y)) <span class="sc">/</span> denominator,</span>
<span id="cb24-4"><a href=""></a>    <span class="at">b =</span> (<span class="fu">length</span>(x) <span class="sc">*</span> <span class="fu">sum</span>(x <span class="sc">*</span> y) <span class="sc">-</span> <span class="fu">sum</span>(x) <span class="sc">*</span> <span class="fu">sum</span>(y)) <span class="sc">/</span> denominator)</span>
<span id="cb24-5"><a href=""></a>}</span>
<span id="cb24-6"><a href=""></a></span>
<span id="cb24-7"><a href=""></a><span class="fu">regression_coefficients</span>(ad_spend, orders)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  a   b 
115   3 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href=""></a>model_ads <span class="ot">&lt;-</span> <span class="fu">lm</span>(orders <span class="sc">~</span> ad_spend)</span>
<span id="cb26-2"><a href=""></a><span class="fu">coef</span>(model_ads)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)    ad_spend 
        115           3 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="example-10-9-3" class="slide level2">
<h2>Example 10-9</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Output figure (Figure 10-14)</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href=""></a>scatter_ads <span class="sc">+</span></span>
<span id="cb28-2"><a href=""></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"red"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="ch10_files/figure-revealjs/e10-9-2-1.png" class="quarto-figure quarto-figure-center" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="example-10-10" class="slide level2">
<h2>Example 10-10</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Days Late and Customer Rating</strong></p>
</div>
<div class="callout-content">
<p>Find the equation of the regression line for the data in <a href="#/example-10-5">Example 10-5</a>, and graph the line on the scatter plot.</p>
<p>Back to <a href="#/example-10-11">Example 10-11</a></p>
</div>
</div>
</div>
</section>
<section id="example-10-10-1" class="slide level2">
<h2>Example 10-10</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p>The values needed are <span class="math inline">n = 7</span>, <span class="math inline">\sum x = 28</span>, <span class="math inline">\sum y = 560</span>, <span class="math inline">\sum xy = 2128</span>, <span class="math inline">\sum x^2 = 140</span>.</p>
<p><span class="math display">a = \frac{(560)(140) - (28)(2128)}{7(140) - 28^2} = \frac{18{,}816}{196} = 96</span></p>
<p><span class="math display">b = \frac{7(2128) - (28)(560)}{7(140) - 28^2} = \frac{-784}{196} = -4</span></p>
<p>Hence the equation of the regression line is</p>
<p><span class="math display">y' = 96 - 4x</span></p>
</div>
</div>
</div>
</section>
<section id="example-10-10-2" class="slide level2">
<h2>Example 10-10</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Compute in R and output the figure (Figure 10-15)</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href=""></a>model_rating <span class="ot">&lt;-</span> <span class="fu">lm</span>(rating <span class="sc">~</span> days_late)</span>
<span id="cb29-2"><a href=""></a><span class="fu">coef</span>(model_rating)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)   days_late 
         96          -4 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href=""></a>scatter_rating <span class="sc">+</span></span>
<span id="cb31-2"><a href=""></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"darkred"</span>) <span class="sc">+</span></span>
<span id="cb31-3"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Regression Line for Days Late and Customer Rating"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="ch10_files/figure-revealjs/e10-10-1-1.png" class="quarto-figure quarto-figure-center" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="properties-of-the-regression-line" class="slide level2">
<h2>Properties of the Regression Line</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Two Properties</strong></p>
</div>
<div class="callout-content">
<p>The sign of the correlation coefficient and the sign of the slope of the regression line are <strong>always the same</strong>: if <span class="math inline">r</span> is positive, <span class="math inline">b</span> is positive; if <span class="math inline">r</span> is negative, <span class="math inline">b</span> is negative. The numerators of the two formulas are identical and the denominators are always positive.</p>
<p>The regression line <strong>always passes through the point <span class="math inline">(\bar{x}, \bar{y})</span></strong>, whose coordinates are the mean of the <span class="math inline">x</span> values and the mean of the <span class="math inline">y</span> values.</p>
</div>
</div>
</div>
</section>
<section id="guidelines-for-making-predictions" class="slide level2">
<h2>Guidelines for Making Predictions</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Use These Guidelines</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>The points of the scatter plot fit the linear regression line reasonably well.</li>
<li>The value of <span class="math inline">r</span> is <strong>significant</strong>.</li>
<li>The value of a specific <span class="math inline">x</span> is <strong>not much beyond the observed <span class="math inline">x</span> values</strong> in the original data.</li>
<li>If <span class="math inline">r</span> is <strong>not</strong> significant, then the best predicted value for a specific <span class="math inline">x</span> value is the <strong>mean of the <span class="math inline">y</span> values</strong> in the original data.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="assumptions-for-valid-predictions-in-regression" class="slide level2">
<h2>Assumptions for Valid Predictions in Regression</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Three Assumptions (Figure 10-16)</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>The sample is a <strong>random sample</strong>.</li>
<li>For any specific value of the independent variable <span class="math inline">x</span>, the value of the dependent variable <span class="math inline">y</span> must be <strong>normally distributed about the regression line</strong>.</li>
<li>The <strong>standard deviation of each of the dependent variables must be the same</strong> for each value of the independent variable, that is, <span class="math inline">\sigma_1 = \sigma_2 = \cdots = \sigma_n</span>.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="example-10-11" class="slide level2">
<h2>Example 10-11</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Days Late and Customer Rating</strong></p>
</div>
<div class="callout-content">
<p>Use the equation of the regression line in <a href="#/example-10-10">Example 10-10</a> to predict the customer rating for an order that arrives <strong>2 days late</strong>.</p>
</div>
</div>
</div>
</section>
<section id="example-10-11-1" class="slide level2">
<h2>Example 10-11</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p>Substitute <span class="math inline">2</span> for <span class="math inline">x</span> in the regression line equation <span class="math inline">y' = 96 - 4x</span>:</p>
<p><span class="math display">y' = 96 - 4(2) = 88</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href=""></a><span class="fu">predict</span>(model_rating, <span class="fu">data.frame</span>(<span class="at">days_late =</span> <span class="dv">2</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> 1 
88 </code></pre>
</div>
</div>
<p>Hence, an order that arrives 2 days late is predicted to receive a customer rating of about <strong>88</strong>. This is a <strong>point prediction</strong>: no degree of accuracy or confidence can be attached to it (see Section 10-3).</p>
</div>
</div>
</div>
</section>
<section id="marginal-change" class="slide level2">
<h2>Marginal Change</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Marginal Change</strong></p>
</div>
<div class="callout-content">
<p>The magnitude of the change in one variable when the other variable changes <strong>exactly 1 unit</strong> is called a <strong>marginal change</strong>. The value of the slope <span class="math inline">b</span> of the regression line equation represents the marginal change.</p>
<p>In <a href="#/example-10-10">Example 10-10</a>, <span class="math inline">b = -4</span>: for each additional day a shipment is late, the predicted customer rating falls by <span class="math inline">4</span> points, on average.</p>
</div>
</div>
</div>
</section>
<section id="caution-extrapolation" class="slide level2">
<h2>Caution: Extrapolation</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Caution</strong></p>
</div>
<div class="callout-content">
<p><strong>Extrapolation</strong>, or making predictions beyond the bounds of the data, must be interpreted cautiously.</p>
<p>Suppose the regression of monthly revenue on store floor area is fitted from branches of 8 to 18 ping. Using that line to predict the revenue of a 60-ping flagship store assumes the same straight-line relationship holds far outside the range that was measured. It usually does not: a store that large draws on a different catchment, carries a different product mix, and faces costs the sample never saw.</p>
<p>Predictions are based on present conditions or on the premise that present trends will continue. That assumption may or may not prove true in the future.</p>
</div>
</div>
</div>
</section>
<section id="outliers-and-influential-points" class="slide level2">
<h2>Outliers and Influential Points</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Influential Points</strong></p>
</div>
<div class="callout-content">
<p>A scatter plot should be checked for <strong>outliers</strong>: points that seem out of place compared with the other points. Outliers that affect the equation of the regression line are called <strong>influential points</strong> (or <em>influential observations</em>).</p>
<p>An influential point tends to “pull” the regression line toward itself. To check, graph the regression line <strong>with</strong> the point and then <strong>without</strong> it; if the position of the line changes considerably, the point is influential. Points that are outliers in the <span class="math inline">x</span> direction tend to be influential.</p>
</div>
</div>
</div>
<p>Researchers use their judgment about whether to include influential observations, or collect additional data near that <span class="math inline">x</span> value.</p>
</section></section>
<section>
<section id="section-10-3-coefficient-of-determination-and-standard-error-of-the-estimate" class="title-slide slide level1 center" data-background-color="#2c4a6e">
<h1>Section 10-3: Coefficient of Determination and Standard Error of the Estimate</h1>

</section>
<section id="types-of-variation-for-the-regression-model" class="slide level2">
<h2>Types of Variation for the Regression Model</h2>
<p>Consider a small set of five observations (hypothetical data): <span class="math inline">x</span> is the number of staff on duty at a night-market stall and <span class="math inline">y</span> is the number of set meals sold per hour. Its regression equation is <span class="math inline">y' = 8 + 4x</span> and <span class="math inline">r = 0.933</span>.</p>
<pre><code>x     1     2     3     4     5
y    14    16    16    24    30</code></pre>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Three Types of Variation</strong></p>
</div>
<div class="callout-content">
<p>The <strong>total variation</strong> <span class="math inline">\sum(y - \bar{y})^2</span> is the sum of the squares of the vertical distances each point is from the mean. It divides into two parts.</p>
<p>The <strong>explained variation</strong> <span class="math inline">\sum(y' - \bar{y})^2</span> is the variation obtained from the relationship, that is, from the predicted <span class="math inline">y'</span> values.</p>
<p>The <strong>unexplained variation</strong> <span class="math inline">\sum(y - y')^2</span> is the variation due to chance; it cannot be attributed to the relationship.</p>
<p><span class="math display">\sum(y - \bar{y})^2 = \sum(y' - \bar{y})^2 + \sum(y - y')^2</span></p>
</div>
</div>
</div>
</section>
<section id="types-of-variation-in-r" class="slide level2">
<h2>Types of Variation in R</h2>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href=""></a>staff_on_duty <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span></span>
<span id="cb35-2"><a href=""></a>units_sold    <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">14</span>, <span class="dv">16</span>, <span class="dv">16</span>, <span class="dv">24</span>, <span class="dv">30</span>)</span>
<span id="cb35-3"><a href=""></a>model_stall   <span class="ot">&lt;-</span> <span class="fu">lm</span>(units_sold <span class="sc">~</span> staff_on_duty)</span>
<span id="cb35-4"><a href=""></a></span>
<span id="cb35-5"><a href=""></a>mean_sold <span class="ot">&lt;-</span> <span class="fu">mean</span>(units_sold)</span>
<span id="cb35-6"><a href=""></a></span>
<span id="cb35-7"><a href=""></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">total =</span> <span class="fu">sum</span>((units_sold <span class="sc">-</span> mean_sold)<span class="sc">^</span><span class="dv">2</span>),</span>
<span id="cb35-8"><a href=""></a>        <span class="at">explained =</span> <span class="fu">sum</span>((<span class="fu">fitted</span>(model_stall) <span class="sc">-</span> mean_sold)<span class="sc">^</span><span class="dv">2</span>),</span>
<span id="cb35-9"><a href=""></a>        <span class="at">unexplained =</span> <span class="fu">sum</span>(<span class="fu">resid</span>(model_stall)<span class="sc">^</span><span class="dv">2</span>)), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      total   explained unexplained 
        184         160          24 </code></pre>
</div>
</div>
<p>Total variation <span class="math inline">= 184</span>, explained variation <span class="math inline">= 160</span>, unexplained variation <span class="math inline">= 24</span>, and <span class="math inline">184 = 160 + 24</span>.</p>
</section>
<section id="residual-plots" class="slide level2">
<h2>Residual Plots</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Residual Plot</strong></p>
</div>
<div class="callout-content">
<p>The values <span class="math inline">y - y'</span> are called <strong>residuals</strong> (sometimes the <em>prediction errors</em>). These values can be plotted against the <span class="math inline">x</span> values, and the plot, called a <strong>residual plot</strong>, can be used to determine how well the regression line can be used to make predictions.</p>
</div>
</div>
</div>
<p>The <span class="math inline">x</span> values are plotted on the horizontal axis and the residuals on the vertical axis. Since the <strong>mean of the residuals is always zero</strong>, a horizontal line at <span class="math inline">0</span> is drawn on the plot.</p>
<pre><code>x            1      2      3      4      5
y - y'       2      0     -4      0      2</code></pre>
</section>
<section id="residual-plot-in-r" class="slide level2">
<h2>Residual Plot in R</h2>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href=""></a><span class="fu">ggplot</span>(<span class="fu">data.frame</span>(staff_on_duty, <span class="at">residual =</span> <span class="fu">resid</span>(model_stall)),</span>
<span id="cb38-2"><a href=""></a>       <span class="fu">aes</span>(<span class="at">x =</span> staff_on_duty, <span class="at">y =</span> residual)) <span class="sc">+</span></span>
<span id="cb38-3"><a href=""></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb38-4"><a href=""></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb38-5"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Residual Plot"</span>, <span class="at">x =</span> <span class="st">"Staff on duty"</span>, <span class="at">y =</span> <span class="st">"Residual"</span>) <span class="sc">+</span></span>
<span id="cb38-6"><a href=""></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="ch10_files/figure-revealjs/s10-3-2-1.png" class="quarto-figure quarto-figure-center r-stretch" style="width:80.0%"></section>
<section id="interpreting-a-residual-plot" class="slide level2">
<h2>Interpreting a Residual Plot</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Four Patterns (Figure 10-19)</strong></p>
</div>
<div class="callout-content">
<ul>
<li><strong>(a)</strong> The residual values are more or less <strong>evenly distributed about the line</strong>: the relationship between <span class="math inline">x</span> and <span class="math inline">y</span> is linear and the regression line can be used to make predictions. This is the <strong>homoscedasticity assumption</strong> — the standard deviations of each of the dependent variables are the same for each value of the independent variable.</li>
<li><strong>(b)</strong> The <strong>variance of the residuals increases</strong> as <span class="math inline">x</span> increases: the regression line is not suitable for predictions.</li>
<li><strong>(c)</strong> A <strong>curvilinear relationship</strong> between the <span class="math inline">x</span> values and the residual values: the regression line is not suitable for predictions.</li>
<li><strong>(d)</strong> As <span class="math inline">x</span> increases, the residuals <strong>increase and become more dispersed</strong>: the regression line is not suitable for predictions.</li>
</ul>
</div>
</div>
</div>
<p>The residual plot for <span class="math inline">y' = 8 + 4x</span> makes that line somewhat questionable for predictions, due to the small sample size.</p>
</section>
<section id="coefficient-of-determination" class="slide level2">
<h2>Coefficient of Determination</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Coefficient of Determination</strong></p>
</div>
<div class="callout-content">
<p>The <strong>coefficient of determination</strong> is the ratio of the explained variation to the total variation, denoted by <span class="math inline">r^2</span>:</p>
<p><span class="math display">r^2 = \frac{\text{explained variation}}{\text{total variation}}</span></p>
<p>It measures the variation of the dependent variable that is explained by the regression line and the independent variable, and <span class="math inline">0 \leq r^2 \leq 1</span>.</p>
</div>
</div>
</div>
<p>For the stall data, <span class="math inline">r^2 = 160 / 184 = 0.870</span>: <span class="math inline">87.0\%</span> of the total variation is explained by the regression line. Squaring <span class="math inline">r = 0.933</span> gives the same value.</p>
</section>
<section id="coefficient-of-nondetermination" class="slide level2">
<h2>Coefficient of Nondetermination</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Coefficient of Nondetermination</strong></p>
</div>
<div class="callout-content">
<p><span class="math display">1.00 - r^2</span></p>
<p>If <span class="math inline">r = 0.90</span>, then <span class="math inline">r^2 = 0.81</span>, so <span class="math inline">81\%</span> of the variation in the dependent variable is accounted for by the variation in the independent variable, and the remaining <span class="math inline">0.19</span>, or <span class="math inline">19\%</span>, is unexplained.</p>
<p>As <span class="math inline">r</span> approaches <span class="math inline">0</span>, <span class="math inline">r^2</span> decreases more rapidly: if <span class="math inline">r = 0.6</span>, then <span class="math inline">r^2 = 0.36</span>, so only <span class="math inline">36\%</span> of the variation is attributable to the independent variable.</p>
</div>
</div>
</div>
</section>
<section id="coefficient-of-determination-in-r" class="slide level2">
<h2>Coefficient of Determination in R</h2>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href=""></a>r_squared_rating <span class="ot">&lt;-</span> <span class="fu">summary</span>(model_rating)<span class="sc">$</span>r.squared</span>
<span id="cb39-2"><a href=""></a></span>
<span id="cb39-3"><a href=""></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">r =</span> <span class="fu">cor</span>(days_late, rating),</span>
<span id="cb39-4"><a href=""></a>        <span class="at">r_squared =</span> r_squared_rating,</span>
<span id="cb39-5"><a href=""></a>        <span class="at">nondetermination =</span> <span class="dv">1</span> <span class="sc">-</span> r_squared_rating), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>               r        r_squared nondetermination 
          -0.950            0.903            0.097 </code></pre>
</div>
</div>
<p>In <a href="#/example-10-5">Example 10-5</a>, <span class="math inline">r = -0.950</span>, so <span class="math inline">r^2 = 0.903</span>: about <span class="math inline">90.3\%</span> of the variation in the customer ratings can be explained by the linear relationship with the number of days late, and about <span class="math inline">9.7\%</span> cannot.</p>
</section>
<section id="prediction-interval-and-standard-error-of-the-estimate" class="slide level2">
<h2>Prediction Interval and Standard Error of the Estimate</h2>
<p>A point prediction gives no information about how accurate it is. The interval estimate used in regression is the <strong>prediction interval</strong>.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Two Definitions</strong></p>
</div>
<div class="callout-content">
<p>A <strong>prediction interval</strong> is an interval estimate of a predicted value of <span class="math inline">y</span> when the regression equation is used and a specific value of <span class="math inline">x</span> is given.</p>
<p>The <strong>standard error of the estimate</strong>, denoted by <span class="math inline">s_{est}</span>, is the standard deviation of the observed <span class="math inline">y</span> values about the predicted <span class="math inline">y'</span> values:</p>
<p><span class="math display">s_{est} = \sqrt{\frac{\sum(y - y')^2}{n-2}}</span></p>
</div>
</div>
</div>
<p><span class="math inline">s_{est}</span> is the square root of the unexplained variation divided by <span class="math inline">n - 2</span>: the closer the observed values are to the predicted values, the smaller it is.</p>
</section>
<section id="procedure-table-finding-s_est" class="slide level2">
<h2>Procedure Table: Finding <span class="math inline">s_{est}</span></h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Finding the Standard Error of the Estimate</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1</strong> Make a table with columns <span class="math inline">x</span>, <span class="math inline">y</span>, <span class="math inline">y'</span>, <span class="math inline">y - y'</span>, <span class="math inline">(y - y')^2</span>.</p>
<p><strong>Step 2</strong> Find the predicted values <span class="math inline">y'</span> for each <span class="math inline">x</span> value and place them under <span class="math inline">y'</span>.</p>
<p><strong>Step 3</strong> Subtract each <span class="math inline">y'</span> value from each <span class="math inline">y</span> value and place the answers in the <span class="math inline">y - y'</span> column.</p>
<p><strong>Step 4</strong> Square each of the values in Step 3 and place them in the <span class="math inline">(y - y')^2</span> column.</p>
<p><strong>Step 5</strong> Find the sum of the values in the <span class="math inline">(y - y')^2</span> column.</p>
<p><strong>Step 6</strong> Substitute in the formula and find <span class="math inline">s_{est}</span>.</p>
</div>
</div>
</div>
</section>
<section id="example-10-12" class="slide level2">
<h2>Example 10-12</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Store Floor Area and Monthly Revenue</strong></p>
</div>
<div class="callout-content">
<p>A retail analyst collects the following data for six branches of a bubble-tea chain and determines that there is a significant relationship between a store’s floor area and its average monthly revenue. The regression equation is <span class="math inline">y' = 25 + 5x</span>. Find the standard error of the estimate.</p>
<pre><code>Branch                              A      B      C      D      E      F
Floor area, x (ping)                8     10     12     14     16     18
Monthly revenue, y (NT$10,000)     70     75     80     90    105    120</code></pre>
<p><em>(hypothetical data)</em></p>
<p>Back to <a href="#/example-10-13">Example 10-13</a> and <a href="#/example-10-14">Example 10-14</a></p>
</div>
</div>
</div>
</section>
<section id="example-10-12-1" class="slide level2">
<h2>Example 10-12</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Steps 1 to 5 — build the table</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th><span class="math inline">x</span></th>
<th><span class="math inline">y</span></th>
<th><span class="math inline">y'</span></th>
<th><span class="math inline">y - y'</span></th>
<th><span class="math inline">(y - y')^2</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>8</td>
<td>70</td>
<td>65</td>
<td>5</td>
<td>25</td>
</tr>
<tr class="even">
<td>10</td>
<td>75</td>
<td>75</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td>12</td>
<td>80</td>
<td>85</td>
<td><span class="math inline">-5</span></td>
<td>25</td>
</tr>
<tr class="even">
<td>14</td>
<td>90</td>
<td>95</td>
<td><span class="math inline">-5</span></td>
<td>25</td>
</tr>
<tr class="odd">
<td>16</td>
<td>105</td>
<td>105</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>18</td>
<td>120</td>
<td>115</td>
<td>5</td>
<td>25</td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td><span class="math inline">\sum(y-y')^2</span></td>
<td>100</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="example-10-12-2" class="slide level2">
<h2>Example 10-12</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 6 — substitute in the formula</strong></p>
<p><span class="math display">s_{est} = \sqrt{\frac{\sum(y-y')^2}{n-2}} = \sqrt{\frac{100}{6-2}} = 5</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href=""></a>floor_area      <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">8</span>, <span class="dv">10</span>, <span class="dv">12</span>, <span class="dv">14</span>, <span class="dv">16</span>, <span class="dv">18</span>)</span>
<span id="cb42-2"><a href=""></a>monthly_revenue <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">70</span>, <span class="dv">75</span>, <span class="dv">80</span>, <span class="dv">90</span>, <span class="dv">105</span>, <span class="dv">120</span>)</span>
<span id="cb42-3"><a href=""></a>model_store     <span class="ot">&lt;-</span> <span class="fu">lm</span>(monthly_revenue <span class="sc">~</span> floor_area)</span>
<span id="cb42-4"><a href=""></a></span>
<span id="cb42-5"><a href=""></a>residuals_store <span class="ot">&lt;-</span> <span class="fu">resid</span>(model_store)</span>
<span id="cb42-6"><a href=""></a></span>
<span id="cb42-7"><a href=""></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">sse =</span> <span class="fu">sum</span>(residuals_store<span class="sc">^</span><span class="dv">2</span>),</span>
<span id="cb42-8"><a href=""></a>        <span class="at">s_est =</span> <span class="fu">sqrt</span>(<span class="fu">sum</span>(residuals_store<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> <span class="fu">df.residual</span>(model_store))), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  sse s_est 
  100     5 </code></pre>
</div>
</div>
<p>The standard deviation of the observed values about the predicted values is <strong>5</strong>.</p>
</div>
</div>
</div>
</section>
<section id="alternative-formula-for-s_est" class="slide level2">
<h2>Alternative Formula for <span class="math inline">s_{est}</span></h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Alternative Method for Finding the Standard Error of the Estimate</strong></p>
</div>
<div class="callout-content">
<p><span class="math display">s_{est} = \sqrt{\frac{\sum y^2 - a\sum y - b\sum xy}{n-2}}</span></p>
<p><strong>Step 1</strong> Make a table with columns <span class="math inline">x</span>, <span class="math inline">y</span>, <span class="math inline">xy</span>, <span class="math inline">y^2</span>.</p>
<p><strong>Step 2</strong> Place the <span class="math inline">x</span> and <span class="math inline">y</span> values in the first two columns, the products <span class="math inline">xy</span> in the third and the squares <span class="math inline">y^2</span> in the fourth.</p>
<p><strong>Step 3</strong> Find the sum of the values in the <span class="math inline">y</span>, <span class="math inline">xy</span> and <span class="math inline">y^2</span> columns.</p>
<p><strong>Step 4</strong> Identify <span class="math inline">a</span> and <span class="math inline">b</span> from the regression equation, substitute in the formula and evaluate.</p>
</div>
</div>
</div>
</section>
<section id="example-10-13" class="slide level2">
<h2>Example 10-13</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Store Floor Area and Monthly Revenue</strong></p>
</div>
<div class="callout-content">
<p>Find the standard error of the estimate for the data in <a href="#/example-10-12">Example 10-12</a> by using the alternative formula. The equation of the regression line is <span class="math inline">y' = 25 + 5x</span>.</p>
<p>Back to <a href="#/example-10-14">Example 10-14</a></p>
</div>
</div>
</div>
</section>
<section id="example-10-13-1" class="slide level2">
<h2>Example 10-13</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Steps 1 to 3 — build the table</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th><span class="math inline">x</span></th>
<th><span class="math inline">y</span></th>
<th><span class="math inline">xy</span></th>
<th><span class="math inline">y^2</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>8</td>
<td>70</td>
<td>560</td>
<td>4,900</td>
</tr>
<tr class="even">
<td>10</td>
<td>75</td>
<td>750</td>
<td>5,625</td>
</tr>
<tr class="odd">
<td>12</td>
<td>80</td>
<td>960</td>
<td>6,400</td>
</tr>
<tr class="even">
<td>14</td>
<td>90</td>
<td>1,260</td>
<td>8,100</td>
</tr>
<tr class="odd">
<td>16</td>
<td>105</td>
<td>1,680</td>
<td>11,025</td>
</tr>
<tr class="even">
<td>18</td>
<td>120</td>
<td>2,160</td>
<td>14,400</td>
</tr>
<tr class="odd">
<td></td>
<td><span class="math inline">\sum y = 540</span></td>
<td><span class="math inline">\sum xy = 7370</span></td>
<td><span class="math inline">\sum y^2 = 50{,}450</span></td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="example-10-13-2" class="slide level2">
<h2>Example 10-13</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 4 — substitute and solve</strong></p>
<p><span class="math display">s_{est} = \sqrt{\frac{50{,}450 - (25)(540) - (5)(7370)}{6-2}} = \sqrt{\frac{100}{4}} = 5</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href=""></a>intercept <span class="ot">&lt;-</span> <span class="fu">coef</span>(model_store)[[<span class="st">"(Intercept)"</span>]]</span>
<span id="cb44-2"><a href=""></a>slope     <span class="ot">&lt;-</span> <span class="fu">coef</span>(model_store)[[<span class="st">"floor_area"</span>]]</span>
<span id="cb44-3"><a href=""></a></span>
<span id="cb44-4"><a href=""></a>alternative_s_est <span class="ot">&lt;-</span> <span class="fu">sqrt</span>((<span class="fu">sum</span>(monthly_revenue<span class="sc">^</span><span class="dv">2</span>) <span class="sc">-</span></span>
<span id="cb44-5"><a href=""></a>                           intercept <span class="sc">*</span> <span class="fu">sum</span>(monthly_revenue) <span class="sc">-</span></span>
<span id="cb44-6"><a href=""></a>                           slope <span class="sc">*</span> <span class="fu">sum</span>(floor_area <span class="sc">*</span> monthly_revenue)) <span class="sc">/</span></span>
<span id="cb44-7"><a href=""></a>                          <span class="fu">df.residual</span>(model_store))</span>
<span id="cb44-8"><a href=""></a></span>
<span id="cb44-9"><a href=""></a><span class="fu">round</span>(alternative_s_est, <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5</code></pre>
</div>
</div>
<p>The alternative formula is algebraically the same expression, so it returns exactly the value found in <a href="#/example-10-12">Example 10-12</a>, <span class="math inline">s_{est} = 5</span>.</p>
</div>
</div>
</div>
</section>
<section id="formula-for-the-prediction-interval" class="slide level2">
<h2>Formula for the Prediction Interval</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Prediction Interval about a Value <span class="math inline">y'</span></strong></p>
</div>
<div class="callout-content">
<p><span class="math display">y' - t_{\alpha/2}\, s_{est} \sqrt{1 + \frac{1}{n} + \frac{n(x - \bar{x})^2}{n\sum x^2 - (\sum x)^2}} &lt; y &lt; y' + t_{\alpha/2}\, s_{est} \sqrt{1 + \frac{1}{n} + \frac{n(x - \bar{x})^2}{n\sum x^2 - (\sum x)^2}}</span></p>
<p>with <span class="math inline">\text{d.f.} = n - 2</span>.</p>
<p><strong>Step 1</strong> Find <span class="math inline">\sum x</span>, <span class="math inline">\sum x^2</span> and <span class="math inline">\bar{x}</span>. <strong>Step 2</strong> Find <span class="math inline">y'</span> for the specific <span class="math inline">x</span> value. <strong>Step 3</strong> Find <span class="math inline">s_{est}</span>. <strong>Step 4</strong> Substitute in the formula and evaluate.</p>
</div>
</div>
</div>
</section>
<section id="example-10-14" class="slide level2">
<h2>Example 10-14</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Store Floor Area and Monthly Revenue</strong></p>
</div>
<div class="callout-content">
<p>For the data in <a href="#/example-10-12">Example 10-12</a>, find the <strong>95% prediction interval</strong> for the average monthly revenue of a branch with a floor area of <strong>12 ping</strong>.</p>
</div>
</div>
</div>
</section>
<section id="example-10-14-1" class="slide level2">
<h2>Example 10-14</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1</strong> <span class="math inline">\sum x = 78</span>, <span class="math inline">\sum x^2 = 1084</span>, <span class="math inline">\bar{x} = 78/6 = 13</span>.</p>
<p><strong>Step 2</strong> <span class="math inline">y' = 25 + 5(12) = 85</span>.</p>
<p><strong>Step 3</strong> <span class="math inline">s_{est} = 5</span>, as shown in <a href="#/example-10-13">Example 10-13</a>.</p>
<p><strong>Step 4</strong> With <span class="math inline">t_{\alpha/2} = 2.776</span> and <span class="math inline">\text{d.f.} = 6 - 2 = 4</span> for 95%, the square-root factor is</p>
<p><span class="math display">\sqrt{1 + \frac{1}{6} + \frac{6(12 - 13)^2}{6(1084) - 78^2}} = 1.087</span></p>
<p><span class="math display">85 - (2.776)(5)(1.087) &lt; y &lt; 85 + (2.776)(5)(1.087)</span></p>
<p><span class="math display">\mathbf{69.91 &lt; y &lt; 100.09}</span></p>
</div>
</div>
</div>
</section>
<section id="example-10-14-2" class="slide level2">
<h2>Example 10-14</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Compute in R</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href=""></a>n_stores   <span class="ot">&lt;-</span> <span class="fu">length</span>(floor_area)</span>
<span id="cb46-2"><a href=""></a>t_critical <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="at">df =</span> <span class="fu">df.residual</span>(model_store))</span>
<span id="cb46-3"><a href=""></a></span>
<span id="cb46-4"><a href=""></a>spread <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="dv">1</span> <span class="sc">+</span> <span class="dv">1</span> <span class="sc">/</span> n_stores <span class="sc">+</span> n_stores <span class="sc">*</span> (<span class="dv">12</span> <span class="sc">-</span> <span class="fu">mean</span>(floor_area))<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span></span>
<span id="cb46-5"><a href=""></a>                 (n_stores <span class="sc">*</span> <span class="fu">sum</span>(floor_area<span class="sc">^</span><span class="dv">2</span>) <span class="sc">-</span> <span class="fu">sum</span>(floor_area)<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb46-6"><a href=""></a></span>
<span id="cb46-7"><a href=""></a>margin_of_error <span class="ot">&lt;-</span> t_critical <span class="sc">*</span> <span class="fu">sigma</span>(model_store) <span class="sc">*</span> spread</span>
<span id="cb46-8"><a href=""></a></span>
<span id="cb46-9"><a href=""></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">t =</span> t_critical, <span class="at">factor =</span> spread, <span class="at">margin =</span> margin_of_error), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     t factor margin 
 2.776  1.087 15.086 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href=""></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">lower =</span> <span class="dv">85</span> <span class="sc">-</span> margin_of_error, <span class="at">upper =</span> <span class="dv">85</span> <span class="sc">+</span> margin_of_error), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> lower  upper 
 69.91 100.09 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="example-10-14-3" class="slide level2">
<h2>Example 10-14</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Check with <code>predict()</code></strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href=""></a><span class="fu">round</span>(<span class="fu">predict</span>(model_store, <span class="fu">data.frame</span>(<span class="at">floor_area =</span> <span class="dv">12</span>),</span>
<span id="cb50-2"><a href=""></a>              <span class="at">interval =</span> <span class="st">"prediction"</span>, <span class="at">level =</span> <span class="fl">0.95</span>), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  fit   lwr    upr
1  85 69.91 100.09</code></pre>
</div>
</div>
<p><code>predict()</code> returns the same interval, <span class="math inline">69.91 &lt; y &lt; 100.09</span>. You can be <strong>95% confident</strong> that a branch with 12 ping of floor space has an average monthly revenue between <span class="math inline">69.91</span> and <span class="math inline">100.09</span> (in units of ten thousand NT dollars). The range is wide because <span class="math inline">n = 6</span> is small.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="section-10-4-multiple-regression-optional" class="title-slide slide level1 center" data-background-color="#2c4a6e">
<h1>Section 10-4: Multiple Regression (Optional)</h1>

</section>
<section id="from-simple-to-multiple-regression" class="slide level2">
<h2>From Simple to Multiple Regression</h2>
<p>In simple linear regression the equation contains one independent variable <span class="math inline">x</span> and one dependent variable <span class="math inline">y'</span>, written <span class="math inline">y' = a + bx</span>. In <strong>multiple regression</strong> there are several independent variables and one dependent variable.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>General Form of the Multiple Regression Equation</strong></p>
</div>
<div class="callout-content">
<p>The general form of the multiple regression equation with <span class="math inline">k</span> independent variables is</p>
<p><span class="math display">y' = a + b_1x_1 + b_2x_2 + \cdots + b_kx_k</span></p>
<p>With two independent variables it is <span class="math inline">y' = a + b_1x_1 + b_2x_2</span>; with three, <span class="math inline">y' = a + b_1x_1 + b_2x_2 + b_3x_3</span>.</p>
</div>
</div>
</div>
<p>Multiple regression is used when a statistician thinks several independent variables contribute to the variation of the dependent variable; it increases the accuracy of predictions over one independent variable alone.</p>
</section>
<section id="shipping-costs-the-data" class="slide level2">
<h2>Shipping Costs: the Data</h2>
<p>A courier company wishes to see whether the distance a parcel travels and its weight are related to the shipping cost quoted for it. Five recent international shipments are selected <em>(hypothetical data)</em>.</p>
<pre><code>Shipment                          A       B       C       D       E
Distance, x1 (100 km)             4       9       6      13       8
Weight, x2 (kg)                  25      15      21      33      31
Shipping cost, y (NT dollars)  5400    4950    4750    8200    6900</code></pre>
<p>The multiple regression equation obtained from the data using technology is</p>
<p><span class="math display">y' = 844.016 + 205.440x_1 + 142.098x_2</span></p>
<p>For a parcel travelling <span class="math inline">1{,}000</span> km that weighs <span class="math inline">28</span> kg,</p>
<p><span class="math display">y' = 844.016 + 205.440(10) + 142.098(28) \approx 6877</span></p>
</section>
<section id="multiple-regression-in-r" class="slide level2">
<h2>Multiple Regression in R</h2>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href=""></a>distance      <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">9</span>, <span class="dv">6</span>, <span class="dv">13</span>, <span class="dv">8</span>)</span>
<span id="cb53-2"><a href=""></a>weight        <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">25</span>, <span class="dv">15</span>, <span class="dv">21</span>, <span class="dv">33</span>, <span class="dv">31</span>)</span>
<span id="cb53-3"><a href=""></a>shipping_cost <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">5400</span>, <span class="dv">4950</span>, <span class="dv">4750</span>, <span class="dv">8200</span>, <span class="dv">6900</span>)</span>
<span id="cb53-4"><a href=""></a></span>
<span id="cb53-5"><a href=""></a>model_shipping <span class="ot">&lt;-</span> <span class="fu">lm</span>(shipping_cost <span class="sc">~</span> distance <span class="sc">+</span> weight)</span>
<span id="cb53-6"><a href=""></a><span class="fu">round</span>(<span class="fu">coef</span>(model_shipping), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)    distance      weight 
    844.016     205.440     142.098 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href=""></a><span class="fu">round</span>(<span class="fu">predict</span>(model_shipping, <span class="fu">data.frame</span>(<span class="at">distance =</span> <span class="dv">10</span>, <span class="at">weight =</span> <span class="dv">28</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   1 
6877 </code></pre>
</div>
</div>
<p>The predicted shipping cost is <strong>6877</strong> NT dollars.</p>
</section>
<section id="partial-regression-coefficients" class="slide level2">
<h2>Partial Regression Coefficients</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Partial Regression Coefficients</strong></p>
</div>
<div class="callout-content">
<p>In <span class="math inline">y' = a + b_1x_1 + b_2x_2 + \cdots + b_kx_k</span>, the <span class="math inline">x</span>’s are the independent variables and <span class="math inline">a</span> is more or less an intercept — with two independent variables the equation describes a <strong>plane</strong> rather than a line.</p>
<p>The <span class="math inline">b</span>’s are called <strong>partial regression coefficients</strong>. Each <span class="math inline">b</span> represents the amount of change in <span class="math inline">y'</span> for <strong>one unit of change in the corresponding <span class="math inline">x</span> value when the other <span class="math inline">x</span> values are held constant</strong>.</p>
</div>
</div>
</div>
<p>For <span class="math inline">y' = 844.016 + 205.440x_1 + 142.098x_2</span>: each additional 100 km of distance raises the predicted shipping cost by <span class="math inline">205.440</span> NT dollars with weight held constant, and each additional kilogram raises it by <span class="math inline">142.098</span> NT dollars with distance held constant.</p>
</section>
<section id="assumptions-for-multiple-regression" class="slide level2">
<h2>Assumptions for Multiple Regression</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Five Assumptions</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>For any specific value of the independent variable, the values of the <span class="math inline">y</span> variable are <strong>normally distributed</strong> (the <em>normality</em> assumption).</li>
<li>The variances (or standard deviations) for the <span class="math inline">y</span> variables are the <strong>same for each value</strong> of the independent variable (the <em>equal-variance</em> assumption).</li>
<li>There is a <strong>linear relationship</strong> between the dependent variable and the independent variables (the <em>linearity</em> assumption).</li>
<li>The independent variables are <strong>not correlated</strong> (the <em>nonmulticollinearity</em> assumption).</li>
<li>The values for the <span class="math inline">y</span> variables are <strong>independent</strong> (the <em>independence</em> assumption).</li>
</ol>
</div>
</div>
</div>
</section>
<section id="the-multiple-correlation-coefficient-r" class="slide level2">
<h2>The Multiple Correlation Coefficient <span class="math inline">R</span></h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Multiple Correlation Coefficient</strong></p>
</div>
<div class="callout-content">
<p>The strength of the relationship between the independent variables and the dependent variable is measured by the <strong>multiple correlation coefficient</strong>, symbolized by <span class="math inline">R</span>.</p>
<p>The value of <span class="math inline">R</span> can range from <span class="math inline">0</span> to <span class="math inline">+1</span> and <strong>can never be negative</strong>. The closer to <span class="math inline">+1</span>, the stronger the relationship. <span class="math inline">R</span> takes into account all the independent variables and is <strong>always higher than the individual correlation coefficients</strong>.</p>
</div>
</div>
</div>
</section>
<section id="formula-for-the-multiple-correlation-coefficient" class="slide level2">
<h2>Formula for the Multiple Correlation Coefficient</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Formula for <span class="math inline">R</span> with Two Independent Variables</strong></p>
</div>
<div class="callout-content">
<p><span class="math display">R = \sqrt{\frac{r_{yx_1}^2 + r_{yx_2}^2 - 2r_{yx_1} \cdot r_{yx_2} \cdot r_{x_1x_2}}{1 - r_{x_1x_2}^2}}</span></p>
<p>where <span class="math inline">r_{yx_1}</span> is the correlation coefficient for <span class="math inline">y</span> and <span class="math inline">x_1</span>, <span class="math inline">r_{yx_2}</span> is the correlation coefficient for <span class="math inline">y</span> and <span class="math inline">x_2</span>, and <span class="math inline">r_{x_1x_2}</span> is the correlation coefficient for <span class="math inline">x_1</span> and <span class="math inline">x_2</span>.</p>
</div>
</div>
</div>
</section>
<section id="example-10-15" class="slide level2">
<h2>Example 10-15</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Shipping Costs</strong></p>
</div>
<div class="callout-content">
<p>For the data on the five international shipments, find the value of <span class="math inline">R</span>. The values of the correlation coefficients are <span class="math inline">r_{yx_1} = 0.744</span>, <span class="math inline">r_{yx_2} = 0.890</span> and <span class="math inline">r_{x_1x_2} = 0.381</span>.</p>
<p>Back to <a href="#/example-10-16">Example 10-16</a> and <a href="#/example-10-17">Example 10-17</a></p>
</div>
</div>
</div>
</section>
<section id="example-10-15-1" class="slide level2">
<h2>Example 10-15</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><span class="math display">R = \sqrt{\frac{(0.744)^2 + (0.890)^2 - 2(0.744)(0.890)(0.381)}{1 - 0.381^2}} = \sqrt{\frac{0.841070}{0.854839}} = \sqrt{0.983893} = 0.992</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href=""></a>r_cost_distance   <span class="ot">&lt;-</span> <span class="fu">cor</span>(shipping_cost, distance)</span>
<span id="cb57-2"><a href=""></a>r_cost_weight     <span class="ot">&lt;-</span> <span class="fu">cor</span>(shipping_cost, weight)</span>
<span id="cb57-3"><a href=""></a>r_distance_weight <span class="ot">&lt;-</span> <span class="fu">cor</span>(distance, weight)</span>
<span id="cb57-4"><a href=""></a></span>
<span id="cb57-5"><a href=""></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">r_yx1 =</span> r_cost_distance, <span class="at">r_yx2 =</span> r_cost_weight,</span>
<span id="cb57-6"><a href=""></a>        <span class="at">r_x1x2 =</span> r_distance_weight), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> r_yx1  r_yx2 r_x1x2 
 0.744  0.890  0.381 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href=""></a>multiple_r <span class="ot">&lt;-</span> <span class="fu">sqrt</span>((r_cost_distance<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> r_cost_weight<span class="sc">^</span><span class="dv">2</span> <span class="sc">-</span></span>
<span id="cb59-2"><a href=""></a>                    <span class="dv">2</span> <span class="sc">*</span> r_cost_distance <span class="sc">*</span> r_cost_weight <span class="sc">*</span> r_distance_weight) <span class="sc">/</span></span>
<span id="cb59-3"><a href=""></a>                   (<span class="dv">1</span> <span class="sc">-</span> r_distance_weight<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb59-4"><a href=""></a></span>
<span id="cb59-5"><a href=""></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">formula =</span> multiple_r,</span>
<span id="cb59-6"><a href=""></a>        <span class="at">from_model =</span> <span class="fu">sqrt</span>(<span class="fu">summary</span>(model_shipping)<span class="sc">$</span>r.squared)), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   formula from_model 
     0.992      0.992 </code></pre>
</div>
</div>
<p>The correlation between the distance and weight of a parcel and its shipping cost is <strong>0.992</strong>: a strong relationship, since <span class="math inline">R</span> is close to <span class="math inline">1.00</span>. It is higher than either individual coefficient, <span class="math inline">0.744</span> and <span class="math inline">0.890</span>.</p>
</div>
</div>
</div>
</section>
<section id="coefficient-of-multiple-determination" class="slide level2">
<h2>Coefficient of Multiple Determination</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong><span class="math inline">R^2</span> and the Residual Variation</strong></p>
</div>
<div class="callout-content">
<p>As with simple regression, <span class="math inline">R^2</span> is the <strong>coefficient of multiple determination</strong>: the amount of variation explained by the regression model.</p>
<p>The expression <span class="math inline">1 - R^2</span> represents the amount of unexplained variation, called the <strong>error</strong> or <strong>residual variation</strong>.</p>
</div>
</div>
</div>
<p>In <a href="#/example-10-15">Example 10-15</a>, <span class="math inline">R = 0.992</span> and, to four decimal places, <span class="math inline">R^2 = 0.9832</span>, so <span class="math inline">1 - R^2 = 0.0168</span>.</p>
</section>
<section id="testing-the-significance-of-r-1" class="slide level2">
<h2>Testing the Significance of <span class="math inline">R</span></h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong><span class="math inline">F</span> Test for Significance of <span class="math inline">R</span></strong></p>
</div>
<div class="callout-content">
<p>The hypotheses are <span class="math inline">H_0: \rho = 0</span> and <span class="math inline">H_1: \rho \neq 0</span>, where <span class="math inline">\rho</span> is the population correlation coefficient for multiple correlation. The test statistic is</p>
<p><span class="math display">F = \frac{R^2 / k}{(1 - R^2)/(n - k - 1)}</span></p>
<p>where <span class="math inline">n</span> is the number of data groups <span class="math inline">(x_1, x_2, \ldots, y)</span> and <span class="math inline">k</span> is the number of independent variables.</p>
<p>The degrees of freedom are <span class="math inline">\text{d.f.N.} = n - k</span> and <span class="math inline">\text{d.f.D.} = n - k - 1</span>.</p>
</div>
</div>
</div>
</section>
<section id="example-10-16" class="slide level2">
<h2>Example 10-16</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Shipping Costs</strong></p>
</div>
<div class="callout-content">
<p>Test the significance of the <span class="math inline">R</span> obtained in <a href="#/example-10-15">Example 10-15</a> at <span class="math inline">\alpha = 0.05</span>.</p>
</div>
</div>
</div>
</section>
<section id="example-10-16-1" class="slide level2">
<h2>Example 10-16</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p>Here <span class="math inline">k = 2</span> and <span class="math inline">n - k - 1 = 2</span>, so the two divisors cancel and</p>
<p><span class="math display">F = \frac{R^2/k}{(1-R^2)/(n-k-1)} = \frac{R^2}{1-R^2} = 58.6</span></p>
<p>The critical value obtained from Table A-7 with <span class="math inline">\alpha = 0.05</span>, <span class="math inline">\text{d.f.N.} = n - k = 3</span> and <span class="math inline">\text{d.f.D.} = n - k - 1 = 2</span> is <span class="math inline">19.16</span>.</p>
<p>Hence, the decision is to <strong>reject the null hypothesis</strong> and conclude that there is a <strong>significant relationship</strong> among the distance a parcel travels, its weight and its shipping cost.</p>
</div>
</div>
</div>
</section>
<section id="example-10-16-2" class="slide level2">
<h2>Example 10-16</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Compute in R</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href=""></a>n_shipments <span class="ot">&lt;-</span> <span class="fu">length</span>(shipping_cost)</span>
<span id="cb61-2"><a href=""></a>k_variables <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb61-3"><a href=""></a></span>
<span id="cb61-4"><a href=""></a>r_squared_shipping <span class="ot">&lt;-</span> <span class="fu">summary</span>(model_shipping)<span class="sc">$</span>r.squared</span>
<span id="cb61-5"><a href=""></a>f_statistic <span class="ot">&lt;-</span> (r_squared_shipping <span class="sc">/</span> k_variables) <span class="sc">/</span></span>
<span id="cb61-6"><a href=""></a>  ((<span class="dv">1</span> <span class="sc">-</span> r_squared_shipping) <span class="sc">/</span> (n_shipments <span class="sc">-</span> k_variables <span class="sc">-</span> <span class="dv">1</span>))</span>
<span id="cb61-7"><a href=""></a></span>
<span id="cb61-8"><a href=""></a><span class="fu">round</span>(r_squared_shipping, <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9832</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href=""></a><span class="fu">round</span>(f_statistic, <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 58.6</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href=""></a><span class="fu">round</span>(<span class="fu">qf</span>(<span class="fl">0.95</span>, <span class="at">df1 =</span> n_shipments <span class="sc">-</span> k_variables,</span>
<span id="cb65-2"><a href=""></a>         <span class="at">df2 =</span> n_shipments <span class="sc">-</span> k_variables <span class="sc">-</span> <span class="dv">1</span>), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 19.16</code></pre>
</div>
</div>
<p><span class="math inline">F = 58.6 &gt; 19.16</span>, so reject <span class="math inline">H_0</span>.</p>
</div>
</div>
</div>
</section>
<section id="adjusted-r2" class="slide level2">
<h2>Adjusted <span class="math inline">R^2</span></h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Why Adjust <span class="math inline">R^2</span></strong></p>
</div>
<div class="callout-content">
<p>Since the value of <span class="math inline">R^2</span> depends on <span class="math inline">n</span> (the number of data pairs) and <span class="math inline">k</span> (the number of variables), statisticians also calculate an <strong>adjusted <span class="math inline">R^2</span></strong>, denoted <span class="math inline">R^2_{adj}</span>, which is based on the number of degrees of freedom.</p>
</div>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Formula for the Adjusted <span class="math inline">R^2</span></strong></p>
</div>
<div class="callout-content">
<p><span class="math display">R^2_{adj} = 1 - \frac{(1-R^2)(n-1)}{n-k-1}</span></p>
</div>
</div>
</div>
<p>The adjusted <span class="math inline">R^2</span> is <strong>smaller than <span class="math inline">R^2</span></strong> and takes into account that when <span class="math inline">n</span> and <span class="math inline">k</span> are approximately equal, <span class="math inline">R</span> may be artificially high because of sampling error rather than a true relationship. Both <span class="math inline">R^2</span> and <span class="math inline">R^2_{adj}</span> are usually reported.</p>
</section>
<section id="example-10-17" class="slide level2">
<h2>Example 10-17</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Shipping Costs</strong></p>
</div>
<div class="callout-content">
<p>Calculate the adjusted <span class="math inline">R^2</span> for the data in <a href="#/example-10-15">Example 10-15</a>. The value for <span class="math inline">R</span> is <span class="math inline">0.992</span>, so <span class="math inline">R^2 = 0.9832</span>.</p>
</div>
</div>
</div>
</section>
<section id="example-10-17-1" class="slide level2">
<h2>Example 10-17</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><span class="math display">R^2_{adj} = 1 - \frac{(1-R^2)(n-1)}{n-k-1} = 1 - \frac{(1 - 0.9832)(5-1)}{5-2-1} = 1 - 0.0336 = 0.966</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb67"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href=""></a>adjusted_r_squared <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> (<span class="dv">1</span> <span class="sc">-</span> r_squared_shipping) <span class="sc">*</span> (n_shipments <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">/</span></span>
<span id="cb67-2"><a href=""></a>  (n_shipments <span class="sc">-</span> k_variables <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb67-3"><a href=""></a></span>
<span id="cb67-4"><a href=""></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">formula =</span> adjusted_r_squared,</span>
<span id="cb67-5"><a href=""></a>        <span class="at">from_model =</span> <span class="fu">summary</span>(model_shipping)<span class="sc">$</span>adj.r.squared), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   formula from_model 
     0.966      0.966 </code></pre>
</div>
</div>
<p>When the number of data groups and the number of independent variables are accounted for, the adjusted multiple coefficient of determination is <strong>0.966</strong>.</p>
</div>
</div>
</div>
</section>
<section id="important-terms" class="slide level2">
<h2>Important Terms</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Chapter 10 Vocabulary</strong></p>
</div>
<div class="callout-content">
<p>adjusted <span class="math inline">R^2</span> · coefficient of determination · coefficient of multiple determination · correlation · correlation coefficient · dependent variable · extrapolation · independent variable · influential point or observation · lurking variable · marginal change · multiple correlation coefficient · multiple regression · negative linear relationship · Pearson product moment correlation coefficient (PPMC) · population correlation coefficient · positive linear relationship · prediction interval · regression line · residual · residual plot · scatter plot · standard error of the estimate</p>
</div>
</div>
</div>
</section>
<section id="key-formulas" class="slide level2">
<h2>Key Formulas</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Correlation and the Regression Line</strong></p>
</div>
<div class="callout-content">
<p>The correlation coefficient:</p>
<p><span class="math display">r = \frac{n(\sum xy) - (\sum x)(\sum y)}{\sqrt{[n(\sum x^2) - (\sum x)^2][n(\sum y^2) - (\sum y)^2]}}</span></p>
<p>The <span class="math inline">t</span> test for the correlation coefficient, <span class="math inline">\text{d.f.} = n - 2</span>:</p>
<p><span class="math display">t = r\sqrt{\frac{n-2}{1-r^2}}</span></p>
<p>The regression line equation <span class="math inline">y' = a + bx</span>, where</p>
<p><span class="math display">a = \frac{(\sum y)(\sum x^2) - (\sum x)(\sum xy)}{n(\sum x^2) - (\sum x)^2} \qquad b = \frac{n(\sum xy) - (\sum x)(\sum y)}{n(\sum x^2) - (\sum x)^2}</span></p>
</div>
</div>
</div>
</section>
<section id="key-formulas-1" class="slide level2">
<h2>Key Formulas</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Variation, Prediction and Multiple Regression</strong></p>
</div>
<div class="callout-content">
<p>The standard error of the estimate:</p>
<p><span class="math display">s_{est} = \sqrt{\frac{\sum(y-y')^2}{n-2}} \qquad \text{or} \qquad s_{est} = \sqrt{\frac{\sum y^2 - a\sum y - b\sum xy}{n-2}}</span></p>
<p>The prediction interval for a value <span class="math inline">y'</span>, <span class="math inline">\text{d.f.} = n - 2</span>:</p>
<p><span class="math display">y' \pm t_{\alpha/2}\, s_{est} \sqrt{1 + \frac{1}{n} + \frac{n(x - \bar{x})^2}{n\sum x^2 - (\sum x)^2}}</span></p>
<p>The multiple correlation coefficient, the <span class="math inline">F</span> test for <span class="math inline">R</span> with <span class="math inline">\text{d.f.N.} = n - k</span> and <span class="math inline">\text{d.f.D.} = n - k - 1</span>, and the adjusted <span class="math inline">R^2</span>:</p>
<p><span class="math display">R = \sqrt{\frac{r_{yx_1}^2 + r_{yx_2}^2 - 2r_{yx_1} r_{yx_2} r_{x_1x_2}}{1 - r_{x_1x_2}^2}} \qquad F = \frac{R^2/k}{(1-R^2)/(n-k-1)} \qquad R^2_{adj} = 1 - \frac{(1-R^2)(n-1)}{n-k-1}</span></p>
</div>
</div>
</div>
</section>
<section id="key-takeaways" class="slide level2">
<h2>Key Takeaways</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Key point</strong></p>
</div>
<div class="callout-content">
<ul>
<li>A <strong>scatter plot</strong> of the ordered pairs <span class="math inline">(x, y)</span> shows whether the relationship between the independent variable <span class="math inline">x</span> and the dependent variable <span class="math inline">y</span> is positive linear, negative linear, curvilinear or nonexistent</li>
<li>The <strong>linear correlation coefficient</strong> <span class="math inline">r</span> measures the strength and direction of a linear relationship, <span class="math inline">-1 \leq r \leq 1</span>; it is unitless, unchanged when <span class="math inline">x</span> and <span class="math inline">y</span> are interchanged or rescaled, and sensitive to outliers; round <span class="math inline">r</span> to three decimal places</li>
<li>Test <span class="math inline">H_0: \rho = 0</span> against <span class="math inline">H_1: \rho \neq 0</span> with <span class="math inline">t = r\sqrt{(n-2)/(1-r^2)}</span> and <span class="math inline">\text{d.f.} = n - 2</span> using Table A-5, with the P-value method, or by comparing <span class="math inline">r</span> directly with the two-tailed critical values of Table A-8</li>
<li>A significant <span class="math inline">r</span> does <strong>not</strong> prove causation: the five possibilities are direct cause and effect, reverse cause and effect, a third (lurking) variable, a complexity of interrelationships, and coincidence</li>
<li>The <strong>regression line</strong> <span class="math inline">y' = a + bx</span> is the line of best fit found by the method of least squares; round <span class="math inline">a</span> and <span class="math inline">b</span> to three decimal places, and compute it only when <span class="math inline">r</span> is significant</li>
</ul>
</div>
</div>
</div>
</section>
<section id="key-takeaways-1" class="slide level2">
<h2>Key Takeaways</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Key point</strong></p>
</div>
<div class="callout-content">
<ul>
<li>The slope <span class="math inline">b</span> is the <strong>marginal change</strong> in <span class="math inline">y</span> per one-unit change in <span class="math inline">x</span>; <strong>extrapolation</strong> beyond the observed <span class="math inline">x</span> values is unreliable, and influential points can pull the line toward themselves</li>
<li>Total variation <span class="math inline">=</span> explained variation <span class="math inline">+</span> unexplained variation; the <strong>residual plot</strong> shows whether the line is suitable for predictions, and <span class="math inline">r^2</span> is the proportion of variation explained, with <span class="math inline">1 - r^2</span> the <strong>coefficient of nondetermination</strong></li>
<li>The <strong>standard error of the estimate</strong> <span class="math inline">s_{est}</span> measures the spread of the observed <span class="math inline">y</span> values about the regression line and is used to build a <strong>prediction interval</strong> with <span class="math inline">\text{d.f.} = n - 2</span></li>
<li>In <strong>multiple regression</strong> <span class="math inline">y' = a + b_1x_1 + \cdots + b_kx_k</span> the <span class="math inline">b</span>’s are partial regression coefficients; <span class="math inline">R</span> is never negative and is always higher than the individual correlation coefficients, its significance is tested with an <span class="math inline">F</span> test, and <span class="math inline">R^2_{adj}</span> corrects <span class="math inline">R^2</span> for <span class="math inline">n</span> and <span class="math inline">k</span></li>
</ul>
</div>
</div>
</div>
</section>
<section id="acknowledgement" class="slide level2">
<h2>Acknowledgement</h2>
<ul>
<li><p><strong>Copyright notice.</strong> These teaching materials follow the organization and terminology of <strong>Bluman, A. G. (2023). Elementary statistics: A step by step approach (11th ed.). McGraw Hill</strong>. All rights in the original work are reserved by its authors and publishers.</p></li>
<li><p><strong>Original examples.</strong> Every worked example, data set, and R script in these slides was written for this course. The data are hypothetical unless stated otherwise.</p></li>
<li><p><strong>Non-commercial use only.</strong> These materials are strictly intended for educational purposes and must not be used for commercial gain or profit.</p></li>
<li><p><strong>Proper attribution.</strong> Any reproduction, distribution, or use of these materials must provide proper attribution to the original source.</p></li>
</ul>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="logo.svg" class="slide-logo"></p>
<div class="footer footer-default">
<p>Elementary Statistics: A Step by Step Approach</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="ch10_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="ch10_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="ch10_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="ch10_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="ch10_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="ch10_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="ch10_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="ch10_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="ch10_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":false,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true,"hideMissingTitles":true,"titleSelector":"h1"},
'smaller': true,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    <script>
    Reveal.on('ready', function() {
      var title = Reveal.getSlides()[0];
      if (title) {
        title.insertAdjacentHTML('beforeend',
          '<p style="font-size:0.5em; margin-top:1.5em;">' +
          '<a href="ch10-zh.html"  style="color:#555;">[中文版由此去]</a>' +
          '</p>');
      }
    });
    </script>
    

</body></html>