<!DOCTYPE html>
<html lang="en"><head>
<script src="ch9_files/libs/clipboard/clipboard.min.js"></script>
<script src="ch9_files/libs/quarto-html/tabby.min.js"></script>
<script src="ch9_files/libs/quarto-html/popper.min.js"></script>
<script src="ch9_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="ch9_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="ch9_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="ch9_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.38">

  <meta name="author" content="Yu-You Liou">
  <meta name="dcterms.date" content="2026-09-20">
  <title>Statistics</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="ch9_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="ch9_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="ch9_files/libs/revealjs/dist/theme/quarto-2abc1c5b7b5c7eecd6137558e106e4c3.css">
  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">
  <link href="ch9_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="ch9_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="ch9_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="ch9_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-notes="" class="quarto-title-block center">
  <h1 class="title">Statistics</h1>
  <p class="subtitle">Chapter 9: Testing the Difference Between Two Means, Two Proportions, and Two Variances</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Yu-You Liou 
</div>
        <p class="quarto-title-affiliation">
            Shih Chien University
          </p>
    </div>
</div>

  <p class="date">2026-09-20</p>
</section>
<section id="overview" class="slide level2">
<h2>Overview</h2>
<p>Chapter 9 extends hypothesis testing from <strong>one parameter</strong> to the <strong>comparison of two parameters</strong> — two means, two proportions, or two variances — using the same five-step procedure introduced in Chapter 8.</p>
<table class="caption-top">
<colgroup>
<col style="width: 52%">
<col style="width: 47%">
</colgroup>
<thead>
<tr class="header">
<th>Section</th>
<th>Topics</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>9-1</td>
<td>Two-parameter comparisons; independent vs.&nbsp;dependent samples; distribution of <span class="math inline">\bar{X}_1 - \bar{X}_2</span></td>
</tr>
<tr class="even">
<td>9-2</td>
<td><span class="math inline">z</span> test for two means (<span class="math inline">\sigma</span> known); testing a specific difference; <span class="math inline">z</span> CI for <span class="math inline">\mu_1 - \mu_2</span></td>
</tr>
<tr class="odd">
<td>9-3</td>
<td><span class="math inline">t</span> test, independent samples (<span class="math inline">\sigma</span> unknown); d.f. rule; pooled variance; <span class="math inline">t</span> CI</td>
</tr>
</tbody>
</table>
</section>
<section id="overview-continued" class="slide level2">
<h2>Overview (continued)</h2>
<table class="caption-top">
<colgroup>
<col style="width: 52%">
<col style="width: 47%">
</colgroup>
<thead>
<tr class="header">
<th>Section</th>
<th>Topics</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>9-4</td>
<td>Dependent (matched-pair) samples; <span class="math inline">t</span> test on <span class="math inline">\bar{D}</span>, <span class="math inline">s_D</span>; procedure table; CI for <span class="math inline">\mu_D</span></td>
</tr>
<tr class="even">
<td>9-5</td>
<td><span class="math inline">z</span> test for two proportions; weighted <span class="math inline">\bar{p}</span>, <span class="math inline">\bar{q}</span>; CI for <span class="math inline">p_1 - p_2</span></td>
</tr>
<tr class="odd">
<td>9-6</td>
<td><span class="math inline">F</span> distribution; <span class="math inline">F</span> test for two variances; d.f.N., d.f.D.; cautions</td>
</tr>
</tbody>
</table>
</section>
<section id="chapter-objectives" class="slide level2">
<h2>Chapter Objectives</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>After completing this chapter, you should be able to</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>Test the difference between two means, using the <span class="math inline">z</span> test.</li>
<li>Test the difference between two means for independent samples, using the <span class="math inline">t</span> test.</li>
<li>Test the difference between two means for dependent samples.</li>
<li>Test the difference between two proportions.</li>
<li>Test the difference between two variances or standard deviations.</li>
</ol>
</div>
</div>
</div>
</section>
<section>
<section id="section-9-1-testing-the-difference-between-two-parameters" class="title-slide slide level1 center" data-background-color="#2c4a6e">
<h1>Section 9-1: Testing the Difference Between Two Parameters</h1>

</section>
<section id="comparing-two-groups" class="slide level2">
<h2>Comparing Two Groups</h2>
<p>In Chapter 8 a single sample mean, variance, or proportion was compared with a <em>specific</em> population value. Researchers, however, often want to compare <strong>two groups</strong> — an experimental group and a control group, two brands of bus tires, two fertilizers, two brands of cough syrup.</p>
<p>Suppose a researcher asks: <em>Does the mean age of nursing students who enroll at a community college differ from the mean age of nursing students who enroll at a university?</em> The researcher is not interested in the mean age of all beginning nursing students; the interest is in <strong>comparing the means of the two groups</strong>.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Two Equivalent Ways of Stating the Hypotheses</strong></p>
</div>
<div class="callout-content">
<p><span class="math display">H_0:\ \mu_1 = \mu_2 \qquad H_1:\ \mu_1 \neq \mu_2</span></p>
<p>or, equivalently,</p>
<p><span class="math display">H_0:\ \mu_1 - \mu_2 = 0 \qquad H_1:\ \mu_1 - \mu_2 \neq 0</span></p>
<p>If there is no difference in the population means, subtracting them gives zero; if they differ, subtracting gives a number other than zero. Both statements are correct; <strong>this text uses the first form</strong> when the hypothesized difference is zero.</p>
</div>
</div>
</div>
</section>
<section id="hypotheses-for-means-and-for-proportions" class="slide level2">
<h2>Hypotheses for Means and for Proportions</h2>
<p>The same reasoning applies to proportions. If a researcher believes the percentage of male workers who work more than 5 days a week differs from the percentage of female workers who do, the hypotheses are <span class="math inline">H_0:\ p_1 = p_2</span> and <span class="math inline">H_1:\ p_1 \neq p_2</span> (or <span class="math inline">H_0:\ p_1 - p_2 = 0</span> and <span class="math inline">H_1:\ p_1 - p_2 \neq 0</span>).</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Two-Tailed, Right-Tailed, and Left-Tailed Forms</strong></p>
</div>
<div class="callout-content">
<table class="caption-top">
<colgroup>
<col style="width: 23%">
<col style="width: 26%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Test</th>
<th>Means</th>
<th>Proportions</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Two-tailed</td>
<td><span class="math inline">H_0:\ \mu_1 = \mu_2</span>; <span class="math inline">H_1:\ \mu_1 \neq \mu_2</span></td>
<td><span class="math inline">H_0:\ p_1 = p_2</span>; <span class="math inline">H_1:\ p_1 \neq p_2</span></td>
</tr>
<tr class="even">
<td>Right-tailed</td>
<td><span class="math inline">H_0:\ \mu_1 = \mu_2</span>; <span class="math inline">H_1:\ \mu_1 &gt; \mu_2</span></td>
<td><span class="math inline">H_0:\ p_1 = p_2</span>; <span class="math inline">H_1:\ p_1 &gt; p_2</span></td>
</tr>
<tr class="odd">
<td>Left-tailed</td>
<td><span class="math inline">H_0:\ \mu_1 = \mu_2</span>; <span class="math inline">H_1:\ \mu_1 &lt; \mu_2</span></td>
<td><span class="math inline">H_0:\ p_1 = p_2</span>; <span class="math inline">H_1:\ p_1 &lt; p_2</span></td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="independent-and-dependent-samples" class="slide level2">
<h2>Independent and Dependent Samples</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Independent Samples</strong></p>
</div>
<div class="callout-content">
<p>Two samples are <strong>independent</strong> when the subjects selected for the first sample in no way influence the way the subjects are selected for the second sample.</p>
<p><em>Example:</em> 50 people are randomly divided into two groups of 25 to test a new drug; one group receives the drug and the other a placebo.</p>
</div>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Dependent Samples</strong></p>
</div>
<div class="callout-content">
<p>Two samples are <strong>dependent</strong> when the selection of subjects for the first group in some way influences the selection of subjects for the other group.</p>
<p><em>Example:</em> to see whether a person’s right foot is slightly larger than the left, once a person’s right foot is selected for sample 1, that same person’s left foot must be selected for sample 2.</p>
</div>
</div>
</div>
</section>
<section id="the-distribution-of-the-differences-of-means" class="slide level2">
<h2>The Distribution of the Differences of Means</h2>
<p>The theory behind testing the difference between two means is based on selecting <strong>pairs of samples</strong> and comparing the means of the pairs. The population means need not be known.</p>
<p>All possible pairs of samples are taken from the populations; the means of each pair are computed and subtracted, and the differences are plotted. If both populations have the same mean, most differences will be zero or close to zero, with a few large differences — some positive, some negative — due to chance alone. The resulting curve is shaped like a normal distribution with a mean of zero (Figure 9-1).</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>General Formula for the Test Statistic</strong></p>
</div>
<div class="callout-content">
<p><span class="math display">\text{Test statistic} = \frac{(\text{observed value}) - (\text{expected value})}{\text{standard error}}</span></p>
<p>Every test in this chapter — for two means, two proportions, and (in a different form) two variances — is a special case of this format.</p>
</div>
</div>
</div>
</section>
<section id="distribution-of-differences-of-means-in-r" class="slide level2">
<h2>Distribution of Differences of Means in R</h2>
<p><strong>Draw figure</strong> — a simulation of Figure 9-1: repeatedly draw two samples from populations with the <em>same</em> mean and plot <span class="math inline">\bar{X}_1 - \bar{X}_2</span>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href=""></a><span class="fu">set.seed</span>(<span class="dv">2023</span>)</span>
<span id="cb1-2"><a href=""></a>mean_differences <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">5000</span>,</span>
<span id="cb1-3"><a href=""></a>  <span class="fu">mean</span>(<span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="dv">100</span>, <span class="dv">15</span>)) <span class="sc">-</span> <span class="fu">mean</span>(<span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="dv">100</span>, <span class="dv">15</span>)))</span>
<span id="cb1-4"><a href=""></a><span class="fu">ggplot</span>(<span class="fu">data.frame</span>(<span class="at">difference =</span> mean_differences), <span class="fu">aes</span>(difference)) <span class="sc">+</span></span>
<span id="cb1-5"><a href=""></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">40</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">colour =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb1-6"><a href=""></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb1-7"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Differences of Means of Pairs of Samples"</span>,</span>
<span id="cb1-8"><a href=""></a>       <span class="at">x =</span> <span class="st">"Xbar1 - Xbar2"</span>, <span class="at">y =</span> <span class="st">"Frequency"</span>) <span class="sc">+</span></span>
<span id="cb1-9"><a href=""></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="ch9_files/figure-revealjs/s9-1-1-1.png" class="quarto-figure quarto-figure-center r-stretch" style="width:70.0%"><p>The differences centre on <strong>zero</strong>: when <span class="math inline">\mu_1 = \mu_2</span>, a difference far from zero is unlikely by chance alone, and that is what makes the test work.</p>
</section></section>
<section>
<section id="section-9-2-testing-the-difference-between-two-means-using-the-z-test" class="title-slide slide level1 center" data-background-color="#2c4a6e">
<h1>Section 9-2: Testing the Difference Between Two Means: Using the z Test</h1>

</section>
<section id="assumptions-for-the-z-test" class="slide level2">
<h2>Assumptions for the z Test</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Assumptions for the z Test to Determine the Difference Between Two Means</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>Both samples are <strong>random samples</strong>.</li>
<li>The samples must be <strong>independent</strong> of each other — there can be no relationship between the subjects in each sample.</li>
<li>The <strong>standard deviations of both populations must be known</strong>; and if the sample sizes are less than 30, the populations must be normally or approximately normally distributed.</li>
</ol>
</div>
</div>
</div>
<p>In this book the assumptions are stated in the exercises; in other situations you must check that they have been met before proceeding.</p>
</section>
<section id="formula-for-the-z-test-for-two-means" class="slide level2">
<h2>Formula for the z Test for Two Means</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>z Test for Comparing Two Means from Independent Populations</strong></p>
</div>
<div class="callout-content">
<p><span class="math display">z = \frac{(\bar{X}_1 - \bar{X}_2) - (\mu_1 - \mu_2)}{\sqrt{\dfrac{\sigma_1^2}{n_1} + \dfrac{\sigma_2^2}{n_2}}}</span></p>
<p>The denominator is the <strong>standard error of the difference</strong>, because the variance of <span class="math inline">\bar{X}_1 - \bar{X}_2</span> is the <em>sum</em> of the individual variances:</p>
<p><span class="math display">\sigma^2_{\bar{X}_1 - \bar{X}_2} = \sigma^2_{\bar{X}_1} + \sigma^2_{\bar{X}_2} = \frac{\sigma_1^2}{n_1} + \frac{\sigma_2^2}{n_2}</span></p>
<p>Here <span class="math inline">\bar{X}_1 - \bar{X}_2</span> is the observed value and <span class="math inline">\mu_1 - \mu_2</span> is the expected value, which equals <strong>zero</strong> when <span class="math inline">H_0:\ \mu_1 = \mu_2</span>.</p>
</div>
</div>
</div>
</section>
<section id="the-two-testing-procedures" class="slide level2">
<h2>The Two Testing Procedures</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Traditional Method</strong></p>
</div>
<div class="callout-content">
<table class="caption-top">
<thead>
<tr class="header">
<th>Step</th>
<th>Action</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>State the hypotheses and identify the claim.</td>
</tr>
<tr class="even">
<td>2</td>
<td>Find the critical value(s).</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Compute the test statistic.</td>
</tr>
<tr class="even">
<td>4</td>
<td>Make the decision.</td>
</tr>
<tr class="odd">
<td>5</td>
<td>Summarize the results.</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>P-Value Method</strong></p>
</div>
<div class="callout-content">
<table class="caption-top">
<thead>
<tr class="header">
<th>Step</th>
<th>Action</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>State the hypotheses and identify the claim.</td>
</tr>
<tr class="even">
<td>2</td>
<td>Compute the test statistic.</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Find the P-value.</td>
</tr>
<tr class="even">
<td>4</td>
<td>Make the decision.</td>
</tr>
<tr class="odd">
<td>5</td>
<td>Summarize the results.</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The critical values are the same ones used in Section 8-2.</p>
</section>
<section id="example-9-1" class="slide level2">
<h2>Example 9-1</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Average Order Value by Channel</strong></p>
</div>
<div class="callout-content">
<p>An e-commerce platform in Taipei compares the average order value of purchases placed through its mobile app with purchases placed through its website. Random samples of 40 app orders and 40 website orders gave mean order values of NT$1685 and NT$1512. From several years of transaction records the population standard deviations are taken to be NT$320 for app orders and NT$285 for website orders. At <span class="math inline">\alpha = 0.05</span>, can it be concluded that there is a significant difference in the mean order value of the two channels? <em>(hypothetical data)</em></p>
<pre><code>                   App      Website
Sample mean       1685         1512
sigma              320          285
n                   40           40</code></pre>
<p>Back to <a href="#/example-9-3">Example 9-3</a></p>
</div>
</div>
</div>
</section>
<section id="example-9-1-1" class="slide level2">
<h2>Example 9-1</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> State the hypotheses and identify the claim.</p>
<p><span class="math display">H_0:\ \mu_1 = \mu_2 \qquad H_1:\ \mu_1 \neq \mu_2 \ \textit{(claim)}</span></p>
<p><strong>Step 2.</strong> Find the critical values. Since <span class="math inline">\alpha = 0.05</span> and the test is two-tailed, the critical values are <span class="math inline">-1.96</span> and <span class="math inline">+1.96</span>.</p>
<p><strong>Step 3.</strong> Compute the test statistic.</p>
<p><span class="math display">z = \frac{(1685 - 1512) - 0}{\sqrt{\dfrac{320^2}{40} + \dfrac{285^2}{40}}} = \frac{173}{67.75} = 2.55</span></p>
</div>
</div>
</div>
</section>
<section id="example-9-1-2" class="slide level2">
<h2>Example 9-1</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 3 in R</strong> — critical values, test statistic, and P-value.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href=""></a>mean_app <span class="ot">&lt;-</span> <span class="dv">1685</span>; sigma_app <span class="ot">&lt;-</span> <span class="dv">320</span>; n_app <span class="ot">&lt;-</span> <span class="dv">40</span></span>
<span id="cb3-2"><a href=""></a>mean_web <span class="ot">&lt;-</span> <span class="dv">1512</span>; sigma_web <span class="ot">&lt;-</span> <span class="dv">285</span>; n_web <span class="ot">&lt;-</span> <span class="dv">40</span></span>
<span id="cb3-3"><a href=""></a>se_orders <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(sigma_app<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> n_app <span class="sc">+</span> sigma_web<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> n_web)</span>
<span id="cb3-4"><a href=""></a>z_statistic <span class="ot">&lt;-</span> (mean_app <span class="sc">-</span> mean_web) <span class="sc">/</span> se_orders</span>
<span id="cb3-5"><a href=""></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">standard_error =</span> se_orders, <span class="at">z =</span> z_statistic), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>standard_error              z 
         67.75           2.55 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href=""></a><span class="fu">round</span>(<span class="fu">qnorm</span>(<span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>)), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1.96  1.96</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href=""></a><span class="fu">round</span>(<span class="dv">2</span> <span class="sc">*</span> <span class="fu">pnorm</span>(<span class="fu">abs</span>(z_statistic), <span class="at">lower.tail =</span> <span class="cn">FALSE</span>), <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0107</code></pre>
</div>
</div>
<p><strong>Step 4.</strong> Make the decision. Reject <span class="math inline">H_0</span>, since <span class="math inline">2.55 &gt; 1.96</span> (equivalently <span class="math inline">P = 0.0107 &lt; \alpha = 0.05</span>).</p>
<p><strong>Step 5.</strong> There is enough evidence to say that the mean order value differs between the app channel and the website channel at the 0.05 significance level.</p>
</div>
</div>
</div>
</section>
<section id="example-9-2" class="slide level2">
<h2>Example 9-2</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Order Lines Picked per Order</strong></p>
</div>
<div class="callout-content">
<p>A logistics company hypothesizes that the average number of order lines picked per order is greater at its Taoyuan distribution centre than at its Taichung distribution centre. A random sample of 50 orders from each centre is shown. At <span class="math inline">\alpha = 0.10</span>, is there enough evidence to support the claim? Assume <span class="math inline">\sigma_1</span> and <span class="math inline">\sigma_2 = 4</span>. Use the P-value method. <em>(hypothetical data)</em></p>
<pre><code>            Taoyuan                     Taichung
14   6  16   7  18          13  10  16  10  10
10  13  14   7  11           9  13   8   9  16
18  10  15  16  11          11  17  12   8  14
15   5   7  11  15           8  16   5   8   6
 6  15  16  13   9           8  13   7  16  14
14  15  14   7  19          12  12  18  14  18
16   6  10   6  17          16  15  12   7  11
14  13  11  22  19          20   7   9  14   8
 8  13  11  15  13          11  11  16  15  15
10  14  11  10  14          13  12  15   7   5</code></pre>
</div>
</div>
</div>
</section>
<section id="example-9-2-1" class="slide level2">
<h2>Example 9-2</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> State the hypotheses and identify the claim.</p>
<p><span class="math display">H_0:\ \mu_1 = \mu_2 \qquad H_1:\ \mu_1 &gt; \mu_2 \ \textit{(claim)}</span></p>
<p><strong>Step 2 — compute the test statistic.</strong> First find the mean of each data set.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href=""></a>taoyuan  <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">14</span>,  <span class="dv">6</span>, <span class="dv">16</span>,  <span class="dv">7</span>, <span class="dv">18</span>, <span class="dv">10</span>, <span class="dv">13</span>, <span class="dv">14</span>,  <span class="dv">7</span>, <span class="dv">11</span>,</span>
<span id="cb10-2"><a href=""></a>              <span class="dv">18</span>, <span class="dv">10</span>, <span class="dv">15</span>, <span class="dv">16</span>, <span class="dv">11</span>, <span class="dv">15</span>,  <span class="dv">5</span>,  <span class="dv">7</span>, <span class="dv">11</span>, <span class="dv">15</span>,</span>
<span id="cb10-3"><a href=""></a>               <span class="dv">6</span>, <span class="dv">15</span>, <span class="dv">16</span>, <span class="dv">13</span>,  <span class="dv">9</span>, <span class="dv">14</span>, <span class="dv">15</span>, <span class="dv">14</span>,  <span class="dv">7</span>, <span class="dv">19</span>,</span>
<span id="cb10-4"><a href=""></a>              <span class="dv">16</span>,  <span class="dv">6</span>, <span class="dv">10</span>,  <span class="dv">6</span>, <span class="dv">17</span>, <span class="dv">14</span>, <span class="dv">13</span>, <span class="dv">11</span>, <span class="dv">22</span>, <span class="dv">19</span>,</span>
<span id="cb10-5"><a href=""></a>               <span class="dv">8</span>, <span class="dv">13</span>, <span class="dv">11</span>, <span class="dv">15</span>, <span class="dv">13</span>, <span class="dv">10</span>, <span class="dv">14</span>, <span class="dv">11</span>, <span class="dv">10</span>, <span class="dv">14</span>)</span>
<span id="cb10-6"><a href=""></a>taichung <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">13</span>, <span class="dv">10</span>, <span class="dv">16</span>, <span class="dv">10</span>, <span class="dv">10</span>,  <span class="dv">9</span>, <span class="dv">13</span>,  <span class="dv">8</span>,  <span class="dv">9</span>, <span class="dv">16</span>,</span>
<span id="cb10-7"><a href=""></a>              <span class="dv">11</span>, <span class="dv">17</span>, <span class="dv">12</span>,  <span class="dv">8</span>, <span class="dv">14</span>,  <span class="dv">8</span>, <span class="dv">16</span>,  <span class="dv">5</span>,  <span class="dv">8</span>,  <span class="dv">6</span>,</span>
<span id="cb10-8"><a href=""></a>               <span class="dv">8</span>, <span class="dv">13</span>,  <span class="dv">7</span>, <span class="dv">16</span>, <span class="dv">14</span>, <span class="dv">12</span>, <span class="dv">12</span>, <span class="dv">18</span>, <span class="dv">14</span>, <span class="dv">18</span>,</span>
<span id="cb10-9"><a href=""></a>              <span class="dv">16</span>, <span class="dv">15</span>, <span class="dv">12</span>,  <span class="dv">7</span>, <span class="dv">11</span>, <span class="dv">20</span>,  <span class="dv">7</span>,  <span class="dv">9</span>, <span class="dv">14</span>,  <span class="dv">8</span>,</span>
<span id="cb10-10"><a href=""></a>              <span class="dv">11</span>, <span class="dv">11</span>, <span class="dv">16</span>, <span class="dv">15</span>, <span class="dv">15</span>, <span class="dv">13</span>, <span class="dv">12</span>, <span class="dv">15</span>,  <span class="dv">7</span>,  <span class="dv">5</span>)</span>
<span id="cb10-11"><a href=""></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">n_taoyuan =</span> <span class="fu">length</span>(taoyuan), <span class="at">n_taichung =</span> <span class="fu">length</span>(taichung),</span>
<span id="cb10-12"><a href=""></a>        <span class="at">mean_taoyuan =</span> <span class="fu">mean</span>(taoyuan), <span class="at">mean_taichung =</span> <span class="fu">mean</span>(taichung)), <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    n_taoyuan    n_taichung  mean_taoyuan mean_taichung 
         50.0          50.0          12.4          11.8 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="example-9-2-2" class="slide level2">
<h2>Example 9-2</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 2 (continued).</strong> With <span class="math inline">\bar{X}_1 = 12.4</span>, <span class="math inline">\bar{X}_2 = 11.8</span> and <span class="math inline">\sigma_1 = \sigma_2 = 4</span>,</p>
<p><span class="math display">z = \frac{(12.4 - 11.8) - 0}{\sqrt{\dfrac{4^2}{50} + \dfrac{4^2}{50}}} = 0.75</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href=""></a>sigma_lines <span class="ot">&lt;-</span> <span class="dv">4</span></span>
<span id="cb12-2"><a href=""></a>se_lines <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(sigma_lines<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="fu">length</span>(taoyuan) <span class="sc">+</span></span>
<span id="cb12-3"><a href=""></a>                 sigma_lines<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="fu">length</span>(taichung))</span>
<span id="cb12-4"><a href=""></a>z_statistic <span class="ot">&lt;-</span> (<span class="fu">mean</span>(taoyuan) <span class="sc">-</span> <span class="fu">mean</span>(taichung)) <span class="sc">/</span> se_lines</span>
<span id="cb12-5"><a href=""></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">z =</span> z_statistic,</span>
<span id="cb12-6"><a href=""></a>        <span class="at">p_value =</span> <span class="fu">pnorm</span>(z_statistic, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)), <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      z p_value 
 0.7500  0.2266 </code></pre>
</div>
</div>
<p><strong>Step 3.</strong> Find the P-value. For <span class="math inline">z = 0.75</span> the area to the left is 0.7734, and <span class="math inline">1.0000 - 0.7734 = 0.2266</span>.</p>
<p><strong>Step 4.</strong> Since the P-value is larger than <span class="math inline">\alpha</span> (<span class="math inline">0.2266 &gt; 0.10</span>), do not reject <span class="math inline">H_0</span>.</p>
<p><strong>Step 5.</strong> There is not enough evidence to support the claim that the Taoyuan centre picks more order lines per order than the Taichung centre at the 0.10 level of significance.</p>
</div>
</div>
</div>
</section>
<section id="testing-a-specific-difference" class="slide level2">
<h2>Testing a Specific Difference</h2>
<p>Sometimes the researcher tests a difference in means <strong>other than zero</strong>. For example, a researcher might hypothesize that nursing students at a community college are on average 3.2 years older than those at a university:</p>
<p><span class="math display">H_0:\ \mu_1 - \mu_2 = 3.2 \qquad H_1:\ \mu_1 - \mu_2 &gt; 3.2</span></p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Hypothesized Difference</strong></p>
</div>
<div class="callout-content">
<p>The formula for the <span class="math inline">z</span> test is unchanged; the term <span class="math inline">\mu_1 - \mu_2</span> in the numerator is the <strong>hypothesized difference</strong>, or expected value. In this case <span class="math inline">\mu_1 - \mu_2 = 3.2</span> is substituted instead of 0.</p>
</div>
</div>
</div>
</section>
<section id="confidence-interval-for-mu_1---mu_2-sigma_1-and-sigma_2-known" class="slide level2">
<h2>Confidence Interval for <span class="math inline">\mu_1 - \mu_2</span> (<span class="math inline">\sigma_1</span> and <span class="math inline">\sigma_2</span> Known)</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>z Confidence Interval for the Difference Between Two Means</strong></p>
</div>
<div class="callout-content">
<p><span class="math display">(\bar{X}_1 - \bar{X}_2) - z_{\alpha/2}\sqrt{\frac{\sigma_1^2}{n_1}+\frac{\sigma_2^2}{n_2}} &lt; \mu_1-\mu_2 &lt; (\bar{X}_1 - \bar{X}_2) + z_{\alpha/2}\sqrt{\frac{\sigma_1^2}{n_1}+\frac{\sigma_2^2}{n_2}}</span></p>
<p>When the hypothesized difference is zero: if the confidence interval <strong>contains zero</strong>, <span class="math inline">H_0</span> is not rejected; if it <strong>does not contain zero</strong>, <span class="math inline">H_0</span> is rejected.</p>
</div>
</div>
</div>
</section>
<section id="example-9-3" class="slide level2">
<h2>Example 9-3</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Average Order Value by Channel</strong></p>
</div>
<div class="callout-content">
<p>Find the 95% confidence interval for the difference between the means in <a href="#/example-9-1">Example 9-1</a>.</p>
</div>
</div>
</div>
</section>
<section id="example-9-3-1" class="slide level2">
<h2>Example 9-3</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Substitute in the formula</strong>, using <span class="math inline">z_{\alpha/2} = 1.96</span>.</p>
<p><span class="math display">(1685 - 1512) \pm 1.96\sqrt{\dfrac{320^2}{40} + \dfrac{285^2}{40}} = 173 \pm 132.80</span></p>
<p><span class="math display">40.20 &lt; \mu_1 - \mu_2 &lt; 305.80</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href=""></a>margin_of_error <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="fl">0.975</span>) <span class="sc">*</span> se_orders</span>
<span id="cb14-2"><a href=""></a>difference <span class="ot">&lt;-</span> mean_app <span class="sc">-</span> mean_web</span>
<span id="cb14-3"><a href=""></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">lower =</span> difference <span class="sc">-</span> margin_of_error,</span>
<span id="cb14-4"><a href=""></a>        <span class="at">upper =</span> difference <span class="sc">+</span> margin_of_error), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>lower upper 
 40.2 305.8 </code></pre>
</div>
</div>
<p>Since the confidence interval does not contain zero, the decision is to <strong>reject <span class="math inline">H_0</span></strong>, which agrees with Example 9-1.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="section-9-3-testing-the-difference-between-two-means-independent-samples" class="title-slide slide level1 center" data-background-color="#2c4a6e">
<h1>Section 9-3: Testing the Difference Between Two Means (Independent Samples)</h1>

</section>
<section id="when-the-population-standard-deviations-are-unknown" class="slide level2">
<h2>When the Population Standard Deviations Are Unknown</h2>
<p>In Section 9-2 the <span class="math inline">z</span> test was used when the population standard deviations were known. In many situations that condition cannot be met. In those cases a <strong><span class="math inline">t</span> test</strong> is used to test the difference between means when the two samples are independent and are taken from two normally or approximately normally distributed populations.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Independent Samples</strong></p>
</div>
<div class="callout-content">
<p>Samples are <strong>independent samples</strong> when they are not related. Throughout this section it is also assumed that <strong>the variances are not equal</strong>.</p>
</div>
</div>
</div>
</section>
<section id="formula-for-the-t-test-independent-samples" class="slide level2">
<h2>Formula for the t Test (Independent Samples)</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>t Test for the Difference Between Two Means, Independent Samples</strong></p>
</div>
<div class="callout-content">
<p>Variances are assumed to be <strong>unequal</strong>:</p>
<p><span class="math display">t = \frac{(\bar{X}_1 - \bar{X}_2) - (\mu_1 - \mu_2)}{\sqrt{\dfrac{s_1^2}{n_1} + \dfrac{s_2^2}{n_2}}}</span></p>
<p>where the degrees of freedom are equal to the <strong>smaller of <span class="math inline">n_1 - 1</span> or <span class="math inline">n_2 - 1</span></strong>.</p>
<p>The denominator is the standard error of the difference between two means; <span class="math inline">s_1</span> and <span class="math inline">s_2</span> replace the unknown <span class="math inline">\sigma_1</span> and <span class="math inline">\sigma_2</span>.</p>
</div>
</div>
</div>
</section>
<section id="assumptions-for-the-t-test" class="slide level2">
<h2>Assumptions for the t Test</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Assumptions for the t Test for Two Independent Means When <span class="math inline">\sigma_1</span> and <span class="math inline">\sigma_2</span> Are Unknown</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>The samples are <strong>random samples</strong>.</li>
<li>The sample data are <strong>independent</strong> of one another.</li>
<li>When the sample sizes are less than 30, the populations must be <strong>normally or approximately normally distributed</strong>.</li>
</ol>
</div>
</div>
</div>
<p>The hypothesis test follows the same five steps as in Section 9-2; the formula uses <span class="math inline">s_1</span> and <span class="math inline">s_2</span>, and the critical values come from the <span class="math inline">t</span> distribution.</p>
</section>
<section id="example-9-4" class="slide level2">
<h2>Example 9-4</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Monthly Revenue by Store Format</strong></p>
</div>
<div class="callout-content">
<p>A coffee chain wants to know whether mean monthly revenue differs between its street-level stores and its shopping-mall counters. Random samples of 10 stores of each format were selected. The street-level stores averaged NT$854 thousand per month and the mall counters averaged NT$814 thousand. The standard deviations of the samples were NT$52 thousand and NT$61 thousand, respectively. At <span class="math inline">\alpha = 0.05</span>, can it be concluded that there is a difference in the means of the two samples? Assume the variables are normally distributed. <em>(hypothetical data)</em></p>
<pre><code>                    Street-level    Mall counter
Sample mean                  854             814
s                             52              61
n                             10              10</code></pre>
<p>Back to <a href="#/example-9-5">Example 9-5</a></p>
</div>
</div>
</div>
</section>
<section id="example-9-4-1" class="slide level2">
<h2>Example 9-4</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> State the hypotheses and identify the claim.</p>
<p><span class="math display">H_0:\ \mu_1 = \mu_2 \qquad H_1:\ \mu_1 \neq \mu_2 \ \textit{(claim)}</span></p>
<p><strong>Step 2.</strong> Find the critical values. The test is two-tailed with <span class="math inline">\alpha = 0.05</span>. The degrees of freedom are the smaller of <span class="math inline">n_1 - 1</span> and <span class="math inline">n_2 - 1</span>; here both equal <span class="math inline">10 - 1 = 9</span>, so the critical values are <span class="math inline">+2.262</span> and <span class="math inline">-2.262</span>.</p>
<p><strong>Step 3.</strong> Find the test statistic.</p>
<p><span class="math display">t = \frac{(854 - 814) - 0}{\sqrt{\dfrac{52^2}{10} + \dfrac{61^2}{10}}} = \frac{40}{25.348} = 1.578</span></p>
</div>
</div>
</div>
</section>
<section id="example-9-4-2" class="slide level2">
<h2>Example 9-4</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 3 in R</strong> — degrees of freedom, critical values, test statistic, and P-value.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href=""></a>mean_street <span class="ot">&lt;-</span> <span class="dv">854</span>; sd_street <span class="ot">&lt;-</span> <span class="dv">52</span>; n_street <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb17-2"><a href=""></a>mean_mall   <span class="ot">&lt;-</span> <span class="dv">814</span>; sd_mall   <span class="ot">&lt;-</span> <span class="dv">61</span>; n_mall   <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb17-3"><a href=""></a>degrees_freedom <span class="ot">&lt;-</span> <span class="fu">min</span>(n_street <span class="sc">-</span> <span class="dv">1</span>, n_mall <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb17-4"><a href=""></a>se_revenue <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(sd_street<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> n_street <span class="sc">+</span> sd_mall<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> n_mall)</span>
<span id="cb17-5"><a href=""></a>t_statistic <span class="ot">&lt;-</span> (mean_street <span class="sc">-</span> mean_mall) <span class="sc">/</span> se_revenue</span>
<span id="cb17-6"><a href=""></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">df =</span> degrees_freedom, <span class="at">standard_error =</span> se_revenue,</span>
<span id="cb17-7"><a href=""></a>        <span class="at">t =</span> t_statistic), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            df standard_error              t 
         9.000         25.348          1.578 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href=""></a><span class="fu">round</span>(<span class="fu">qt</span>(<span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>), degrees_freedom), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -2.262  2.262</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href=""></a><span class="fu">round</span>(<span class="dv">2</span> <span class="sc">*</span> <span class="fu">pt</span>(<span class="fu">abs</span>(t_statistic), degrees_freedom, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>), <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.149</code></pre>
</div>
</div>
<p><strong>Step 4.</strong> Do not reject <span class="math inline">H_0</span>, since <span class="math inline">1.578 &lt; 2.262</span>.</p>
<p><strong>Step 5.</strong> There is not enough evidence to support the claim that the means are different.</p>
</div>
</div>
</div>
</section>
<section id="confidence-interval-for-mu_1---mu_2-sigma_1-and-sigma_2-unknown" class="slide level2">
<h2>Confidence Interval for <span class="math inline">\mu_1 - \mu_2</span> (<span class="math inline">\sigma_1</span> and <span class="math inline">\sigma_2</span> Unknown)</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Confidence Interval for the Difference of Two Means: Independent Samples</strong></p>
</div>
<div class="callout-content">
<p>Variances assumed to be <strong>unequal</strong>:</p>
<p><span class="math display">(\bar{X}_1 - \bar{X}_2) - t_{\alpha/2}\sqrt{\frac{s_1^2}{n_1}+\frac{s_2^2}{n_2}} &lt; \mu_1-\mu_2 &lt; (\bar{X}_1 - \bar{X}_2) + t_{\alpha/2}\sqrt{\frac{s_1^2}{n_1}+\frac{s_2^2}{n_2}}</span></p>
<p>with <span class="math inline">\text{d.f.} =</span> the smaller value of <span class="math inline">n_1 - 1</span> or <span class="math inline">n_2 - 1</span>.</p>
</div>
</div>
</div>
</section>
<section id="example-9-5" class="slide level2">
<h2>Example 9-5</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Monthly Revenue by Store Format</strong></p>
</div>
<div class="callout-content">
<p>Find the 95% confidence interval for the data in <a href="#/example-9-4">Example 9-4</a>.</p>
</div>
</div>
</div>
</section>
<section id="example-9-5-1" class="slide level2">
<h2>Example 9-5</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Substitute in the formula</strong>, using <span class="math inline">t_{\alpha/2} = 2.262</span> with <span class="math inline">\text{d.f.} = 9</span>.</p>
<p><span class="math display">(854 - 814) \pm 2.262\sqrt{\dfrac{52^2}{10} + \dfrac{61^2}{10}} = 40 \pm 57.34</span></p>
<p><span class="math display">-17.34 &lt; \mu_1 - \mu_2 &lt; 97.34</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href=""></a>margin_of_error <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="fl">0.975</span>, degrees_freedom) <span class="sc">*</span> se_revenue</span>
<span id="cb23-2"><a href=""></a>difference <span class="ot">&lt;-</span> mean_street <span class="sc">-</span> mean_mall</span>
<span id="cb23-3"><a href=""></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">lower =</span> difference <span class="sc">-</span> margin_of_error,</span>
<span id="cb23-4"><a href=""></a>        <span class="at">upper =</span> difference <span class="sc">+</span> margin_of_error), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> lower  upper 
-17.34  97.34 </code></pre>
</div>
</div>
<p>Since 0 is contained in the interval, there is not enough evidence to support the claim that the means are different.</p>
</div>
</div>
</div>
</section>
<section id="degrees-of-freedom-in-software" class="slide level2">
<h2>Degrees of Freedom in Software</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>The Welch Degrees of Freedom</strong></p>
</div>
<div class="callout-content">
<p>Many statistical software packages compute the degrees of freedom for this <span class="math inline">t</span> test from</p>
<p><span class="math display">\text{d.f.} = \frac{\left(\dfrac{s_1^2}{n_1} + \dfrac{s_2^2}{n_2}\right)^2}{\dfrac{(s_1^2/n_1)^2}{n_1 - 1} + \dfrac{(s_2^2/n_2)^2}{n_2 - 1}}</span></p>
<p><strong>This formula is not used in this textbook.</strong> The textbook always uses the smaller of <span class="math inline">n_1 - 1</span> and <span class="math inline">n_2 - 1</span>, which is the more conservative choice.</p>
</div>
</div>
</div>
</section>
<section id="the-pooled-estimate-of-the-variance" class="slide level2">
<h2>The Pooled Estimate of the Variance</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>t Test When the Variances Are Assumed Equal</strong></p>
</div>
<div class="callout-content">
<p><span class="math display">t = \frac{(\bar{X}_1 - \bar{X}_2) - (\mu_1 - \mu_2)}{\sqrt{\dfrac{(n_1-1)s_1^2 + (n_2-1)s_2^2}{n_1 + n_2 - 2}}\sqrt{\dfrac{1}{n_1}+\dfrac{1}{n_2}}}\qquad \text{d.f.} = n_1 + n_2 - 2</span></p>
</div>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Pooled Estimate of the Variance</strong></p>
</div>
<div class="callout-content">
<p>A <strong>pooled estimate of the variance</strong> is a weighted average of the variance using the two sample variances and the degrees of freedom of each variance as the weights.</p>
</div>
</div>
</div>
</section>
<section id="choosing-between-the-two-t-tests" class="slide level2">
<h2>Choosing Between the Two t Tests</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Caution</strong></p>
</div>
<div class="callout-content">
<p>There are two options for the <span class="math inline">t</span> test: one for <strong>unequal</strong> population variances and one for <strong>equal</strong> variances. To decide whether two sample variances are equal, a researcher can use an <span class="math inline">F</span> test (Section 9-6).</p>
<p>However, <strong>not all statisticians agree</strong> on using the <span class="math inline">F</span> test before the <span class="math inline">t</span> test: conducting the <span class="math inline">F</span> and <span class="math inline">t</span> tests at the same level of significance changes the overall level of significance of the <span class="math inline">t</span> test. <strong>Because of this, this text assumes <span class="math inline">\sigma_1 \neq \sigma_2</span> throughout.</strong></p>
</div>
</div>
</div>
</section>
<section id="the-two-sample-t-test-in-r" class="slide level2">
<h2>The Two-Sample t Test in R</h2>
<p><strong>Compare the textbook’s conservative d.f. with the Welch d.f.</strong> used by <code>t.test()</code>, starting from the Example 9-4 summaries.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href=""></a>welch_df <span class="ot">&lt;-</span> <span class="cf">function</span>(sd1, n1, sd2, n2) {</span>
<span id="cb25-2"><a href=""></a>  (sd1<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> n1 <span class="sc">+</span> sd2<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> n2)<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span></span>
<span id="cb25-3"><a href=""></a>    ((sd1<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> n1)<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> (n1 <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">+</span> (sd2<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> n2)<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> (n2 <span class="sc">-</span> <span class="dv">1</span>))</span>
<span id="cb25-4"><a href=""></a>}</span>
<span id="cb25-5"><a href=""></a>df_welch <span class="ot">&lt;-</span> <span class="fu">welch_df</span>(sd_street, n_street, sd_mall, n_mall)</span>
<span id="cb25-6"><a href=""></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">df_book =</span> degrees_freedom, <span class="at">df_welch =</span> df_welch), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> df_book df_welch 
    9.00    17.56 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href=""></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">p_book  =</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">pt</span>(<span class="fu">abs</span>(t_statistic), degrees_freedom, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>),</span>
<span id="cb27-2"><a href=""></a>        <span class="at">p_welch =</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">pt</span>(<span class="fu">abs</span>(t_statistic), df_welch, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)), <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> p_book p_welch 
 0.1490  0.1324 </code></pre>
</div>
</div>
<p>The test statistic is the same either way; only the degrees of freedom, and therefore the P-value, differ. The textbook always uses <span class="math inline">\text{d.f.} = 9</span>, the more conservative choice.</p>
</section></section>
<section>
<section id="section-9-4-testing-the-difference-between-two-means-dependent-samples" class="title-slide slide level1 center" data-background-color="#2c4a6e">
<h1>Section 9-4: Testing the Difference Between Two Means: Dependent Samples</h1>

</section>
<section id="dependent-samples-1" class="slide level2">
<h2>Dependent Samples</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Dependent Samples</strong></p>
</div>
<div class="callout-content">
<p>Samples are considered to be <strong>dependent samples</strong> when the subjects are <strong>paired or matched</strong> in some way. Dependent samples are sometimes called <strong>matched-pair samples</strong>.</p>
</div>
</div>
</div>
<p>Examples: a pretest and a posttest on the same subjects before and after taking a drug; SAT scores before and after a preparation course; preweights and postweights in a counseling program. Students can also be <strong>matched</strong> on a pertinent variable — such as IQ — with one of each pair assigned to each group. Matching helps reduce <strong>type II error</strong> by eliminating extraneous variables.</p>
</section>
<section id="two-cautions-about-matching" class="slide level2">
<h2>Two Cautions About Matching</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Caution</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>When subjects are matched according to <strong>one</strong> variable, the matching process does <strong>not</strong> eliminate the influence of other variables. Matching students on IQ does not account for their mathematical ability or their familiarity with computers.</li>
<li>When the same subjects are used in a pre-post study, the knowledge that they are participating in a study can itself influence the results — people placed in a special program may be more highly motivated simply because they were selected.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="hypotheses-for-dependent-samples" class="slide level2">
<h2>Hypotheses for Dependent Samples</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Hypotheses Using <span class="math inline">\mu_D</span></strong></p>
</div>
<div class="callout-content">
<table class="caption-top">
<thead>
<tr class="header">
<th>Two-tailed</th>
<th>Left-tailed</th>
<th>Right-tailed</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">H_0:\ \mu_D = 0</span></td>
<td><span class="math inline">H_0:\ \mu_D = 0</span></td>
<td><span class="math inline">H_0:\ \mu_D = 0</span></td>
</tr>
<tr class="even">
<td><span class="math inline">H_1:\ \mu_D \neq 0</span></td>
<td><span class="math inline">H_1:\ \mu_D &lt; 0</span></td>
<td><span class="math inline">H_1:\ \mu_D &gt; 0</span></td>
</tr>
</tbody>
</table>
<p>Here <span class="math inline">\mu_D</span> is the expected mean of the difference of the matched pairs, and <span class="math inline">D = X_1 - X_2</span>.</p>
</div>
</div>
</div>
</section>
<section id="assumptions-and-formulas" class="slide level2">
<h2>Assumptions and Formulas</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Assumptions for the t Test for Two Means When the Samples Are Dependent</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>The sample or samples are <strong>random</strong>.</li>
<li>The sample data are <strong>dependent</strong>.</li>
<li>When the sample size or sample sizes are less than 30, the population or populations must be <strong>normally or approximately normally distributed</strong>.</li>
</ol>
</div>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Formulas for the t Test for Dependent Samples</strong></p>
</div>
<div class="callout-content">
<p><span class="math display">t = \frac{\bar{D} - \mu_D}{s_D/\sqrt{n}} \qquad \text{d.f.} = n - 1</span></p>
<p><span class="math display">\bar{D} = \frac{\sum D}{n} \qquad s_D = \sqrt{\frac{n\sum D^2 - \left(\sum D\right)^2}{n(n-1)}}</span></p>
</div>
</div>
</div>
</section>
<section id="procedure-table" class="slide level2">
<h2>Procedure Table</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Testing the Difference Between Means for Dependent Samples</strong></p>
</div>
<div class="callout-content">
<table class="caption-top">
<thead>
<tr class="header">
<th>Step</th>
<th>Action</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>State the hypotheses and identify the claim.</td>
</tr>
<tr class="even">
<td>2</td>
<td>Find the critical value(s).</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Compute the test statistic (a–f below).</td>
</tr>
<tr class="even">
<td>4</td>
<td>Make the decision.</td>
</tr>
<tr class="odd">
<td>5</td>
<td>Summarize the results.</td>
</tr>
</tbody>
</table>
<p><strong>Step 3 in detail.</strong> (a) Make a table with columns <span class="math inline">X_1</span>, <span class="math inline">X_2</span>, A <span class="math inline">= D = X_1 - X_2</span>, and B <span class="math inline">= D^2 = (X_1 - X_2)^2</span>. (b) Find the differences and place them in column A. (c) Find the mean of the differences, <span class="math inline">\bar{D} = \sum D / n</span>. (d) Square the differences and place them in column B. (e) Find <span class="math inline">s_D</span>. (f) Find the test statistic <span class="math inline">t = (\bar{D} - \mu_D)/(s_D/\sqrt{n})</span> with <span class="math inline">\text{d.f.} = n - 1</span>.</p>
</div>
</div>
</div>
</section>
<section id="example-9-6" class="slide level2">
<h2>Example 9-6</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Outlet Revenue Three Years Apart</strong></p>
</div>
<div class="callout-content">
<p>A random sample of nine outlets of a bubble-tea chain shows their average monthly revenue (in NT$ millions) 3 years ago and their average monthly revenue today. At <span class="math inline">\alpha = 0.05</span>, can it be concluded that the average monthly revenue of the outlets is greater today than it was 3 years ago? Assume the variable is normally distributed. <em>(hypothetical data)</em></p>
<pre><code>Outlet          1      2     3     4     5     6     7     8     9
3 years ago   7.00   3.40  3.90  3.50  4.00  3.30  4.00  5.30  3.90
Today         5.20   3.80  6.40  2.90  7.10  4.50  8.20  3.30  6.80</code></pre>
</div>
</div>
</div>
</section>
<section id="example-9-6-1" class="slide level2">
<h2>Example 9-6</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> State the hypotheses and identify the claim. If revenue has increased, the revenue 3 years ago must be significantly <strong>less</strong> than the revenue today, so the mean of the differences must be less than zero.</p>
<p><span class="math display">H_0:\ \mu_D = 0 \qquad H_1:\ \mu_D &lt; 0 \ \textit{(claim)}</span></p>
<p><strong>Step 2.</strong> Find the critical value. The degrees of freedom are <span class="math inline">n - 1 = 9 - 1 = 8</span>; for a left-tailed test with <span class="math inline">\alpha = 0.05</span> the critical value is <span class="math inline">-1.860</span>.</p>
<p><strong>Step 3.</strong> Compute the test statistic. With <span class="math inline">\sum D = -9.90</span> and <span class="math inline">\sum D^2 = 51.11</span>,</p>
<p><span class="math display">\bar{D} = \frac{-9.90}{9} = -1.100 \qquad s_D = \sqrt{\frac{9(51.11) - (-9.90)^2}{9(8)}} = 2.242</span></p>
<p><span class="math display">t = \frac{-1.100 - 0}{2.242/\sqrt{9}} = -1.472</span></p>
</div>
</div>
</div>
</section>
<section id="example-9-6-2" class="slide level2">
<h2>Example 9-6</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution - Step 3 in R</strong></p>
</div>
<div class="callout-content">
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href=""></a>three_years_ago <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">7.00</span>, <span class="fl">3.40</span>, <span class="fl">3.90</span>, <span class="fl">3.50</span>, <span class="fl">4.00</span>, <span class="fl">3.30</span>, <span class="fl">4.00</span>, <span class="fl">5.30</span>, <span class="fl">3.90</span>)</span>
<span id="cb30-2"><a href=""></a>today           <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">5.20</span>, <span class="fl">3.80</span>, <span class="fl">6.40</span>, <span class="fl">2.90</span>, <span class="fl">7.10</span>, <span class="fl">4.50</span>, <span class="fl">8.20</span>, <span class="fl">3.30</span>, <span class="fl">6.80</span>)</span>
<span id="cb30-3"><a href=""></a>revenue_change  <span class="ot">&lt;-</span> three_years_ago <span class="sc">-</span> today</span>
<span id="cb30-4"><a href=""></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">data.frame</span>(<span class="at">X1 =</span> three_years_ago, <span class="at">X2 =</span> today, <span class="at">D =</span> revenue_change,</span>
<span id="cb30-5"><a href=""></a>                        <span class="at">D2 =</span> revenue_change<span class="sc">^</span><span class="dv">2</span>), <span class="at">align =</span> <span class="st">"c"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">X1</th>
<th style="text-align: center;">X2</th>
<th style="text-align: center;">D</th>
<th style="text-align: center;">D2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">7.0</td>
<td style="text-align: center;">5.2</td>
<td style="text-align: center;">1.8</td>
<td style="text-align: center;">3.24</td>
</tr>
<tr class="even">
<td style="text-align: center;">3.4</td>
<td style="text-align: center;">3.8</td>
<td style="text-align: center;">-0.4</td>
<td style="text-align: center;">0.16</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3.9</td>
<td style="text-align: center;">6.4</td>
<td style="text-align: center;">-2.5</td>
<td style="text-align: center;">6.25</td>
</tr>
<tr class="even">
<td style="text-align: center;">3.5</td>
<td style="text-align: center;">2.9</td>
<td style="text-align: center;">0.6</td>
<td style="text-align: center;">0.36</td>
</tr>
<tr class="odd">
<td style="text-align: center;">4.0</td>
<td style="text-align: center;">7.1</td>
<td style="text-align: center;">-3.1</td>
<td style="text-align: center;">9.61</td>
</tr>
<tr class="even">
<td style="text-align: center;">3.3</td>
<td style="text-align: center;">4.5</td>
<td style="text-align: center;">-1.2</td>
<td style="text-align: center;">1.44</td>
</tr>
<tr class="odd">
<td style="text-align: center;">4.0</td>
<td style="text-align: center;">8.2</td>
<td style="text-align: center;">-4.2</td>
<td style="text-align: center;">17.64</td>
</tr>
<tr class="even">
<td style="text-align: center;">5.3</td>
<td style="text-align: center;">3.3</td>
<td style="text-align: center;">2.0</td>
<td style="text-align: center;">4.00</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3.9</td>
<td style="text-align: center;">6.8</td>
<td style="text-align: center;">-2.9</td>
<td style="text-align: center;">8.41</td>
</tr>
</tbody>
</table>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href=""></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">sumD =</span> <span class="fu">sum</span>(revenue_change), <span class="at">sumD2 =</span> <span class="fu">sum</span>(revenue_change<span class="sc">^</span><span class="dv">2</span>)), <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> sumD sumD2 
-9.90 51.11 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="example-9-6-3" class="slide level2">
<h2>Example 9-6</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Steps 3-5 in R</strong> — test statistic, critical value, P-value, and decision.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href=""></a>n_outlets <span class="ot">&lt;-</span> <span class="fu">length</span>(revenue_change)</span>
<span id="cb33-2"><a href=""></a>t_statistic <span class="ot">&lt;-</span> <span class="fu">mean</span>(revenue_change) <span class="sc">/</span> (<span class="fu">sd</span>(revenue_change) <span class="sc">/</span> <span class="fu">sqrt</span>(n_outlets))</span>
<span id="cb33-3"><a href=""></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">Dbar =</span> <span class="fu">mean</span>(revenue_change), <span class="at">sD =</span> <span class="fu">sd</span>(revenue_change),</span>
<span id="cb33-4"><a href=""></a>        <span class="at">t =</span> t_statistic), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Dbar     sD      t 
-1.100  2.242 -1.472 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href=""></a><span class="fu">round</span>(<span class="fu">qt</span>(<span class="fl">0.05</span>, n_outlets <span class="sc">-</span> <span class="dv">1</span>), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1.86</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href=""></a><span class="fu">round</span>(<span class="fu">pt</span>(t_statistic, n_outlets <span class="sc">-</span> <span class="dv">1</span>), <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0896</code></pre>
</div>
</div>
<p><strong>Step 4.</strong> Do not reject <span class="math inline">H_0</span>, since the test statistic <span class="math inline">-1.472</span> is greater than the critical value <span class="math inline">-1.860</span> (equivalently <span class="math inline">P = 0.0896 &gt; 0.05</span>).</p>
<p><strong>Step 5.</strong> There is not enough evidence to show that the average monthly revenue of the outlets has increased over the last 3 years.</p>
</div>
</div>
</div>
</section>
<section id="example-9-7" class="slide level2">
<h2>Example 9-7</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Defect Rate After a Procedure Change</strong></p>
</div>
<div class="callout-content">
<p>A quality engineer wishes to see whether the batch defect rate of a production line changes after a revised standard operating procedure is introduced. Six randomly selected lines were measured before the revision, and then they ran under the new procedure for a 6-week period. The results are shown in the table (defects per 1000 units). Can it be concluded that the defect rate has changed at <span class="math inline">\alpha = 0.10</span>? Assume the variable is approximately normally distributed. <em>(hypothetical data)</em></p>
<pre><code>Line           1     2     3     4     5     6
Before (X1)   34    28    41    37    25    30
After  (X2)   28    26    42    29    24    31</code></pre>
<p>Back to <a href="#/example-9-8">Example 9-8</a></p>
</div>
</div>
</div>
</section>
<section id="example-9-7-1" class="slide level2">
<h2>Example 9-7</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> State the hypotheses and identify the claim. If the revised procedure has an effect, the before rates should be different from the after rates.</p>
<p><span class="math display">H_0:\ \mu_D = 0 \qquad H_1:\ \mu_D \neq 0 \ \textit{(claim)}</span></p>
<p><strong>Step 2.</strong> Find the critical values. The degrees of freedom are <span class="math inline">6 - 1 = 5</span>; at <span class="math inline">\alpha = 0.10</span> the critical values are <span class="math inline">\pm 2.015</span>.</p>
<p><strong>Step 3.</strong> Compute the test statistic. With <span class="math inline">\sum D = 15</span> and <span class="math inline">\sum D^2 = 107</span>,</p>
<p><span class="math display">\bar{D} = \frac{15}{6} = 2.500 \qquad s_D = \sqrt{\frac{6(107) - 15^2}{6(5)}} = \sqrt{\frac{642 - 225}{30}} = 3.728</span></p>
<p><span class="math display">t = \frac{2.500 - 0}{3.728/\sqrt{6}} = 1.643</span></p>
</div>
</div>
</div>
</section>
<section id="example-9-7-2" class="slide level2">
<h2>Example 9-7</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 3 in R</strong> — build the table and compute the test statistic.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href=""></a>before <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">34</span>, <span class="dv">28</span>, <span class="dv">41</span>, <span class="dv">37</span>, <span class="dv">25</span>, <span class="dv">30</span>)</span>
<span id="cb40-2"><a href=""></a>after  <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">28</span>, <span class="dv">26</span>, <span class="dv">42</span>, <span class="dv">29</span>, <span class="dv">24</span>, <span class="dv">31</span>)</span>
<span id="cb40-3"><a href=""></a>defect_change <span class="ot">&lt;-</span> before <span class="sc">-</span> after</span>
<span id="cb40-4"><a href=""></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">data.frame</span>(<span class="at">X1 =</span> before, <span class="at">X2 =</span> after,</span>
<span id="cb40-5"><a href=""></a>                        <span class="at">D =</span> defect_change, <span class="at">D2 =</span> defect_change<span class="sc">^</span><span class="dv">2</span>), <span class="at">align =</span> <span class="st">"c"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">X1</th>
<th style="text-align: center;">X2</th>
<th style="text-align: center;">D</th>
<th style="text-align: center;">D2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">34</td>
<td style="text-align: center;">28</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">36</td>
</tr>
<tr class="even">
<td style="text-align: center;">28</td>
<td style="text-align: center;">26</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="odd">
<td style="text-align: center;">41</td>
<td style="text-align: center;">42</td>
<td style="text-align: center;">-1</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">37</td>
<td style="text-align: center;">29</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">64</td>
</tr>
<tr class="odd">
<td style="text-align: center;">25</td>
<td style="text-align: center;">24</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">30</td>
<td style="text-align: center;">31</td>
<td style="text-align: center;">-1</td>
<td style="text-align: center;">1</td>
</tr>
</tbody>
</table>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href=""></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">sumD =</span> <span class="fu">sum</span>(defect_change), <span class="at">sumD2 =</span> <span class="fu">sum</span>(defect_change<span class="sc">^</span><span class="dv">2</span>),</span>
<span id="cb41-2"><a href=""></a>        <span class="at">Dbar =</span> <span class="fu">mean</span>(defect_change), <span class="at">sD =</span> <span class="fu">sd</span>(defect_change)), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   sumD   sumD2    Dbar      sD 
 15.000 107.000   2.500   3.728 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="example-9-7-3" class="slide level2">
<h2>Example 9-7</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Steps 3-5 in R</strong> — critical values, test statistic, P-value, and decision.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href=""></a>n_lines <span class="ot">&lt;-</span> <span class="fu">length</span>(defect_change)</span>
<span id="cb43-2"><a href=""></a>t_statistic <span class="ot">&lt;-</span> <span class="fu">mean</span>(defect_change) <span class="sc">/</span> (<span class="fu">sd</span>(defect_change) <span class="sc">/</span> <span class="fu">sqrt</span>(n_lines))</span>
<span id="cb43-3"><a href=""></a><span class="fu">round</span>(t_statistic, <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.643</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href=""></a><span class="fu">round</span>(<span class="fu">qt</span>(<span class="fu">c</span>(<span class="fl">0.05</span>, <span class="fl">0.95</span>), n_lines <span class="sc">-</span> <span class="dv">1</span>), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -2.015  2.015</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href=""></a><span class="fu">round</span>(<span class="dv">2</span> <span class="sc">*</span> <span class="fu">pt</span>(<span class="fu">abs</span>(t_statistic), n_lines <span class="sc">-</span> <span class="dv">1</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>), <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1614</code></pre>
</div>
</div>
<p><strong>Step 4.</strong> Do not reject <span class="math inline">H_0</span>: the test statistic 1.643 lies in the noncritical region.</p>
<p><strong>Step 5.</strong> There is not enough evidence to support the claim that the revised procedure changes the defect rate of a line.</p>
</div>
</div>
</div>
</section>
<section id="a-specific-hypothesized-difference" class="slide level2">
<h2>A Specific Hypothesized Difference</h2>
<p>If a specific difference is hypothesized, the same formula is used with <span class="math inline">\mu_D</span> equal to that value. For example, if a dietitian claims that people on a specific diet will lose an average of 3 pounds in a week, the hypotheses are</p>
<p><span class="math display">H_0:\ \mu_D = 3 \qquad H_1:\ \mu_D \neq 3</span></p>
<p>and the value 3 is substituted for <span class="math inline">\mu_D</span> in the test statistic.</p>
</section>
<section id="confidence-interval-for-the-mean-difference" class="slide level2">
<h2>Confidence Interval for the Mean Difference</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Confidence Interval for <span class="math inline">\mu_D</span></strong></p>
</div>
<div class="callout-content">
<p><span class="math display">\bar{D} - t_{\alpha/2}\frac{s_D}{\sqrt{n}} &lt; \mu_D &lt; \bar{D} + t_{\alpha/2}\frac{s_D}{\sqrt{n}} \qquad \text{d.f.} = n - 1</span></p>
</div>
</div>
</div>
</section>
<section id="example-9-8" class="slide level2">
<h2>Example 9-8</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Defect Rate After a Procedure Change</strong></p>
</div>
<div class="callout-content">
<p>Find the 90% confidence interval for the data in <a href="#/example-9-7">Example 9-7</a>.</p>
</div>
</div>
</div>
</section>
<section id="example-9-8-1" class="slide level2">
<h2>Example 9-8</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Substitute in the formula</strong>, using <span class="math inline">t_{\alpha/2} = 2.015</span> with <span class="math inline">\text{d.f.} = 5</span>.</p>
<p><span class="math display">2.500 \pm 2.015\cdot\frac{3.728}{\sqrt{6}} = 2.500 \pm 3.07</span></p>
<p><span class="math display">-0.57 &lt; \mu_D &lt; 5.57</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href=""></a>margin_of_error <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="fl">0.95</span>, n_lines <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> <span class="fu">sd</span>(defect_change) <span class="sc">/</span> <span class="fu">sqrt</span>(n_lines)</span>
<span id="cb49-2"><a href=""></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">lower =</span> <span class="fu">mean</span>(defect_change) <span class="sc">-</span> margin_of_error,</span>
<span id="cb49-3"><a href=""></a>        <span class="at">upper =</span> <span class="fu">mean</span>(defect_change) <span class="sc">+</span> margin_of_error), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>lower upper 
-0.57  5.57 </code></pre>
</div>
</div>
<p>Since 0 is contained in the interval, the decision is to not reject <span class="math inline">H_0:\ \mu_D = 0</span>; there is not enough evidence to support the claim that the revised procedure changes the defect rate.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="section-9-5-testing-the-difference-between-proportions" class="title-slide slide level1 center" data-background-color="#2c4a6e">
<h1>Section 9-5: Testing the Difference Between Proportions</h1>

</section>
<section id="sample-proportions" class="slide level2">
<h2>Sample Proportions</h2>
<p>Recall from Chapter 7 that <span class="math inline">\hat{p}</span> (“p hat”) is the sample proportion used to estimate the population proportion <span class="math inline">p</span>.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Sample Proportion</strong></p>
</div>
<div class="callout-content">
<p><span class="math display">\hat{p} = \frac{X}{n}</span></p>
<p>where <span class="math inline">X</span> is the number of units that possess the characteristic of interest and <span class="math inline">n</span> is the sample size.</p>
</div>
</div>
</div>
<p>When testing the difference between two population proportions <span class="math inline">p_1</span> and <span class="math inline">p_2</span>, with no specific difference hypothesized:</p>
<p><span class="math display">H_0:\ p_1 = p_2 \qquad H_1:\ p_1 \neq p_2</span></p>
<p>or equivalently <span class="math inline">H_0:\ p_1 - p_2 = 0</span> and <span class="math inline">H_1:\ p_1 - p_2 \neq 0</span>. Similar statements using <span class="math inline">&lt;</span> or <span class="math inline">&gt;</span> give one-tailed tests.</p>
</section>
<section id="the-weighted-estimate-barp" class="slide level2">
<h2>The Weighted Estimate <span class="math inline">\bar{p}</span></h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Weighted (Pooled) Estimate of <span class="math inline">p</span></strong></p>
</div>
<div class="callout-content">
<p>Since <span class="math inline">p_1</span> and <span class="math inline">p_2</span> are unknown, a <strong>weighted estimate</strong> is computed from</p>
<p><span class="math display">\bar{p} = \frac{n_1\hat{p}_1 + n_2\hat{p}_2}{n_1 + n_2} = \frac{X_1 + X_2}{n_1 + n_2} \qquad \bar{q} = 1 - \bar{p}</span></p>
<p>This estimate is based on the hypothesis that <span class="math inline">p_1 = p_2</span>; <span class="math inline">\bar{p}</span> is a better estimate than either <span class="math inline">\hat{p}_1</span> or <span class="math inline">\hat{p}_2</span> alone because it is a combined average using both.</p>
<p>The standard error of the difference in terms of the weighted estimate is</p>
<p><span class="math display">\sigma_{\hat{p}_1 - \hat{p}_2} = \sqrt{\bar{p}\,\bar{q}\left(\frac{1}{n_1}+\frac{1}{n_2}\right)}</span></p>
</div>
</div>
</div>
</section>
<section id="formula-and-assumptions" class="slide level2">
<h2>Formula and Assumptions</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>z Test Statistic for Comparing Two Proportions</strong></p>
</div>
<div class="callout-content">
<p><span class="math display">z = \frac{(\hat{p}_1 - \hat{p}_2) - (p_1 - p_2)}{\sqrt{\bar{p}\,\bar{q}\left(\dfrac{1}{n_1}+\dfrac{1}{n_2}\right)}}</span></p>
<p>where <span class="math inline">\ \bar{p} = \dfrac{X_1 + X_2}{n_1+n_2}</span>, <span class="math inline">\ \bar{q} = 1 - \bar{p}</span>, <span class="math inline">\ \hat{p}_1 = \dfrac{X_1}{n_1}</span>, <span class="math inline">\ \hat{p}_2 = \dfrac{X_2}{n_2}</span>.</p>
</div>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Assumptions for the z Test for Two Proportions</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>The samples must be <strong>random samples</strong>.</li>
<li>The sample data are <strong>independent</strong> of one another.</li>
<li>For both samples <span class="math inline">np \geq 5</span> and <span class="math inline">nq \geq 5</span>.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="example-9-9" class="slide level2">
<h2>Example 9-9</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Mobile-Wallet Payments at Two Store Formats</strong></p>
</div>
<div class="callout-content">
<p>A retail group compares how often customers pay with a mobile wallet at its hypermarkets and at its convenience stores. In a random sample of 45 hypermarket transactions, 18 were paid with a mobile wallet, while in a random sample of 35 convenience-store transactions, 25 were. At <span class="math inline">\alpha = 0.05</span>, test the claim that there is <strong>no difference</strong> in the proportions of mobile-wallet payments at the two store formats. <em>(hypothetical data)</em></p>
<pre><code>                          Hypermarket    Convenience
Mobile-wallet payments             18             25
Transactions sampled               45             35</code></pre>
<p>Back to <a href="#/example-9-11">Example 9-11</a></p>
</div>
</div>
</div>
</section>
<section id="example-9-9-1" class="slide level2">
<h2>Example 9-9</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> State the hypotheses and identify the claim.</p>
<p><span class="math display">H_0:\ p_1 = p_2 \ \textit{(claim)} \qquad H_1:\ p_1 \neq p_2</span></p>
<p><strong>Step 2.</strong> Find the critical values. Since <span class="math inline">\alpha = 0.05</span>, the critical values are <span class="math inline">+1.96</span> and <span class="math inline">-1.96</span>.</p>
<p><strong>Step 3.</strong> Compute the test statistic.</p>
<p><span class="math display">\hat{p}_1 = \frac{18}{45} = 0.4000 \qquad \hat{p}_2 = \frac{25}{35} = 0.7143</span></p>
<p><span class="math display">\bar{p} = \frac{18+25}{45+35} = \frac{43}{80} = 0.5375 \qquad \bar{q} = 0.4625</span></p>
<p><span class="math display">z = \frac{(0.4000 - 0.7143) - 0}{\sqrt{(0.5375)(0.4625)\left(\dfrac{1}{45}+\dfrac{1}{35}\right)}} = \frac{-0.3143}{0.1124} = -2.80</span></p>
</div>
</div>
</div>
</section>
<section id="example-9-9-2" class="slide level2">
<h2>Example 9-9</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 3 in R</strong> — proportions, weighted estimate, test statistic, and P-value.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href=""></a>wallet_hyper <span class="ot">&lt;-</span> <span class="dv">18</span>; n_hyper <span class="ot">&lt;-</span> <span class="dv">45</span></span>
<span id="cb52-2"><a href=""></a>wallet_cvs   <span class="ot">&lt;-</span> <span class="dv">25</span>; n_cvs   <span class="ot">&lt;-</span> <span class="dv">35</span></span>
<span id="cb52-3"><a href=""></a>phat_hyper <span class="ot">&lt;-</span> wallet_hyper <span class="sc">/</span> n_hyper</span>
<span id="cb52-4"><a href=""></a>phat_cvs   <span class="ot">&lt;-</span> wallet_cvs <span class="sc">/</span> n_cvs</span>
<span id="cb52-5"><a href=""></a>pbar <span class="ot">&lt;-</span> (wallet_hyper <span class="sc">+</span> wallet_cvs) <span class="sc">/</span> (n_hyper <span class="sc">+</span> n_cvs)</span>
<span id="cb52-6"><a href=""></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">phat_hyper =</span> phat_hyper, <span class="at">phat_cvs =</span> phat_cvs,</span>
<span id="cb52-7"><a href=""></a>        <span class="at">pbar =</span> pbar, <span class="at">qbar =</span> <span class="dv">1</span> <span class="sc">-</span> pbar), <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>phat_hyper   phat_cvs       pbar       qbar 
    0.4000     0.7143     0.5375     0.4625 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href=""></a>z_statistic <span class="ot">&lt;-</span> (phat_hyper <span class="sc">-</span> phat_cvs) <span class="sc">/</span></span>
<span id="cb54-2"><a href=""></a>  <span class="fu">sqrt</span>(pbar <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> pbar) <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">/</span> n_hyper <span class="sc">+</span> <span class="dv">1</span> <span class="sc">/</span> n_cvs))</span>
<span id="cb54-3"><a href=""></a><span class="fu">round</span>(z_statistic, <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -2.8</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href=""></a><span class="fu">round</span>(<span class="fu">qnorm</span>(<span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>)), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1.96  1.96</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href=""></a><span class="fu">round</span>(<span class="dv">2</span> <span class="sc">*</span> <span class="fu">pnorm</span>(<span class="fu">abs</span>(z_statistic), <span class="at">lower.tail =</span> <span class="cn">FALSE</span>), <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0052</code></pre>
</div>
</div>
<p><strong>Step 4.</strong> Reject <span class="math inline">H_0</span>, since <span class="math inline">-2.80 &lt; -1.96</span> (equivalently <span class="math inline">P = 0.0052 &lt; \alpha = 0.05</span>).</p>
<p><strong>Step 5.</strong> There is enough evidence to reject the claim that there is no difference in the proportions of mobile-wallet payments at the two store formats.</p>
</div>
</div>
</div>
</section>
<section id="example-9-10" class="slide level2">
<h2>Example 9-10</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Booking a Hotel Through an App</strong></p>
</div>
<div class="callout-content">
<p>A survey of 250 randomly selected business travellers to Taiwan found that 72% booked their hotel through a mobile app, while for a random sample of 150 leisure travellers, 60% booked their hotel through a mobile app. At <span class="math inline">\alpha = 0.10</span>, can it be concluded that the percentage of business travellers who book through an app is greater than the percentage of leisure travellers who do? <em>(hypothetical data)</em></p>
<pre><code>                 Business      Leisure
Percentage            72%          60%
n                     250          150</code></pre>
</div>
</div>
</div>
</section>
<section id="example-9-10-1" class="slide level2">
<h2>Example 9-10</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> State the hypotheses and identify the claim.</p>
<p><span class="math display">H_0:\ p_1 = p_2 \qquad H_1:\ p_1 &gt; p_2 \ \textit{(claim)}</span></p>
<p><strong>Step 2.</strong> Find the critical value. At <span class="math inline">\alpha = 0.10</span> for a right-tailed test the critical value is 1.28.</p>
<p><strong>Step 3.</strong> Compute the test statistic. Since <strong>percentages</strong> are given, first recover the counts:</p>
<p><span class="math display">X_1 = \hat{p}_1 n_1 = 0.72(250) = 180 \qquad X_2 = \hat{p}_2 n_2 = 0.60(150) = 90</span></p>
<p><span class="math display">\bar{p} = \frac{180+90}{250+150} = \frac{270}{400} = 0.675 \qquad \bar{q} = 0.325</span></p>
<p><span class="math display">z = \frac{(0.72 - 0.60) - 0}{\sqrt{(0.675)(0.325)\left(\dfrac{1}{250}+\dfrac{1}{150}\right)}} = \frac{0.12}{0.0484} = 2.48</span></p>
</div>
</div>
</div>
</section>
<section id="example-9-10-2" class="slide level2">
<h2>Example 9-10</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 3 in R</strong> — counts, weighted estimate, test statistic, critical value, P-value.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href=""></a>phat_business <span class="ot">&lt;-</span> <span class="fl">0.72</span>; n_business <span class="ot">&lt;-</span> <span class="dv">250</span></span>
<span id="cb61-2"><a href=""></a>phat_leisure  <span class="ot">&lt;-</span> <span class="fl">0.60</span>; n_leisure  <span class="ot">&lt;-</span> <span class="dv">150</span></span>
<span id="cb61-3"><a href=""></a>count_business <span class="ot">&lt;-</span> phat_business <span class="sc">*</span> n_business</span>
<span id="cb61-4"><a href=""></a>count_leisure  <span class="ot">&lt;-</span> phat_leisure <span class="sc">*</span> n_leisure</span>
<span id="cb61-5"><a href=""></a>pbar <span class="ot">&lt;-</span> (count_business <span class="sc">+</span> count_leisure) <span class="sc">/</span> (n_business <span class="sc">+</span> n_leisure)</span>
<span id="cb61-6"><a href=""></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">X1 =</span> count_business, <span class="at">X2 =</span> count_leisure,</span>
<span id="cb61-7"><a href=""></a>        <span class="at">pbar =</span> pbar, <span class="at">qbar =</span> <span class="dv">1</span> <span class="sc">-</span> pbar), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     X1      X2    pbar    qbar 
180.000  90.000   0.675   0.325 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href=""></a>z_statistic <span class="ot">&lt;-</span> (phat_business <span class="sc">-</span> phat_leisure) <span class="sc">/</span></span>
<span id="cb63-2"><a href=""></a>  <span class="fu">sqrt</span>(pbar <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> pbar) <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">/</span> n_business <span class="sc">+</span> <span class="dv">1</span> <span class="sc">/</span> n_leisure))</span>
<span id="cb63-3"><a href=""></a><span class="fu">round</span>(z_statistic, <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.48</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href=""></a><span class="fu">round</span>(<span class="fu">qnorm</span>(<span class="fl">0.90</span>), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.28</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb67"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href=""></a><span class="fu">round</span>(<span class="fu">pnorm</span>(z_statistic, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>), <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0066</code></pre>
</div>
</div>
<p><strong>Step 4.</strong> Reject <span class="math inline">H_0</span>, since <span class="math inline">2.48 &gt; 1.28</span> (equivalently <span class="math inline">P = 0.0066 &lt; 0.10</span>).</p>
<p><strong>Step 5.</strong> There is enough evidence that the proportion of business travellers who book their hotel through an app is greater than the proportion of leisure travellers who do.</p>
</div>
</div>
</div>
</section>
<section id="confidence-interval-for-p_1---p_2" class="slide level2">
<h2>Confidence Interval for <span class="math inline">p_1 - p_2</span></h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Confidence Interval for the Difference Between Two Proportions</strong></p>
</div>
<div class="callout-content">
<p><span class="math display">(\hat{p}_1-\hat{p}_2) - z_{\alpha/2}\sqrt{\frac{\hat{p}_1\hat{q}_1}{n_1}+\frac{\hat{p}_2\hat{q}_2}{n_2}} &lt; p_1-p_2 &lt; (\hat{p}_1-\hat{p}_2) + z_{\alpha/2}\sqrt{\frac{\hat{p}_1\hat{q}_1}{n_1}+\frac{\hat{p}_2\hat{q}_2}{n_2}}</span></p>
</div>
</div>
</div>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Caution</strong></p>
</div>
<div class="callout-content">
<p>The confidence interval uses a standard deviation based on the <strong>estimated</strong> population proportions, but the hypothesis test uses a standard deviation based on the <strong>assumption that the two population proportions are equal</strong>. As a result, the two procedures can lead to different conclusions. When testing for a difference of two proportions, <strong>use the <span class="math inline">z</span> test rather than the confidence interval</strong>.</p>
</div>
</div>
</div>
</section>
<section id="example-9-11" class="slide level2">
<h2>Example 9-11</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Mobile-Wallet Payments at Two Store Formats</strong></p>
</div>
<div class="callout-content">
<p>Find the 95% confidence interval for the difference of proportions for the data in <a href="#/example-9-9">Example 9-9</a>.</p>
</div>
</div>
</div>
</section>
<section id="example-9-11-1" class="slide level2">
<h2>Example 9-11</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Substitute in the formula</strong>, using <span class="math inline">\hat{p}_1 = 0.4000</span>, <span class="math inline">\hat{q}_1 = 0.6000</span>, <span class="math inline">\hat{p}_2 = 0.7143</span>, <span class="math inline">\hat{q}_2 = 0.2857</span> and <span class="math inline">z_{\alpha/2} = 1.96</span>.</p>
<p><span class="math display">(0.4000 - 0.7143) \pm 1.96\sqrt{\dfrac{(0.4000)(0.6000)}{45} + \dfrac{(0.7143)(0.2857)}{35}} = -0.3143 \pm 0.207</span></p>
<p><span class="math display">-0.521 &lt; p_1 - p_2 &lt; -0.107</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb69"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href=""></a>margin_of_error <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="fl">0.975</span>) <span class="sc">*</span></span>
<span id="cb69-2"><a href=""></a>  <span class="fu">sqrt</span>(phat_hyper <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> phat_hyper) <span class="sc">/</span> n_hyper <span class="sc">+</span></span>
<span id="cb69-3"><a href=""></a>       phat_cvs <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> phat_cvs) <span class="sc">/</span> n_cvs)</span>
<span id="cb69-4"><a href=""></a>difference <span class="ot">&lt;-</span> phat_hyper <span class="sc">-</span> phat_cvs</span>
<span id="cb69-5"><a href=""></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">lower =</span> difference <span class="sc">-</span> margin_of_error,</span>
<span id="cb69-6"><a href=""></a>        <span class="at">upper =</span> difference <span class="sc">+</span> margin_of_error), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> lower  upper 
-0.521 -0.107 </code></pre>
</div>
</div>
<p>The interval lies entirely below zero, which agrees with the decision to reject <span class="math inline">H_0</span> in Example 9-9.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="section-9-6-testing-the-difference-between-two-variances" class="title-slide slide level1 center" data-background-color="#2c4a6e">
<h1>Section 9-6: Testing the Difference Between Two Variances</h1>

</section>
<section id="the-f-distribution" class="slide level2">
<h2>The F Distribution</h2>
<p>Statisticians also compare two <strong>variances or standard deviations</strong> — for example, the variation in monthly temperatures of two cities. This comparison uses an <strong><span class="math inline">F</span> test</strong>, which should not be confused with the chi-square test of Chapter 8, where a <em>single</em> sample variance is compared to a specific population variance.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>The F Distribution</strong></p>
</div>
<div class="callout-content">
<p>If two independent samples are selected from two normally distributed populations in which the population variances are equal (<span class="math inline">\sigma_1^2 = \sigma_2^2</span>), and the sample variances are compared as <span class="math inline">s_1^2/s_2^2</span>, the sampling distribution of that ratio is called the <strong><span class="math inline">F</span> distribution</strong>.</p>
</div>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Characteristics of the F Distribution</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>The values of <span class="math inline">F</span> <strong>cannot be negative</strong>, because variances are always positive or zero.</li>
<li>The distribution is <strong>positively skewed</strong>.</li>
<li>The <strong>mean value of <span class="math inline">F</span> is equal to 1</strong>.</li>
<li>The <span class="math inline">F</span> distribution is a <strong>family of curves</strong> based on the degrees of freedom of the variance of the numerator and the degrees of freedom of the variance of the denominator.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="the-f-family-of-curves-in-r" class="slide level2">
<h2>The F Family of Curves in R</h2>
<p><strong>Draw figure</strong> — Figure 9-10: several <span class="math inline">F</span> curves with different degrees of freedom.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb71"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href=""></a>f_value <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fl">0.01</span>, <span class="dv">5</span>, <span class="at">length.out =</span> <span class="dv">400</span>)</span>
<span id="cb71-2"><a href=""></a>f_curves <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(</span>
<span id="cb71-3"><a href=""></a>  <span class="fu">tibble</span>(f_value, <span class="at">density =</span> <span class="fu">df</span>(f_value,  <span class="dv">3</span>,  <span class="dv">5</span>), <span class="at">degrees =</span> <span class="st">"3, 5"</span>),</span>
<span id="cb71-4"><a href=""></a>  <span class="fu">tibble</span>(f_value, <span class="at">density =</span> <span class="fu">df</span>(f_value, <span class="dv">10</span>, <span class="dv">10</span>), <span class="at">degrees =</span> <span class="st">"10, 10"</span>),</span>
<span id="cb71-5"><a href=""></a>  <span class="fu">tibble</span>(f_value, <span class="at">density =</span> <span class="fu">df</span>(f_value, <span class="dv">20</span>, <span class="dv">30</span>), <span class="at">degrees =</span> <span class="st">"20, 30"</span>)</span>
<span id="cb71-6"><a href=""></a>)</span>
<span id="cb71-7"><a href=""></a><span class="fu">ggplot</span>(f_curves, <span class="fu">aes</span>(f_value, density, <span class="at">colour =</span> degrees)) <span class="sc">+</span></span>
<span id="cb71-8"><a href=""></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="fl">0.9</span>) <span class="sc">+</span></span>
<span id="cb71-9"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"The F Family of Curves"</span>, <span class="at">x =</span> <span class="st">"F"</span>, <span class="at">y =</span> <span class="st">"Density"</span>,</span>
<span id="cb71-10"><a href=""></a>       <span class="at">colour =</span> <span class="st">"d.f.N., d.f.D."</span>) <span class="sc">+</span></span>
<span id="cb71-11"><a href=""></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="ch9_files/figure-revealjs/s9-6-1-1.png" class="quarto-figure quarto-figure-center r-stretch" style="width:70.0%"><p>Every curve is positively skewed and begins at <span class="math inline">F = 0</span>.</p>
</section>
<section id="formula-for-the-f-test" class="slide level2">
<h2>Formula for the F Test</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>F Test for Comparing Two Variances</strong></p>
</div>
<div class="callout-content">
<p><span class="math display">F = \frac{s_1^2}{s_2^2}</span></p>
<p>where the <strong>larger</strong> of the two variances is placed in the numerator regardless of the subscripts.</p>
<p>The <span class="math inline">F</span> test has two degrees of freedom: that of the numerator, <span class="math inline">\text{d.f.N.} = n_1 - 1</span>, and that of the denominator, <span class="math inline">\text{d.f.D.} = n_2 - 1</span>, where <span class="math inline">n_1</span> is the sample size <strong>from which the larger variance was obtained</strong> — not necessarily the larger of the two sample sizes.</p>
</div>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Hypotheses for the F Test</strong></p>
</div>
<div class="callout-content">
<table class="caption-top">
<colgroup>
<col style="width: 35%">
<col style="width: 33%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>Right-tailed</th>
<th>Left-tailed</th>
<th>Two-tailed</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">H_0:\ \sigma_1^2 = \sigma_2^2</span></td>
<td><span class="math inline">H_0:\ \sigma_1^2 = \sigma_2^2</span></td>
<td><span class="math inline">H_0:\ \sigma_1^2 = \sigma_2^2</span></td>
</tr>
<tr class="even">
<td><span class="math inline">H_1:\ \sigma_1^2 &gt; \sigma_2^2</span></td>
<td><span class="math inline">H_1:\ \sigma_1^2 &lt; \sigma_2^2</span></td>
<td><span class="math inline">H_1:\ \sigma_1^2 \neq \sigma_2^2</span></td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="notes-and-assumptions-for-the-f-test" class="slide level2">
<h2>Notes and Assumptions for the F Test</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Notes for the Use of the F Test</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>The <strong>larger variance</strong> should always be placed in the numerator of the formula regardless of the subscripts.</li>
<li>For a <strong>two-tailed test</strong>, the <span class="math inline">\alpha</span> value must be divided by 2 and the critical value placed on the right side of the <span class="math inline">F</span> curve.</li>
<li>If <strong>standard deviations</strong> instead of variances are given in the problem, they must be <strong>squared</strong> for the <span class="math inline">F</span> test formula.</li>
<li>When the degrees of freedom cannot be found in Table A-7, the <strong>closest value on the smaller side</strong> should be used.</li>
</ol>
</div>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Assumptions for Testing the Difference Between Two Variances</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>The samples must be <strong>random samples</strong>.</li>
<li>The populations from which the samples were obtained must be <strong>normally distributed</strong>.</li>
<li>The samples must be <strong>independent</strong> of one another.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="cautions-for-the-f-test" class="slide level2">
<h2>Cautions for the F Test</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Caution</strong></p>
</div>
<div class="callout-content">
<ul>
<li>This procedure is <strong>not robust</strong>: minor departures from normality will affect the results, so the test should not be used when the distributions depart from normality. Standard deviations are not a good measure of spread in nonsymmetrical distributions because they are not resistant to outliers.</li>
<li>It is <strong>not absolutely necessary</strong> to place the larger variance in the numerator. Critical values for left-tailed tests can be found by interchanging the degrees of freedom and taking the reciprocal of the value from Table A-7.</li>
<li>Use caution: the data can run contrary to the hypotheses. If <span class="math inline">H_1:\ \sigma_1^2 &gt; \sigma_2^2</span> but <span class="math inline">s_1^2 &lt; s_2^2</span>, the <span class="math inline">F</span> test should <strong>not</strong> be performed and <span class="math inline">H_0</span> would not be rejected.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="example-9-12" class="slide level2">
<h2>Example 9-12</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Finding a Critical Value, Right-Tailed</strong></p>
</div>
<div class="callout-content">
<p>Find the critical value for a right-tailed <span class="math inline">F</span> test when <span class="math inline">\alpha = 0.05</span>, the degrees of freedom for the numerator (abbreviated d.f.N.) are 12, and the degrees of freedom for the denominator (d.f.D.) are 18.</p>
</div>
</div>
</div>
</section>
<section id="example-9-12-1" class="slide level2">
<h2>Example 9-12</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p>Since this test is right-tailed with <span class="math inline">\alpha = 0.05</span>, use the <span class="math inline">\alpha = 0.05</span> table of Table A-7. The d.f.N. is listed across the top and the d.f.D. in the left column; the critical value is found where row and column intersect. In this case it is <strong>2.34</strong>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb72"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href=""></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb72-2"><a href=""></a>df_numerator <span class="ot">&lt;-</span> <span class="dv">12</span>; df_denominator <span class="ot">&lt;-</span> <span class="dv">18</span></span>
<span id="cb72-3"><a href=""></a><span class="fu">round</span>(<span class="fu">qf</span>(<span class="dv">1</span> <span class="sc">-</span> alpha, df_numerator, df_denominator), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.34</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="example-9-13" class="slide level2">
<h2>Example 9-13</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Finding a Critical Value, Two-Tailed</strong></p>
</div>
<div class="callout-content">
<p>Find the critical value for a two-tailed <span class="math inline">F</span> test with <span class="math inline">\alpha = 0.05</span> when the sample size from which the variance for the numerator was obtained was 16 and the sample size from which the variance for the denominator was obtained was 25.</p>
</div>
</div>
</div>
</section>
<section id="example-9-13-1" class="slide level2">
<h2>Example 9-13</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p>Since this is a two-tailed test with <span class="math inline">\alpha = 0.05</span>, the <span class="math inline">0.05/2 = 0.025</span> table must be used. Here <span class="math inline">\text{d.f.N.} = 16 - 1 = 15</span> and <span class="math inline">\text{d.f.D.} = 25 - 1 = 24</span>; the critical value is <strong>2.44</strong>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb74"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href=""></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb74-2"><a href=""></a>n_numerator <span class="ot">&lt;-</span> <span class="dv">16</span>; n_denominator <span class="ot">&lt;-</span> <span class="dv">25</span></span>
<span id="cb74-3"><a href=""></a>df_numerator <span class="ot">&lt;-</span> n_numerator <span class="sc">-</span> <span class="dv">1</span>; df_denominator <span class="ot">&lt;-</span> n_denominator <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb74-4"><a href=""></a><span class="fu">c</span>(<span class="at">dfN =</span> df_numerator, <span class="at">dfD =</span> df_denominator)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>dfN dfD 
 15  24 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb76"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href=""></a><span class="fu">round</span>(<span class="fu">qf</span>(<span class="dv">1</span> <span class="sc">-</span> alpha<span class="sc">/</span><span class="dv">2</span>, df_numerator, df_denominator), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.44</code></pre>
</div>
</div>
<p>Only the <strong>right</strong> tail is used, because the <span class="math inline">F</span> test statistic is always greater than or equal to 1 when the larger variance is placed in the numerator.</p>
</div>
</div>
</div>
</section>
<section id="example-9-14" class="slide level2">
<h2>Example 9-14</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Order-Picking Times at Two Warehouses</strong></p>
</div>
<div class="callout-content">
<p>A logistics manager wishes to see if the variance of the times it takes to pick an order at the Taoyuan warehouse is different from the variance of the times at the Taichung warehouse. The manager selects random samples of orders at each warehouse and compares the variances of each. At <span class="math inline">\alpha = 0.05</span>, is there enough evidence to support the claim that the variances are not equal? Assume the variable is normally distributed. <em>(hypothetical data)</em></p>
<pre><code>              Taoyuan    Taichung
n                  25          19
s^2              45.0        23.5</code></pre>
</div>
</div>
</div>
</section>
<section id="example-9-14-1" class="slide level2">
<h2>Example 9-14</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> State the hypotheses and identify the claim.</p>
<p><span class="math display">H_0:\ \sigma_1^2 = \sigma_2^2 \qquad H_1:\ \sigma_1^2 \neq \sigma_2^2 \ \textit{(claim)}</span></p>
<p><strong>Step 2.</strong> Find the critical value. Use Table A-7 with 0.025, since <span class="math inline">\alpha = 0.05</span> and the test is two-tailed. The larger variance comes from the Taoyuan sample, so <span class="math inline">\text{d.f.N.} = 25 - 1 = 24</span> and <span class="math inline">\text{d.f.D.} = 19 - 1 = 18</span>; the critical value is <strong>2.50</strong>.</p>
<p><strong>Step 3.</strong> Compute the test statistic.</p>
<p><span class="math display">F = \frac{s_1^2}{s_2^2} = \frac{45.0}{23.5} = 1.91</span></p>
</div>
</div>
</div>
</section>
<section id="example-9-14-2" class="slide level2">
<h2>Example 9-14</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Steps 2-5 in R</strong> — critical value, test statistic, P-value, and decision.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb79"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href=""></a>var_taoyuan  <span class="ot">&lt;-</span> <span class="fl">45.0</span>; n_taoyuan_picks  <span class="ot">&lt;-</span> <span class="dv">25</span></span>
<span id="cb79-2"><a href=""></a>var_taichung <span class="ot">&lt;-</span> <span class="fl">23.5</span>; n_taichung_picks <span class="ot">&lt;-</span> <span class="dv">19</span></span>
<span id="cb79-3"><a href=""></a>df_numerator <span class="ot">&lt;-</span> n_taoyuan_picks <span class="sc">-</span> <span class="dv">1</span>; df_denominator <span class="ot">&lt;-</span> n_taichung_picks <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb79-4"><a href=""></a>f_statistic <span class="ot">&lt;-</span> var_taoyuan <span class="sc">/</span> var_taichung</span>
<span id="cb79-5"><a href=""></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">dfN =</span> df_numerator, <span class="at">dfD =</span> df_denominator, <span class="at">F =</span> f_statistic), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  dfN   dfD     F 
24.00 18.00  1.91 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb81"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href=""></a><span class="fu">round</span>(<span class="fu">qf</span>(<span class="fl">0.975</span>, df_numerator, df_denominator), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.5</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb83"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href=""></a><span class="fu">round</span>(<span class="dv">2</span> <span class="sc">*</span> <span class="fu">pf</span>(f_statistic, df_numerator, df_denominator, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>), <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1612</code></pre>
</div>
</div>
<p><strong>Step 4.</strong> Do not reject <span class="math inline">H_0</span>, since <span class="math inline">1.91 &lt; 2.50</span>. (The P-value is 0.1612.)</p>
<p><strong>Step 5.</strong> There is not enough evidence to support the claim that the variances are not equal.</p>
</div>
</div>
</div>
</section>
<section id="example-9-15" class="slide level2">
<h2>Example 9-15</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Lead-Time Variability of Two Suppliers</strong></p>
</div>
<div class="callout-content">
<p>An import manager selected a random sample of 12 shipments from Supplier A and found the standard deviation of their lead times was 0.84 day. Then the manager selected a random sample of 16 shipments from Supplier B and found that the standard deviation of their lead times was 0.55 day. At <span class="math inline">\alpha = 0.01</span>, can we conclude that the variance of the lead times of Supplier A is greater than the variance of the lead times of Supplier B? <em>(hypothetical data)</em></p>
<pre><code>                 Supplier A    Supplier B
n                        12            16
s                      0.84          0.55</code></pre>
</div>
</div>
</div>
</section>
<section id="example-9-15-1" class="slide level2">
<h2>Example 9-15</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> State the hypotheses and identify the claim.</p>
<p><span class="math display">H_0:\ \sigma_1^2 = \sigma_2^2 \qquad H_1:\ \sigma_1^2 &gt; \sigma_2^2 \ \textit{(claim)}</span></p>
<p><strong>Step 2.</strong> Find the critical value. The larger variance comes from the Supplier A sample, so <span class="math inline">\text{d.f.N.} = 12 - 1 = 11</span> and <span class="math inline">\text{d.f.D.} = 16 - 1 = 15</span>; from Table A-7 at <span class="math inline">\alpha = 0.01</span> the critical value is <strong>3.73</strong>.</p>
<p><strong>Step 3.</strong> Compute the test statistic. The standard deviations must be squared.</p>
<p><span class="math display">F = \frac{s_1^2}{s_2^2} = \frac{0.84^2}{0.55^2} = 2.33</span></p>
</div>
</div>
</div>
</section>
<section id="example-9-15-2" class="slide level2">
<h2>Example 9-15</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Steps 2-5 in R</strong> — critical value, test statistic, P-value, and decision.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb86"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href=""></a>sd_supplier_a <span class="ot">&lt;-</span> <span class="fl">0.84</span>; n_supplier_a <span class="ot">&lt;-</span> <span class="dv">12</span></span>
<span id="cb86-2"><a href=""></a>sd_supplier_b <span class="ot">&lt;-</span> <span class="fl">0.55</span>; n_supplier_b <span class="ot">&lt;-</span> <span class="dv">16</span></span>
<span id="cb86-3"><a href=""></a>df_numerator <span class="ot">&lt;-</span> n_supplier_a <span class="sc">-</span> <span class="dv">1</span>; df_denominator <span class="ot">&lt;-</span> n_supplier_b <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb86-4"><a href=""></a>f_statistic <span class="ot">&lt;-</span> sd_supplier_a<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> sd_supplier_b<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb86-5"><a href=""></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">dfN =</span> df_numerator, <span class="at">dfD =</span> df_denominator, <span class="at">F =</span> f_statistic), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  dfN   dfD     F 
11.00 15.00  2.33 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb88"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href=""></a><span class="fu">round</span>(<span class="fu">qf</span>(<span class="fl">0.99</span>, df_numerator, df_denominator), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.73</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb90"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href=""></a><span class="fu">round</span>(<span class="fu">pf</span>(f_statistic, df_numerator, df_denominator, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>), <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0643</code></pre>
</div>
</div>
<p><strong>Step 4.</strong> Do not reject <span class="math inline">H_0</span>, since <span class="math inline">2.33 &lt; 3.73</span>.</p>
<p><strong>Step 5.</strong> There is not enough evidence to support the claim that the variance of the lead times of Supplier A is greater than the variance of the lead times of Supplier B.</p>
</div>
</div>
</div>
</section>
<section id="p-values-for-the-f-test" class="slide level2">
<h2>P-Values for the F Test</h2>
<p>Finding P-values for an <span class="math inline">F</span> test statistic from the tables requires looking through all five <span class="math inline">\alpha</span> tables of Table A-7 for the given d.f.N. and d.f.D.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Reading a P-Value Interval from Table A-7</strong></p>
</div>
<div class="callout-content">
<p>For <span class="math inline">F = 3.58</span> with <span class="math inline">\text{d.f.N.} = 5</span> and <span class="math inline">\text{d.f.D.} = 10</span>:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th><span class="math inline">\alpha</span></th>
<th>0.10</th>
<th>0.05</th>
<th>0.025</th>
<th>0.01</th>
<th>0.005</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">F</span></td>
<td>2.52</td>
<td>3.33</td>
<td>4.24</td>
<td>5.64</td>
<td>6.87</td>
</tr>
</tbody>
</table>
<p>The test statistic 3.58 falls between 3.33 and 4.24, so for a <strong>right-tailed</strong> test <span class="math inline">0.025 &lt; P\text{-value} &lt; 0.05</span>. For a <strong>two-tailed</strong> test the table <span class="math inline">\alpha</span> values must be <strong>doubled</strong>, giving <span class="math inline">0.05 &lt; P\text{-value} &lt; 0.10</span>. A calculator gives <span class="math inline">P = 0.0408</span>.</p>
<p>As always, if the P-value is less than <span class="math inline">\alpha</span>, reject <span class="math inline">H_0</span>.</p>
</div>
</div>
</div>
<p>With R, <code>pf(F, dfN, dfD, lower.tail = FALSE)</code> gives the exact right-tailed P-value directly.</p>
</section>
<section id="example-9-16" class="slide level2">
<h2>Example 9-16</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Monthly Shipping Volume by Region</strong></p>
</div>
<div class="callout-content">
<p>The operations director of a freight forwarder hypothesizes that the variance in the monthly shipping volume of the company’s northern branches is greater than the variance in the monthly shipping volume of its southern branches. At <span class="math inline">\alpha = 0.10</span>, is there enough evidence to support the hypothesis? The data in thousands of cartons per month are shown for selected branches. Use the <strong>P-value method</strong>. Assume the variable is normally distributed and the samples are random and independent. <em>(hypothetical data)</em></p>
<pre><code>Northern branches        Southern branches
  48.2      55.3            50.4     53.2
  61.5      44.6            41.2     45.9
  39.8      58.1</code></pre>
</div>
</div>
</div>
</section>
<section id="example-9-16-1" class="slide level2">
<h2>Example 9-16</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> State the hypotheses and identify the claim.</p>
<p><span class="math display">H_0:\ \sigma_1^2 = \sigma_2^2 \qquad H_1:\ \sigma_1^2 &gt; \sigma_2^2 \ \textit{(claim)}</span></p>
<p><strong>Step 2.</strong> Compute the test statistic. Find the variance for each group: <span class="math inline">s_1^2 = 70.60</span> and <span class="math inline">s_2^2 = 27.68</span>.</p>
<p><span class="math display">F = \frac{s_1^2}{s_2^2} = \frac{70.60}{27.68} = 2.55</span></p>
<p><strong>Step 3.</strong> Find the P-value with <span class="math inline">\text{d.f.N.} = 6 - 1 = 5</span> and <span class="math inline">\text{d.f.D.} = 4 - 1 = 3</span>.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th><span class="math inline">\alpha</span></th>
<th>0.10</th>
<th>0.05</th>
<th>0.025</th>
<th>0.01</th>
<th>0.005</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">F</span></td>
<td>5.31</td>
<td>9.01</td>
<td>14.88</td>
<td>28.24</td>
<td>45.39</td>
</tr>
</tbody>
</table>
<p>Since 2.55 is less than 5.31, the P-value is greater than 0.10.</p>
</div>
</div>
</div>
</section>
<section id="example-9-16-2" class="slide level2">
<h2>Example 9-16</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Steps 2-5 in R</strong> — variances, test statistic, and exact P-value.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb93"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href=""></a>northern <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">48.2</span>, <span class="fl">61.5</span>, <span class="fl">39.8</span>, <span class="fl">55.3</span>, <span class="fl">44.6</span>, <span class="fl">58.1</span>)</span>
<span id="cb93-2"><a href=""></a>southern <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">50.4</span>, <span class="fl">41.2</span>, <span class="fl">53.2</span>, <span class="fl">45.9</span>)</span>
<span id="cb93-3"><a href=""></a>df_numerator <span class="ot">&lt;-</span> <span class="fu">length</span>(northern) <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb93-4"><a href=""></a>df_denominator <span class="ot">&lt;-</span> <span class="fu">length</span>(southern) <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb93-5"><a href=""></a>f_statistic <span class="ot">&lt;-</span> <span class="fu">var</span>(northern) <span class="sc">/</span> <span class="fu">var</span>(southern)</span>
<span id="cb93-6"><a href=""></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">var_northern =</span> <span class="fu">var</span>(northern), <span class="at">var_southern =</span> <span class="fu">var</span>(southern)), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>var_northern var_southern 
       70.60        27.68 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb95"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href=""></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">dfN =</span> df_numerator, <span class="at">dfD =</span> df_denominator, <span class="at">F =</span> f_statistic), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> dfN  dfD    F 
5.00 3.00 2.55 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb97"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href=""></a><span class="fu">round</span>(<span class="fu">pf</span>(f_statistic, df_numerator, df_denominator, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.235</code></pre>
</div>
</div>
<p><strong>Step 4.</strong> Do not reject <span class="math inline">H_0</span>, since P-value <span class="math inline">&gt; 0.10</span>. (The exact value from R is 0.235.)</p>
<p><strong>Step 5.</strong> There is not enough evidence to support the claim that the variance in the monthly shipping volume of the northern branches is greater than the variance in the monthly shipping volume of the southern branches.</p>
</div>
</div>
</div>
</section>
<section id="important-terms" class="slide level2">
<h2>Important Terms</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Chapter 9 Vocabulary</strong></p>
</div>
<div class="callout-content">
<p>dependent samples · <span class="math inline">F</span> distribution · <span class="math inline">F</span> test · independent samples · pooled estimate of the variance</p>
</div>
</div>
</div>
</section>
<section id="key-formulas" class="slide level2">
<h2>Key Formulas</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Two Means: z Test and t Test</strong></p>
</div>
<div class="callout-content">
<p><span class="math inline">z</span> test for two means, <span class="math inline">\sigma_1</span> and <span class="math inline">\sigma_2</span> known, and its confidence interval:</p>
<p><span class="math display">z = \frac{(\bar{X}_1 - \bar{X}_2) - (\mu_1 - \mu_2)}{\sqrt{\dfrac{\sigma_1^2}{n_1}+\dfrac{\sigma_2^2}{n_2}}} \qquad (\bar{X}_1 - \bar{X}_2) \pm z_{\alpha/2}\sqrt{\frac{\sigma_1^2}{n_1}+\frac{\sigma_2^2}{n_2}}</span></p>
<p><span class="math inline">t</span> test for two means, independent samples, variances unequal, $ = $ smaller of <span class="math inline">n_1-1</span> and <span class="math inline">n_2-1</span>:</p>
<p><span class="math display">t = \frac{(\bar{X}_1 - \bar{X}_2) - (\mu_1 - \mu_2)}{\sqrt{\dfrac{s_1^2}{n_1}+\dfrac{s_2^2}{n_2}}} \qquad (\bar{X}_1 - \bar{X}_2) \pm t_{\alpha/2}\sqrt{\frac{s_1^2}{n_1}+\frac{s_2^2}{n_2}}</span></p>
</div>
</div>
</div>
</section>
<section id="key-formulas-1" class="slide level2">
<h2>Key Formulas</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Dependent Samples, Proportions, and Variances</strong></p>
</div>
<div class="callout-content">
<p><span class="math inline">t</span> test for dependent samples, <span class="math inline">\text{d.f.} = n - 1</span>, and its confidence interval:</p>
<p><span class="math display">t = \frac{\bar{D} - \mu_D}{s_D/\sqrt{n}} \quad \bar{D} = \frac{\sum D}{n} \quad s_D = \sqrt{\frac{n\sum D^2 - (\sum D)^2}{n(n-1)}} \quad \bar{D} \pm t_{\alpha/2}\frac{s_D}{\sqrt{n}}</span></p>
<p><span class="math inline">z</span> test for two proportions and the confidence interval for <span class="math inline">p_1 - p_2</span>:</p>
<p><span class="math display">z = \frac{(\hat{p}_1 - \hat{p}_2) - (p_1 - p_2)}{\sqrt{\bar{p}\,\bar{q}\left(\dfrac{1}{n_1}+\dfrac{1}{n_2}\right)}} \qquad (\hat{p}_1-\hat{p}_2) \pm z_{\alpha/2}\sqrt{\frac{\hat{p}_1\hat{q}_1}{n_1}+\frac{\hat{p}_2\hat{q}_2}{n_2}}</span></p>
<p><span class="math inline">F</span> test for two variances, <span class="math inline">\text{d.f.N.} = n_1 - 1</span>, <span class="math inline">\text{d.f.D.} = n_2 - 1</span>, larger variance on top:</p>
<p><span class="math display">F = \frac{s_1^2}{s_2^2}</span></p>
</div>
</div>
</div>
</section>
<section id="key-takeaways" class="slide level2">
<h2>Key Takeaways</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Key point</strong></p>
</div>
<div class="callout-content">
<ul>
<li>Comparing two parameters uses the same five-step procedure as Chapter 8; every test statistic has the form <span class="math inline">(\text{observed} - \text{expected})/\text{standard error}</span>, and <span class="math inline">H_0</span> can be written as <span class="math inline">\mu_1 = \mu_2</span> or as <span class="math inline">\mu_1 - \mu_2 = 0</span></li>
<li>Samples are <strong>independent</strong> when the selection of one sample does not influence the other, and <strong>dependent</strong> (matched-pair) when subjects are paired or matched</li>
<li>Use the <strong><span class="math inline">z</span> test</strong> for two means when <span class="math inline">\sigma_1</span> and <span class="math inline">\sigma_2</span> are <strong>known</strong> (and, if <span class="math inline">n &lt; 30</span>, the populations are normal); the standard error is <span class="math inline">\sqrt{\sigma_1^2/n_1 + \sigma_2^2/n_2}</span></li>
<li>Use the <strong><span class="math inline">t</span> test</strong> for two independent means when <span class="math inline">\sigma_1</span> and <span class="math inline">\sigma_2</span> are <strong>unknown</strong>; this text assumes unequal variances and uses $ = $ the <strong>smaller</strong> of <span class="math inline">n_1-1</span> and <span class="math inline">n_2-1</span>, which is conservative</li>
<li>For <strong>dependent samples</strong>, test the differences <span class="math inline">D = X_1 - X_2</span> with <span class="math inline">t = \bar{D}/(s_D/\sqrt{n})</span> and <span class="math inline">\text{d.f.} = n-1</span>; matching reduces type II error but does not control other variables</li>
<li>For <strong>two proportions</strong>, pool the samples into <span class="math inline">\bar{p} = (X_1+X_2)/(n_1+n_2)</span> and <span class="math inline">\bar{q} = 1 - \bar{p}</span>; the test requires <span class="math inline">np \geq 5</span> and <span class="math inline">nq \geq 5</span> in both samples</li>
<li>For <strong>two variances</strong>, <span class="math inline">F = s_1^2/s_2^2</span> with the <strong>larger variance in the numerator</strong>, <span class="math inline">\text{d.f.N.} = n_1-1</span>, <span class="math inline">\text{d.f.D.} = n_2-1</span>, and <span class="math inline">\alpha</span> <strong>halved</strong> for a two-tailed test; the <span class="math inline">F</span> test is <strong>not robust</strong> to departures from normality</li>
<li>A confidence interval that <strong>contains zero</strong> agrees with a decision not to reject <span class="math inline">H_0</span> — except for two proportions, where the test and the interval use different standard errors and the <span class="math inline">z</span> test governs</li>
</ul>
</div>
</div>
</div>
</section>
<section id="acknowledgement" class="slide level2">
<h2>Acknowledgement</h2>
<ul>
<li><p><strong>Copyright notice.</strong> These teaching materials follow the organization and terminology of <strong>Bluman, A. G. (2023). Elementary statistics: A step by step approach (11th ed.). McGraw Hill</strong>. All rights in the original work are reserved by its authors and publishers.</p></li>
<li><p><strong>Original examples.</strong> Every worked example, data set, and R script in these slides was written for this course. The data are hypothetical unless stated otherwise.</p></li>
<li><p><strong>Non-commercial use only.</strong> These materials are strictly intended for educational purposes and must not be used for commercial gain or profit.</p></li>
<li><p><strong>Proper attribution.</strong> Any reproduction, distribution, or use of these materials must provide proper attribution to the original source.</p></li>
</ul>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="logo.svg" class="slide-logo"></p>
<div class="footer footer-default">
<p>Elementary Statistics: A Step by Step Approach</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="ch9_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="ch9_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="ch9_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="ch9_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="ch9_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="ch9_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="ch9_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="ch9_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="ch9_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":false,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true,"hideMissingTitles":true,"titleSelector":"h1"},
'smaller': true,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    <script>
    Reveal.on('ready', function() {
      var title = Reveal.getSlides()[0];
      if (title) {
        title.insertAdjacentHTML('beforeend',
          '<p style="font-size:0.5em; margin-top:1.5em;">' +
          '<a href="ch9-zh.html"  style="color:#555;">[中文版由此去]</a>' +
          '</p>');
      }
    });
    </script>
    

</body></html>