<!DOCTYPE html>
<html lang="en"><head>
<script src="ch8_files/libs/clipboard/clipboard.min.js"></script>
<script src="ch8_files/libs/quarto-html/tabby.min.js"></script>
<script src="ch8_files/libs/quarto-html/popper.min.js"></script>
<script src="ch8_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="ch8_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="ch8_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="ch8_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.38">

  <meta name="author" content="Yu-You Liou">
  <meta name="dcterms.date" content="2026-10-08">
  <title>Statistics</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="ch8_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="ch8_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="ch8_files/libs/revealjs/dist/theme/quarto-2abc1c5b7b5c7eecd6137558e106e4c3.css">
  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">
  <link href="ch8_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="ch8_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="ch8_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="ch8_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-notes="" class="quarto-title-block center">
  <h1 class="title">Statistics</h1>
  <p class="subtitle">Chapter 8: Hypothesis Testing</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Yu-You Liou 
</div>
        <p class="quarto-title-affiliation">
            Shih Chien University
          </p>
    </div>
</div>

  <p class="date">2026-10-08</p>
</section>
<section id="overview" class="slide level2">
<h2>Overview</h2>
<p>Chapter 8 is about <strong>hypothesis testing</strong> — using sample data to evaluate a claim about a population parameter.</p>
<table class="caption-top">
<colgroup>
<col style="width: 52%">
<col style="width: 47%">
</colgroup>
<thead>
<tr class="header">
<th>Section</th>
<th>Topics</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>8-1</td>
<td>Null and alternative hypotheses; test statistic; type I and II errors; <span class="math inline">\alpha</span>; critical value and region; one- and two-tailed tests; traditional and P-value methods</td>
</tr>
<tr class="even">
<td>8-2</td>
<td><span class="math inline">z</span> test for a mean, <span class="math inline">\sigma</span> known; assumptions; traditional and P-value methods</td>
</tr>
<tr class="odd">
<td>8-3</td>
<td><span class="math inline">t</span> test for a mean, <span class="math inline">\sigma</span> unknown; critical <span class="math inline">t</span> values; P-value intervals; <span class="math inline">z</span> versus <span class="math inline">t</span></td>
</tr>
</tbody>
</table>
</section>
<section id="overview-continued" class="slide level2">
<h2>Overview (continued)</h2>
<table class="caption-top">
<colgroup>
<col style="width: 52%">
<col style="width: 47%">
</colgroup>
<thead>
<tr class="header">
<th>Section</th>
<th>Topics</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>8-4</td>
<td><span class="math inline">z</span> test for a proportion; assumptions <span class="math inline">np \geq 5</span>, <span class="math inline">nq \geq 5</span></td>
</tr>
<tr class="even">
<td>8-5</td>
<td><span class="math inline">\chi^2</span> test for a variance or standard deviation; critical <span class="math inline">\chi^2</span> values</td>
</tr>
<tr class="odd">
<td>8-6</td>
<td>Confidence intervals and hypothesis testing; type II error, <span class="math inline">\beta</span>, power</td>
</tr>
</tbody>
</table>
</section>
<section id="chapter-objectives" class="slide level2">
<h2>Chapter Objectives</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>After completing this chapter, you should be able to</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>Understand the definitions used in hypothesis testing.</li>
<li>State the null and alternative hypotheses.</li>
<li>Find critical values for the <span class="math inline">z</span> test.</li>
<li>State the five steps used in hypothesis testing.</li>
<li>Test means when <span class="math inline">\sigma</span> is known, using the <span class="math inline">z</span> test.</li>
<li>Test means when <span class="math inline">\sigma</span> is unknown, using the <span class="math inline">t</span> test.</li>
<li>Test proportions, using the <span class="math inline">z</span> test.</li>
<li>Test variances or standard deviations, using the chi-square test.</li>
<li>Test hypotheses, using confidence intervals.</li>
<li>Explain the relationship between type I and type II errors and the power of a test.</li>
</ol>
</div>
</div>
</div>
</section>
<section>
<section id="section-8-1-steps-in-hypothesis-testingtraditional-method" class="title-slide slide level1 center" data-background-color="#2c4a6e">
<h1>Section 8-1: Steps in Hypothesis Testing—Traditional Method</h1>

</section>
<section id="hypothesis-testing" class="slide level2">
<h2>Hypothesis Testing</h2>
<p><strong>Statistical hypothesis testing</strong> is a decision-making process for evaluating claims about a population. The researcher defines the population, states the hypotheses, gives the significance level, selects a sample, collects the data, performs the calculations required for the statistical test, and reaches a conclusion.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Three Methods Used to Test Hypotheses</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>The <strong>traditional method</strong> — compare the test statistic with a critical value.</li>
<li>The <strong>P-value method</strong> — compare the P-value with <span class="math inline">\alpha</span>.</li>
<li>The <strong>confidence interval method</strong> — see whether the interval contains the hypothesized value (Section 8-6).</li>
</ol>
<p>The traditional method has been used since hypothesis testing was formulated; the P-value method became popular with modern computers and statistical calculators.</p>
</div>
</div>
</div>
</section>
<section id="statistical-hypotheses" class="slide level2">
<h2>Statistical Hypotheses</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Statistical Hypothesis</strong></p>
</div>
<div class="callout-content">
<p>A <strong>statistical hypothesis</strong> is a conjecture about a population parameter. This conjecture may or may not be true.</p>
</div>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Null and Alternative Hypotheses</strong></p>
</div>
<div class="callout-content">
<p>The <strong>null hypothesis</strong>, symbolized by <span class="math inline">H_0</span>, is a statistical hypothesis that states that there is no difference between a parameter and a specific value, or that there is no difference between two parameters.</p>
<p>The <strong>alternative hypothesis</strong>, symbolized by <span class="math inline">H_1</span>, is a statistical hypothesis that states the existence of a difference between a parameter and a specific value, or states that there is a difference between two parameters.</p>
</div>
</div>
</div>
</section>
<section id="three-illustrative-situations" class="slide level2">
<h2>Three Illustrative Situations</h2>
<p><strong>Situation A.</strong> A medical researcher asks whether a new medication changes the pulse rate; the population mean is 82 beats per minute. <span class="math inline">H_0: \mu = 82</span> and <span class="math inline">H_1: \mu \neq 82</span> — a <strong>two-tailed</strong> test.</p>
<p><strong>Situation B.</strong> A chemist invents an additive to increase battery life; the mean lifetime without it is 36 months. <span class="math inline">H_0: \mu = 36</span> and <span class="math inline">H_1: \mu &gt; 36</span> — a <strong>right-tailed</strong> test.</p>
<p><strong>Situation C.</strong> A contractor wishes to lower the average monthly heating bill of $78 with special insulation. <span class="math inline">H_0: \mu = 78</span> and <span class="math inline">H_1: \mu &lt; 78</span> — a <strong>left-tailed</strong> test.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Stating the Hypotheses Together</strong></p>
</div>
<div class="callout-content">
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Two-tailed test</th>
<th>Right-tailed test</th>
<th>Left-tailed test</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mean</td>
<td><span class="math inline">H_0: \mu = k</span>, <span class="math inline">H_1: \mu \neq k</span></td>
<td><span class="math inline">H_0: \mu = k</span>, <span class="math inline">H_1: \mu &gt; k</span></td>
<td><span class="math inline">H_0: \mu = k</span>, <span class="math inline">H_1: \mu &lt; k</span></td>
</tr>
<tr class="even">
<td>Proportion</td>
<td><span class="math inline">H_0: p = k</span>, <span class="math inline">H_1: p \neq k</span></td>
<td><span class="math inline">H_0: p = k</span>, <span class="math inline">H_1: p &gt; k</span></td>
<td><span class="math inline">H_0: p = k</span>, <span class="math inline">H_1: p &lt; k</span></td>
</tr>
</tbody>
</table>
<p>In this book the null hypothesis is <strong>always</strong> stated with an equals sign. Because a researcher generally looks for evidence to <em>support</em> a claim, the claim is usually stated as the alternative hypothesis — which is why <span class="math inline">H_1</span> is sometimes called the <strong>research hypothesis</strong>.</p>
</div>
</div>
</div>
</section>
<section id="table-8-1-hypothesis-testing-common-phrases" class="slide level2">
<h2>Table 8-1: Hypothesis-Testing Common Phrases</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Translating Words into Symbols</strong></p>
</div>
<div class="callout-content">
<table class="caption-top">
<thead>
<tr class="header">
<th><span class="math inline">&gt;</span></th>
<th><span class="math inline">&lt;</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Is greater than</td>
<td>Is less than</td>
</tr>
<tr class="even">
<td>Is above</td>
<td>Is below</td>
</tr>
<tr class="odd">
<td>Is higher than</td>
<td>Is lower than</td>
</tr>
<tr class="even">
<td>Is longer than</td>
<td>Is shorter than</td>
</tr>
<tr class="odd">
<td>Is bigger than</td>
<td>Is smaller than</td>
</tr>
<tr class="even">
<td>Is increased</td>
<td>Is decreased or reduced from</td>
</tr>
</tbody>
</table>
<table class="caption-top">
<thead>
<tr class="header">
<th><span class="math inline">=</span></th>
<th><span class="math inline">\neq</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Is equal to</td>
<td>Is not equal to</td>
</tr>
<tr class="even">
<td>Is no different from</td>
<td>Is different from</td>
</tr>
<tr class="odd">
<td>Has not changed from</td>
<td>Has changed from</td>
</tr>
<tr class="even">
<td>Is the same as</td>
<td>Is not the same as</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="at-least-and-at-most" class="slide level2">
<h2>“At Least” and “At Most”</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Caution</strong></p>
</div>
<div class="callout-content">
<p>A claim stated with the words <strong>“at least”</strong> or <strong>“at most”</strong> is a <em>null</em> hypothesis.</p>
<ul>
<li>“You must be at least 21 years of age” means <span class="math inline">\mu \geq 21</span>, written as <span class="math inline">\mu = 21</span> for <span class="math inline">H_0</span>; then <span class="math inline">H_1: \mu &lt; 21</span>.</li>
<li>“A theater can seat at most 115 persons” means <span class="math inline">\mu \leq 115</span>, written as <span class="math inline">\mu = 115</span> for <span class="math inline">H_0</span>; then <span class="math inline">H_1: \mu &gt; 115</span>.</li>
</ul>
</div>
</div>
</div>
<p>A claim can be stated as either the null or the alternative hypothesis, but statistical evidence can only <strong>support</strong> the claim when it is the alternative hypothesis, and can only <strong>reject</strong> the claim when it is the null hypothesis.</p>
</section>
<section id="example-8-1" class="slide level2">
<h2>Example 8-1</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Stating the Null and Alternative Hypotheses</strong></p>
</div>
<div class="callout-content">
<p>State the null and alternative hypotheses for each conjecture.</p>
<p><strong>(a)</strong> A logistics manager thinks that the average picking time per order at a distribution centre is less than 42 seconds.</p>
<p><strong>(b)</strong> A hotel group believes that the average length of stay of a foreign guest in Taipei is greater than 2.8 nights.</p>
<p><strong>(c)</strong> An analyst thinks that the average weekday number of passengers entering Taipei Main Station has changed from 320 thousand.</p>
<p><strong>(d)</strong> Forty-six percent of online shoppers in Taiwan pay by cash on delivery at a convenience store.</p>
<p><strong>(e)</strong> More than 35% of the export containers leaving Kaohsiung are bound for Southeast Asia.</p>
<p><strong>(f)</strong> Less than 58% of food-delivery orders are placed on a weekday.</p>
</div>
</div>
</div>
</section>
<section id="example-8-1-1" class="slide level2">
<h2>Example 8-1</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>(a)</strong> <span class="math inline">H_0: \mu = 42</span> and <span class="math inline">H_1: \mu &lt; 42</span></p>
<p><strong>(b)</strong> <span class="math inline">H_0: \mu = 2.8</span> and <span class="math inline">H_1: \mu &gt; 2.8</span></p>
<p><strong>(c)</strong> <span class="math inline">H_0: \mu = 320</span> and <span class="math inline">H_1: \mu \neq 320</span></p>
<p><strong>(d)</strong> <span class="math inline">H_0: p = 0.46</span> and <span class="math inline">H_1: p \neq 0.46</span></p>
<p><strong>(e)</strong> <span class="math inline">H_0: p = 0.35</span> and <span class="math inline">H_1: p &gt; 0.35</span></p>
<p><strong>(f)</strong> <span class="math inline">H_0: p = 0.58</span> and <span class="math inline">H_1: p &lt; 0.58</span></p>
</div>
</div>
</div>
</section>
<section id="statistical-test-and-test-statistic" class="slide level2">
<h2>Statistical Test and Test Statistic</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Statistical Test</strong></p>
</div>
<div class="callout-content">
<p>A <strong>statistical test</strong> uses the data obtained from a sample to make a decision about whether the null hypothesis should be rejected.</p>
<p>The numerical value obtained from a statistical test is called the <strong>test statistic</strong>.</p>
</div>
</div>
</div>
<p>Even when <span class="math inline">H_0</span> is true, the sample mean will rarely equal the population mean exactly. Either the difference is due to chance, or the sample came from a population whose mean is some other, unknown value. The farther the sample mean is from the hypothesized mean, the more evidence there is for rejecting <span class="math inline">H_0</span>.</p>
</section>
<section id="four-possible-outcomes" class="slide level2">
<h2>Four Possible Outcomes</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Figure 8-2: Possible Outcomes of a Hypothesis Test</strong></p>
</div>
<div class="callout-content">
<table class="caption-top">
<thead>
<tr class="header">
<th>Decision</th>
<th><span class="math inline">H_0</span> true</th>
<th><span class="math inline">H_0</span> false</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Reject <span class="math inline">H_0</span></td>
<td><strong>Type I error</strong></td>
<td>Correct decision</td>
</tr>
<tr class="even">
<td>Do not reject <span class="math inline">H_0</span></td>
<td>Correct decision</td>
<td><strong>Type II error</strong></td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Type I and Type II Errors</strong></p>
</div>
<div class="callout-content">
<p>A <strong>type I error</strong> occurs if you reject the null hypothesis when it is true.</p>
<p>A <strong>type II error</strong> occurs if you do not reject the null hypothesis when it is false.</p>
</div>
</div>
</div>
</section>
<section id="hypothesis-testing-and-a-jury-trial" class="slide level2">
<h2>Hypothesis Testing and a Jury Trial</h2>
<p>The hypotheses are <span class="math inline">H_0</span>: the defendant is innocent; <span class="math inline">H_1</span>: the defendant is not innocent.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Figure 8-3: The Results of a Trial</strong></p>
</div>
<div class="callout-content">
<table class="caption-top">
<thead>
<tr class="header">
<th>Decision</th>
<th><span class="math inline">H_0</span> true (innocent)</th>
<th><span class="math inline">H_0</span> false (not innocent)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Reject <span class="math inline">H_0</span> (convict)</td>
<td>Type I error</td>
<td>Correct decision</td>
</tr>
<tr class="even">
<td>Do not reject <span class="math inline">H_0</span> (acquit)</td>
<td>Correct decision</td>
<td>Type II error</td>
</tr>
</tbody>
</table>
<p>A type I error puts an innocent person in jail; a type II error lets a guilty person go free.</p>
</div>
</div>
</div>
<p>The verdict does not <em>prove</em> that the defendant did or did not commit the crime — it is based on the evidence presented. Likewise, rejecting or not rejecting <span class="math inline">H_0</span> proves nothing; the decision is made on the basis of probabilities.</p>
</section>
<section id="level-of-significance" class="slide level2">
<h2>Level of Significance</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Level of Significance</strong></p>
</div>
<div class="callout-content">
<p>The <strong>level of significance</strong> is the maximum probability of committing a type I error. This probability is symbolized by <span class="math inline">\alpha</span>. That is, <span class="math inline">P(\text{type I error}) = \alpha</span>.</p>
<p>The probability of a type II error is symbolized by <span class="math inline">\beta</span>: <span class="math inline">P(\text{type II error}) = \beta</span>.</p>
</div>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Three Conventional Levels</strong></p>
</div>
<div class="callout-content">
<p>Statisticians generally agree on the <strong>0.10, 0.05 and 0.01</strong> levels. When <span class="math inline">\alpha = 0.10</span> there is a 10% chance of rejecting a true null hypothesis; when <span class="math inline">\alpha = 0.05</span>, a 5% chance; when <span class="math inline">\alpha = 0.01</span>, a 1% chance.</p>
<p>In most hypothesis-testing situations <span class="math inline">\beta</span> cannot be easily computed; <span class="math inline">\alpha</span> and <span class="math inline">\beta</span> are related in that decreasing one increases the other.</p>
</div>
</div>
</div>
</section>
<section id="critical-region-noncritical-region-and-critical-value" class="slide level2">
<h2>Critical Region, Noncritical Region and Critical Value</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Three Definitions</strong></p>
</div>
<div class="callout-content">
<p>The <strong>critical or rejection region</strong> is the range of test statistics that indicates that there is a significant difference and that the null hypothesis should be rejected.</p>
<p>The <strong>noncritical or nonrejection region</strong> is the range of test statistics that indicates that the difference was probably due to chance and that the null hypothesis should not be rejected.</p>
<p>The <strong>critical value</strong> separates the critical region from the noncritical region. The symbol for critical value is C.V.</p>
</div>
</div>
</div>
</section>
<section id="one-tailed-and-two-tailed-tests" class="slide level2">
<h2>One-Tailed and Two-Tailed Tests</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>One-Tailed Test</strong></p>
</div>
<div class="callout-content">
<p>A <strong>one-tailed test</strong> indicates that the null hypothesis should be rejected when the test statistic is in the critical region on one side of the mean. A one-tailed test is either a right-tailed test or a left-tailed test, depending on the direction of the inequality of the alternative hypothesis.</p>
</div>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Two-Tailed Test</strong></p>
</div>
<div class="callout-content">
<p>In a <strong>two-tailed test</strong>, the null hypothesis should be rejected when the test statistic is in either of the two critical regions. The critical region must be split into two equal parts, each with area <span class="math inline">\alpha/2</span>.</p>
</div>
</div>
</div>
</section>
<section id="figure-8-9-summary-of-hypothesis-testing-and-critical-values" class="slide level2">
<h2>Figure 8-9: Summary of Hypothesis Testing and Critical Values</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Critical Values for the z Test</strong></p>
</div>
<div class="callout-content">
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Test</th>
<th><span class="math inline">\alpha = 0.10</span></th>
<th><span class="math inline">\alpha = 0.05</span></th>
<th><span class="math inline">\alpha = 0.01</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Left-tailed: <span class="math inline">H_0: \mu = k</span>, <span class="math inline">H_1: \mu &lt; k</span></td>
<td>C.V. <span class="math inline">= -1.282</span></td>
<td>C.V. <span class="math inline">= -1.645</span></td>
<td>C.V. <span class="math inline">= -2.326</span></td>
</tr>
<tr class="even">
<td>Right-tailed: <span class="math inline">H_0: \mu = k</span>, <span class="math inline">H_1: \mu &gt; k</span></td>
<td>C.V. <span class="math inline">= +1.282</span></td>
<td>C.V. <span class="math inline">= +1.645</span></td>
<td>C.V. <span class="math inline">= +2.326</span></td>
</tr>
<tr class="odd">
<td>Two-tailed: <span class="math inline">H_0: \mu = k</span>, <span class="math inline">H_1: \mu \neq k</span></td>
<td>C.V. <span class="math inline">= \pm 1.645</span></td>
<td>C.V. <span class="math inline">= \pm 1.960</span></td>
<td>C.V. <span class="math inline">= \pm 2.576</span></td>
</tr>
</tbody>
</table>
<p>Table A-4 in Appendix A is a convenient way to look these values up by hand. Every critical value quoted in this chapter is the value <code>qnorm()</code> returns.</p>
</div>
</div>
</div>
</section>
<section id="procedure-table-finding-critical-values-for-specific-alpha-values" class="slide level2">
<h2>Procedure Table: Finding Critical Values for Specific <span class="math inline">\alpha</span> Values</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Using Table A-4</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> Draw the figure and indicate the appropriate area.</p>
<ol type="a">
<li>If the test is <strong>left-tailed</strong>, the critical region, with area <span class="math inline">\alpha</span>, is on the left side of the mean.</li>
<li>If the test is <strong>right-tailed</strong>, the critical region, with area <span class="math inline">\alpha</span>, is on the right side of the mean.</li>
<li>If the test is <strong>two-tailed</strong>, <span class="math inline">\alpha</span> must be divided by 2; half the area is on each side.</li>
</ol>
<p><strong>Step 2.</strong></p>
<ol type="a">
<li>For a left-tailed test, use the <span class="math inline">z</span> score that corresponds to the area equivalent to <span class="math inline">\alpha</span>.</li>
<li>For a right-tailed test, use the <span class="math inline">z</span> score that corresponds to the area equivalent to <span class="math inline">1 - \alpha</span>.</li>
<li>For a two-tailed test, use the <span class="math inline">z</span> score corresponding to <span class="math inline">\alpha/2</span> for the (negative) left value, and to <span class="math inline">1 - \alpha/2</span> for the (positive) right value.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="example-8-2" class="slide level2">
<h2>Example 8-2</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Finding the Critical Value(s)</strong></p>
</div>
<div class="callout-content">
<p>Find the critical value(s) for each situation and draw the appropriate figure, showing the critical region. Table A-4 in Appendix A gives the same values by hand.</p>
<p><strong>(a)</strong> A right-tailed test with <span class="math inline">\alpha = 0.02</span>.</p>
<p><strong>(b)</strong> A two-tailed test with <span class="math inline">\alpha = 0.05</span>.</p>
<p><strong>(c)</strong> A left-tailed test with <span class="math inline">\alpha = 0.10</span>.</p>
</div>
</div>
</div>
</section>
<section id="example-8-2-1" class="slide level2">
<h2>Example 8-2</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1 — draw the figure and locate the area.</strong> In (a) the area 0.02 sits in the right tail; in (b) two areas of <span class="math inline">\alpha/2 = 0.025</span> sit in the two tails; in (c) the area 0.10 sits in the left tail.</p>
<p><strong>Step 2 — read the <span class="math inline">z</span> score.</strong> In R, <code>qnorm()</code> plays the role of Table A-4.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href=""></a><span class="fu">qnorm</span>(<span class="fl">0.98</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.053749</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href=""></a><span class="fu">qnorm</span>(<span class="fl">0.025</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1.959964</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href=""></a><span class="fu">qnorm</span>(<span class="fl">0.975</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.959964</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href=""></a><span class="fu">qnorm</span>(<span class="fl">0.10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1.281552</code></pre>
</div>
</div>
<p><strong>Answers.</strong> (a) <span class="math inline">+2.05</span>; (b) <span class="math inline">-1.96</span> and <span class="math inline">+1.96</span>; (c) <span class="math inline">-1.28</span>.</p>
</div>
</div>
</div>
</section>
<section id="critical-and-noncritical-regions-in-r" class="slide level2">
<h2>Critical and Noncritical Regions in R</h2>
<p><strong>Prepare data</strong> — the right-tailed case of Figure 8-5, with <span class="math inline">\alpha = 0.01</span>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href=""></a>cv <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="fl">0.99</span>)</span>
<span id="cb9-2"><a href=""></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">4</span>, <span class="dv">4</span>, <span class="at">by =</span> <span class="fl">0.01</span>)</span>
<span id="cb9-3"><a href=""></a>curve <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(x, <span class="at">density =</span> <span class="fu">dnorm</span>(x))</span>
<span id="cb9-4"><a href=""></a></span>
<span id="cb9-5"><a href=""></a>cv</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.326348</code></pre>
</div>
</div>
</section>
<section id="critical-and-noncritical-regions-in-r-1" class="slide level2">
<h2>Critical and Noncritical Regions in R</h2>
<p><strong>Output figure</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href=""></a><span class="fu">ggplot</span>(curve, <span class="fu">aes</span>(x, density)) <span class="sc">+</span></span>
<span id="cb11-2"><a href=""></a>  <span class="fu">geom_area</span>(<span class="at">data =</span> <span class="fu">filter</span>(curve, x <span class="sc">&gt;=</span> cv)) <span class="sc">+</span></span>
<span id="cb11-3"><a href=""></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb11-4"><a href=""></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> cv) <span class="sc">+</span></span>
<span id="cb11-5"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Critical and Noncritical Regions, Right-Tailed Test"</span>,</span>
<span id="cb11-6"><a href=""></a>       <span class="at">x =</span> <span class="st">"z"</span>, <span class="at">y =</span> <span class="st">"Density"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="ch8_files/figure-revealjs/s8-1-2-1.png" class="quarto-figure quarto-figure-center r-stretch" style="width:80.0%"><p>The shaded area to the right of the critical value <span class="math inline">z = 2.326</span> is the <strong>critical (rejection) region</strong>; everything to the left is the <strong>noncritical (nonrejection) region</strong>.</p>
</section>
<section id="the-five-steps-of-hypothesis-testing" class="slide level2">
<h2>The Five Steps of Hypothesis Testing</h2>
<p>In general a study proceeds by (a) stating the hypotheses, (b) designing the study, (c) conducting the study and collecting the data, (d) evaluating the data, and (e) summarizing the results. Because designing the study and collecting the data are omitted here, a simplified version is used.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Procedure Table: Solving Hypothesis-Testing Problems (Traditional Method)</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> State the hypotheses and identify the claim.</p>
<p><strong>Step 2.</strong> Find the critical value(s) from the appropriate table in Appendix A.</p>
<p><strong>Step 3.</strong> Compute the test statistic.</p>
<p><strong>Step 4.</strong> Make the decision to reject or not reject the null hypothesis.</p>
<p><strong>Step 5.</strong> Summarize the results.</p>
</div>
</div>
</div>
</section>
<section id="summarizing-the-results" class="slide level2">
<h2>Summarizing the Results</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Wording the Conclusion</strong></p>
</div>
<div class="callout-content">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Decision</th>
<th>Claim is <span class="math inline">H_0</span></th>
<th>Claim is <span class="math inline">H_1</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Reject <span class="math inline">H_0</span></td>
<td>There is enough evidence to <strong>reject</strong> the claim.</td>
<td>There is enough evidence to <strong>support</strong> the claim.</td>
</tr>
<tr class="even">
<td>Do not reject <span class="math inline">H_0</span></td>
<td>There is not enough evidence to <strong>reject</strong> the claim.</td>
<td>There is not enough evidence to <strong>support</strong> the claim.</td>
</tr>
</tbody>
</table>
<p>Nothing is proved true or false. The statistician only states that there is, or is not, enough evidence to say that a claim is probably true or false.</p>
</div>
</div>
</div>
</section>
<section id="the-p-value-method-for-hypothesis-testing" class="slide level2">
<h2>The P-Value Method for Hypothesis Testing</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>P-Value</strong></p>
</div>
<div class="callout-content">
<p>The <strong>P-value</strong> (or probability value) is the probability of getting a sample statistic (such as the sample mean) or a more extreme sample statistic in the direction of the alternative hypothesis when the null hypothesis is true.</p>
</div>
</div>
</div>
<p>The P-value is the actual area under the curve of the appropriate distribution representing the probability of the observed sample statistic, or a more extreme one, occurring if <span class="math inline">H_0</span> is true.</p>
</section>
<section id="comparing-alpha-values-and-p-values" class="slide level2">
<h2>Comparing <span class="math inline">\alpha</span> Values and P-Values</h2>
<p>Suppose <span class="math inline">H_1: \mu &gt; 50</span> and a sample gives <span class="math inline">\bar{X} = 52</span>. If software reports a P-value of 0.0356, then the probability of getting a sample mean of 52 or greater is 0.0356 when the true population mean is 50. For <span class="math inline">P = 0.0356</span>, <span class="math inline">H_0</span> would be rejected at <span class="math inline">\alpha = 0.05</span> but <strong>not</strong> at <span class="math inline">\alpha = 0.01</span>.</p>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Caution</strong></p>
</div>
<div class="callout-content">
<p>When the test is two-tailed, the area in one tail must be <strong>doubled</strong>. If the area in one tail is 0.0356, the P-value is <span class="math inline">2(0.0356) = 0.0712</span>, so <span class="math inline">H_0</span> would not be rejected at <span class="math inline">\alpha = 0.05</span>.</p>
<p>Most calculators and computers report the exact two-tailed P-value already, so it should <strong>not</strong> be doubled again.</p>
</div>
</div>
</div>
</section>
<section id="decision-rule-when-using-a-p-value" class="slide level2">
<h2>Decision Rule When Using a P-Value</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>The Rule</strong></p>
</div>
<div class="callout-content">
<p>If P-value <span class="math inline">\leq \alpha</span>, <strong>reject</strong> the null hypothesis.</p>
<p>If P-value <span class="math inline">&gt; \alpha</span>, <strong>do not reject</strong> the null hypothesis.</p>
</div>
</div>
</div>
<p>The <span class="math inline">\alpha</span> value is chosen by the researcher <strong>before</strong> the statistical test is conducted; the P-value is computed <strong>after</strong> the sample statistic has been found.</p>
</section></section>
<section>
<section id="section-8-2-z-test-for-a-mean" class="title-slide slide level1 center" data-background-color="#2c4a6e">
<h1>Section 8-2: z Test for a Mean</h1>

</section>
<section id="the-general-form-of-a-test-statistic" class="slide level2">
<h2>The General Form of a Test Statistic</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>General Formula</strong></p>
</div>
<div class="callout-content">
<p><span class="math display">\text{Test statistic} = \frac{(\text{observed value}) - (\text{expected value})}{\text{standard error}}</span></p>
<p>The <strong>observed value</strong> is the statistic computed from the sample data; the <strong>expected value</strong> is the parameter you would expect if <span class="math inline">H_0</span> were true; the denominator is the standard error of the statistic being tested.</p>
</div>
</div>
</div>
</section>
<section id="the-z-test" class="slide level2">
<h2>The z Test</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>z Test</strong></p>
</div>
<div class="callout-content">
<p>The <strong><span class="math inline">z</span> test</strong> is a statistical test for the mean of a population. It can be used either when <span class="math inline">n \geq 30</span> or when the population is normally distributed and <span class="math inline">\sigma</span> is known. The formula for the <span class="math inline">z</span> test statistic is</p>
<p><span class="math display">z = \frac{\bar{X} - \mu}{\sigma / \sqrt{n}}</span></p>
<p>where <span class="math inline">\bar{X}</span> is the sample mean, <span class="math inline">\mu</span> the hypothesized population mean, <span class="math inline">\sigma</span> the population standard deviation and <span class="math inline">n</span> the sample size.</p>
</div>
</div>
</div>
</section>
<section id="assumptions-and-rounding" class="slide level2">
<h2>Assumptions and Rounding</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Assumptions for the z Test for a Mean When <span class="math inline">\sigma</span> Is Known</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>The sample is a <strong>random sample</strong>.</li>
<li>Either <span class="math inline">n \geq 30</span>, or the population is normally distributed when <span class="math inline">n &lt; 30</span>.</li>
</ol>
</div>
</div>
</div>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Caution</strong></p>
</div>
<div class="callout-content">
<p>Test statistics are <strong>reported</strong> to two or three decimal places so that they are easy to read, but every decision in this chapter is made with the full-precision value R computes. Never round an intermediate result and then keep calculating with the rounded number.</p>
</div>
</div>
</div>
</section>
<section id="example-8-3" class="slide level2">
<h2>Example 8-3</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Basket Size at a Convenience-Store Chain</strong></p>
</div>
<div class="callout-content">
<p>A category manager believes that the average basket size at her convenience-store chain is now more than the NT$118 reported for last year. Assume the population standard deviation is NT$12. A random sample of 35 transactions has a mean of NT$122.5 <em>(hypothetical data)</em>. Test the claim at <span class="math inline">\alpha = 0.05</span>.</p>
</div>
</div>
</div>
</section>
<section id="example-8-3-1" class="slide level2">
<h2>Example 8-3</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> <span class="math inline">H_0: \mu = 118</span> and <span class="math inline">H_1: \mu &gt; 118</span> <em>(claim; right-tailed)</em>.</p>
<p><strong>Step 2.</strong> Since <span class="math inline">\alpha = 0.05</span> and the test is right-tailed, the critical value is <span class="math inline">z = +1.645</span>.</p>
<p><strong>Step 3 — compute the test statistic.</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href=""></a>(<span class="fl">122.5</span> <span class="sc">-</span> <span class="dv">118</span>) <span class="sc">/</span> (<span class="dv">12</span> <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">35</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.21853</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href=""></a><span class="fu">qnorm</span>(<span class="fl">0.95</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.644854</code></pre>
</div>
</div>
<p><strong>Step 4.</strong> Since <span class="math inline">2.219</span> is greater than the critical value <span class="math inline">1.645</span>, the decision is to <strong>reject <span class="math inline">H_0</span></strong>.</p>
<p><strong>Step 5.</strong> There is enough evidence to support the claim that the average basket size is greater than NT$118.</p>
</div>
</div>
</div>
</section>
<section id="example-8-4" class="slide level2">
<h2>Example 8-4</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Island-Wide Parcel Delivery Time</strong></p>
</div>
<div class="callout-content">
<p>An e-commerce platform states that island-wide parcels arrive on average 48 hours after dispatch. The variable is normally distributed and the population standard deviation is 9 hours. A category manager wishes to see whether parcels in her category arrive significantly faster. She randomly selected 36 parcels and recorded the delivery time in hours, as shown <em>(hypothetical data)</em>. At <span class="math inline">\alpha = 0.10</span>, is there enough evidence to support the claim?</p>
<pre><code>46   52   44   49   41   55
50   43   48   47   39   53
45   51   42   56   38   49
72   44   47   50   46   43
26   48   52   45   49   47
80   41   44   50   30   48</code></pre>
</div>
</div>
</div>
</section>
<section id="example-8-4-1" class="slide level2">
<h2>Example 8-4</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> <span class="math inline">H_0: \mu = 48</span> and <span class="math inline">H_1: \mu &lt; 48</span> <em>(claim; left-tailed)</em>.</p>
<p><strong>Step 2.</strong> Since <span class="math inline">\alpha = 0.10</span> and the test is left-tailed, the critical value is <span class="math inline">-1.282</span>.</p>
<p><strong>Step 3 — prepare data and compute the test statistic.</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href=""></a>delivery_hours <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">46</span>, <span class="dv">52</span>, <span class="dv">44</span>, <span class="dv">49</span>, <span class="dv">41</span>, <span class="dv">55</span>,</span>
<span id="cb17-2"><a href=""></a>                    <span class="dv">50</span>, <span class="dv">43</span>, <span class="dv">48</span>, <span class="dv">47</span>, <span class="dv">39</span>, <span class="dv">53</span>,</span>
<span id="cb17-3"><a href=""></a>                    <span class="dv">45</span>, <span class="dv">51</span>, <span class="dv">42</span>, <span class="dv">56</span>, <span class="dv">38</span>, <span class="dv">49</span>,</span>
<span id="cb17-4"><a href=""></a>                    <span class="dv">72</span>, <span class="dv">44</span>, <span class="dv">47</span>, <span class="dv">50</span>, <span class="dv">46</span>, <span class="dv">43</span>,</span>
<span id="cb17-5"><a href=""></a>                    <span class="dv">26</span>, <span class="dv">48</span>, <span class="dv">52</span>, <span class="dv">45</span>, <span class="dv">49</span>, <span class="dv">47</span>,</span>
<span id="cb17-6"><a href=""></a>                    <span class="dv">80</span>, <span class="dv">41</span>, <span class="dv">44</span>, <span class="dv">50</span>, <span class="dv">30</span>, <span class="dv">48</span>)</span>
<span id="cb17-7"><a href=""></a>x_bar <span class="ot">&lt;-</span> <span class="fu">mean</span>(delivery_hours)</span>
<span id="cb17-8"><a href=""></a></span>
<span id="cb17-9"><a href=""></a>x_bar</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 47.5</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href=""></a>(x_bar <span class="sc">-</span> <span class="dv">48</span>) <span class="sc">/</span> (<span class="dv">9</span> <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">36</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.3333333</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href=""></a><span class="fu">qnorm</span>(<span class="fl">0.10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1.281552</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="example-8-4-2" class="slide level2">
<h2>Example 8-4</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 4.</strong> The test statistic <span class="math inline">-0.333</span> falls in the noncritical region, so the decision is to <strong>not reject <span class="math inline">H_0</span></strong>.</p>
<p><strong>Step 5.</strong> There is not enough evidence to support the claim that parcels in this category arrive faster than the platform average.</p>
<p><strong>Comment.</strong> Even though the sample mean 47.5 hours is lower than the hypothesized mean 48 hours, it is not <em>significantly</em> lower; the difference may be due to chance. When <span class="math inline">H_0</span> is not rejected, a type II error is still possible, and <span class="math inline">H_0</span> cannot be accepted as true — there is merely not enough evidence to say that it is false.</p>
</div>
</div>
</div>
</section>
<section id="example-8-5" class="slide level2">
<h2>Example 8-5</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Checked Baggage on a Regional Route</strong></p>
</div>
<div class="callout-content">
<p>An airline’s operations report states that checked bags on its Taipei-Tokyo route weigh 18.0 kilograms on average. A load planner selects a random sample of 40 checked bags and finds a mean weight of 19.1 kilograms <em>(hypothetical data)</em>. Assume the population standard deviation is 3.0 kilograms. At <span class="math inline">\alpha = 0.01</span>, can it be concluded that the mean weight is not equal to 18.0 kilograms?</p>
</div>
</div>
</div>
</section>
<section id="example-8-5-1" class="slide level2">
<h2>Example 8-5</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> <span class="math inline">H_0: \mu = 18</span> and <span class="math inline">H_1: \mu \neq 18</span> <em>(claim; two-tailed)</em>.</p>
<p><strong>Step 2.</strong> Since <span class="math inline">\alpha = 0.01</span> and the test is two-tailed, the critical values are <span class="math inline">+2.576</span> and <span class="math inline">-2.576</span>.</p>
<p><strong>Step 3 — compute the test statistic.</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href=""></a>(<span class="fl">19.1</span> <span class="sc">-</span> <span class="dv">18</span>) <span class="sc">/</span> (<span class="fl">3.0</span> <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">40</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.319004</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href=""></a><span class="fu">qnorm</span>(<span class="fl">0.005</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -2.575829</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href=""></a><span class="fu">qnorm</span>(<span class="fl">0.995</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.575829</code></pre>
</div>
</div>
<p><strong>Step 4.</strong> The test statistic <span class="math inline">2.319</span> falls in the noncritical region, so <strong>do not reject <span class="math inline">H_0</span></strong>.</p>
<p><strong>Step 5.</strong> There is not enough evidence to support the claim that the average weight of a checked bag is not equal to 18.0 kilograms.</p>
</div>
</div>
</div>
</section>
<section id="procedure-table-the-p-value-method" class="slide level2">
<h2>Procedure Table: The P-Value Method</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solving Hypothesis-Testing Problems (P-Value Method)</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> State the hypotheses and identify the claim.</p>
<p><strong>Step 2.</strong> Compute the test statistic.</p>
<p><strong>Step 3.</strong> Find the P-value.</p>
<p><strong>Step 4.</strong> Make the decision.</p>
<p><strong>Step 5.</strong> Summarize the results.</p>
<p>Recall the decision rule: if P-value <span class="math inline">\leq \alpha</span>, reject <span class="math inline">H_0</span>; if P-value <span class="math inline">&gt; \alpha</span>, do not reject <span class="math inline">H_0</span>.</p>
</div>
</div>
</div>
</section>
<section id="example-8-6" class="slide level2">
<h2>Example 8-6</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Monthly Revenue of a Coffee-Chain Store</strong></p>
</div>
<div class="callout-content">
<p>A franchise consultant wishes to test the claim that the average monthly revenue of a single coffee-chain store is greater than NT$860 thousand. She selects a random sample of 36 stores and finds the mean to be NT$902 thousand <em>(hypothetical data)</em>. The population standard deviation is NT$118 thousand. Is there evidence to support the claim at <span class="math inline">\alpha = 0.05</span>? Use the P-value method.</p>
</div>
</div>
</div>
</section>
<section id="example-8-6-1" class="slide level2">
<h2>Example 8-6</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> <span class="math inline">H_0: \mu = 860</span> and <span class="math inline">H_1: \mu &gt; 860</span> <em>(claim; right-tailed)</em>.</p>
<p><strong>Step 2 and Step 3 — compute the test statistic and the P-value.</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href=""></a>z <span class="ot">&lt;-</span> (<span class="dv">902</span> <span class="sc">-</span> <span class="dv">860</span>) <span class="sc">/</span> (<span class="dv">118</span> <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">36</span>))</span>
<span id="cb29-2"><a href=""></a></span>
<span id="cb29-3"><a href=""></a>z</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.135593</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href=""></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(z)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.01635629</code></pre>
</div>
</div>
<p><strong>Step 4.</strong> Since the P-value <span class="math inline">0.0164</span> is less than 0.05, <strong>reject <span class="math inline">H_0</span></strong>.</p>
<p><strong>Step 5.</strong> There is enough evidence to support the claim that the average monthly revenue of a store is greater than NT$860 thousand. Had <span class="math inline">\alpha = 0.01</span> been chosen, <span class="math inline">H_0</span> would not have been rejected.</p>
</div>
</div>
</div>
</section>
<section id="example-8-7" class="slide level2">
<h2>Example 8-7</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Courier Pick-Up Time</strong></p>
</div>
<div class="callout-content">
<p>A food-delivery platform claims that the average time a courier needs to pick up an order from a restaurant is 12 minutes. A sample of 32 pick-ups has an average time of 12.6 minutes <em>(hypothetical data)</em>. The standard deviation of the population is 1.9 minutes. At <span class="math inline">\alpha = 0.05</span>, is there enough evidence to reject the claim? Use the P-value method.</p>
</div>
</div>
</div>
</section>
<section id="example-8-7-1" class="slide level2">
<h2>Example 8-7</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> <span class="math inline">H_0: \mu = 12</span> <em>(claim)</em> and <span class="math inline">H_1: \mu \neq 12</span> <em>(two-tailed)</em>.</p>
<p><strong>Step 2 and Step 3 — compute the test statistic and the P-value.</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href=""></a>z <span class="ot">&lt;-</span> (<span class="fl">12.6</span> <span class="sc">-</span> <span class="dv">12</span>) <span class="sc">/</span> (<span class="fl">1.9</span> <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">32</span>))</span>
<span id="cb33-2"><a href=""></a></span>
<span id="cb33-3"><a href=""></a>z</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.786375</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href=""></a><span class="dv">2</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="fu">abs</span>(z)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.07403856</code></pre>
</div>
</div>
<p><strong>Step 4.</strong> The decision is to <strong>not reject <span class="math inline">H_0</span></strong>, since the P-value <span class="math inline">0.0740</span> is greater than 0.05.</p>
<p><strong>Step 5.</strong> There is not enough evidence to reject the claim that the average pick-up time is 12 minutes.</p>
</div>
</div>
</div>
</section>
<section id="guidelines-for-p-values" class="slide level2">
<h2>Guidelines for P-Values</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>When No <span class="math inline">\alpha</span> Level Is Chosen</strong></p>
</div>
<div class="callout-content">
<p>Some researchers report the P-value and let the reader decide. These guidelines can then be used.</p>
<ul>
<li>If P-value <span class="math inline">\leq 0.01</span>, reject the null hypothesis. The difference is <strong>highly significant</strong>.</li>
<li>If P-value <span class="math inline">&gt; 0.01</span> but P-value <span class="math inline">\leq 0.05</span>, reject the null hypothesis. The difference is <strong>significant</strong>.</li>
<li>If P-value <span class="math inline">&gt; 0.05</span> but P-value <span class="math inline">\leq 0.10</span>, consider the consequences of a type I error before rejecting the null hypothesis.</li>
</ul>
</div>
</div>
</div>
</section></section>
<section>
<section id="section-8-3-t-test-for-a-mean" class="title-slide slide level1 center" data-background-color="#2c4a6e">
<h1>Section 8-3: t Test for a Mean</h1>

</section>
<section id="the-t-distribution" class="slide level2">
<h2>The <span class="math inline">t</span> Distribution</h2>
<p>When the population standard deviation is unknown, the <span class="math inline">z</span> test is not typically used for testing hypotheses involving means; the <strong><span class="math inline">t</span> test</strong> is used instead, and the distribution of the variable should be approximately normal.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>How the <span class="math inline">t</span> Distribution Compares with the Standard Normal</strong></p>
</div>
<div class="callout-content">
<p><strong>Similarities.</strong> It is bell-shaped; it is symmetric about the mean; the mean, median and mode are equal to 0 and are located at the centre of the distribution; the curve approaches but never touches the <span class="math inline">x</span> axis.</p>
<p><strong>Differences.</strong> The variance is greater than 1; it is a family of curves based on the degrees of freedom; as the sample size increases, the <span class="math inline">t</span> distribution approaches the normal distribution.</p>
</div>
</div>
</div>
</section>
<section id="the-t-test" class="slide level2">
<h2>The t Test</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>t Test</strong></p>
</div>
<div class="callout-content">
<p>The <strong><span class="math inline">t</span> test</strong> is a statistical test for the mean of a population and is used when the population is normally or approximately normally distributed and <span class="math inline">\sigma</span> is unknown. The formula for the <span class="math inline">t</span> test statistic is</p>
<p><span class="math display">t = \frac{\bar{X} - \mu}{s / \sqrt{n}}</span></p>
<p>The degrees of freedom are <span class="math inline">\text{d.f.} = n - 1</span>.</p>
</div>
</div>
</div>
<p>The formula is the same as for the <span class="math inline">z</span> test, except that the sample standard deviation <span class="math inline">s</span> replaces the unknown <span class="math inline">\sigma</span>.</p>
</section>
<section id="reading-table-a-5" class="slide level2">
<h2>Reading Table A-5</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Caution</strong></p>
</div>
<div class="callout-content">
<p>Table A-5 gives degrees of freedom for values from 1 through 30, then at intervals above 30. When a critical value is looked up by hand and the degrees of freedom are above 30, <strong>round down</strong> to the nearest table value — for example, if <span class="math inline">\text{d.f.} = 59</span>, read <span class="math inline">\text{d.f.} = 55</span>. This is a conservative approach.</p>
<p>As the degrees of freedom get larger, the critical values approach the <span class="math inline">z</span> scores. In R, <code>qt()</code> returns the critical value for the <strong>exact</strong> degrees of freedom, and that is the value quoted on every slide in this chapter; the round-down rule is needed only when the table is read by hand.</p>
</div>
</div>
</div>
</section>
<section id="example-8-8" class="slide level2">
<h2>Example 8-8</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Critical t Value, Right-Tailed</strong></p>
</div>
<div class="callout-content">
<p>Find the critical <span class="math inline">t</span> value for <span class="math inline">\alpha = 0.05</span> with <span class="math inline">\text{d.f.} = 19</span> for a right-tailed <span class="math inline">t</span> test.</p>
</div>
</div>
</div>
</section>
<section id="example-8-8-1" class="slide level2">
<h2>Example 8-8</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p>Find the 0.05 column in the top row labelled <em>One tail</em> and 19 in the left-hand column. The critical value is <span class="math inline">+1.729</span>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href=""></a><span class="fu">qt</span>(<span class="fl">0.95</span>, <span class="at">df =</span> <span class="dv">19</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.729133</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="example-8-9" class="slide level2">
<h2>Example 8-9</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Critical t Value, Left-Tailed</strong></p>
</div>
<div class="callout-content">
<p>Find the critical <span class="math inline">t</span> value for <span class="math inline">\alpha = 0.01</span> with <span class="math inline">\text{d.f.} = 17</span> for a left-tailed <span class="math inline">t</span> test.</p>
</div>
</div>
</div>
</section>
<section id="example-8-9-1" class="slide level2">
<h2>Example 8-9</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p>Find the critical value in the 0.01 column in the row labelled <em>One tail</em>, and find 17 in the left column. The critical value is <span class="math inline">-2.567</span>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href=""></a><span class="fu">qt</span>(<span class="fl">0.01</span>, <span class="at">df =</span> <span class="dv">17</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -2.566934</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="example-8-10" class="slide level2">
<h2>Example 8-10</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Critical t Values, Two-Tailed</strong></p>
</div>
<div class="callout-content">
<p>Find the critical values for <span class="math inline">\alpha = 0.05</span> with <span class="math inline">\text{d.f.} = 23</span> for a two-tailed test.</p>
</div>
</div>
</div>
</section>
<section id="example-8-10-1" class="slide level2">
<h2>Example 8-10</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p>Find the 0.05 column in the row labelled <em>Two tails</em> and 23 in the column labelled d.f. The critical values are <span class="math inline">-2.069</span> and <span class="math inline">+2.069</span>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href=""></a><span class="fu">qt</span>(<span class="fl">0.025</span>, <span class="at">df =</span> <span class="dv">23</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -2.068658</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href=""></a><span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="at">df =</span> <span class="dv">23</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.068658</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="example-8-11" class="slide level2">
<h2>Example 8-11</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Critical t Value, Right-Tailed</strong></p>
</div>
<div class="callout-content">
<p>Find the critical value for <span class="math inline">\alpha = 0.10</span> with <span class="math inline">\text{d.f.} = 12</span> for a right-tailed test.</p>
</div>
</div>
</div>
</section>
<section id="example-8-11-1" class="slide level2">
<h2>Example 8-11</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p>Find the critical value in the 0.10 column in the <em>One tail</em> row and 12 in the d.f. column. The critical value is <span class="math inline">+1.356</span>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href=""></a><span class="fu">qt</span>(<span class="fl">0.90</span>, <span class="at">df =</span> <span class="dv">12</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.356217</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="assumptions-for-the-t-test" class="slide level2">
<h2>Assumptions for the t Test</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Assumptions for the t Test for a Mean When <span class="math inline">\sigma</span> Is Unknown</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>The sample is a <strong>random sample</strong>.</li>
<li>Either <span class="math inline">n \geq 30</span>, or the population is normally distributed when <span class="math inline">n &lt; 30</span>.</li>
</ol>
</div>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Traditional Method with the t Test</strong></p>
</div>
<div class="callout-content">
<p>The same five steps are used as for the <span class="math inline">z</span> test, except that critical values come from <strong>Table A-5</strong>: state the hypotheses and identify the claim; find the critical value(s); compute the test statistic; make the decision; summarize the results.</p>
</div>
</div>
</div>
</section>
<section id="example-8-12" class="slide level2">
<h2>Example 8-12</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Call Handling Time</strong></p>
</div>
<div class="callout-content">
<p>A customer-service centre claims that the average time an agent needs to handle one call is 4.5 minutes. A random sample of 12 calls had a mean handling time of 5.3 minutes with a standard deviation of 1.1 minutes <em>(hypothetical data)</em>. Is there enough evidence to reject the claim at <span class="math inline">\alpha = 0.05</span>? Assume the variable is normally distributed.</p>
</div>
</div>
</div>
</section>
<section id="example-8-12-1" class="slide level2">
<h2>Example 8-12</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> <span class="math inline">H_0: \mu = 4.5</span> <em>(claim)</em> and <span class="math inline">H_1: \mu \neq 4.5</span> <em>(two-tailed)</em>.</p>
<p><strong>Step 2.</strong> The critical values are <span class="math inline">+2.201</span> and <span class="math inline">-2.201</span> for <span class="math inline">\alpha = 0.05</span> and <span class="math inline">\text{d.f.} = 11</span>.</p>
<p><strong>Step 3 — compute the test statistic.</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href=""></a>(<span class="fl">5.3</span> <span class="sc">-</span> <span class="fl">4.5</span>) <span class="sc">/</span> (<span class="fl">1.1</span> <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">12</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.519347</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href=""></a><span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="at">df =</span> <span class="dv">11</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.200985</code></pre>
</div>
</div>
<p><strong>Step 4.</strong> <strong>Reject <span class="math inline">H_0</span></strong> since <span class="math inline">2.519 &gt; 2.201</span>.</p>
<p><strong>Step 5.</strong> There is enough evidence to reject the claim that the average call handling time is 4.5 minutes.</p>
</div>
</div>
</div>
</section>
<section id="example-8-13" class="slide level2">
<h2>Example 8-13</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Days to Payment on Export Invoices</strong></p>
</div>
<div class="callout-content">
<p>An industry report states that small exporters wait on average 27 days to be paid. A trade-finance analyst believes that the exporters using her platform are paid in less time. A random sample of 10 invoices was selected and the number of days to payment is shown <em>(hypothetical data)</em>. Test the claim at <span class="math inline">\alpha = 0.10</span>. Assume the variable is normally distributed.</p>
<pre><code>24   31   19   27   22   30   18   25   21   26</code></pre>
</div>
</div>
</div>
</section>
<section id="example-8-13-1" class="slide level2">
<h2>Example 8-13</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> <span class="math inline">H_0: \mu = 27</span> and <span class="math inline">H_1: \mu &lt; 27</span> <em>(claim; left-tailed)</em>.</p>
<p><strong>Step 2.</strong> At <span class="math inline">\alpha = 0.10</span> and <span class="math inline">\text{d.f.} = 9</span>, the critical value is <span class="math inline">-1.383</span>.</p>
<p><strong>Step 3 — prepare data and compute the test statistic.</strong> With the raw data in hand, <code>t.test()</code> does the arithmetic.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href=""></a>days_to_payment <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">24</span>, <span class="dv">31</span>, <span class="dv">19</span>, <span class="dv">27</span>, <span class="dv">22</span>, <span class="dv">30</span>, <span class="dv">18</span>, <span class="dv">25</span>, <span class="dv">21</span>, <span class="dv">26</span>)</span>
<span id="cb52-2"><a href=""></a></span>
<span id="cb52-3"><a href=""></a><span class="fu">mean</span>(days_to_payment)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 24.3</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href=""></a><span class="fu">sd</span>(days_to_payment)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.372896</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href=""></a><span class="fu">t.test</span>(days_to_payment, <span class="at">mu =</span> <span class="dv">27</span>, <span class="at">alternative =</span> <span class="st">"less"</span>)<span class="sc">$</span>statistic</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        t 
-1.952516 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href=""></a><span class="fu">qt</span>(<span class="fl">0.10</span>, <span class="at">df =</span> <span class="dv">9</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1.383029</code></pre>
</div>
</div>
<p><strong>Step 4.</strong> <strong>Reject <span class="math inline">H_0</span></strong> since <span class="math inline">-1.953</span> falls in the critical region.</p>
<p><strong>Step 5.</strong> There is enough evidence to support the claim that exporters on the platform are paid in fewer than 27 days.</p>
</div>
</div>
</div>
</section>
<section id="p-value-intervals-for-the-t-test" class="slide level2">
<h2>P-Value Intervals for the t Test</h2>
<p>P-values for <span class="math inline">t</span> tests cannot be read directly from Table A-5, since only selected values of <span class="math inline">\alpha</span> are given. Only an <strong>interval</strong> for the P-value can be found from the table: locate the row for the degrees of freedom, find the two table values the test statistic falls between, and read the corresponding <span class="math inline">\alpha</span> values from the <em>One tail</em> row (one-tailed test) or the <em>Two tails</em> row (two-tailed test).</p>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Caution</strong></p>
</div>
<div class="callout-content">
<p>R’s <code>pt()</code> gives the exact P-value. Table A-5 gives only an interval, and the exact value always falls inside that interval. Every decision on these slides is made with the exact value.</p>
</div>
</div>
</div>
</section>
<section id="example-8-14" class="slide level2">
<h2>Example 8-14</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>P-Value Interval, Right-Tailed</strong></p>
</div>
<div class="callout-content">
<p>Find the P-value when the <span class="math inline">t</span> test statistic is 2.462, the sample size is 14, and the test is right-tailed.</p>
</div>
</div>
</div>
</section>
<section id="example-8-14-1" class="slide level2">
<h2>Example 8-14</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p>Across the row with <span class="math inline">\text{d.f.} = 13</span>, the value 2.462 falls between 2.160 and 2.650, which correspond to <span class="math inline">\alpha = 0.025</span> and <span class="math inline">\alpha = 0.01</span> in the <em>One tail</em> row. Hence</p>
<p><span class="math display">0.01 &lt; P\text{-value} &lt; 0.025</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href=""></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pt</span>(<span class="fl">2.462</span>, <span class="at">df =</span> <span class="dv">13</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.01428067</code></pre>
</div>
</div>
<p>The exact P-value is <span class="math inline">0.0143</span>, which lies inside the interval read from the table. If <span class="math inline">\alpha</span> were 0.05, <span class="math inline">H_0</span> would be rejected; if <span class="math inline">\alpha</span> were 0.01, it would not.</p>
</div>
</div>
</div>
</section>
<section id="example-8-15" class="slide level2">
<h2>Example 8-15</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>P-Value Interval, Two-Tailed</strong></p>
</div>
<div class="callout-content">
<p>Find the P-value when the <span class="math inline">t</span> test statistic is 2.575, the sample size is 9, and the test is two-tailed.</p>
</div>
</div>
</div>
</section>
<section id="example-8-15-1" class="slide level2">
<h2>Example 8-15</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p>Across the row with <span class="math inline">\text{d.f.} = 8</span>, the value 2.575 falls between 2.306 and 2.896, which correspond to <span class="math inline">\alpha = 0.05</span> and <span class="math inline">\alpha = 0.02</span> in the <em>Two tails</em> row. Hence</p>
<p><span class="math display">0.02 &lt; P\text{-value} &lt; 0.05</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href=""></a><span class="dv">2</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pt</span>(<span class="fl">2.575</span>, <span class="at">df =</span> <span class="dv">8</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.03287093</code></pre>
</div>
</div>
<p>The exact P-value is <span class="math inline">0.0329</span>. At <span class="math inline">\alpha = 0.05</span> the null hypothesis can be rejected; at <span class="math inline">\alpha = 0.01</span> it cannot.</p>
</div>
</div>
</div>
</section>
<section id="example-8-16" class="slide level2">
<h2>Example 8-16</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Containers Shipped by Programme Members</strong></p>
</div>
<div class="callout-content">
<p>A trade association claims that firms which joined its export-promotion programme ship more containers per month than the industry average of 24. A random sample of 15 member firms has a mean of 27.8 containers per month and a standard deviation of 6.2 containers <em>(hypothetical data)</em>. Is there enough evidence to support the claim at <span class="math inline">\alpha = 0.05</span>? Assume the variable is normally distributed. Use the P-value method.</p>
</div>
</div>
</div>
</section>
<section id="example-8-16-1" class="slide level2">
<h2>Example 8-16</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> <span class="math inline">H_0: \mu = 24</span> and <span class="math inline">H_1: \mu &gt; 24</span> <em>(claim; right-tailed)</em>.</p>
<p><strong>Step 2 and Step 3 — compute the test statistic and the P-value.</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href=""></a>t_stat <span class="ot">&lt;-</span> (<span class="fl">27.8</span> <span class="sc">-</span> <span class="dv">24</span>) <span class="sc">/</span> (<span class="fl">6.2</span> <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">15</span>))</span>
<span id="cb64-2"><a href=""></a></span>
<span id="cb64-3"><a href=""></a>t_stat</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.373764</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href=""></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pt</span>(t_stat, <span class="at">df =</span> <span class="dv">14</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.01622883</code></pre>
</div>
</div>
<p>From Table A-5 with <span class="math inline">\text{d.f.} = 14</span>, the value 2.3738 falls between 2.145 and 2.624, so <span class="math inline">0.01 &lt; P\text{-value} &lt; 0.025</span>; the exact P-value is <span class="math inline">0.0162</span>.</p>
<p><strong>Step 4.</strong> <strong>Reject <span class="math inline">H_0</span></strong> since P-value <span class="math inline">&lt; \alpha</span>.</p>
<p><strong>Step 5.</strong> There is enough evidence to support the claim that member firms ship more than 24 containers per month.</p>
</div>
</div>
</div>
</section>
<section id="choosing-between-the-z-test-and-the-t-test" class="slide level2">
<h2>Choosing Between the z Test and the t Test</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Figure 8-23: The Rules</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>If <span class="math inline">\sigma</span> is <strong>known</strong>, use the <span class="math inline">z</span> test. The variable must be normally distributed if <span class="math inline">n &lt; 30</span>.</li>
<li>If <span class="math inline">\sigma</span> is <strong>unknown</strong> but <span class="math inline">n \geq 30</span>, use the <span class="math inline">t</span> test.</li>
<li>If <span class="math inline">\sigma</span> is <strong>unknown</strong> and <span class="math inline">n &lt; 30</span>, use the <span class="math inline">t</span> test; the population must be approximately normally distributed.</li>
</ol>
<p>These are the same rules that were used for confidence intervals in Chapter 7.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="section-8-4-z-test-for-a-proportion" class="title-slide slide level1 center" data-background-color="#2c4a6e">
<h1>Section 8-4: z Test for a Proportion</h1>

</section>
<section id="testing-a-proportion" class="slide level2">
<h2>Testing a Proportion</h2>
<p>Many hypothesis-testing situations involve <strong>proportions</strong>; a proportion is the same as a percentage of the population. A hypothesis test involving a population proportion can be considered a binomial experiment when there are only two outcomes and the probability of a success does not change from trial to trial.</p>
<p>Since a normal distribution can be used to approximate the binomial distribution when <span class="math inline">np \geq 5</span> and <span class="math inline">nq \geq 5</span>, the standard normal distribution can be used to test hypotheses for proportions.</p>
</section>
<section id="formula-for-the-z-test-for-proportions" class="slide level2">
<h2>Formula for the z Test for Proportions</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>The Test Statistic</strong></p>
</div>
<div class="callout-content">
<p><span class="math display">z = \frac{\hat{p} - p}{\sqrt{pq/n}}</span></p>
<p>where <span class="math inline">\hat{p} = X/n</span> is the sample proportion, <span class="math inline">p</span> is the hypothesized population proportion, <span class="math inline">q = 1 - p</span> and <span class="math inline">n</span> is the sample size.</p>
<p>The formula follows the general form: <span class="math inline">\hat{p}</span> is the observed value, <span class="math inline">p</span> the expected value, and <span class="math inline">\sqrt{pq/n}</span> the standard error. It is derived from the normal approximation to the binomial by substituting <span class="math inline">\mu = np</span> and <span class="math inline">\sigma = \sqrt{npq}</span> and dividing numerator and denominator by <span class="math inline">n</span>.</p>
</div>
</div>
</div>
</section>
<section id="assumptions-for-testing-a-proportion" class="slide level2">
<h2>Assumptions for Testing a Proportion</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Three Assumptions</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>The sample is a <strong>random sample</strong>.</li>
<li>The conditions for a <strong>binomial experiment</strong> are satisfied.</li>
<li><span class="math inline">np \geq 5</span> <strong>and</strong> <span class="math inline">nq \geq 5</span>.</li>
</ol>
</div>
</div>
</div>
<p>Table A-4 is used to find both critical values and P-values. Examples 8-17 to 8-19 use the traditional method; Example 8-20 uses the P-value method.</p>
</section>
<section id="example-8-17" class="slide level2">
<h2>Example 8-17</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Mobile-Wallet Payments</strong></p>
</div>
<div class="callout-content">
<p>A market-research note claims that 30% of online shoppers in Taiwan pay with a mobile wallet. To test the claim, a student randomly selected 120 online shoppers and found that 42 of them paid with a mobile wallet <em>(hypothetical data)</em>. At <span class="math inline">\alpha = 0.05</span>, is there enough evidence to reject the claim?</p>
</div>
</div>
</div>
</section>
<section id="example-8-17-1" class="slide level2">
<h2>Example 8-17</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> <span class="math inline">H_0: p = 0.30</span> <em>(claim)</em> and <span class="math inline">H_1: p \neq 0.30</span> <em>(two-tailed)</em>.</p>
<p><strong>Step 2.</strong> Since <span class="math inline">\alpha = 0.05</span> and the test is two-tailed, the critical values are <span class="math inline">\pm 1.960</span>.</p>
<p><strong>Step 3 — compute the test statistic.</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb68"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href=""></a>p_hat <span class="ot">&lt;-</span> <span class="dv">42</span> <span class="sc">/</span> <span class="dv">120</span></span>
<span id="cb68-2"><a href=""></a></span>
<span id="cb68-3"><a href=""></a>p_hat</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.35</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb70"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href=""></a>(p_hat <span class="sc">-</span> <span class="fl">0.30</span>) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fl">0.30</span> <span class="sc">*</span> <span class="fl">0.70</span> <span class="sc">/</span> <span class="dv">120</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.195229</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb72"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href=""></a><span class="fu">qnorm</span>(<span class="fl">0.975</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.959964</code></pre>
</div>
</div>
<p><strong>Step 4.</strong> <strong>Do not reject <span class="math inline">H_0</span></strong>, since the test statistic <span class="math inline">1.195</span> falls in the noncritical region.</p>
<p><strong>Step 5.</strong> There is not enough evidence to reject the claim that 30% of online shoppers pay with a mobile wallet.</p>
</div>
</div>
</div>
</section>
<section id="example-8-18" class="slide level2">
<h2>Example 8-18</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Night-Market Stalls Accepting Mobile Payment</strong></p>
</div>
<div class="callout-content">
<p>An industry survey reports that 40% of night-market stalls accept mobile payment. A researcher believes that the percentage is lower at one particular night market. She randomly selected 60 stalls there and found that 20 accept mobile payment <em>(hypothetical data)</em>. At <span class="math inline">\alpha = 0.01</span>, is there enough evidence to support the claim?</p>
</div>
</div>
</div>
</section>
<section id="example-8-18-1" class="slide level2">
<h2>Example 8-18</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> <span class="math inline">H_0: p = 0.40</span> and <span class="math inline">H_1: p &lt; 0.40</span> <em>(claim; left-tailed)</em>.</p>
<p><strong>Step 2.</strong> Since <span class="math inline">\alpha = 0.01</span> and the test is one-tailed, the critical value is <span class="math inline">-2.326</span>.</p>
<p><strong>Step 3 — compute the test statistic.</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb74"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href=""></a>p_hat <span class="ot">&lt;-</span> <span class="dv">20</span> <span class="sc">/</span> <span class="dv">60</span></span>
<span id="cb74-2"><a href=""></a></span>
<span id="cb74-3"><a href=""></a>p_hat</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3333333</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb76"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href=""></a>(p_hat <span class="sc">-</span> <span class="fl">0.40</span>) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fl">0.40</span> <span class="sc">*</span> <span class="fl">0.60</span> <span class="sc">/</span> <span class="dv">60</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1.054093</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb78"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href=""></a><span class="fu">qnorm</span>(<span class="fl">0.01</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -2.326348</code></pre>
</div>
</div>
<p><strong>Step 4.</strong> <strong>Do not reject <span class="math inline">H_0</span></strong>, since the test statistic <span class="math inline">-1.054</span> does not fall in the critical region.</p>
<p><strong>Step 5.</strong> There is not enough evidence to support the claim that fewer than 40% of the stalls at this night market accept mobile payment.</p>
</div>
</div>
</div>
</section>
<section id="example-8-19" class="slide level2">
<h2>Example 8-19</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Booking Accommodation Online</strong></p>
</div>
<div class="callout-content">
<p>A tourism report states that at least 72% of inbound visitors to Taiwan book their accommodation online. To see whether this claim is valid, a researcher selected a random sample of 90 inbound visitors and found that 60 of them had booked online <em>(hypothetical data)</em>. At <span class="math inline">\alpha = 0.01</span>, test the claim that at least 72% of inbound visitors book their accommodation online.</p>
</div>
</div>
</div>
</section>
<section id="example-8-19-1" class="slide level2">
<h2>Example 8-19</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> <span class="math inline">H_0: p = 0.72</span> <em>(claim)</em> and <span class="math inline">H_1: p &lt; 0.72</span> <em>(left-tailed)</em>.</p>
<p><strong>Step 2.</strong> Since <span class="math inline">\alpha = 0.01</span> and the test is left-tailed, the critical value is <span class="math inline">-2.326</span>.</p>
<p><strong>Step 3 — compute the test statistic.</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb80"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href=""></a>p_hat <span class="ot">&lt;-</span> <span class="dv">60</span> <span class="sc">/</span> <span class="dv">90</span></span>
<span id="cb80-2"><a href=""></a></span>
<span id="cb80-3"><a href=""></a>p_hat</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6666667</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb82"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href=""></a>(p_hat <span class="sc">-</span> <span class="fl">0.72</span>) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fl">0.72</span> <span class="sc">*</span> <span class="fl">0.28</span> <span class="sc">/</span> <span class="dv">90</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1.126872</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb84"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href=""></a><span class="fu">qnorm</span>(<span class="fl">0.01</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -2.326348</code></pre>
</div>
</div>
<p><strong>Step 4.</strong> <strong>Do not reject <span class="math inline">H_0</span></strong>, since the test statistic <span class="math inline">-1.127</span> does not fall in the critical region.</p>
<p><strong>Step 5.</strong> There is not enough evidence to reject the claim that at least 72% of inbound visitors book their accommodation online.</p>
</div>
</div>
</div>
</section>
<section id="example-8-20" class="slide level2">
<h2>Example 8-20</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Cross-Border Orders Shipped to Japan</strong></p>
</div>
<div class="callout-content">
<p>A payments company claims that more than 20% of the cross-border e-commerce orders placed from Taiwan are shipped to Japan. A random sample of 250 cross-border orders showed that 63 were shipped to Japan <em>(hypothetical data)</em>. At <span class="math inline">\alpha = 0.05</span>, is there enough evidence to support the claim? Use the P-value method.</p>
</div>
</div>
</div>
</section>
<section id="example-8-20-1" class="slide level2">
<h2>Example 8-20</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> <span class="math inline">H_0: p = 0.20</span> and <span class="math inline">H_1: p &gt; 0.20</span> <em>(claim; right-tailed)</em>.</p>
<p><strong>Step 2 and Step 3 — compute the test statistic and the P-value.</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb86"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href=""></a>p_hat <span class="ot">&lt;-</span> <span class="dv">63</span> <span class="sc">/</span> <span class="dv">250</span></span>
<span id="cb86-2"><a href=""></a>z     <span class="ot">&lt;-</span> (p_hat <span class="sc">-</span> <span class="fl">0.20</span>) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fl">0.20</span> <span class="sc">*</span> <span class="fl">0.80</span> <span class="sc">/</span> <span class="dv">250</span>)</span>
<span id="cb86-3"><a href=""></a></span>
<span id="cb86-4"><a href=""></a>p_hat</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.252</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb88"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href=""></a>z</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.05548</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb90"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href=""></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(z)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.01991631</code></pre>
</div>
</div>
<p><strong>Step 4.</strong> <strong>Reject <span class="math inline">H_0</span></strong>, since the P-value <span class="math inline">0.0199</span> is less than 0.05.</p>
<p><strong>Step 5.</strong> There is enough evidence to support the claim that more than 20% of the cross-border orders placed from Taiwan are shipped to Japan.</p>
</div>
</div>
</div>
</section>
<section id="finding-chi-square-critical-values" class="slide level2">
<h2>Finding Chi-Square Critical Values</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Three Cases Using Table A-6</strong></p>
</div>
<div class="callout-content">
<p>Table A-6 gives the areas <strong>to the right</strong> of the critical value.</p>
<ol type="1">
<li><strong>Right-tailed test</strong> — use the area under the <span class="math inline">\alpha</span> value for the specific degrees of freedom.</li>
<li><strong>Left-tailed test</strong> — subtract <span class="math inline">\alpha</span> from 1, then use the area for <span class="math inline">1 - \alpha</span>.</li>
<li><strong>Two-tailed test</strong> — divide <span class="math inline">\alpha</span> by 2; use the area for <span class="math inline">\alpha/2</span> for the right critical value and the area for <span class="math inline">1 - \alpha/2</span> for the left critical value.</li>
</ol>
<p>In R, <code>qchisq(area, df)</code> returns the value with <code>area</code> to its <strong>left</strong>, which is why the arguments below are <span class="math inline">1 - \alpha</span>, <span class="math inline">\alpha</span>, and so on.</p>
</div>
</div>
</div>
</section>
<section id="example-8-21" class="slide level2">
<h2>Example 8-21</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Critical Chi-Square Value, Right-Tailed</strong></p>
</div>
<div class="callout-content">
<p>Find the critical chi-square value for 18 degrees of freedom when <span class="math inline">\alpha = 0.05</span> and the test is right-tailed.</p>
</div>
</div>
</div>
</section>
<section id="example-8-21-1" class="slide level2">
<h2>Example 8-21</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p>Find the <span class="math inline">\alpha</span> value at the top of Table A-6 and the degrees of freedom in the left column. The critical value is located where the two columns meet: <strong>28.869</strong>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb92"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href=""></a><span class="fu">qchisq</span>(<span class="fl">0.95</span>, <span class="at">df =</span> <span class="dv">18</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 28.8693</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="example-8-22" class="slide level2">
<h2>Example 8-22</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Critical Chi-Square Value, Left-Tailed</strong></p>
</div>
<div class="callout-content">
<p>Find the critical chi-square value for 14 degrees of freedom when <span class="math inline">\alpha = 0.05</span> and the test is left-tailed.</p>
</div>
</div>
</div>
</section>
<section id="example-8-22-1" class="slide level2">
<h2>Example 8-22</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p>When the test is left-tailed, the <span class="math inline">\alpha</span> value must be subtracted from 1: <span class="math inline">1 - 0.05 = 0.95</span>. The chi-square table gives the area to the right of the critical value, and chi-square values cannot be negative, so 95% of the area will be to the right of the value. For 0.95 and 14 degrees of freedom the critical value is <strong>6.571</strong>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb94"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href=""></a><span class="fu">qchisq</span>(<span class="fl">0.05</span>, <span class="at">df =</span> <span class="dv">14</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6.570631</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="example-8-23" class="slide level2">
<h2>Example 8-23</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Critical Chi-Square Values, Two-Tailed</strong></p>
</div>
<div class="callout-content">
<p>Find the critical chi-square values for 19 degrees of freedom when <span class="math inline">\alpha = 0.10</span> and a two-tailed test is conducted.</p>
</div>
</div>
</div>
</section>
<section id="example-8-23-1" class="slide level2">
<h2>Example 8-23</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p>The area must be split: the area to the right of the larger value is <span class="math inline">\alpha/2 = 0.05</span>, and the area to the right of the smaller value is <span class="math inline">1 - \alpha/2 = 0.95</span>. With 19 degrees of freedom the critical values are <strong>10.117</strong> and <strong>30.144</strong>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb96"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href=""></a><span class="fu">qchisq</span>(<span class="fl">0.05</span>, <span class="at">df =</span> <span class="dv">19</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10.11701</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb98"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href=""></a><span class="fu">qchisq</span>(<span class="fl">0.95</span>, <span class="at">df =</span> <span class="dv">19</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 30.14353</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="degrees-of-freedom-beyond-the-table" class="slide level2">
<h2>Degrees of Freedom Beyond the Table</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Caution</strong></p>
</div>
<div class="callout-content">
<p>Table A-6 gives values only up to 30 degrees of freedom. When the degrees of freedom exceed those specified in the table, <strong>use the table value for 30 degrees of freedom</strong>. This guideline keeps the type I error equal to or below the <span class="math inline">\alpha</span> value.</p>
</div>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Three Test Situations for a Variance</strong></p>
</div>
<div class="callout-content">
<p>If a researcher believes the variance of a population is greater than 225: <span class="math inline">H_0: \sigma^2 = 225</span> and <span class="math inline">H_1: \sigma^2 &gt; 225</span> — right-tailed.</p>
<p>If less than 225: <span class="math inline">H_0: \sigma^2 = 225</span> and <span class="math inline">H_1: \sigma^2 &lt; 225</span> — left-tailed.</p>
<p>If no direction is specified: <span class="math inline">H_0: \sigma^2 = 225</span> and <span class="math inline">H_1: \sigma^2 \neq 225</span> — two-tailed.</p>
</div>
</div>
</div>
</section>
<section id="the-chi-square-test-for-a-single-variance" class="slide level2">
<h2>The Chi-Square Test for a Single Variance</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Formula</strong></p>
</div>
<div class="callout-content">
<p><span class="math display">\chi^2 = \frac{(n-1)s^2}{\sigma^2}</span></p>
<p>with degrees of freedom equal to <span class="math inline">n - 1</span>, where <span class="math inline">n</span> is the sample size, <span class="math inline">s^2</span> the sample variance and <span class="math inline">\sigma^2</span> the population variance.</p>
</div>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Assumptions for the Chi-Square Test for a Single Variance</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>The sample must be <strong>randomly selected</strong> from the population.</li>
<li>The population must be <strong>normally distributed</strong> for the variable under study.</li>
<li>The observations must be <strong>independent</strong> of one another.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="why-test-a-variance" class="slide level2">
<h2>Why Test a Variance?</h2>
<p>Wherever consistency is required, the smallest possible variation is wanted. When bolts are manufactured, the variation in diameters must be kept to a minimum, or the nuts will not fit properly. In education, a test used repeatedly on the same students should produce approximately the same grades, so the variance of each student’s grades should be small — but a test used to judge learning should have a large overall standard deviation, so that those who have learned can be distinguished from those who have not.</p>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Caution</strong></p>
</div>
<div class="callout-content">
<p>The methods used to test a hypothesis about a population variance or standard deviation are <strong>not robust</strong>. If the data come from a population that is not normally distributed, these methods cannot be used.</p>
</div>
</div>
</div>
</section>
<section id="example-8-24" class="slide level2">
<h2>Example 8-24</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Fill Weight of Snack Packs</strong></p>
</div>
<div class="callout-content">
<p>A quality engineer wishes to see whether the variance of the fill weight of a snack pack on one production line is less than the process standard of <span class="math inline">\sigma^2 = 36</span> (grams squared). A random sample of 12 packs from that line had a variance of <span class="math inline">s^2 = 27</span> <em>(hypothetical data)</em>. Test her claim at <span class="math inline">\alpha = 0.05</span>.</p>
</div>
</div>
</div>
</section>
<section id="example-8-24-1" class="slide level2">
<h2>Example 8-24</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> <span class="math inline">H_0: \sigma^2 = 36</span> and <span class="math inline">H_1: \sigma^2 &lt; 36</span> <em>(claim; left-tailed)</em>.</p>
<p><strong>Step 2.</strong> Since this is a left-tailed test and <span class="math inline">\alpha = 0.05</span>, the value <span class="math inline">1 - 0.05 = 0.95</span> is used with <span class="math inline">\text{d.f.} = 11</span>. The critical value is <span class="math inline">4.575</span>.</p>
<p><strong>Step 3 — compute the test statistic.</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb100"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href=""></a>(<span class="dv">12</span> <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> <span class="dv">27</span> <span class="sc">/</span> <span class="dv">36</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8.25</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb102"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href=""></a><span class="fu">qchisq</span>(<span class="fl">0.05</span>, <span class="at">df =</span> <span class="dv">11</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.574813</code></pre>
</div>
</div>
<p><strong>Step 4.</strong> Since <span class="math inline">8.250</span> falls in the noncritical region, <strong>do not reject <span class="math inline">H_0</span></strong>.</p>
<p><strong>Step 5.</strong> There is not enough evidence to support the claim that the variance of the fill weight on this line is less than 36.</p>
</div>
</div>
</div>
</section>
<section id="example-8-25" class="slide level2">
<h2>Example 8-25</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Orders Picked per Hour</strong></p>
</div>
<div class="callout-content">
<p>A distribution-centre manager believes that the standard deviation of the number of orders picked per hour is greater than 6. A random sample of 15 hours is selected and the number of orders picked in each hour is shown <em>(hypothetical data)</em>. At <span class="math inline">\alpha = 0.10</span>, is there enough evidence to support the manager’s claim? Assume the variable is normally distributed.</p>
<pre><code>38   52   45   61   40
55   33   48   57   42
36   50   65   44   39</code></pre>
</div>
</div>
</div>
</section>
<section id="example-8-25-1" class="slide level2">
<h2>Example 8-25</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> <span class="math inline">H_0: \sigma = 6</span> and <span class="math inline">H_1: \sigma &gt; 6</span> <em>(claim; right-tailed)</em>. Since the standard deviation is given, it is squared to get the variance.</p>
<p><strong>Step 2.</strong> Right-tailed with <span class="math inline">\text{d.f.} = 14</span> and <span class="math inline">\alpha = 0.10</span>: the critical value is <span class="math inline">21.064</span>.</p>
<p><strong>Step 3 — prepare data and compute the test statistic.</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb105"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href=""></a>orders_per_hour <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">38</span>, <span class="dv">52</span>, <span class="dv">45</span>, <span class="dv">61</span>, <span class="dv">40</span>,</span>
<span id="cb105-2"><a href=""></a>                     <span class="dv">55</span>, <span class="dv">33</span>, <span class="dv">48</span>, <span class="dv">57</span>, <span class="dv">42</span>,</span>
<span id="cb105-3"><a href=""></a>                     <span class="dv">36</span>, <span class="dv">50</span>, <span class="dv">65</span>, <span class="dv">44</span>, <span class="dv">39</span>)</span>
<span id="cb105-4"><a href=""></a></span>
<span id="cb105-5"><a href=""></a><span class="fu">sd</span>(orders_per_hour)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9.516902</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb107"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href=""></a>(<span class="dv">15</span> <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> <span class="fu">var</span>(orders_per_hour) <span class="sc">/</span> <span class="dv">6</span><span class="sc">^</span><span class="dv">2</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 35.22222</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb109"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href=""></a><span class="fu">qchisq</span>(<span class="fl">0.90</span>, <span class="at">df =</span> <span class="dv">14</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 21.06414</code></pre>
</div>
</div>
<p><strong>Step 4.</strong> <strong>Reject <span class="math inline">H_0</span></strong>, since <span class="math inline">35.222 &gt; 21.064</span>.</p>
<p><strong>Step 5.</strong> There is enough evidence to support the claim that the standard deviation of the number of orders picked per hour is greater than 6.</p>
</div>
</div>
</div>
</section>
<section id="example-8-26" class="slide level2">
<h2>Example 8-26</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Net Weight of Instant-Noodle Packs</strong></p>
</div>
<div class="callout-content">
<p>A contract manufacturer wishes to test the claim that the variance of the net weight of its instant-noodle packs is 2.25. Net weight is measured in grams, and assume that it is normally distributed. A random sample of 20 packs has a standard deviation of 1.8 grams <em>(hypothetical data)</em>. At <span class="math inline">\alpha = 0.05</span>, is there enough evidence to reject the manufacturer’s claim?</p>
</div>
</div>
</div>
</section>
<section id="example-8-26-1" class="slide level2">
<h2>Example 8-26</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> <span class="math inline">H_0: \sigma^2 = 2.25</span> <em>(claim)</em> and <span class="math inline">H_1: \sigma^2 \neq 2.25</span> <em>(two-tailed)</em>.</p>
<p><strong>Step 2.</strong> Two-tailed at <span class="math inline">\alpha = 0.05</span>, so the critical values for 0.025 and 0.975 are needed. With <span class="math inline">\text{d.f.} = 19</span> they are <span class="math inline">8.907</span> and <span class="math inline">32.852</span>.</p>
<p><strong>Step 3 — compute the test statistic.</strong> Since the sample standard deviation is given, it must be squared for the formula.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb111"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href=""></a>(<span class="dv">20</span> <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> <span class="fl">1.8</span><span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="fl">2.25</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 27.36</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb113"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href=""></a><span class="fu">qchisq</span>(<span class="fl">0.025</span>, <span class="at">df =</span> <span class="dv">19</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8.906516</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb115"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href=""></a><span class="fu">qchisq</span>(<span class="fl">0.975</span>, <span class="at">df =</span> <span class="dv">19</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 32.85233</code></pre>
</div>
</div>
<p><strong>Step 4.</strong> <strong>Do not reject <span class="math inline">H_0</span></strong>, since <span class="math inline">8.907 &lt; 27.360 &lt; 32.852</span>.</p>
<p><strong>Step 5.</strong> There is not enough evidence to reject the manufacturer’s claim that the variance of the net weight is equal to 2.25.</p>
</div>
</div>
</div>
</section>
<section id="p-value-intervals-for-the-chi-square-test" class="slide level2">
<h2>P-Value Intervals for the Chi-Square Test</h2>
<p>Approximate P-values for the chi-square test can be found from Table A-6, but the procedure is more complicated than for the <span class="math inline">z</span> and <span class="math inline">t</span> tests, since the chi-square distribution is not symmetric and <span class="math inline">\chi^2</span> values cannot be negative.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Reading the Interval</strong></p>
</div>
<div class="callout-content">
<ul>
<li><strong>Right-tailed.</strong> Find the two table values the test statistic falls between and read the corresponding <span class="math inline">\alpha</span> values directly.</li>
<li><strong>Left-tailed.</strong> Read the corresponding table values, then <strong>subtract each from 1</strong>.</li>
<li><strong>Two-tailed.</strong> Find the interval as above, then <strong>double both endpoints</strong>.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="example-8-27" class="slide level2">
<h2>Example 8-27</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>P-Value Interval, Right-Tailed</strong></p>
</div>
<div class="callout-content">
<p>Find the P-value when <span class="math inline">\chi^2 = 21.5</span>, <span class="math inline">n = 11</span>, and the test is right-tailed.</p>
</div>
</div>
</div>
</section>
<section id="example-8-27-1" class="slide level2">
<h2>Example 8-27</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p>Across the row with <span class="math inline">\text{d.f.} = 10</span>, the value 21.5 falls between 20.483 and 23.209, corresponding to 0.025 and 0.01 respectively. Hence</p>
<p><span class="math display">0.01 &lt; P\text{-value} &lt; 0.025</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb117"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href=""></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pchisq</span>(<span class="fl">21.5</span>, <span class="at">df =</span> <span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.01786459</code></pre>
</div>
</div>
<p>The exact P-value is <span class="math inline">0.0179</span>, which lies inside that interval.</p>
</div>
</div>
</div>
</section>
<section id="example-8-28" class="slide level2">
<h2>Example 8-28</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>P-Value Interval, Left-Tailed</strong></p>
</div>
<div class="callout-content">
<p>Find the P-value when <span class="math inline">\chi^2 = 5.892</span>, <span class="math inline">n = 15</span>, and the test is left-tailed.</p>
</div>
</div>
</div>
</section>
<section id="example-8-28-1" class="slide level2">
<h2>Example 8-28</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p>Across the row with <span class="math inline">\text{d.f.} = 14</span>, the value 5.892 falls between 5.629 and 6.571, corresponding to 0.975 and 0.95. Because the test statistic falls on the left side, each value must be subtracted from 1: <span class="math inline">1 - 0.975 = 0.025</span> and <span class="math inline">1 - 0.95 = 0.05</span>. Hence</p>
<p><span class="math display">0.025 &lt; P\text{-value} &lt; 0.05</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb119"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb119-1"><a href=""></a><span class="fu">pchisq</span>(<span class="fl">5.892</span>, <span class="at">df =</span> <span class="dv">14</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.03085947</code></pre>
</div>
</div>
<p>The exact P-value is <span class="math inline">0.0309</span>. Had the test been two-tailed, the interval would be doubled: <span class="math inline">0.05 &lt; P\text{-value} &lt; 0.10</span>.</p>
</div>
</div>
</div>
</section>
<section id="example-8-29" class="slide level2">
<h2>Example 8-29</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Customs Clearance Times</strong></p>
</div>
<div class="callout-content">
<p>A customs broker knows from past records that the standard deviation of the time needed to clear an import container is 9.5 hours. A random sample of 25 containers is selected and timed; the standard deviation is 7.0 hours <em>(hypothetical data)</em>. At <span class="math inline">\alpha = 0.05</span>, can it be concluded that the standard deviation has changed? Use the P-value method. Assume the variable is normally distributed.</p>
</div>
</div>
</div>
</section>
<section id="example-8-29-1" class="slide level2">
<h2>Example 8-29</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> <span class="math inline">H_0: \sigma = 9.5</span> and <span class="math inline">H_1: \sigma \neq 9.5</span> <em>(claim; two-tailed)</em>.</p>
<p><strong>Step 2 and Step 3 — compute the test statistic and the P-value.</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb121"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb121-1"><a href=""></a>chi_sq <span class="ot">&lt;-</span> (<span class="dv">25</span> <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> <span class="fl">7.0</span><span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="fl">9.5</span><span class="sc">^</span><span class="dv">2</span></span>
<span id="cb121-2"><a href=""></a></span>
<span id="cb121-3"><a href=""></a>chi_sq</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 13.03047</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb123"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb123-1"><a href=""></a><span class="dv">2</span> <span class="sc">*</span> <span class="fu">pchisq</span>(chi_sq, <span class="at">df =</span> <span class="dv">24</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.06876872</code></pre>
</div>
</div>
<p>With <span class="math inline">\text{d.f.} = 24</span>, the value 13.0305 falls between 12.401 and 13.848, corresponding to 0.975 and 0.95. Subtracting from 1 gives 0.025 and 0.05, and doubling for the two tails gives <span class="math inline">0.05 &lt; P\text{-value} &lt; 0.10</span>; the exact P-value is <span class="math inline">0.0688</span>.</p>
<p><strong>Step 4.</strong> <strong>Do not reject <span class="math inline">H_0</span></strong>, since P-value <span class="math inline">&gt; \alpha</span>.</p>
<p><strong>Step 5.</strong> There is not enough evidence to support the claim that the standard deviation of the customs clearance time has changed.</p>
</div>
</div>
</div>
</section>
<section id="example-8-30" class="slide level2">
<h2>Example 8-30</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Value of Air-Freight Shipments</strong></p>
</div>
<div class="callout-content">
<p>A trade magazine reports that the average declared value of an air-freight shipment leaving Taoyuan is NT$68 thousand. A freight forwarder randomly selected 50 recent shipments and found that the average declared value was NT$63.8 thousand and the standard deviation was NT$9.6 thousand <em>(hypothetical data)</em>. Is there enough evidence at <span class="math inline">\alpha = 0.05</span> to conclude that the average value is not NT$68 thousand? Assume the variable is normally distributed. Also find the 95% confidence interval of the true mean.</p>
</div>
</div>
</div>
</section>
<section id="example-8-30-1" class="slide level2">
<h2>Example 8-30</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> <span class="math inline">H_0: \mu = 68</span> and <span class="math inline">H_1: \mu \neq 68</span> <em>(claim; two-tailed)</em>.</p>
<p><strong>Step 2.</strong> At <span class="math inline">\alpha = 0.05</span> with <span class="math inline">\text{d.f.} = 49</span>, <code>qt()</code> gives the critical values <span class="math inline">+2.010</span> and <span class="math inline">-2.010</span>.</p>
<p><strong>Step 3 — compute the test statistic.</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb125"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb125-1"><a href=""></a>(<span class="fl">63.8</span> <span class="sc">-</span> <span class="dv">68</span>) <span class="sc">/</span> (<span class="fl">9.6</span> <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">50</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -3.093592</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb127"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb127-1"><a href=""></a><span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="at">df =</span> <span class="dv">49</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.009575</code></pre>
</div>
</div>
<p><strong>Step 4.</strong> Since <span class="math inline">-3.094 &lt; -2.010</span>, the decision is to <strong>reject <span class="math inline">H_0</span></strong>.</p>
<p><strong>Step 5.</strong> There is enough evidence to support the claim that the average declared value is not NT$68 thousand.</p>
</div>
</div>
</div>
</section>
<section id="example-8-30-2" class="slide level2">
<h2>Example 8-30</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>The 95% confidence interval.</strong></p>
<p><span class="math display">\bar{X} - t_{\alpha/2}\frac{s}{\sqrt{n}} &lt; \mu &lt; \bar{X} + t_{\alpha/2}\frac{s}{\sqrt{n}}</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb129"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb129-1"><a href=""></a>margin <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="at">df =</span> <span class="dv">49</span>) <span class="sc">*</span> <span class="fl">9.6</span> <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">50</span>)</span>
<span id="cb129-2"><a href=""></a></span>
<span id="cb129-3"><a href=""></a><span class="fl">63.8</span> <span class="sc">-</span> margin</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 61.07171</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb131"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb131-1"><a href=""></a><span class="fl">63.8</span> <span class="sc">+</span> margin</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 66.52829</code></pre>
</div>
</div>
<p>The interval <span class="math inline">61.07 &lt; \mu &lt; 66.53</span> does <strong>not</strong> contain the hypothesized value <span class="math inline">\mu = 68</span>. There is agreement between the hypothesis test and the confidence interval.</p>
</div>
</div>
</div>
</section>
<section id="example-8-31" class="slide level2">
<h2>Example 8-31</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Net Weight of Tea-Bag Cartons</strong></p>
</div>
<div class="callout-content">
<p>A supplier claims that its cartons of tea bags have an average net weight of 120 grams. A random sample of 10 cartons has an average net weight of 118.6 grams and a standard deviation of 2.8 grams <em>(hypothetical data)</em>. At <span class="math inline">\alpha = 0.05</span>, can the claim be rejected? Also, find the 95% confidence interval of the true mean. Assume the variable is normally distributed.</p>
</div>
</div>
</div>
</section>
<section id="example-8-31-1" class="slide level2">
<h2>Example 8-31</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Solution</strong></p>
</div>
<div class="callout-content">
<p><strong>Step 1.</strong> <span class="math inline">H_0: \mu = 120</span> <em>(claim)</em> and <span class="math inline">H_1: \mu \neq 120</span> <em>(two-tailed)</em>.</p>
<p><strong>Step 2.</strong> At <span class="math inline">\alpha = 0.05</span> and <span class="math inline">\text{d.f.} = 9</span>, the critical values are <span class="math inline">+2.262</span> and <span class="math inline">-2.262</span>.</p>
<p><strong>Step 3 — compute the test statistic and the interval.</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb133"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb133-1"><a href=""></a>margin <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="at">df =</span> <span class="dv">9</span>) <span class="sc">*</span> <span class="fl">2.8</span> <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">10</span>)</span>
<span id="cb133-2"><a href=""></a></span>
<span id="cb133-3"><a href=""></a>(<span class="fl">118.6</span> <span class="sc">-</span> <span class="dv">120</span>) <span class="sc">/</span> (<span class="fl">2.8</span> <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">10</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1.581139</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb135"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb135-1"><a href=""></a><span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="at">df =</span> <span class="dv">9</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.262157</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb137"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb137-1"><a href=""></a><span class="fl">118.6</span> <span class="sc">-</span> margin</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 116.597</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb139"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb139-1"><a href=""></a><span class="fl">118.6</span> <span class="sc">+</span> margin</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 120.603</code></pre>
</div>
</div>
<p><strong>Step 4 and Step 5.</strong> <strong>Do not reject <span class="math inline">H_0</span></strong>. There is not enough evidence to reject the claim that the mean net weight is 120 grams. The 95% interval <span class="math inline">116.6 &lt; \mu &lt; 120.6</span> <strong>does</strong> contain <span class="math inline">\mu = 120</span>; again there is agreement.</p>
</div>
</div>
</div>
</section>
<section id="type-ii-error-and-the-power-of-a-test" class="slide level2">
<h2>Type II Error and the Power of a Test</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Figure 8-40: Possibilities in Hypothesis Testing</strong></p>
</div>
<div class="callout-content">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Decision</th>
<th><span class="math inline">H_0</span> true</th>
<th><span class="math inline">H_0</span> false</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Reject <span class="math inline">H_0</span></td>
<td>Type I error, <span class="math inline">\alpha</span></td>
<td>Correct decision, <span class="math inline">1 - \beta</span></td>
</tr>
<tr class="even">
<td>Do not reject <span class="math inline">H_0</span></td>
<td>Correct decision, <span class="math inline">1 - \alpha</span></td>
<td>Type II error, <span class="math inline">\beta</span></td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The value of <span class="math inline">\beta</span> depends on <span class="math inline">\alpha</span>, the sample size, the population standard deviation, and the actual difference between the hypothesized parameter and the true parameter. Since that last difference is unknown, <span class="math inline">\beta</span> cannot be computed.</p>
</section>
<section id="the-power-of-a-test" class="slide level2">
<h2>The Power of a Test</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Power of a Test</strong></p>
</div>
<div class="callout-content">
<p>The <strong>power of a statistical test</strong> measures the sensitivity of the test to detect a real difference in parameters if one actually exists. The power of a test is equal to</p>
<p><span class="math display">\text{Power} = 1 - \beta</span></p>
<p>Power is a probability and can take values from 0 to 1. The closer the power is to 1, the better the test is at rejecting the null hypothesis when the null hypothesis is in fact false. If <span class="math inline">\beta = 0.04</span>, the power is <span class="math inline">1 - 0.04 = 0.96</span>, or 96%.</p>
</div>
</div>
</div>
</section>
<section id="increasing-the-power-of-a-test" class="slide level2">
<h2>Increasing the Power of a Test</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Two Practical Methods</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li><strong>Increase <span class="math inline">\alpha</span></strong> — for example use <span class="math inline">\alpha = 0.05</span> instead of <span class="math inline">\alpha = 0.01</span>. As <span class="math inline">\alpha</span> increases, <span class="math inline">\beta</span> decreases, so <span class="math inline">1 - \beta</span> increases.</li>
<li><strong>Select a larger sample size</strong> — a larger <span class="math inline">n</span> makes the standard error of the mean smaller and consequently reduces <span class="math inline">\beta</span>.</li>
</ol>
<p>Neither should be used at the researcher’s whim. Before increasing <span class="math inline">\alpha</span>, consider the consequences of a type I error; increasing the sample size costs money and time.</p>
<p>When a choice of statistical tests exists, use the test with the highest power for the data — provided its assumptions can be met. If they cannot, a test with lower power must be used.</p>
</div>
</div>
</div>
</section>
<section id="power-in-r" class="slide level2">
<h2>Power in R</h2>
<p><strong>Prepare data</strong> — the distribution of <span class="math inline">\bar{X}</span> under <span class="math inline">H_0: \mu = 50</span> and under the true value <span class="math inline">\mu = 54</span>, with <span class="math inline">\sigma = 10</span>, <span class="math inline">n = 25</span> and a right-tailed test at <span class="math inline">\alpha = 0.05</span>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb141"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb141-1"><a href=""></a>se   <span class="ot">&lt;-</span> <span class="dv">10</span> <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">25</span>)</span>
<span id="cb141-2"><a href=""></a>cv   <span class="ot">&lt;-</span> <span class="dv">50</span> <span class="sc">+</span> <span class="fu">qnorm</span>(<span class="fl">0.95</span>) <span class="sc">*</span> se</span>
<span id="cb141-3"><a href=""></a>beta <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(cv, <span class="dv">54</span>, se)</span>
<span id="cb141-4"><a href=""></a></span>
<span id="cb141-5"><a href=""></a>cv</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 53.28971</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb143"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb143-1"><a href=""></a>beta</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.36124</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb145"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb145-1"><a href=""></a><span class="dv">1</span> <span class="sc">-</span> beta</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.63876</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb147"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb147-1"><a href=""></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">40</span>, <span class="dv">68</span>, <span class="at">by =</span> <span class="fl">0.1</span>)</span>
<span id="cb147-2"><a href=""></a>curves <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(x, <span class="at">h0 =</span> <span class="fu">dnorm</span>(x, <span class="dv">50</span>, se), <span class="at">h1 =</span> <span class="fu">dnorm</span>(x, <span class="dv">54</span>, se))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="power-in-r-1" class="slide level2">
<h2>Power in R</h2>
<p><strong>Output figure</strong></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb148"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb148-1"><a href=""></a><span class="fu">ggplot</span>(curves, <span class="fu">aes</span>(x)) <span class="sc">+</span></span>
<span id="cb148-2"><a href=""></a>  <span class="fu">geom_area</span>(<span class="at">data =</span> <span class="fu">filter</span>(curves, x <span class="sc">&gt;=</span> cv), <span class="fu">aes</span>(<span class="at">y =</span> h1)) <span class="sc">+</span></span>
<span id="cb148-3"><a href=""></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> h0)) <span class="sc">+</span></span>
<span id="cb148-4"><a href=""></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> h1), <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb148-5"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Power of a Right-Tailed Test"</span>, <span class="at">x =</span> <span class="st">"Sample mean"</span>, <span class="at">y =</span> <span class="st">"Density"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="ch8_files/figure-revealjs/s8-6-2-1.png" class="quarto-figure quarto-figure-center r-stretch" style="width:80.0%"><p>The solid curve is for <span class="math inline">H_0: \mu = 50</span> and the dashed curve for the true value <span class="math inline">\mu = 54</span>. The shaded area is the power <span class="math inline">1 - \beta = 0.639</span>; the unshaded part of the dashed curve is <span class="math inline">\beta = 0.361</span>. Increasing <span class="math inline">n</span> narrows both curves and increases the power.</p>
</section>
<section id="a-final-comment" class="slide level2">
<h2>A Final Comment</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Caution</strong></p>
</div>
<div class="callout-content">
<p>When the researcher fails to reject the null hypothesis, this does <strong>not</strong> mean that there is not enough evidence to support alternative hypotheses. It may be that the null hypothesis is false but the statistical test has too low a power to detect the real difference. One can conclude only that in this study there is not enough evidence to reject the null hypothesis.</p>
<p>Whether the decision is to reject <span class="math inline">H_0</span> or not to reject <span class="math inline">H_0</span>, there is in either case a chance of being wrong. The goal is to keep the probabilities of type I and type II errors as small as possible.</p>
</div>
</div>
</div>
</section>
<section id="important-terms" class="slide level2">
<h2>Important Terms</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Chapter 8 Vocabulary</strong></p>
</div>
<div class="callout-content">
<p><span class="math inline">\alpha</span> (alpha) · alternative hypothesis · <span class="math inline">\beta</span> (beta) · chi-square test · critical or rejection region · critical value · hypothesis testing · left-tailed test · level of significance · noncritical or nonrejection region · null hypothesis · one-tailed test · power of a test · P-value · research hypothesis · right-tailed test · statistical hypothesis · statistical test · test statistic · <span class="math inline">t</span> test · two-tailed test · type I error · type II error · <span class="math inline">z</span> test</p>
</div>
</div>
</div>
</section>
<section id="key-formulas" class="slide level2">
<h2>Key Formulas</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tests for Means</strong></p>
</div>
<div class="callout-content">
<p>The general form of a test statistic:</p>
<p><span class="math display">\text{Test statistic} = \frac{(\text{observed value}) - (\text{expected value})}{\text{standard error}}</span></p>
<p>The <span class="math inline">z</span> test for means — if <span class="math inline">n &lt; 30</span>, the variable must be normally distributed:</p>
<p><span class="math display">z = \frac{\bar{X} - \mu}{\sigma / \sqrt{n}}</span></p>
<p>The <span class="math inline">t</span> test for means, <span class="math inline">\text{d.f.} = n - 1</span> — if <span class="math inline">n &lt; 30</span>, the variable must be normally distributed:</p>
<p><span class="math display">t = \frac{\bar{X} - \mu}{s / \sqrt{n}}</span></p>
</div>
</div>
</div>
</section>
<section id="key-formulas-1" class="slide level2">
<h2>Key Formulas</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tests for Proportions, Variances and Standard Deviations</strong></p>
</div>
<div class="callout-content">
<p>The <span class="math inline">z</span> test for proportions, valid if <span class="math inline">np \geq 5</span> and <span class="math inline">nq \geq 5</span>, where <span class="math inline">\hat{p} = X/n</span> and <span class="math inline">q = 1 - p</span>:</p>
<p><span class="math display">z = \frac{\hat{p} - p}{\sqrt{pq/n}}</span></p>
<p>The chi-square test for a variance or standard deviation, <span class="math inline">\text{d.f.} = n - 1</span> — the variable must be normally distributed:</p>
<p><span class="math display">\chi^2 = \frac{(n-1)s^2}{\sigma^2}</span></p>
<p>The power of a test:</p>
<p><span class="math display">\text{Power} = 1 - \beta</span></p>
</div>
</div>
</div>
</section>
<section id="key-takeaways" class="slide level2">
<h2>Key Takeaways</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Key point</strong></p>
</div>
<div class="callout-content">
<ul>
<li>A <strong>statistical hypothesis</strong> is a conjecture about a population parameter; <span class="math inline">H_0</span> states no difference and always carries the equals sign, while <span class="math inline">H_1</span> states a difference and is also called the <strong>research hypothesis</strong></li>
<li>Evidence can <strong>support</strong> a claim only when the claim is <span class="math inline">H_1</span>, and can <strong>reject</strong> a claim only when the claim is <span class="math inline">H_0</span>; nothing is ever proved</li>
<li>A <strong>type I error</strong> rejects a true <span class="math inline">H_0</span> and has probability <span class="math inline">\alpha</span>, the <strong>level of significance</strong>; a <strong>type II error</strong> fails to reject a false <span class="math inline">H_0</span> and has probability <span class="math inline">\beta</span> — decreasing one increases the other</li>
<li>The <strong>critical value</strong> separates the <strong>critical (rejection) region</strong> from the <strong>noncritical (nonrejection) region</strong>; the direction of <span class="math inline">H_1</span> decides whether the test is left-tailed, right-tailed or two-tailed</li>
<li><strong>Traditional method:</strong> state the hypotheses and identify the claim, find the critical value(s), compute the test statistic, make the decision, summarize the results</li>
</ul>
</div>
</div>
</div>
</section>
<section id="key-takeaways-1" class="slide level2">
<h2>Key Takeaways</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Key point</strong></p>
</div>
<div class="callout-content">
<ul>
<li><strong>P-value method:</strong> state the hypotheses and identify the claim, compute the test statistic, find the P-value, make the decision, summarize the results — reject <span class="math inline">H_0</span> when P-value <span class="math inline">\leq \alpha</span></li>
<li>Use the <span class="math inline">z</span> test when <span class="math inline">\sigma</span> is known, the <span class="math inline">t</span> test with <span class="math inline">\text{d.f.} = n - 1</span> when <span class="math inline">\sigma</span> is unknown; test a proportion with <span class="math inline">z</span> when <span class="math inline">np \geq 5</span> and <span class="math inline">nq \geq 5</span>, and a variance with <span class="math inline">\chi^2</span> when the population is normal</li>
<li>For a two-tailed test, the <span class="math inline">(1 - \alpha)</span> confidence interval contains the hypothesized value exactly when <span class="math inline">H_0</span> is not rejected</li>
<li>The <strong>power</strong> of a test is <span class="math inline">1 - \beta</span>; it is raised by increasing <span class="math inline">\alpha</span> or, better, by increasing the sample size</li>
</ul>
</div>
</div>
</div>
</section>
<section id="acknowledgement" class="slide level2">
<h2>Acknowledgement</h2>
<ul>
<li><p><strong>Copyright notice.</strong> These teaching materials follow the organization and terminology of <strong>Bluman, A. G. (2023). Elementary statistics: A step by step approach (11th ed.). McGraw Hill</strong>. All rights in the original work are reserved by its authors and publishers.</p></li>
<li><p><strong>Original examples.</strong> Every worked example, data set, and R script in these slides was written for this course. The data are hypothetical unless stated otherwise.</p></li>
<li><p><strong>Non-commercial use only.</strong> These materials are strictly intended for educational purposes and must not be used for commercial gain or profit.</p></li>
<li><p><strong>Proper attribution.</strong> Any reproduction, distribution, or use of these materials must provide proper attribution to the original source.</p></li>
</ul>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="logo.svg" class="slide-logo"></p>
<div class="footer footer-default">
<p>Elementary Statistics: A Step by Step Approach</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="ch8_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="ch8_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="ch8_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="ch8_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="ch8_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="ch8_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="ch8_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="ch8_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="ch8_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":false,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true,"hideMissingTitles":true,"titleSelector":"h1"},
'smaller': true,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    <script>
    Reveal.on('ready', function() {
      var title = Reveal.getSlides()[0];
      if (title) {
        title.insertAdjacentHTML('beforeend',
          '<p style="font-size:0.5em; margin-top:1.5em;">' +
          '<a href="ch8-zh.html"  style="color:#555;">[中文版由此去]</a>' +
          '</p>');
      }
    });
    </script>
    

</body></html>