---
title: "Exercise 2"
output:
  pdf_document: default
  html_document: default
date: "2026-10-03"
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
```
## Q1
```{r}
commute <- c(18, 25, 32, 41, 27, 35, 22, 19, 45, 38, 29, 24,
             31, 36, 40, 26, 33, 28, 21, 44, 30, 37, 23, 39)

# Range
range <- max(commute) - min(commute)
range

# Class width
class_width <- ceiling(range / 5)
class_width

# Create 5 classes
classes <- cut(commute,
               breaks = c(18, 24, 30, 36, 42, 48),
               right = FALSE)

# Frequency
frequency <- table(classes)
frequency

# Cumulative frequency
cumulative_frequency <- cumsum(frequency)
cumulative_frequency
```

## Q2
```{r}
library(ggplot2)

ggplot(data.frame(commute), aes(x = commute)) +
  geom_histogram(bins = 5) +
  labs(
    title = "Histogram of Daily Commuting Times",
    x = "Commuting Time (minutes)",
    y = "Frequency"
  )
```
## Q3
```{r}
library(ggplot2)

ogive_data <- data.frame(
  upper_boundary = c(24, 30, 36, 42, 48),
  cumulative_frequency = c(5, 11, 16, 22, 24)
)

ggplot(ogive_data,
       aes(x = upper_boundary, y = cumulative_frequency)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Ogive of Daily Commuting Times",
    x = "Upper Class Boundary (minutes)",
    y = "Cumulative Frequency"
  )
```