project:
  type: website
  output-dir: ..

website:
  title: "Statistics"
  navbar:
    left:
      - href: sylla.qmd
        text: Syllabus
      - href: slide.qmd
        text: Slides
      - href: prob.qmd
        text: Problem sets
      - href: r.qmd
        text: R

format:
  html:
    theme:
      - Minty
      - brand
    # css: styles.css 
    toc: true

editor: visual

# quarto rende