project:
  type: website
  output-dir: .

website:
  title: "Statistics"
  favicon: hex/stat.svg
  navbar:
    logo: hex/stat.svg
    left:
      - href: sylla.qmd
        text: Syllabus
      - href: slide.qmd
        text: Slides
      - href: prob.qmd
        text: Problem sets
      - href: r.qmd
        text: R

format:
  html:
    theme:
      - Minty
      - brand
    toc: true
    toc-depth: 3

editor: visual

# quarto rende